### ISSUE TITLE
disable mTLS using a flag

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1001]
**Please describe the Improvement and/or Feature Request**

Disable mTLS using a flag on install: `osm install --disable-mTLS` For the first run, we may also want to require the `--disable-access-control` flag if you use `--disable-mTLS` if it helps us keep the `osm-controller` logic simple.

**Scope**
- [x] New Functionality
- [ ] Traffic Access Control
- [ ] Traffic Specs
- [ ] Traffic Metrics
- [ ] Traffic Split

**Possible use cases**

As a user, I'd like to install OSM. I'm most familiar with metrics related features of service mesh so I'd like to start by disabling mTLS and access control. I only want to view metrics and shift traffic. Once I understand the value, then I'll add mTLS and access control features to my OSM setup.

**Comment by draychev** [comment]
We bulit OSM with the assumption that certs are always used for Envoy-to-Envoy and Envoy-to-ControlPlane communication. It'd take some work to turn off mTLS. We are leaving this issue open to hear from the community and see whether folks are interested in implementing this.

**Comment by shashankram** [comment]
@addozhang hinted in https://github.com/openservicemesh/osm/issues/2012#issuecomment-730684175 that it would be desirable to turn off mTLS for gradual migration of new services into the mesh.

**Comment by addozhang** [comment]
@shashankram thanks.

Yes, this is our requirement. We are running hundreds of spring cloud serivces on openshift. The Netflix Eureka acts as service discovery. Access among services is via pod-ip:port, and there is only ip:port existing in HOST field of request.

We are planing to migrate to mesh architech to lervage power of mesh, such as trafflic split.

At the same time, we hope the migration smoothly.

**Comment by shashankram** [comment]
> @shashankram thanks.
> 
> Yes, this is our requirement. We are running hundreds of spring cloud serivces on openshift. The Netflix Eureka acts as service discovery. Access among services is via pod-ip:port, and there is only ip:port existing in HOST field of request.
> 
> Except above, we hope that the `matches`(HttpRouteGroup) of **`v1alpha3.TrafficSplit`** could be implementd in `RDS_Inbound` route. During migration, the commucation mode is mixed: enovy to envoy, envoy to non-mesh and non-mesh to envoy.
> 
> With all above, it will help us to push the migration to mesh. I think not only us, many teams will welcome this. It will be like replace tire for a running car. After all, companies or teams are operating an existing system/architech.
> 
> we all hope the migration smoothly.

@addozhang your requirements make sense to me. I will try to summarize the high level requirements in https://github.com/openservicemesh/osm/issues/2012.
