### ISSUE TITLE
Finer granularity for Prometheus monitored namespaces

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#1016]
**Please describe the Improvement and/or Feature Request**
As of today, all pods that are a part of the mesh enable the collection of metrics by default. We want to make this configurable, whereby only the specified namespaces (via the config map) are annotated with Prometheus annotations for metrics collection 

Part of #966 

**Possible use cases**
This will give users the ability to collect metrics  only for specified namespaces

**Comment by shashankram** [comment]
This should be driven through `osm cli` if annotations are required on prometheus pods post install.

**Comment by shashankram** [comment]
> This should be driven through `osm cli` if annotations are required on prometheus pods post install.

Needs a bit of discussion over implementation details.

**Comment by shashankram** [comment]
Prioritizing #1619 till we iron out the proposal.

**Comment by snehachhabria** [comment]
@shashankram is the proposal for this ironed out ? We might need to prioritize the work on this. cc @delqn

**Comment by shashankram** [comment]
I'll look into this and come up with a proposal.
