### ISSUE TITLE
gradual mTLS rollout

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#102]
When service mesh is rolled out to a brownfield a service may need to be mTLS-optional.
If two existing services A-B are enabled for mTLS, there will be before and after mTLS is enabled. Not all pods will be mTLS ready at the same time. This will result in some old pods connecting to new mTLS pods and most likely 503 errors.
To prevent that we need mTLS-optional for a period of time, where if mTLS does not work we switch to non-mTLS.

What about traffic split, where one group is mTLS the other is not?

**Comment by steeling** [comment]
Related issues 

* #2012
* #1001
* #2172

**Comment by keithmattix** [comment]
I think this is definitely a feature we should implement in the next couple of releases
