### ISSUE TITLE
Refactor code so that ads can be configured with `CertificateStore` and a `CertificateManager`. 

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1034]
Create interfaces for `CertificateStore` and a `CertificateManager`. 

The `CertificateStore` interface should describe a collection of methods for configuring and working with storage options for certificates (create, get, list). Implement `CertificateStore` for Azure Key Vault (AKV), Kubernetes Secrets, In Memory.

The `CertificateManager` interface should describe a collection of methods for configuring and working with certificate manager options (that is software that will issue and manage certificates). Implement `CertificateManager` for Vault and Tresor`. Update `ads` flags, helm chart, and osm cli options accordingly.

**Comment by shashankram** [comment]
Closing this as the certificate related code has evolved a lot since the issue was filed.
