### ISSUE TITLE
Refactor how azureResource/VM is configured in ads

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1036]
Right now, to configure the osm-controller with access to an application running on a VM, a user can use the `--azureAuthFile` flag. This is a bit hard to understand. If the `--azureAuthFile` flag is given to `osm-controller`, then it will be configured to watch for changes on  `AzureResource` Kubernetes resources. `AzureResource` is custom CRD we created to help keep track of Azure compute resources (Azure VMs) so that `osm-controller` can fetch endpoints of services running on that set of Azure VMs.

We need to figure out how to represent VMs in a pluggable way so we can support multiple VM platforms. This issue should be tackled as part of #1035.

**Comment by draychev** [comment]
The Azure VM code has been removed from the repo.
