### ISSUE TITLE
Update osm-controller rbac to allow it to watch, list, read `AzureResource` objects in Kubernetes. Remove dependency on kubeconfig file.

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1037]
Update osm-controller rbac to allow it to watch, list, read `AzureResource` objects in Kubernetes. By granting access for this in the `osm-controller` helm chart where rbac is configured, we'll be able to remove the dependency of `osm-controller` on the kubeconfig file and can remove the `--kubeconfig` flag entirely.

**Comment by draychev** [comment]
AzureResource was removed from the OSM repo.
