### ISSUE TITLE
High Availability for OSM Controller

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1045]
Current version of OSM Controller as of this writing (7/7/2020) is a single pod.
This issue is to brainstorm, design, and implement a highly available and redundant control plane.

A few facts true as of this writing:
  - OSM Controller is stateless - could be easily sharded / replica count of Deployment increased
  - XDS Relay is an excellent prospect for providing Envoy connection dispersement across more pods

**Comment by fredstanley** [comment]
Hey,
I am interested in knowing the limits/bench marks of a single OSM controller PODs.
Also wondering when HA will be available for OSM controllers ?

Thanks!

**Comment by draychev** [comment]
> I am interested in knowing the limits/bench marks of a single OSM controller PODs.
> Also wondering when HA will be available for OSM controllers ?

Hi @fredstanley, Open Service Mesh is not production ready yet. At this point it is a reference implementation of SMI Spec.  We have done some preliminary benchmarks, but since the code base is moving fast, our measurements are stale at this point.
 
We have HA on the road map, but have not committed to a particular ETA.  We need to ensure we have a stable and fast OSM controller and 100% SMI implementation, and then focus on HA.

**Comment by draychev** [comment]
@fredstanley We split the original issue into
  - High Availability https://github.com/openservicemesh/osm/issues/1045 (this issue)
  - Scalability https://github.com/openservicemesh/osm/issues/291

We are going to focus on Scalability https://github.com/openservicemesh/osm/issues/1045 in the near term.

**Comment by draychev** [comment]
@fredstanley, thanks for your patience with this issue.  We have been working hard to make OSM truly SMI-native, and to get it stable and reliable. We'll spend the next few weeks shifting more of our focus on high availability and scalability.

@fredstanley while we are working on HA - I want to ask you for any specific requirements that you may have in your environment. Is there any specific recommendation you can make?

**Comment by fredstanley** [comment]
@draychev As we are based of k8 environment. we wanted the following
1. We wanted to scale the osm-controller to many replicas. That in-turn help us scale our k8 cluster services without any issues. Today all the services/deployments in the cluster talk to just one osm-controller.
2. I assume OSM is stateless. If there are some stateful data, we might need some mechanism so that all instances osm are in sync in a multi instance environment.

**Comment by eduser25** [comment]
hey @fredstanley, thanks for keeping us up on this. We are actively working to verify all works as intended in multi-replica.
(1) Last week we [closed a bug](https://github.com/openservicemesh/osm/pull/2539) that was preventing envoys to be able to connect to multiple OSM instances. You should now be able to deploy multi-replica and have the envoys connect to multiple OSMs.
(2) We should be documenting few more details of the underlying architecture shortly on `DESIGN.md`, but overall you are right. OSM is stateless, no synchronization is needed between the instances.

**Comment by eduser25** [comment]
https://github.com/openservicemesh/osm/blob/main/docs/content/docs/HA.md
@fredstanley 

We will keep testing, we plan to enable pipelines to test multi instance by default as soon as we fix some resource constraints.
