### ISSUE TITLE
Clean up relevant caches when a Pod is terminated

### ISSUE THREAD

**Issue by aanandr** [openservicemesh/osm#1071]
If a user with the right permissions deletes a Pod, what happens? Does the envoy get cleaned up automatically by K8S? Does OSM cleanup the certificates?

**Comment by aanandr** [comment]
So
1. Certs are not removed. This will result in lots of unused certs lying around.
2. For policies looks like OSM knows that there is no Pod associated with them. Does it then remove the policies from its database? Basically, does it cleanup?

**Comment by draychev** [comment]
This is a great issue. Let's work on cleaning the caches and other OSM artifacts when a Pod is deleted / terminated. This is a much needed performance optimization. The goal wolud be to ensure we don't have ever-growing caches.

The idea is for the Endpoints provider to signal to the rest of the system that cache for a given endpoint needs to be cleaned up. Cert manager then could delete this cert / remove from cache. This of course needs to be e2e tested.

**Comment by draychev** [comment]
This issue depends on (is partially implemented by) #1719

**Comment by draychev** [comment]
Closing in favor  #1719
