### ISSUE TITLE
Work with Flagger community to update SMI support to latest version

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#1081]

**Comment by stefanprodan** [comment]
I'm confused by the SMI implementation in OSM. Looking at the code it seems that OSM supports HTTP header routing but it installs TrafficSplit v1alpha2 that doesn't have header filters, that's [v1alpha3](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md).

**Comment by shashankram** [comment]
Upgrading traffic split to v1alpha3 is a WIP: https://github.com/openservicemesh/osm/issues/705

**Comment by michelleN** [comment]
depends on #705

**Comment by michelleN** [comment]
Flagger 1.18 now supports the latest versions of traffic split and can be used with OSM. https://github.com/fluxcd/flagger/pull/897
