### ISSUE TITLE
Document process for building binaries for CLI for release attachment

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#1083]

**Comment by michelleN** [comment]
I believe this is already documented @phillipgibson. Can this be closed?

**Comment by bridgetkromhout** [comment]
The binaries are built as part of the GitHub action in https://github.com/openservicemesh/osm/blob/main/.github/workflows/release.yml

This is documented in https://github.com/openservicemesh/osm/blob/main/docs/content/docs/release_guide.md.
