### ISSUE TITLE
update osm-controller/control plane configuration via the osm cli

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1139]
**Please describe the Improvement and/or Feature Request**

There should be a way via the CLI to update a control plane's configuration. 
`osm update MESH_NAME --flags`

**Scope**
- [ ] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [x] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] CI System

**Possible use cases**
As a user, I may install the control plane in permissive mode (allow all traffic, smi access control disabled). Then, I may want to switch to using SMI access control policies. I need to disable permissive mode. I'd like to do this via the CLI instead of manually updating the ConfigMap.

**Comment by nitishm** [comment]
I can pick this up if it is as simple as doing an update on the ConfigMap using k8s client-go (or whatever library or abstraction is used)

**Comment by nitishm** [comment]
@michelleN What flags would we support in the initial version of the `update` command? Should we start with just toggling in the permissive on and off ?

**Comment by shashankram** [comment]
> @michelleN What flags would we support in the initial version of the `update` command? Should we start with just toggling in the permissive on and off ?

Ideally we would like the CLI to be able to update any of the user exposed settings in `osm-config` configMap, currently its every setting in the configMap.

**Comment by nitishm** [comment]
> > @michelleN What flags would we support in the initial version of the `update` command? Should we start with just toggling in the permissive on and off ?
> 
> 
> 
> Ideally we would like the CLI to be able to update any of the user exposed settings in `osm-config` configMap, currently its every setting in the configMap. 

Would something similar to helm's --set work? This would allow us to write the cmd code once and make it generic or agnostic to the parameters in the ConfigMap (treating them as map[string]string)

**Comment by michelleN** [comment]
Hey @nitishm ! yea so that's what I was thinking as well. We use helm client libraries under the hood to install an osm chart (bulk of that logic lives [here](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L216-L222)). We override the default values with the flag values passed in [here](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L228-L249).

Let's add an `$ osm mesh update <mesh-name>` command that takes the same flags as the install command and then does a essentially a `helm upgrade --set` under the hood using helm libraries. [Here](https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L65) is how helm instantiates a new upgrade client for example. We'll want to do the same. Then, resolve the flags to values and pass them into when we run the upgrade action via helm.

Lmk if you have any questions and feel free to even put up a work in progress pull request if you need another set of eyes on things.

**Comment by nitishm** [comment]
> Hey @nitishm ! yea so that's what I was thinking as well. We use helm client libraries under the hood to install an osm chart (bulk of that logic lives [here](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L216-L222)). We override the default values with the flag values passed in [here](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L228-L249).
> 
> Let's add an `$ osm mesh update <mesh-name>` command that takes the same flags as the install command and then does a essentially a `helm upgrade --set` under the hood using helm libraries. [Here](https://github.com/helm/helm/blob/master/cmd/helm/upgrade.go#L65) is how helm instantiates a new upgrade client for example. We'll want to do the same. Then, resolve the flags to values and pass them into when we run the upgrade action via helm.
> 
> Lmk if you have any questions and feel free to even put up a work in progress pull request if you need another set of eyes on things.

Sounds good to me!! 
Created a WIP PR - #1474

**Comment by nitishm** [comment]
So I looked at the `mesh_delete_test.go` test code and it makes sense to populate the store with a mock release and use the store in the mock helm client. 
```go
rel := release.Mock(&release.MockReleaseOptions{Name: meshName})
store.Create(rel)
```

The issue that I am facing with update is that `updateCmd` similar to `installCmd` needs a kubernetes.Clientset to be configured to carry out the upgrade (whereas in mesh delete it uses ` *action.Uninstall` to uninstall the mesh).

If I follow the `install_test` examples, we use the fake k8s clientset to simulate the tests. 

Now the question is how do I associate the fake clientset with the fake `release.Mock` with the pre-programmed `release` added to it's store, since the clientset is not set to use the same context as the release store.

Or maybe I am looking at it all wrong and I need to reconsider, either the design of the `updateCmd` or the design of suite test ?!

**Comment by nitishm** [comment]
FYI: This is what I tried, but to no avail
```go
package main

import (
	"bytes"
	"io/ioutil"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"k8s.io/client-go/kubernetes"
	fake "k8s.io/client-go/kubernetes/fake"

	helm "helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/chartutil"
	kubefake "helm.sh/helm/v3/pkg/kube/fake"
	"helm.sh/helm/v3/pkg/release"
	"helm.sh/helm/v3/pkg/storage"
	"helm.sh/helm/v3/pkg/storage/driver"
)

var _ = Describe("Running the update command", func() {

	Describe("with vault overriding tresor", func() {
		var (
			out           *bytes.Buffer
			store         *storage.Storage
			config        *helm.Configuration
			err           error
			fakeClientSet kubernetes.Interface
			ch            *chart.Chart
		)

		BeforeEach(func() {
			out = new(bytes.Buffer)
			store = storage.Init(driver.NewMemory())
			if mem, ok := store.Driver.(*driver.Memory); ok {
				mem.SetNamespace(settings.Namespace())
			}

			config = &helm.Configuration{
				Releases: store,
				KubeClient: &kubefake.PrintingKubeClient{
					Out: ioutil.Discard,
				},
				Capabilities: chartutil.DefaultCapabilities,
				Log:          func(format string, v ...interface{}) {},
			}

			ch, err = loader.Load("testdata/test-chart")
			if err != nil {
				panic(err)
			}
			rel := release.Mock(&release.MockReleaseOptions{Name: defaultMeshName, Chart: ch})
			store.Create(rel)

			fakeClientSet = fake.NewSimpleClientset()

			config = &helm.Configuration{
				Releases:     store,
				Capabilities: chartutil.DefaultCapabilities,
				Log:          func(format string, v ...interface{}) {},
			}

			updateCmd := &updateCmd{
				out: out,
				cfg: actionConfig{
					chartPath:                  "testdata/test-chart",
					containerRegistry:          testRegistry,
					containerRegistrySecret:    testRegistrySecret,
					osmImageTag:                testOsmImageTag,
					certManager:                "vault",
					vaultHost:                  testVaultHost,
					vaultToken:                 testVaultToken,
					vaultRole:                  testVaultRole,
					vaultProtocol:              "http",
					serviceCertValidityMinutes: 1,
					prometheusRetentionTime:    testRetentionTime,
					meshName:                   defaultMeshName,
					enableEgress:               true,
					enableMetricsStack:         true,
					meshCIDRRanges:             testMeshCIDRRanges,
				},
				clientSet: fakeClientSet,
			}

			err = updateCmd.run(config)
		})

		It("should not error", func() {
			Expect(err).NotTo(HaveOccurred())
		})

		It("should give a message confirming the successful install", func() {
			Expect(out.String()).To(Equal("OSM successfully updated in namespace [osm-system] with mesh name [osm]"))
		})

	})
})

```
