### ISSUE TITLE
rename mesh top level command to control-plane

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1150]
related to #1140 

The `osm mesh` parent command contains a set of sub commands for working with instances of the osm control planes. The term "mesh" is cute but I'm starting to think "control-plane" might be more descriptive and intuitive. What do folks think?

Current and planned future experience:
```console
$ osm mesh delete
$ osm mesh list
```

Proposed experience:
```
$ osm control-plane delete
$ osm control-plane list
$ osm control plane status
# ... etc
```

**Comment by shalier** [comment]
@michelleN can you follow up on this issue?

**Comment by shashankram** [comment]
In #1140, we decided to continue to use the term `mesh ` instead of `control-plane`: https://github.com/openservicemesh/osm/issues/1140#issuecomment-781586315. This issue is no longer necessary.
