### ISSUE TITLE
expose osm-controller version

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1152]
**Please describe the Improvement and/or Feature Request**
Thanks to #1149, we now have the CLI version but we also need to figure out a user could get the version of `osm-controller` version. Should we get this information from the helm release which contains the osm-controller image tag? or should we have an endpoint on osm-controller that returns version info? What should the cli experience be to expose this info?

**Scope**
- New Functionality

**Possible use cases**
As a user, I'd like to understand what version of osm-controller I am running so I have that information for debugging purposes.

**Comment by nitishm** [comment]
@michelleN i would love to take on this task with some initial guidance. Can I pick this up?

**Comment by draychev** [comment]
@nitishm this is all yours if you want it!

**Comment by nitishm** [comment]
> Should we get this information from the helm release which contains the osm-controller image tag?

This would tie us to a helm based deployment model. I think the latter, 
> an endpoint on osm-controller that returns version info
would be the best approach in the long run.

**Comment by shashankram** [comment]
> > Should we get this information from the helm release which contains the osm-controller image tag?
> 
> This would tie us to a helm based deployment model. I think the latter,
> 
> > an endpoint on osm-controller that returns version info
> > would be the best approach in the long run.
> 
> @draychev @michelleN WDYT?

You can retrieve the information from the controller pod by port-forwarding to the controller pod via the cli. cli already does this for a few commands namely `osm dashboard`, `osm proxy dump-config`

**Comment by nitishm** [comment]
@shashankram correct me if I am wrong. For this task I will need to add a `/version` route to `pkg/httpserver` and then use port forward from the CLI to request that endpoint.

**Comment by shashankram** [comment]
> @shashankram correct me if I am wrong. For this task I will need to add a `/version` route to `pkg/httpserver` and then use port forward from the CLI to request that endpoint.

If you go with the approach of exposing a `/version` endpoint on the osm-controller HTTP server then yes.

**Comment by shashankram** [comment]
@johnsonshi worked on a similar issue that displays the version of the control plane for a given mesh by deriving the version based on the labels added to the osm-controller deployments.
```
$ osm mesh list

MESH NAME   NAMESPACE        CONTROLLER PODS                   VERSION   SMI SUPPORTED
osm         arc-osm-system   osm-controller-744866fdfb-xb6xv   v0.8.4    Unknown
```

This issue seems pretty much the same as https://github.com/openservicemesh/osm/issues/2848 which was resolved. Closing this.
