### ISSUE TITLE
Secure the scraping of Envoys by Prometheus

### ISSUE THREAD

**Issue by aanandr** [openservicemesh/osm#1167]
**Please describe the Improvement and/or Feature Request**
There are two ways to use Prometheus to scrape metrics today
1. Using Prometheus instance that is already present in the customer's cluster
2. Customer deploys Prometheus just for the mesh

In both these cases communication between Prometheus and the Envoys is clear text. The purpose of this improvement request is to explore options to secure this communication.

**Scope**
- [ ] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [x ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] CI System

**Possible use cases**

**Comment by draychev** [comment]
We researched this, experimented with it, and determined that it is not something we are going to pursue.
