### ISSUE TITLE
Client pod without service cannot talk to other services 

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1180]
Feedback from @jocortems - when you install OSM by default and it is in permissive (allow all) traffic mode - individual pods without a service are not allowed to comminucate with other pods/services.

The allow-all mode we observe services and allow each service to communicate with every other service.
Pods that do not belong to a service need to be included as well.

For example - if I install the bookstore example, then spin up a new pod (I'll call in nettools) and try to curl the bookstore from the nettools pod - it should work. Currently this is not allowed.

**Comment by shashankram** [comment]
This issue is true with SMI mode as well, and needs to be resolved.

**Comment by aanandr** [comment]
Glad that it is working the same way in both modes.
All along we have been talking only in terms of services, i.e. policies are always defined for service (or in other words service accounts). Now we have to make a fundamental paradigm shift and say that both Pods and services can be in a mesh. I am wondering whether it is required. If we expose that single Pod as a service does everything work?

**Comment by draychev** [comment]
ref: https://github.com/openservicemesh/osm/pull/1745
