### ISSUE TITLE
When you unjoin all namespaces from the mesh - curling bookstore.bookstore:8080 does not work

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1181]
Per @jocortems - when you unjoin all namespaces from the mesh - curling bookstore.bookstore:8080 does not work.
cURL bookstore-v1.bookstore:8080 works as expected

**Comment by ksubrmnn** [comment]
@draychev can you add more details for the repo? Where are you curling from? How is osm configured? etc

**Comment by shashankram** [comment]
This is a caveat of using the top-level `bookstore` service in the demo which was only to be used when SMI traffic split service exists. With the new demo guide, when a namespace is removed from the mesh, the user needs to ensure that the HTTP request is being sent to an actual service FQDN who has pods backing it, and not an SMI apex service that does not have pods backing it.

**Comment by draychev** [comment]
I believe the issue revolved around the synthetic service and other primitives that are now long gone.
This is no longer an issue.
