### ISSUE TITLE
osm namespace add should fail when adding osm-system NS

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1196]
No! But you know what - we should make sure this errors out really loudly so it does not happen by accident!

_Originally posted by @draychev in https://github.com/open-service-mesh/osm/pull/1193#discussion_r459853647_

**Comment by Sheshagiri** [comment]
I would like to give this a shot.
I'm assuming we can add a condition in https://github.com/openservicemesh/osm/blob/main/cmd/cli/namespace_add.go#L63-L75 that does the namespace name(`osm-system` in this case) check.

**Comment by ksubrmnn** [comment]
@Sheshagiri you can get deployments from the namespace and see if there is an osm-controller there. See https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L205

**Comment by shashankram** [comment]
If I understand correctly, this check should not just handle `osm-system`, but any namespace where `osm-controller` can be installed. Please take this into consideration, since the namespace where OSM is installed to is configurable.
