### ISSUE TITLE
Define which releases should be marked as pre-releases

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1238]
GitHub releases can either be marked as the "latest" or a "pre-release." The only functional difference I've noticed between them is that the "latest" release can be pointed to by github.com/\<repo\>/releases/latest in addition to github.com/\<repo\>/releases/tags/\<tag\> whereas pre-releases only get the link for their specific tags.

We should determine a convention for when to use each kind of release and automate that in the release GH Action if possible.

**Comment by snehachhabria** [comment]
We have a pretty well defined process for release and pre-releases now, closing this issue
