### ISSUE TITLE
Determine which Docker image tags we should push for each release

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1239]
Currently, the release GH Action will push tags named "latest" and the release's git tag on each release. Most projects strip the leading "v" from a tag if it exists for their container image tags and push other floating tags like `MAJOR.MINOR` and `MAJOR` in addition to `MAJOR.MINOR.PATCH`. We should determine if those are things we'd like to also implement for OSM.

**Comment by shashankram** [comment]
The release process has gone through several iterations since this issue was filed ~10 months ago.

Documentation: https://github.com/openservicemesh/osm/blob/main/docs/release_guide.md
