### ISSUE TITLE
Expose XDS protos to end user

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1259]
Exposing XDS protos to end users allows users to configure the envoy sidecars directly without requiring SMI. 

**Scope (please mark with X where applicable)**
- [X] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [X] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Comment by michelleN** [comment]
closing in favor of #1376
