### ISSUE TITLE
Root Cert Rotation

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1260]
We assume that root cert is long lived and will never change.
When we need to rotate the root cert used by OSM for one reason or another we may have to take different paths based on which cert issuer is used by OSM.

For `pkg/tresor` there is no root cert rotation mechanism other than:
  1. delete the current "osm-ca-bundle" secret 
  2. create new / different / own "osm-ca-bundle" secret 
  3. "kubectl rollout restart deployment -n osm-system osm-controller"
  4. "kubectl rollout restart deployment ..." all other deployments that are in the mesh
  
We need to design, develop, and test a root cert rotation mechanism, which will ensure zero-downtime rotation of the root cert.

--- 

# Related
  - doc: Certificates and Rotation (#2860)
  - Root Cert documentation: https://github.com/openservicemesh/osm/blob/707593c3a291ec9ac4a3e92836d8776cb3d84ce3/docs/content/docs/tasks_usage/certificates.md#root-certificate

**Comment by draychev** [comment]
Related to https://github.com/openservicemesh/osm/issues/507

**Comment by michelleN** [comment]
This requires a [design doc](https://github.com/openservicemesh/osm/tree/main/docs/design) before implementing.

**Comment by snehachhabria** [comment]
closing this in lieu of new issue.
