### ISSUE TITLE
(docs): Document usage patterns

### ISSUE THREAD

**Issue by lachie83** [openservicemesh/osm#1286]
I've placed what I think are usage patterns in this directory. I would like this to be reference for how users are supposed to interact with OSM. For example ingress/egress behaviours for example.

https://github.com/openservicemesh/osm/tree/main/docs/patterns

Should be linked here - https://github.com/openservicemesh/osm#osm-usage-patterns

**Comment by SanyaKochhar** [comment]
@lachie83 there seem to be some usage patterns documented now. Are these sufficient and if so, can this be closed?

**Comment by shashankram** [comment]
Usage patterns are documented in https://docs.openservicemesh.io/docs/tasks_usage/, closing this.
