### ISSUE TITLE
Update RDS to handle a list of service hostnames while aggregating routes per host basis

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1316]
While building aggregated routes, RDS expects the hostnames returned by the call to `MeshCatalog` to be a string, with multiple hostnames being comma separated. This is hack and should be fixed to ensure a list of strings can be returned by the catalog instead of a comma separated hostnames in a string.

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [X] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Comment by ksubrmnn** [comment]
Is there a reason we cannot get a list of domains and then call aggregateRoutesByHostName once per domain in the list?

**Comment by shashankram** [comment]
> Is there a reason we cannot get a list of domains and then call aggregateRoutesByHostName once per domain in the list?

It should be doable, don't know if the code handles it but it seemed like the code was written with the assumption that there will just be one hostname. Feel free to refactor as appropriate.

**Comment by ksubrmnn** [comment]
> > Is there a reason we cannot get a list of domains and then call aggregateRoutesByHostName once per domain in the list?
> 
> It should be doable, don't know if the code handles it but it seemed like the code was written with the assumption that there will just be one hostname. Feel free to refactor as appropriate.

@snehachhabria do you know offhand if anything is blocking this? I remember trying to do this and being told it wouldn't work. Otherwise, I can try it
