### ISSUE TITLE
create a quick gif to show osm demo

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1335]
should have:
1. osm install
2. osm namespace add
3. deploy apps
4. show sidecars running

other ideas welcome

**Comment by michelleN** [comment]
let's add these somewhere in the docs. I'm not sure where to place them. Any ideas? and thank you @eduser25

**Comment by phillipgibson** [comment]
@eduser25 let's collaborate on this as we structure the repo on where these should land.
