### ISSUE TITLE
Configure dataplane without using TrafficSplit

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1370]
At the moment, we need an initial TrafficSplit object (as seen in [example usage guide](https://github.com/openservicemesh/osm/tree/main/docs/example)) to properly configure the data plane for applications (domains on Envoys). Define and implement how to enable a workflow in which the user doesn't need to create a TrafficSplit to use OSM.

**Comment by ksubrmnn** [comment]
@michelleN @snehachhabria can you add more detail to this? Bit confused on the exact config needed to repro this issue as we have a CI test with no split already

**Comment by michelleN** [comment]
This is complete with the routes v2 refactor.
