### ISSUE TITLE
investigate packages link option

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm#1386]
There is a "packages" option we aren't currently using, but could. Let's look in https://github.com/features/packages and see if we want that. For now, I have ticky-boxed it off.

![image](https://user-images.githubusercontent.com/2104453/89419679-43253700-d6f7-11ea-968c-8a40b01de679.png)

**Comment by nojnhuh** [comment]
@bridgetkromhout Is this specific issue only about adding the packages link to the front page of the repo, or also about actually utilizing GitHub packages and publishing releases there?

**Comment by bridgetkromhout** [comment]
> Is this specific issue only about adding the packages link to the front page of the repo, or also about actually utilizing GitHub packages and publishing releases there?

@nojnhuh This specific issue is intended for us to investigate if we want to do the kind of package-publishing that would show up on github under that link.

For now, I turned the link off because otherwise it sits there empty and adds nothing to the front page.

**Comment by bridgetkromhout** [comment]
I'm closing this issue as it seems unnecessary; if and when we start using github package publishing, we can update https://github.com/openservicemesh/osm/blob/main/docs/content/docs/release_guide.md.
