### ISSUE TITLE
osm command for verifying mTLS connection between two services

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1388]
**Please describe the Improvement and/or Feature Request**

`osm` command for verifying traffic encryption

**Possible use cases**

As a user, I want an easy way through the `osm` cli to verify that traffic between two services is indeed encrypted.

**Comment by draychev** [comment]
Similar is the following GitHub issue, which will determine whether traffic is allowed between 2 pods: https://github.com/openservicemesh/osm/issues/1945

**Comment by draychev** [comment]
I am a huge fan of this tool (yet to be designed).
Having this would answer the following questions:
1) do both pod A and pod B are belong to namespace(s) participating in the mesh
2) are there sidecars installed for both pods (no sidecar could point to old-pod/new-mesh; broken webhook; cert issue etc)
3) is there a policy to allow both pods to communicate
4) are there certs issued; are they current or expired
...

**Comment by shashankram** [comment]
> As a user, I want an easy way through the `osm` cli to verify that traffic between two services is indeed encrypted.

One needs to use packet capture tool and verify that the traffic between apps is encrypted. The implementation of this is outside the scope of the OSM project. 

https://github.com/clarenceb/osm-mtls-check describes how this can be done.
