### ISSUE TITLE
add instructions for manually testing traffic encryption in example usage guide

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1390]
Add to the [traffic encryption section](https://github.com/openservicemesh/osm/blob/6989d0b977e20378a93c825178720dee67abf437/scripts/get-pcap-bookstore.sh). Can also link in that section to a different file.

Use:
https://github.com/openservicemesh/osm/blob/6989d0b977e20378a93c825178720dee67abf437/scripts/get-pcap-bookstore.sh

**Comment by draychev** [comment]
@shashankram had a great demo today, which showed how to prove that traffic is encrypted end to end.
We could add the method @shashankram used to our docs.

**Comment by michelleN** [comment]
On WSL, this can be done via a combination of the following tools: wireshark/tshark/tcpdump + ksniff (https://github.com/eldadru/ksniff).

On Mac, it's simpler to do via https://github.com/eldadru/ksniff

Thank you for the tips @shashankram
