### ISSUE TITLE
Add checklist to release guide

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1406]
Something like https://helm.sh/docs/community/release_checklist/

Decisions we made for v0.1.0 that we should finalize and document in the release guide:
- Releases will be cut from a `release-vMAJOR.MINOR` branch

- Update versions accordingly: 

version | `main` branch | `release-vX.Y` branch
-|-|-
default `--osm-image-tag` for `osm install` | new version tag | new version tag
`appVersion` in Chart.yaml | new version tag | new version tag
`image.tag` in values.yaml | `latest` | new version tag

Yet to Discuss
- When we merge bug fixes into `main`, how should we cherry pick them into the appropriate release branches?

**Comment by bridgetkromhout** [comment]
The checklist used for the first release:

- Enter desired release number on the main branch, like v.0.1.0 
- Create a release branch called release-v0.1.0 	 
- Send PRs/commits to that branch which updates the chart AppVersion and default image tag version 
- Cut a release by checking out the release branch and pushing a tag v0.1.0 to origin which will kick off the GitHub Action to cut all the artifacts

**Comment by bridgetkromhout** [comment]
Release guide: https://github.com/openservicemesh/osm/blob/main/docs/content/docs/release_guide.md

**Comment by nojnhuh** [comment]
The release guide is largely done. We've been making small updates as needed, but no large pieces are missing that I'm aware of. If we need to make any significant additions, we can open separate issues to track those. The work captured by this issue is done.
