### ISSUE TITLE
ci: Prevent typos from sneakin ginto the repository

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1407]
The "misspell" checker from Go Report Card found a few typos: https://goreportcard.com/report/github.com/openservicemesh/osm

**Comment by Yogendra0Sharma** [comment]
@nojnhuh can I work on this issue? please assign it to me.

**Comment by nojnhuh** [comment]
Absolutely! Thanks.

**Comment by nojnhuh** [comment]
Hi @Yogendra0Sharma, is this still in progress? I'm happy to help if you'd like.

**Comment by shashankram** [comment]
The misspell checker shows https://goreportcard.com/report/github.com/openservicemesh/osm#misspell a 100% score 
![image](https://user-images.githubusercontent.com/21697719/119204669-e3f89f00-ba4a-11eb-8a9f-84ae95c7521f.png)
