### ISSUE TITLE
osm doesn't install on GKE

### ISSUE THREAD

**Issue by anubhavmishra** [openservicemesh/osm#1415]
**Bug description**: Installing osm on GKE cluster via `osm install` doesn't work.

Here is the error that I see:

```bash
osm check --pre-install
ERROR: initialize Kubernetes client
        no Auth Provider found for name "gcp"
Error: Checks failed
```

**Affected area (please mark with X where applicable)**:
- [x] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**: osm installs successfully on a GKE cluster.

**Steps to reproduce the bug (as precisely as possible)**: Spin up a GKE cluster and install osm using `osm install`.

**How was OSM installed?**: 

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: 9e23a75; Date: 2020-08-05-15:59`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by lachie83** [comment]
Possibly related - https://github.com/kubernetes/client-go/issues/242

**Comment by youngnick** [comment]
Doing a first tryout of this myself, looks like @lachie83 got this one right, I did the "fix" listed in kubernetes/client-go#242, built a dev version, and `osm install` then worked fine on a GKE cluster.

The "fix": importing client-go auth plugins in `cmd/cli/install.go`.
```go
import (
       // elide the usual imports
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)
```

Seems pretty dirty, but it *is* a fix.

**Comment by shashankram** [comment]
> Doing a first tryout of this myself, looks like @lachie83 got this one right, I did the "fix" listed in [kubernetes/client-go#242](https://github.com/kubernetes/client-go/issues/242), built a dev version, and `osm install` then worked fine on a GKE cluster.
> 
> The "fix": importing client-go auth plugins in `cmd/cli/install.go`.
> 
> ```go
> import (
>        // elide the usual imports
> 	_ "k8s.io/client-go/plugin/pkg/client/auth"
> )
> ```
> 
> Seems pretty dirty, but it _is_ a fix.
> 
> I can send a PR if you like, assuming I can pass the CLA gate. :)

A PR is very much welcome @youngnick :-)

**Comment by cjaliaga** [comment]
Currently having the same issue with an AKS cluster with AzureAD enabled, I think this fix should also mitigate that one :)

`panic: no Auth Provider found for name "azure"`

Thanks @youngnick!!

**Comment by youngnick** [comment]
Just have to jump through some CLA hoops before I can open the PR.

**Comment by youngnick** [comment]
Just to be clear here, I need to get internal signoffs for this, may take a while. If anyone else wants to pick up the change, feel free.

**Comment by shashankram** [comment]
> Just to be clear here, I need to get internal signoffs for this, may take a while. If anyone else wants to pick up the change, feel free.

Why do you need internal signoffs? Could you create a PR from your fork.

**Comment by youngnick** [comment]
It's for signing the CLA. :(

**Comment by shashankram** [comment]
> It's for signing the CLA. :( (Which I want to do so I can add Contour to the Ingress docs later).

@youngnick Could you open a PR, you should be able the sign the CLA on Github. Or is there some other issue I am not understanding?
If you have an open PR, I can help you with it.

Would love to see Contour ingress integration!

**Comment by youngnick** [comment]
The only issue is that I need my work's legal to give me the all-clear on signing the CLA before I do. Once they've done that, I'll get everything PRed. It's only a one-line change, so it's no big deal, just got to make sure I do the legal thing right first.

**Comment by youngnick** [comment]
Okay, all approved, I opened the PR for this fix.
