### ISSUE TITLE
Make the demo deployable without private resources (other than K8s)

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1416]
Currently some of the demo scripts might assume the need to push locally compiled images in a private registry. 
Since the OS launch, we have official images sitting in dockerhub; this is potentially not strictly needed anymore and would shorten the requirement list and speed up a new user with intention to play with OSM.

**Scope (please mark with X where applicable)**
- [X] Install

**Possible use cases**
New user who wants to play with OSM, can checkout OSM and run the demo with upstream images out of the box with no intermediate steps.

**Comment by nshankar13** [comment]
Hi @eduser25 , is this resolved / ready to be closed?

**Comment by eduser25** [comment]
this is resolved.
