### ISSUE TITLE
Notarize published macOS binaries

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1427]
Currently, published macOS binaries will not execute the first time they're executed because they are not notarized. You can workaround this by either re-downloading from outside a browser (like with `wget` or a package manager) or with a few manual steps as documented [here](https://github.com/openservicemesh/osm/issues/1414#issuecomment-669980618) in the meantime.

**Comment by michelleN** [comment]
@nojnhuh - what are the steps to publish a notarized macos binary? Do we need a developer account or something with apple?

**Comment by nojnhuh** [comment]
I've never done this before and don't know exactly what the whole process entails, but I would imagine that's one step.

**Comment by nojnhuh** [comment]
It looks like macOS only complains about the binary not being signed and notarized when it's downloaded from a browser, per https://github.com/helm/helm/issues/6615#issuecomment-551108259. Installing via something like `wget` or a package manager won't throw the same error. I tried `brew install osm` and it worked fine without any errors the first time it's run.

**Comment by nojnhuh** [comment]
Given that installing via homebrew doesn't exhibit errors related to the binary not being signed/notarized, we're going to prioritize improving the homebrew installation over this for the time being.
