### ISSUE TITLE
make osm cli available via homebrew

### ISSUE THREAD

**Issue by Sheshagiri** [openservicemesh/osm#1428]
**Please describe the Improvement and/or Feature Request**
This is more of a feature request rather than a bug. Making the cli available via homebrew will make the installation of the cli easier on macos.

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [x] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

If it's okay I can give this a try :)

**Comment by michelleN** [comment]
Hey @Sheshagiri - Thanks for your submission. This is a duplicate issue of #868. I'm going to close this in favor of #868 which is currently in progress. Hope to get this available via homebrew asap.
