### ISSUE TITLE
Naming clash with JetStack's cert-manager

### ISSUE THREAD

**Issue by alexellis** [openservicemesh/osm#1440]
**Please describe the Improvement and/or Feature Request**

There is a naming clash with `osm install --cert-manager=vault` with the very well-known project cert-manager from JetStack. https://cert-manager.io

I found this usage of a well-known project as a flag for something very different to be confusing, and other users may have the same reaction. 

https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L112

I also wondered what `tresor` was? I couldn't find anything about it on Google / GitHub, so I wondered if it was a typo, or if it needs bubbling up higher in docs + SEO?

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [x] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Possible use cases**

An alternative could be `osm install --cert-store=vault/tresor`?

**Comment by lachie83** [comment]
Thanks for raising this Alex. We will definitely investigate and see what we can do to make this less confusing

**Comment by shashankram** [comment]
Hi @alexellis , thanks for reporting this. We will look into addressing this ambiguity.

> I also wondered what tresor was? I couldn't find anything about it on Google / GitHub, so I wondered if it was a typo, or if it needs bubbling up higher in docs + SEO?

`tresor` is a custom certificate management facility provided by OSM.

**Comment by lachie83** [comment]
Docs on `tresor` - https://github.com/openservicemesh/osm/blob/main/docs/patterns/certificates.md#using-osms-tresor-certificate-issuer

**Comment by nitishm** [comment]
@michelleN @lachie83 Is this a CLI code change ? If so can I take a stab at it?

**Comment by shashankram** [comment]
This needs a bit of discussion first before proceeding.

**Comment by shashankram** [comment]
> This needs a bit of discussion first before proceeding.

Looks like you created a PR already, so let's discuss over it directly.

**Comment by michelleN** [comment]
Re-opening so we can discuss this further. I'd be open to renaming this component and/or flag further. Glad we have a quick fix in there with the flag name change but I think maybe we should call this component some kind of of a driver. What do we think about certificates driver ? (Naming is hard lol)

**Comment by nitishm** [comment]
Are the parameters passed to the arg names of secret/certificate stores or
full blown PKIs?

**Comment by maelvls** [comment]
I just noticed this issue. Does it still require attention?

**Comment by shashankram** [comment]
This has been resolved, the term `CertificateManager` is being used to refer to the certificate manager to use in OSM (tresor, vault, etc.)
