### ISSUE TITLE
Error when installing into separate namespaces / "mesh" names

### ISSUE THREAD

**Issue by alexellis** [openservicemesh/osm#1441]
**Bug description**:

I [added an app to arkade for OSM](https://github.com/alexellis/arkade/releases/tag/0.6.0), so that we could run a single command to install OSM along with Linkerd, Istio etc.

```bash
arkade install osm
```

Whilst testing the PR, I tried installing twice and got an error, suggesting that I needed to set `--mesh-name` i.e. `--mesh-name mesh2` when running `osm install`

The check command should in theory also take a `--mesh-name`, but it does not appear to? 

The other issue was that there is also a namespace override for the install command, which defaults to osm-system.

Giving `--mesh-name mesh2` returns an error on install about the namespace not being `osm-system`
Giving `--mesh-name mesh2 --namespace mesh2-osm` returns an error on install about the namespace not being `osm-system` and the mesh name not being `osm`

Could someone check that this usecase is supported, and report back on the UX inconsistencies?

**Affected area (please mark with X where applicable)**:
- [x] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

Latest version from GitHub doing a download, then using `osm install`

**Anything else we need to know?**:

MacOS

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):

KinD 1.18

- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@ksubrmnn would you be able to help with this?

**Comment by ksubrmnn** [comment]
I've identified the issue. When a new mesh name and a new namespace are specified in the first install command, everything works as expected. However, if the user makes an error and doesn't specify a new namespace with the new mesh name, then installation fails but we don't clean up the clusterrole/bindings that have already been created. I'll work on a fix.
