### ISSUE TITLE
brew install support request

### ISSUE THREAD

**Issue by Zheaoli** [openservicemesh/osm#1448]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [x] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Possible use cases**

Would you mind to support `brew install` on macOS to install the binary file?

**Comment by evalsocket** [comment]
@shashankram @Zheaoli Can we use goreleaser for publishing binary including brew  and for publishing CLI tool we can use krew(github.com/kubernetes-sigs/krew)

**Comment by shashankram** [comment]
> @shashankram @Zheaoli Can we use goreleaser for publishing binary including brew and for publishing CLI tool we can use krew(github.com/kubernetes-sigs/krew)

@michelleN , @nojnhuh what do you think about this?

**Comment by UsamaMehboob** [comment]
Hi @shashankram was wondering as a good first issue, would it be possible for me to work on it as I want to get involved. if yes, can anyone help me how should I go about it?
thanks

**Comment by shashankram** [comment]
> Hi @shashankram was wondering as a good first issue, would it be possible for me to work on it as I want to get involved. if yes, can anyone help me how should I go about it?
> thanks

Of course.
@nojnhuh would you be able to provide some pointers to enable `brew` based install.

**Comment by nojnhuh** [comment]
I've personally never used goreleaser before, but it certainly looks promising. If we take a look and find it fits our needs, I see no reason not to use it. The only trouble spot I could see is with the current build process, we run a script to encode the Helm chart and embed that in the binary with `ldflags` [here](https://github.com/openservicemesh/osm/blob/76a4dc8814ed299f98008536f2047c6b96296c36/Makefile#L50), which may not be feasible with goreleaser.

I've never published any packages on Homebrew either, but goreleaser has some docs on that: https://goreleaser.com/customization/homebrew/. If goreleaser doesn't work out, I'd start with [Homebrew's docs](https://docs.brew.sh/).

**Comment by evalsocket** [comment]
@nojnhuh 

> The only trouble spot I could see is with the current build process, we run a script to encode the Helm chart and embed that in the binary with `ldflags` [here](https://github.com/openservicemesh/osm/blob/76a4dc8814ed299f98008536f2047c6b96296c36/Makefile#L50), which may not be feasible with goreleaser.

You can check to go releaser it has  `before` hooks
```
before:
  hooks:
    - go run scripts/generate_chart/generate_chart.go
```

**Comment by Sheshagiri** [comment]
This is actually being implemented in #868

**Comment by shashankram** [comment]
> This is actually being implemented in #868

Closing in favor of #868. I was wondering why I couldn't find a matching issue, I was looking for `brew` instead of `homebrew`.

**Comment by evalsocket** [comment]
@shashankram but nice way is to build binary through goreleaser and then publish them on krew. so a user can download osm on any platform 

```
kubectl krew install osm 
kubectl osm install
```

**Comment by shashankram** [comment]
> @shashankram but nice way is to build binary through goreleaser and then publish them on krew. so a user can download osm on any platform
> 
> ```
> kubectl krew install osm 
> kubectl osm install
> ```

Could you file a separate issue for the goreleaser request?
