### ISSUE TITLE
Add Goreleaser for build and realease binary

### ISSUE THREAD

**Issue by evalsocket** [openservicemesh/osm#1451]
**Please describe the Improvement and/or Feature Request**

The plan is to move from make command to goreleaser(https://github.com/goreleaser/goreleaser) for building and publishing binaries. We can use goreleaser for publishing binary on all platform 

When binaries are available then add krew support(github.com/kubernetes-sigs/krew) for installing a plugin. like

```
kubectl krew install osm
kubectl osm 
```

**Scope (please mark with X where applicable)**
- [ ] New Functionality
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [x] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [x] CI System

**Possible use cases**

**Comment by nojnhuh** [comment]
@evalsocket What exactly is involved with integrating with krew? If it's more than some simple configuration in goreleaser, can you separate that out into a different issue?
