### ISSUE TITLE
Thx

### ISSUE THREAD

**Issue by Redface28** [openservicemesh/osm#1468]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by phillipgibson** [comment]
No details listed in the issue @Redface28. Can you please update the issue with the specifics. Thanks.

**Comment by shashankram** [comment]
Bug filed without any details. Please open a bug with relevant information while filling the details requested in the template, not sure what to make of this one.
