### ISSUE TITLE
Bookstore v2 Service container appears to be listening and redirecting on port 8080

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#1470]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- [X] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [ ] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**:
After deploying bookstore-v2 and traffic split, the UI is not reachable.
**Steps to reproduce the bug (as precisely as possible)**:
Run manual demo
**How was OSM installed?**:
osm install
**Anything else we need to know?**:
From script osm/scripts/port-forward-bookstore-ui-v2.sh contains - kubectl port-forward "$POD" -n "$BOOKSTORE_NAMESPACE" 8082:80
**Environment**:
- OSM version (use `osm version`): v0.2.0
- Kubernetes version (use `kubectl version`): 1.16
- Size of cluster (number of worker nodes in the cluster): 3
- Others:

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/1467

**Comment by shashankram** [comment]
Looks like the manifest file for the manual demo is out of sync, which won't work with the scripts. Reopening the bug to track this change. I also opened #1471 for further improvements to keep the specs in sync.
