### ISSUE TITLE
Use consistent spec files between manual and automated demo

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1471]
The manual and automated demo are using separate spec files. This leads to inconsistency in the code and is harder to maintain. For ex, the automated demo uses bookstore with port 80, while the manual demo uses bookstore with port 8080. 

The goal of this issue is to use a common set of spec files for the manual and automated demo.

**Comment by nojnhuh** [comment]
@shashankram Is the bug label still appropriate here? From the description it doesn't sound like anything is broken.

**Comment by shashankram** [comment]
> @shashankram Is the bug label still appropriate here? From the description it doesn't sound like anything is broken.

Not a bug anymore because the port forwarding scripts work with the manual demo specs. We should converge though because its a maintenance hassle to manage a common set of scripts between the automated and manual demo spec files.

**Comment by shashankram** [comment]
The automated demo is primarily used by developers and in the CI, and requires several customizations to the demo apps to function. To use the same spec files for the automated and manual demo would imply the base manifests would need to be templated.

Closing this issue as there is no need for additional complexity at the moment.
