### ISSUE TITLE
add automation to upgrade homebrew formula during osm release process

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1475]
docs should be added as a section in the [release guide](https://github.com/openservicemesh/osm/blob/main/docs/release_guide.md).

More info [here](https://github.com/openservicemesh/osm/issues/868#issuecomment-671071265).

**Comment by michelleN** [comment]
Already happens. TODO: add reference to that here and close.

**Comment by bridgetkromhout** [comment]
Highlighting this for @nojnhuh & @SanyaKochhar because I don't see anything about homebrew on https://github.com/openservicemesh/osm/blob/main/docs/content/docs/release_guide.md or https://github.com/openservicemesh/osm/blob/main/.github/workflows/release.yml.

**Comment by nojnhuh** [comment]
Homebrew has their own automation set up for this, we don't need to do anything per-release on our side.

e.g. https://github.com/Homebrew/homebrew-core/pull/70466 happened a few hours after https://github.com/openservicemesh/osm/releases/tag/v0.7.0
