### ISSUE TITLE
The ports 8080, 8081, 8082 and 8083 cannot be used with Azure Cloud Shell Web Preview

### ISSUE THREAD

**Issue by patricekrakow** [openservicemesh/osm#1483]
While following the [OSM Manual Demo Guide](https://github.com/openservicemesh/osm/blob/main/docs/example/README.md) using _Azure Cloud Shell_ with a Kubernetes cluster created with _Azure Kubernetes Service (AKS)_, I have not been able to view the following UIs using the _Web Preview_:
- http://localhost:8080 - **Bookbuyer**
- http://localhost:8081 - **bookstore-v1**
- http://localhost:8082 - **bookstore-v2** 
- http://localhost:8083 - **bookthief**

because the _Web Preview_ only supports the following port ranges:
```
Configure port to preview
Valid ports include [1025-8079] and [8091-49151]
```
Would it be OK to change the ports 8080, 8081, 8082 and 8083 into, for instance, 7080, 7081, 7082 and 7083 so it would easily work with the _Web Preview_ of _Azure Cloud Shell_?

**Comment by shashankram** [comment]
It would be simple to change the web UI ports. The challenge is ensuring those ports work in all environments. A more flexible approach would be to allow users to configure what port they would like the UI to be exposed on, so that the defaults can be overridden.

**Comment by tstilwell91** [comment]
Hi @shashankram, can I work on this issue?

**Comment by shashankram** [comment]
> Hi @shashankram, can I work on this issue?

Definitely!
