### ISSUE TITLE
Service Certificate Validity not taken into account until renewal

### ISSUE THREAD

**Issue by JoshVanL** [openservicemesh/osm#1484]
**Bug description**:

The controller has the option to set the TTL for services certificates (Defaulted to 1 day).

```
      --service-cert-validity-minutes int   Certificate TTL in minutes (default 1440)
```
However this TTL is only taken into account when the certificate is rotated. New certificates ignore this option, and are instead valid for 10 years.

**Affected area (please mark with X where applicable)**:
- Install                    [ X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ X]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

All service certificates are signed with a TTL according to the option set.

**Steps to reproduce the bug (as precisely as possible)**:

Set, or leave the default option, for service certificates. Observe service certificate duration as 10 years.

```
{"level":"trace","component":"certificate/CertRotor","time":"2020-08-10T16:44:30Z","file":"rotor.go:51","message":"Cert 457513fb-e7ae-41f1-89bc-09503dfbd127.default.hello-world will not be rotated; expires in 87599h59m59.133044761s; renewBeforeCertExpires is 30s"}
```

**How was OSM installed?**:

` $ ./bin/osm install`

**Anything else we need to know?**:

This issue comes about because although each certificate manager is provided the target validity during startup, it can be overridden when consuming the interface. This is the case in these two places:

https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/injector/webhook.go#L48

https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/injector/patch.go#L38

Which are both using this validity duration:

https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/constants/constants.go#L85

During renewal, it seems like it will do the right thing as the certificate manager will use the duration it was given at startup. For example tresor:

https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/certificate/providers/tresor/certificate_manager.go#L146

I think the fix would be to pass in `nil` when issuing certificates for the side car container, as to not override the certificate managers set option.

**Environment**:
- OSM version (use `osm version`): 0.2.0-main
- Kubernetes version (use `kubectl version`):  1.18
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by shashankram** [comment]
> https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/injector/webhook.go#L48
> 
> https://github.com/openservicemesh/osm/blob/55cf1d42bfd351658f805d181977a07890ec0a67/pkg/injector/patch.go#L38
> 
> Which are both using this validity duration:

@JoshVanL , these 2 certificates are not the service certificates. The first one is the cert issued for the webhook, while the second certificate is the certificate used for the connection between the proxy and the controller. Both of these are meant to use longer certificates and not based on the service certificate validity period. So if the issue with the longer validity period only pertains to these 2 certificates, its not an issue.

The service certificates are issued as follows:
https://github.com/openservicemesh/osm/blob/main/pkg/envoy/sds/response.go#L37

**Comment by JoshVanL** [comment]
@shashankram Understood, thanks for clearing that.

This is a bit of an aside, but why are these certificates valid for effectively forever? What is preventing these certificates being short lived, and why are they being treated differently?

**Comment by shashankram** [comment]
> @shashankram Understood, thanks for clearing that up!
> 
> This is a bit of an aside, but why are these certificates valid for effectively forever? What is preventing these certificates being short lived, and why are they being treated differently?

https://github.com/openservicemesh/osm/blob/main/DESIGN.md#d-service-tls-certificate touches upon this a bit.

The service certificates are the certificates used by the services in the mesh to do mutual-TLS for service-to-service traffic. Short lived certificates are used to reduce the burden of certificate revocation. See https://blog.envoyproxy.io/using-spire-to-automatically-deliver-tls-certificates-to-envoy-for-stronger-authentication-be5606ac9c75 on how using short lived certs help. OSM has adopted this principle for service certificates.

The proxy certificate (for proxy to controller connection) are longer lived because its a part of the control plane infra and and don't need to be rotated as often. 

@JoshVanL let me know if its okay to close this issue since things are working as expected.

**Comment by JoshVanL** [comment]
Thanks for the explanation @shashankram :smile: 

Happy to close!
