### ISSUE TITLE
create a troubleshooting guide

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1488]
Create a troubleshooting guide in `docs/`. It should contain common issues folks may run into while working with OSM.

**Comment by SanyaKochhar** [comment]
@ksubrmnn I see you added some troubleshooting docs in PRs https://github.com/openservicemesh/osm/pull/2377 and https://github.com/openservicemesh/osm/pull/2193. Do they partially address this issue?

**Comment by bridgetkromhout** [comment]
I'll close this because we now have a troubleshooting section on the website: https://docs.openservicemesh.io/docs/troubleshooting/

Let's open individuals issues about any specific missing docs for troubleshooting now. Thanks!
