### ISSUE TITLE
osm-controller crash due to incompatibility between CLI and upstream image

### ISSUE THREAD

**Issue by fredstanley** [openservicemesh/osm#1491]
Bug description:
I am tried installing OSM on our K8s. I see the osm-controller created but it keeps crashing with the following error. 
Wondering if there is any prerequisite to install OSM ?  Appreciate the help.

I followed this instructions to build a new osm image and installed osm.
https://github.com/openservicemesh/osm/tree/main/docs/example

```
fredstanley@Freds-MacBook-Pro osm (main) $ kubectl get pods,svc,secrets,configmaps,serviceaccount --namespace osm-system
NAME                                  READY   STATUS             RESTARTS   AGE
pod/osm-controller-66cdc68f64-l2gz7   0/1     CrashLoopBackOff   21         85m


fredstanley@Freds-MacBook-Pro osm (main) $ kubectl logs -f pod/osm-controller-66cdc68f64-l2gz7 -n osm-system
{"level":"trace","component":"ads/main","time":"2020-08-10T17:04:25Z","file":"osm-controller.go:104","message":"Starting ADS"}
unknown flag: --certificate-manager
Usage of ads:
      --azure-auth-file string              Path to Azure Auth File
      --azure-subscription-id string        Azure Subscription ID
      --ca-bundle-secret-name string        Name of the Kubernetes Secret for the OSM CA bundle
      --cert-manager string                 Certificate manager (default "tresor")
      --default-injection                   Enable sidecar injection by default (default true)
      --enable-backpressure-experimental    Enable experimental backpressure feature
      --enable-debug-server                 Enable OSM debug HTTP server
      --init-container-image string         InitContainer image
      --kubeconfig string                   Path to Kubernetes config file.
      --mesh-name string                    OSM mesh name
      --osm-configmap-name string           Name of the OSM ConfigMap (default "osm-config")
      --osm-namespace string                Namespace to which OSM belongs to.
      --port int                            Aggregated Discovery Service port number. (default 15128)
      --service-cert-validity-minutes int   Certificate validityPeriod duration in minutes (default 60)
      --sidecar-image string                Sidecar proxy Container image
      --vault-host string                   Host name of the Hashi Vault (default "vault.default.svc.cluster.local")
      --vault-port int                      Port of the Hashi Vault (default 8200)
      --vault-protocol string               Host name of the Hashi Vault (default "http")
      --vault-role string                   Name of the Vault role dedicated to Open Service Mesh (default "openservicemesh")
      --vault-token string                  Secret token for the the Hashi Vault
  -v, --verbosity string                    Set log verbosity level (default "info")
      --webhook-name string                 Name of the MutatingWebhookConfiguration to be configured by ADS
      --webhook-port int                    Webhook port for sidecar-injector (default 9090)
unknown flag: --certificate-manager

```
OSM version
fredstanley@Freds-MacBook-Pro osm (main) $ osm version
Version: dev; Commit: 55cf1d4; Date: 2020-08-10-10:58

**Comment by shashankram** [comment]
@fredstanley, the error pertains to `osm-controller` not being aware of the `--cert-manager` flag. This flag was recently changed to `--certificate-manager`. It seems as though by default, the images used for `osm-controller` are older, while `osm cli` binary used for install is newer.

**Comment by shashankram** [comment]
@fredstanley how did you get the `osm` cli binary? Was it built from source or downloaded from the release page on Github?

**Comment by shashankram** [comment]
> @fredstanley how did you get the `osm` cli binary? Was it built from source or downloaded from the release page on Github?

Nevermind, per the instruction it asks you to build the `osm` binary from source. This ends up being more recent in your case, while the default `osm-controller` image is older, resulting in incompatibility.

We will update the default `osm-controller` images.

**Comment by sriharshaj70** [comment]
In the meantime, doing a "make build" after "osm install" would work ?

**Comment by shashankram** [comment]
> In the meantime, doing a "make build" after "osm install" would work ?

If you use a custom container registry and follow these instructions so that you build the images from source, it should work:
https://github.com/openservicemesh/osm/blob/main/docs/development_guide.md#create-environment-variables

We will update the default images so that they are compatible with the source code.

**Comment by shashankram** [comment]
@fredstanley , since you are building the `osm` cli from source and running the install command, it is important that the cli binary is compatible with the default image of `osm-controller` (v0.3.0 currently).

To avoid using an older image that points to a release binary, when you build the binary from source, make sure to pass in the Git SHA for the commit you are at when you build the CLI from source.

For ex. if you are building the CLI from source at `commit 54d2812a8ff07723c37999de32b44b7f812ecbee`, you want to install OSM using `osm install --osm-image-tag 54d2812a8ff07723c37999de32b44b7f812ecbee`.

Please let us know if this works.

**Comment by fredstanley** [comment]
@shashankram yes using the tag works.

**Comment by shashankram** [comment]
> @shashankram yes using the tag works.

Great, can I close this particular issue?
