### ISSUE TITLE
Publish newer images on a daily basis

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1492]
It is easy for the OSM images to go out of sync with the tree. If a new user wants to try the manual demo as per https://github.com/openservicemesh/osm/tree/main/docs/example, its possible for the CLI + charts to not be compatible with the default images used. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [X]

**Possible use cases**
More recent images will make it harder for the CLI and hosted images to go out of sync.

**Comment by shashankram** [comment]
@michelleN suggested to push images with the `latest` for every merge to `main`. @michelleN, @nojnhuh can one of you help with this?

**Comment by michelleN** [comment]
I'm thinking we should tag each merge to main with the git commit sha and not latest and yes happy to help here. One of us will take it.
