### ISSUE TITLE
OSM blog submission -- requesting a process 

### ISSUE THREAD

**Issue by bettyjunod** [openservicemesh/osm#1500]
Hello -- interested in seeing a process and set of guidelines for the community to submit blog content to the OSM blog. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by michelleN** [comment]
Hey @bettyjunod ! Great question. We don't have this set up yet but @bridgetkromhout is going to spin up a process like the one for the SMI blog for us. In the meantime, feel free to send over the blog post to @bridgetkromhout and I via email and we can work with you from there.

**Comment by bettyjunod** [comment]
will ping you both on slack if that's cool

**Comment by bridgetkromhout** [comment]
For completeness, to close the loop here: I documented the process in https://github.com/openservicemesh/osm-www#how-to-add-a-blog-post. Thanks again!
