### ISSUE TITLE
Better naming convention for synthetic TrafficTargets in allow-all (permissive) mode

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1503]
As of this writing the name of the synthetic TrafficTargets (generated by the control plane) when in allow-all (permissive) mode look like this:

`"&Service{ObjectMeta:{bookstore  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:servicePort,Protocol:TCP,Port:8888,TargetPort:{1 0 backendName},NodePort:0,AppProtocol:nil,},},Selector:map[string]string{},ClusterIP:,Type:,ExternalIPs:[],SessionAffinity:,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}->&Service{ObjectMeta:{bookbuyer  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:servicePort,Protocol:TCP,Port:8888,TargetPort:{1 0 backendName},NodePort:0,AppProtocol:nil,},},Selector:map[string]string{},ClusterIP:,Type:,ExternalIPs:[],SessionAffinity:,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}"`

We could improve this by using the names of the services or even hashing this.

Search the source code for this Github Issue for references.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@draychev , I don't understand this issue completely. Could you provide more details when you refer to `using the names of the services or even hashing this`? An example would help.

**Comment by draychev** [comment]
> @draychev , I don't understand this issue completely. Could you provide more details when you refer to `using the names of the services or even hashing this`? An example would help.

Here is a link to the unit test where this is visible: https://github.com/openservicemesh/osm/pull/1504/files#diff-3f7cfdfe5c47b3d1cccd1d02268812e4R236-R247

Instead of having a string which represents `struct -> struct` - it would be nice to have `default/bookbuyer -> default/bokstore`

So I think this
```
&Service{ObjectMeta:{bookstore default 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:servicePort,Protocol:TCP,Port:8888,TargetPort:{1 0 backendName},NodePort:0,AppProtocol:nil,},},Selector:map[string]string{},ClusterIP:,Type:,ExternalIPs:[],SessionAffinity:,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}->&Service{ObjectMeta:{bookbuyer default 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:servicePort,Protocol:TCP,Port:8888,TargetPort:{1 0 backendName},NodePort:0,AppProtocol:nil,},},Selector:map[string]string{},ClusterIP:,Type:,ExternalIPs:[],SessionAffinity:,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}
```

can be 

```
default/bookbuyer -> default/bookstore
```

I believe this change should be easy here: https://github.com/openservicemesh/osm/pull/1504/files#diff-8c9bb5aa4e77c52319b6903e889bd59bR350

this could be (plus namespace):
```go
Name: fmt.Sprintf("%s->%s", source.Name, destination.Name),
```

**Comment by shashankram** [comment]
> ```go
> Name: fmt.Sprintf("%s->%s", source.Name, destination.Name),
> ```

This is what I was looking for. This is not intended for sure :-) We should change it.
