### ISSUE TITLE
Support per port traffic target policies for a destination

### ISSUE THREAD

**Issue by sriharshaj70** [openservicemesh/osm#1508]
**Please describe the Improvement and/or Feature Request**

Does OSM support multiple end-points of a service ?

Let us say if we have 2 endpoints in a service. Say Service(Account) A uses port 8080 and 8081.
In SMI TrafficTarget spec, we want to list two different destination specs one for each end-point.
Rules and Sources for each destination are different.

Is this currently supported ? If not, is it planned ?

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [X ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by sriharshaj70** [comment]
Hi Shashank,
Pleased to hear that you are working on this issue and we need it badly. We really appreciate it.
When do you think this will be available ?

Would this be available for both permissive and non-permissive modes ?

Once it is implemented, how would the access policy look like ? 
Is it same as mentioned by SanyaKochhar (I guess that is inline with SMI spec) OR different ?

**Comment by shashankram** [comment]
This issue should be resolved as a part of the effort to consolidate routes per service port. Multiple ports on a service do not share the same route configuration anymore. This change should be available as a part of release v1.0.0.
