### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by alirajabi** [openservicemesh/osm#1510]
Hi, i saw your project, it sounds pretty good, we have decided to use `Linkerd` for our production but your project is impressive.

Do you have a Roadmap? if you share a Roadmap or feature difference, we can make better decision

I have another question do you suggest to use `OSM` in heavy load production for now?

**Comment by michelleN** [comment]
Hey @alirajabi - we have a high level roadmap doc [here](https://github.com/openservicemesh/osm/blob/main/ROADMAP.md). We're also doing some planning at the moment to figure out what our next release will look like. In the meantime, we're working on (1) hardening and finishing off our SMI implementations (2) bug fixes (3) helping answer community questions/respond to issues/PR reviews. We don't recommend OSM for production use at this time. We'd recommend running in test clusters only.
