### ISSUE TITLE
Observability: Integration with AZure monitor

### ISSUE THREAD

**Issue by aelmanaa** [openservicemesh/osm#1511]
**Please describe the Improvement and/or Feature Request**

would it be possible to work on an implementation which is integrated with AZure services? For instance, when you are on AKS and integration with log analytics, metrics are already sent to AZure monitor. (I would say that having a prometheus/grafana is bit redundant)
What would be nice as well it to have an integration with Application insights for APM: request metrics, distributed tracing , real time application map...ETc

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [x ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ x]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Integration with Application insights is useful for people who are on AKS and already using Azure monitor for metrics and logs(via log analytics)

**Comment by draychev** [comment]
Hi @aelmanaa,  Open Service Mesh exposes Prometheus endpoints on each Envoy sidecar as well as the OSM Controller. These are then available to any Prometheus compatible tool. Azure Monitor is one such tool.
Here is a sample document, which explains how to configure Azure Monitor so it scrapes OSM's Prometheus endpoints:  https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-arc-enabled-open-service-mesh#monitoring-application-using-azure-monitor-and-applications-insights

The following OSM doc describes how to enable Metrics (via the `osm metrics` CLI): https://docs.openservicemesh.io/docs/guides/observability/metrics/#metrics-scraping

Closing this issue with the assumption that this is sufficient context to complete the integration with Azure Monitor. Please reopen if we could help further.
