### ISSUE TITLE
Manual demo documentation for permissive mode

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1528]
**Please describe what should be documented
The manual demo doc does not have the examples/manifest files to demo permissive mode. With permissive mode, we need one of the following:
1. Tweak bookbuyer and bookthief apps to make requests to a service backed by pods. By default client apps make requests to the `bookstore` service, but we don't have pods backing this service.
2. Create a manifest for a service `bookstore` with Deployments.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/docs/example/README.md

**Comment by SanyaKochhar** [comment]
Hey Shashank, I saw there was no documentation for the permissive mode feature. That might be a prerequisite to someone building out the manual demo. Should we add that to this issue?

**Comment by shashankram** [comment]
> Hey Shashank, I saw there was no documentation for the permissive mode feature. That might be a prerequisite to someone building out the manual demo. Should we add that to this issue?

Makes sense, we should.

**Comment by michelleN** [comment]
Let's write a doc explaining what permissive mode is like @SanyaKochhar suggested in `docs/features/permissive_mode.md` and then link to a manual demo for that feature there.

**Comment by michelleN** [comment]
@shashankbarsin - do you want to write the docs for permissive mode or would you like for me to take it?

**Comment by shashankram** [comment]
> @shashankbarsin - do you want to write the docs for permissive mode or would you like for me to take it?

Looks like you tagged the wrong username. Either works for me, I can write the doc but wouldn't mind if someone else want to.

**Comment by shashankram** [comment]
@michelleN I unassigned myself since you suggested you can take this one.

**Comment by draychev** [comment]
Hey - we already have a demo for permissive mode. In fact you can see it here: https://vimeo.com/453990442
I believe we can close this.

**Comment by shashankram** [comment]
> Hey - we already have a demo for permissive mode. In fact you can see it here: https://vimeo.com/453990442
> I believe we can close this.

I think this issue is pertaining to documenting how to use the permissive mode feature.

**Comment by shashankram** [comment]
The scope of this work is a bit larger than estimated previously due to the nature of existing doc, that needs to be significantly updated to showcase both permissive and SMI modes while providing a simple onboarding experience.
