### ISSUE TITLE
Disable installation of Zipkin by default with osm install

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1529]
As of this writing the default behavior of `osm install` is to install a Zipkin pod in the `osm-system` namespace and configure all Envoys to send traces to this.

This issue proposes we inverse this behavior.  Change the `osm install` so that Zipkin is *not* installed, and Envoy proxies are *not* configured and are not aware of any tracing.

The goal of this change is to lower the load on clusters, where folks experiment with OSM.
This request comes as a result of us observing higher loads on small clusters when tracing is enabled (Envoy sending traces to Zipkin).

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ X ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ X ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
We can leverage the work that began with this PR:  https://github.com/openservicemesh/osm/pull/1518

**Comment by knight42** [comment]
This is already solved by #1535

**Comment by shashankram** [comment]
Closing since the issue has been resolved.
