### ISSUE TITLE
Clean up resources if Helm installation fails

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#1530]
**Bug description**:
If helm installation fails, resources are not cleaned up such as clusterrolebindings etc. We are left with a half-deployed state.
**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
If install fails, the cluster should be as it was pre-installation
**Steps to reproduce the bug (as precisely as possible)**:
TBD
**How was OSM installed?**:
TBD
**Anything else we need to know?**:
TBD
**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by nojnhuh** [comment]
`helm install` has an `--atomic` flag that will do exactly this which also implies `--wait`, which will wait for pods, pod workloads, services, PVCs, and CRDs to become ready before exiting. Is that the same behavior we want for `osm install`, or would we only want to to clean up resources on error conditions NOT checked by `--wait`?

**Comment by nojnhuh** [comment]
After discussing offline, I'll plan to hardcode `--atomic` to true and adding a `--timeout` flag to `osm install` which will pass through to Helm.
