### ISSUE TITLE
Implement OpenTelemetry

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1531]
OSM started by supporting Zipkin for tracing in the early stages of the project.
This Github Issue is to deprecate Zipkin and implement OpenTelemetry when this becomes available in Envoy: https://github.com/envoyproxy/envoy/issues/9958

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ X ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ X ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by eduser25** [comment]
We will be moving to CNCF-incubated Jaeger too.

**Comment by palmerabollo** [comment]
related https://github.com/openservicemesh/osm/issues/2280 :(

**Comment by keithmattix** [comment]
@shashankram has been doing some interesting work in this area around otel compliant logging. Tracing support should be available within the next couple of releases
