### ISSUE TITLE
Make Prometheus deployment optional and enable compatibility with Prometheus Operator

### ISSUE THREAD

**Issue by carlosjgp** [openservicemesh/osm#1537]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality [ X ]        
- Metrics [ X ]

**Possible use cases**
Custom Prometheus deployments that may run on HA, using Cortex, Thanos, Remote Write/Read for long term storage are normally managed independently due to its size and sometimes complexity

Currently, OSM ["Bring your own"](https://github.com/openservicemesh/osm/blob/main/docs/patterns/observability.md#byo-bring-your-own) Prometheus solution relies on changing the default configuration on Prometheus meaning that it will affect all the existing alerts and dashboards

Using a `ServiceMonitor` or `PodMonitor` will  be easier and easier to adopt

**Comment by eduser25** [comment]
Hey @carlosjgp,

Prometheus (and Grafana) deployment are behind an install toggle (`enableMetricsStack`, present on CRDs and OSM's cli tool), you can disable Prometheus deployment through it.

Regarding Prometheus Operators, I'm not entirely familiar how they deployed, let me check and get back to you if I may.
