### ISSUE TITLE
use a distroless base image for osm-controller and demo apps

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1538]
[Distroless images](https://github.com/GoogleContainerTools/distroless) strip out all tools not necessary for running an application. It just contains the bare bones you need to run an app so attackers have less tools to poke around if they do get access to container(s). We should convert osm-controller image and all demo application images to use distroless base images.

Was watching a KubeCon talk that reminded me of this and @jchauncey is also a fan.

**Comment by elsesiy** [comment]
I can take this one up

**Comment by draychev** [comment]
Hi @elsesiy, are you still interested in this issue?

**Comment by elsesiy** [comment]
Yes, I can take this on
