### ISSUE TITLE
Implement SMI metrics API server

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1540]
**Please describe the Improvement and/or Feature Request**

Add an implementation for OSM to the [SMI metrics API server](https://github.com/servicemeshinterface/smi-metrics).

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by nojnhuh** [comment]
This work is basically complete. Only waiting to merge the changes required by #984 once upstream Envoy supports WASM filters. Code is on my fork: https://github.com/nojnhuh/smi-metrics/tree/openservicemesh

**Comment by nojnhuh** [comment]
Reopening until this is merged.

**Comment by nojnhuh** [comment]
PR open: https://github.com/servicemeshinterface/smi-metrics/pull/77

**Comment by michelleN** [comment]
I think we should create a slim osm-metrics chart in the OSM repo under charts/ and allow folks to install it via the osm CLI now that envoy has WASM support cc/ @nojnhuh @nojnhuh 

What do ya'll think?

**Comment by snehachhabria** [comment]
@nojnhuh please could you share your status on this issue? Looks like you did some work here, is it complete? If there is no more action, please could you close the issue.

**Comment by nojnhuh** [comment]
@snehachhabria There aren't any more changes we need to make to OSM for this. I planned to keep this issue open until the upstream PR I linked above is merged but I'm fine if we want to close it.
