### ISSUE TITLE
GetServiceFromEnvoyCertificate should list all services associated with Envoy

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#1560]
**Please describe the Improvement and/or Feature Request**

GetServiceFromEnvoyCertificate should return a list of services instead of a single service. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Envoy should be programmable for multiple services. This change will allow us to map a pod to multiple services, such as root service and backend service.

**Comment by shashankram** [comment]
@ksubrmnn note that this change required if we want to support multiple services per pod, not related to multiple destinations for a service account.
