### ISSUE TITLE
Collect envoy logs for failed CI runs

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1561]
**Please describe the Improvement and/or Feature Request**
Currently when a CI run fails, envoy logs are not collected. As a result its very hard to understand the reason for a failure especially when its not reproducible locally.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [X]
- Project Release            [ ]

**Comment by SanyaKochhar** [comment]
Could you expand a little bit more about what experience you're envisioning with logging? Should this be an osm CLI command or do you want a script that gets executed at the end of the CI run that dumps all the envoy proxy logs into a file which is available after the CI runs?

**Comment by shashankram** [comment]
> Could you expand a little bit more about what experience you're envisioning with logging? Should this be an osm CLI command or do you want a script that gets executed at the end of the CI run that dumps all the envoy proxy logs into a file which is available after the CI runs?

This issue is to do with the CI system where we do not collect logs from all containers on failures.
