### ISSUE TITLE
Program envoy to use list of services returned by GetServicesFromEnvoyCertificate

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#1575]
**Please describe the Improvement and/or Feature Request**

Envoy should program itself for each of the services returned by GetServicesFromEnvoyCertificate
**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

This will allow Envoy to be programmed for the multiple services that can be associated with a pod.

**Comment by ksubrmnn** [comment]
Search for 1575 in the repo to see instances of where this should change

**Comment by snehachhabria** [comment]
Might be handled by #2064

**Comment by shashankram** [comment]
This will be handled by #2064.
