### ISSUE TITLE
Address golangci-lint issues

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1578]
Currently, we only run `golangci-lint` against new changes. We should strive to remove that [option](https://github.com/openservicemesh/osm/blob/55af4af59d871b5be83b9012e9bda5d279a453a3/.golangci.yml#L5) from our config and enforce rules on the entire codebase once outstanding issues are fixed.

**Comment by snehachhabria** [comment]
This was addressed with #2023
