### ISSUE TITLE
Forwarding http2 traffic from envoy to service

### ISSUE THREAD

**Issue by sriharshaj70** [openservicemesh/osm#1589]
**Bug description**:

How do we instruct OSM so that envoy forwards http2 (instead of http1.1) traffic to the recipient service ?
I see this on remote envoy.
[2020-08-15 13:02:26.510][24][debug][client] [source/common/http/codec_client.cc:128] [C49] protocol error: http/1.1 protocol error: HPE_INVALID_CONSTANT

This indicates that envoy is sending http1.1 traffic to the service even though the original traffic was http2.

envoy has an option to set it. But, how do we instruct OSM to send it to envoy ?

This would be a generic requirement to allow SMI specs to include some annotation or something which
can be transparently passed to envoy by osm-controller.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ X]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@sriharshaj70 Could you share more details regarding your setup and traffic between the services. In your example, can you clarify if the client is attempting HTTP/2 without TLS?

**Comment by shashankram** [comment]
@sriharshaj70 I merged #1591 which allows to use H2C (HTTP/2 over Cleartext). Kindly let me know if this addresses the issue you are seeing regarding HTTP2 traffic being downgraded to HTTP1.1.
