### ISSUE TITLE
Create an endpoint that returns versions of SMI APIs that the osm-controller supports

### ISSUE THREAD

**Issue by elenaspasovaspasova** [openservicemesh/osm#1590]
**Please describe the Improvement and/or Feature Request**

This endpoint would enable users to easily tell which version of the SMI APIs their osm-controller is supporting which would aid the creation, validation, and understanding of YAML files representing SMI components .

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [X]
- SMI Traffic Specs Policy   [X]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [X]
- Debugging                  [X]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

This functionality would make the process of creating component YAML files more robust since users would not have to specify their apiVersion, nor would they be limited to only using the latest version of the api. Instead, this endpoint would be all you need to determine the supported apiVersion and could be used in projects such as the osm dashboard.

**Comment by shashankram** [comment]
@johnsonshi you worked on something similar, would be good to know what you think about this.

**Comment by johnsonshi** [comment]
@shashankram // @draychev - Turns out I already implemented this as part of issue #2849 (PR #3193). The `/smi/version` path of the osm controller's http server already returns the supported smi versions. See https://github.com/openservicemesh/osm/blob/eda8851ab9976083cbe26c7f39448d9bf28eeb69/cmd/osm-controller/osm-controller.go#L246-L247

**Comment by johnsonshi** [comment]
![image](https://user-images.githubusercontent.com/13926417/119610281-d2e2c180-bdad-11eb-9144-572dec82319d.png)
