### ISSUE TITLE
Allow for dynamic tracing configuration on OSM

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1596]
When Tracing is enabled, current implementation hardcodes the tracing protocol to zipkin format on the connectionManager construction.

The improvement consist on making the tracing protocol configurable, so different tracing protocols and multiple tracers could be supported based on configuration parameters fed to OSM.

- New Functionality          [X]

**Possible use cases**
- Support different tracing backends, zipkin is not supported by all.
- [Support OpenTelemetry](https://github.com/openservicemesh/osm/issues/1531) which should become a solid standard for telemetry.

**Comment by SanyaKochhar** [comment]
@eduser25 Does updating from using Zipkin to Jaeger resolve this issue? Are you currently working on this?

**Comment by eduser25** [comment]
This is to allow other protocols (not just zipkin) to send spans through. This is dependant on what the envoys also support.
I have not checked the latest, but I believe they will implement (if they haven't already) opentracing, which will be another proto other than zipkin to send spans.

The amount of work is little, as for us is just configuring the tracing cluster configuration pushed down the envoys.
