### ISSUE TITLE
make grafana installation optional and do not install by default

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1599]
**Please describe the Improvement and/or Feature Request**
- Modify the [osm helm chart](https://github.com/openservicemesh/osm/tree/main/charts/osm) to make the Grafana installation optional.
- Add a value to toggle this in the [values file](https://github.com/openservicemesh/osm/blob/main/charts/osm/values.yaml) and add a conditional that evaluates this value to the relevant [templates](https://github.com/openservicemesh/osm/tree/main/charts/osm/templates). 
- Also modify the cli to be able to toggle the new value with a [flag](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L124-L146) and ensure the [correct value gets passed](https://github.com/openservicemesh/osm/blob/main/cmd/cli/install.go#L233) into the helm chart.
- Ensure that an appropriate message is emitted when someone tries to use `osm dashboard` when the dashboard is not installed.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
A user may not want to use cluster resources to run the Grafana dashboard when using osm.

**Comment by snehachhabria** [comment]
@nshankar13 please can  we update the necessary documentation too as a part of this issue. The PR #1648 fixes the issue but docs need to be updated

**Comment by nshankar13** [comment]
@snehachhabria ok got it!

**Comment by SanyaKochhar** [comment]
@nshankar13 I see there is PR #1690 for this, can this issue now be closed?

**Comment by nshankar13** [comment]
yes
