### ISSUE TITLE
Helm chart installation controller crash

### ISSUE THREAD

**Issue by szihai** [openservicemesh/osm#1600]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
Controller up and running
**Steps to reproduce the bug (as precisely as possible)**:
`osm install`
`kubectl get pods`
`NAME                              READY   STATUS    RESTARTS   AGE
osm-controller-5fcd84d584-kdv9x   0/1     Error     4          114s`
`kubectl logs osm-controller-5fcd84d584-kdv9x -n osm-system`
`{"level":"trace","component":"osm-controller/main","time":"2020-08-20T22:39:57Z","file":"osm-controller.go:104","message":"Starting osm-controller"}
unknown flag: --cert-manager-issuer-name`

**How was OSM installed?**:
"osm install" command line
**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): openservicemesh/osm-controller:v0.3.0
- Kubernetes version (use `kubectl version`): 1.16
- Size of cluster (number of worker nodes in the cluster): 3
- Others:

**Comment by shashankram** [comment]
> Similar to #1491.
> 
> Issue #1527 is open to track updating the instructions.

This is due to incompatible builds used. Already have #1527 open to update the instructions so this can be closed.
