### ISSUE TITLE
osm mesh delete command should be able to take mesh name as an argument

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1618]
Right now, the `osm mesh delete` command is unable to take an argument. It presents a prompt instead to delete the mesh with mesh name "osm". 

The command should be able to take a mesh name that the user wants to delete as an argument. If a user doesn't give an argument, they should be presented with the prompt.

**Comment by ksubrmnn** [comment]
It does! `osm mesh delete --mesh-name mesh3 --namespace osm2`

**Comment by michelleN** [comment]
@ksubrmnn ah thank you.
