### ISSUE TITLE
Enable liveness probe on osm-controller pod

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#1619]
As of today the osm-controller pod has only the readiness probe enabled : 
https://github.com/openservicemesh/osm/blob/49d2526c49ee70ceb56689c82a3969ee5e075d43/charts/osm/templates/osm-deployment.yaml#L63 . We would like to extend this out to enable the liveness probe as well. 

The endpoints for the liveness and readiness probe have been enabled here : https://github.com/openservicemesh/osm/blob/926e281824604452f580012abcef648a43f13a30/pkg/httpserver/httpserver.go#L41-L42  These are just placeholders and we would like to extend this out to ensure that various osm resources are up and running before the osm-controller pod can be termed as live and ready ( e.g.: check if the mutating webhook is up and running) 

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by nitishm** [comment]
I can take this on @snehachhabria

**Comment by snehachhabria** [comment]
@nitishm thanks for volunteering to take up this issue, I am still working on the exact list resources we want to validate/check  on for the readiness/liveness of the osm-controller. Once I have come up with that list and have updated the issue, you are free to work on it. 

I hope to update this issue later this week,

**Comment by shashankram** [comment]
@nitishm I am picking this up since it is high priority for us, hope you don't mind. Will discuss with @snehachhabria on this.
