### ISSUE TITLE
rename osm mesh delete to osm mesh uninstall

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1622]
"uninstall" seems a bit clearer and this is the terminology Helm uses for removing Kubernetes resources as well. Thoughts?

**Comment by nshankar13** [comment]
Agreed!

**Comment by yaron2** [comment]
Hi, Dapr perspective here: we use `dapr uninstall` for the CLI to remove Dapr from a cluster (or local machine), and that came from early user feedback that `delete` is, as you alluded, a bit misleading in that you delete _resources_ and uninstall _deployments_.
