### ISSUE TITLE
How is MetricsStore Library being used

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1630]
@draychev - Can you explain a little bit about what `pkg/metricsstore` should be doing? I can't tell how it is being used. After a new `MetricStore` is created and passed in to create `NewHTTPServer`, I don't see that it is being used unless I'm missing something.

https://github.com/openservicemesh/osm/blob/main/cmd/osm-controller/osm-controller.go#L211-L213
https://github.com/openservicemesh/osm/blob/51513df702d6551e9acb465bbc4fb7bce49237b1/pkg/httpserver/httpserver.go#L39

**Comment by michelleN** [comment]
I'm seeing now that it configures the the metrics store for the osm-controller related metrics like latency and the api event counter and that the metrics store has a specific handler that gets registered on the osm-controller's http server. 👍

**Comment by draychev** [comment]
@michelleN The goal of that package is to collect metrics (these are TBD) and expose them via a prometheus metric.
We should continue to augment this with metrics that are relevant to the osm controller.
