### ISSUE TITLE
Add flag to `osm install` to override arbitrary chart values

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1644]
**Please describe the Improvement and/or Feature Request**
Currently, whenever a new chart parameter is created, it must be surfaced as a flag to `osm install` to be controllable from the CLI. Adding a generic `--set` or similar flag like the one on [`helm install`](https://helm.sh/docs/helm/helm_install/) that takes a key/value pair would allow values to still be controlled from the CLI without requiring any additional code changes.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

- Rarely used or temporary values
- Testing alpha-level features controlled by a feature flag without having to add an explicitly hidden CLI flag.

**Comment by rajdhandus** [comment]
trying to contribute to this.. i am getting the following error while trying to build the project..

```
PS C:\xxxxxxx> make build
process_begin: CreateProcess(NULL, rm -rf bin/osm-controller, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:38: clean-osm-controller] Error 2
```

**Comment by nojnhuh** [comment]
Currently, our build doesn't support native Windows, but WSL should work. If we need to update the docs to make that more clear, feel free to open an issue or PR for that as well.

**Comment by shashankram** [comment]
> **Please describe the Improvement and/or Feature Request**
> Currently, whenever a new chart parameter is created, it must be surfaced as a flag to `osm install` to be controllable from the CLI. Adding a generic `--set` or similar flag like the one on [`helm install`](https://helm.sh/docs/helm/helm_install/) that takes a key/value pair would allow values to still be controlled from the CLI without requiring any additional code changes.

@nojnhuh I see the value here, but also need to ensure the Helm chart values file is exposed to the end user (via documentation or other means) so they know how to fill in the set.

**Comment by nojnhuh** [comment]
@shashankram Helm has a `helm show values` command that takes a local path or URL pointing to a chart and displays its values.yaml. I think that is probably enough as I envisioned this mostly for advanced use cases and keep the existing flags for commonly used options.

**Comment by shashankram** [comment]
> @shashankram Helm has a `helm show values` command that takes a local path or URL pointing to a chart and displays its values.yaml. I think that is probably enough as I envisioned this mostly for advanced use cases and keep the existing flags for commonly used options.

That's great. I guess we would also need a bit of logic for chart values that require validation, ex. `meshCIDRRanges`.

**Comment by nojnhuh** [comment]
I can't remember exactly how @michelleN refactored the validation, but if we validate everything once all the values are parsed and merged, the same validation could run no matter how the values were passed in.

**Comment by shashankram** [comment]
> I can't remember exactly how @michelleN refactored the validation, but if we validate everything once all the values are parsed and merged, the same validation could run no matter how the values were passed in.

Currently certain validations are done on the install flags.

**Comment by rushivarun** [comment]
Hey I am a first time contributor. Can anyone guide me through the process of running osm locally? Help would be greatly appreciated.
