### ISSUE TITLE
Fix Egress test flag

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1653]
Enabling egress testing seems to properly enable egress on deployment (by configuration on OSM and also on bookstore infra), but seems bookbuyer/thief are expecting the wrong value:

with `ENABLE_EGRESS="true"` in `run-osm-demo.sh`:
```
Fetching http://github.com
Request Headers: map[]
Identity: n/a
Booksbought: n/a
Server: GitHub.com
Date: Mon, 31 Aug 2020 21:04:18 GMT
Status: 200 OK
ERROR: response code for "http://github.com" is 200;  expected 404       // Response code is correct, expected is wrong (should expect 200 with ENABLE_EGRESS`
```

**Bug description**:

**Affected area (please mark with X where applicable)**:
- Tests                      [X]

**Expected behavior**:
No error. expected should be 200

**Comment by shashankram** [comment]
Don't quite understand the issue, but here is where the egress flag is set in the CI:
https://github.com/openservicemesh/osm/blob/main/demo/cmd/common/books.go#L38

While you are it, would you mind fixing this if it is not working as expected?

**Comment by eduser25** [comment]
just synchronized to master and redeployed demo.

`.env`
```
export ENABLE_EGRESS=true
```

```
...tail-bookthief.sh | grep github
....
ERROR: response code for "https://github.com" is 200;  expected 0
Fetching http://github.com
ERROR: response code for "http://github.com" is 200;  expected 404
Fetching https://github.com
ERROR: response code for "https://github.com" is 200;  expected 0
Fetching http://github.com
ERROR: response code for "http://github.com" is 200;  expected 404
Fetching http://github.com
ERROR: response code for "http://github.com" is 200;  expected 404
Fetching https://github.com
ERROR: response code for "https://github.com" is 200;  expected 0
```

**Comment by shashankram** [comment]
This is failing for you locally because when you enable egress, you also need to override the `EGRESS_EXPECTED_RESPONSE_CODE` in .env file as done in the CI.
