### ISSUE TITLE
osm install does not work on AKS with integrated AAD

### ISSUE THREAD

**Issue by chrisvugrinec** [openservicemesh/osm#1670]
**Bug description**:

When installing osm on an AKS cluster with the option integrated AAD, the osm installation gives the following error: 
"Error: Could not access Kubernetes cluster. Check kubeconfig"

AKS is installed with terraform containing the following block:
  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed = true
      admin_group_object_ids = [var.admin_group_object_id]
    }

**Affected area (please mark with X where applicable)**:
- Install                    [ X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
I expect that osm is easily installed like my AKS clusters without AAD integration:

OSM installed successfully in namespace [osm-system] with mesh name [osm]

**Steps to reproduce the bug (as precisely as possible)**:
Rollout AKS cluster with AAD integration, see code block above and then try to install osm as per: https://github.com/openservicemesh/osm

**How was OSM installed?**:
via the CLI, "osm install"

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
Version: dev; Commit: 2619af6ea4c5a756c8b4788247ae5dfb40eff549; Date: 2020-09-04-13:47
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1c93c592501dbc0c14e23b5ea2be8f6ea947a3a5", GitTreeState:"clean", BuildDate:"2020-08-25T01:56:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"
- Size of cluster (number of worker nodes in the cluster):
3
- Others:

**Comment by shashankram** [comment]
@chrisvugrinec could you try this again with the latest release, it has additional logging when the command fails.

**Comment by draychev** [comment]
@chrisvugrinec  This was fixed with an earlier release of OSM.
