### ISSUE TITLE
Add support for WebAssembly filters

### ISSUE THREAD

**Issue by marcusschiesser** [openservicemesh/osm#1671]
**Please describe the Improvement and/or Feature Request**
The Envoy proxies configured by OSM can be extended at runtime with filters that are running in a WebAssembly sandbox - similar like this Istio feature: https://istio.io/latest/docs/concepts/wasm/

I see two changes that need to be done to reach that goal:

1. Using an Envoy proxy version that contains the WASM sandbox: https://github.com/envoyproxy/envoy-wasm
2. Provide a possibility to configure the Envoys to use a WASM filter (e.g. similar like the [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) approach)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [x]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Users of OSM can implement whatever feature they need to modify the traffic themselves. OSM can stay light-weight and doesn't have to provide these features for every use-case.

**Comment by nojnhuh** [comment]
We have some ongoing work experimenting with WASM to extend the stats Envoy tracks so we can implement SMI's metrics spec. I have some code on my fork that is functional but still very much WIP: https://github.com/nojnhuh/osm/tree/envoy-wasm

What I have so far isn't designed to be generalizable to any WASM extension, but we have #1376 open to track using Envoy's xDS to configure each proxy more generally, so we'll definitely keep this use case in mind for that.

**Comment by NomadXD** [comment]
Is this open for GSOC 2021 ? If so , I would like to work on this issue. I have some experience with implementing L7 C++ filters in envoy, building the envoy binary using bazel and configuring them through the go-control-plane. Regarding the languages , I have worked with golang and have some basic knowledge in rust (willing to learn).

**Comment by nojnhuh** [comment]
I've been looking into this and have put together thoughts on how this might work in this doc: https://docs.google.com/document/d/16C8Oyq2QOLKHGhPfXsk4Kl0wCMU-VWsslSlmOQeJbRQ/edit?usp=sharing

The permissions on the doc aren't open for comments, but feel free to `> quote` the doc and leave comments here.

**Comment by snehachhabria** [comment]
@nojnhuh please could you share your status on this issue. If you are no longer working on this, please could you move the item to the project backlog and unassing yourself
