### ISSUE TITLE
add unit tests for cmd/cli/dashboard.go

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1672]

**Comment by michelleN** [comment]
@nshankar13 - are you still working on this?

**Comment by shashankram** [comment]
> @nshankar13 - are you still working on this?

Let's close this in favor of https://github.com/openservicemesh/osm/issues/1882, we need a generic way to test port forwarding functionality, which applies to the dashboard cli command as well.

**Comment by SanyaKochhar** [comment]
Duplicated with more info in #3412
