### ISSUE TITLE
Create documentation site: openservicemesh.io/docs

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1678]
Create a dedicated site for OSM documentation under https://openservicemesh.io/docs/

Here is a great example from the Helm project: https://helm.sh/docs/

**Comment by bridgetkromhout** [comment]
The Helm v3 docs work well (Hugo and markdown). English docs are edited in https://github.com/helm/helm-www/tree/master/content/en/docs and displayed on https://helm.sh/docs.

I recommend not using Helm's process for the CLI doc creation: https://github.com/helm/helm-www#updating-the-helm-cli-reference-docs
- Tool removes md file headers, leading to error-prone manual fixes
- Does not support multi-lingual (which the main Helm docs support, as documented in https://helm.sh/docs/community/localization/)
- Can pull in local variables, editing paths incorrectly
- Discussed in https://github.com/helm/helm-www/issues/487 and https://github.com/helm/helm/issues/6592

**Comment by phillipgibson** [comment]
Currently testing layout and design.

**Comment by michelleN** [comment]
Current status: getting subdomain configured via cncf

**Comment by bridgetkromhout** [comment]
Site is available at https://docs.openservicemesh.io/

**Comment by bridgetkromhout** [comment]
Discussed on call and resolving this one. Additional issues being cleared up in https://github.com/openservicemesh/osm/pull/2647.
