### ISSUE TITLE
Decouple Identity of payload from Service Account

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1681]
Current iteration of OSM (and SMI) relies heavily on Kubernetes Service accounts to provide an identity for a given Pod (aka: payload, contianer, Envoy, proxy, etc.)
This issue is to research and implement a mechanism by which OSM could leverage alternative ways of providing an Identity to a given payload so that this could be done in the absence of a Kubernetes cluster (for instance).

This enable adding of VMs and other networked primitives to the mesh: https://github.com/openservicemesh/osm/issues/1035 https://github.com/openservicemesh/osm/issues/279

**Comment by draychev** [comment]
ref https://github.com/openservicemesh/osm/issues/286

**Comment by michelleN** [comment]
Currently looking into how we can migrate to SPIFFE to help us make identity more flexible and pluggable in OSM.
