### ISSUE TITLE
(root) Integrate OSM with Flagger

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1700]
Integrate Flagger with OSM so that OSM <> Flagger has progressive traffic shifting capabilities

**Comment by johnsonshi** [comment]
- [x] https://github.com/openservicemesh/osm/issues/1081
- [x] https://github.com/openservicemesh/osm/issues/315
- [ ] Add OSM Metrics Provider to Flagger for canary metrics analysis capability
- [ ] Add OSM Router Provider to Flagger for traffic shift capability
- [ ] Add OSM E2Es in Flagger
- [ ] OSM Progressive Delivery docs in Flagger repo and OSM repo
- [ ] OSM B/G traffic shifting
- [ ] OSM A/B Testing and shifting
- [ ] OSM B/G traffic mirroring

**Comment by johnsonshi** [comment]
https://github.com/fluxcd/flagger/pull/955

**Comment by draychev** [comment]
Per @johnsonshi - Since https://github.com/fluxcd/flagger/pull/955 has already been merged we can close this issue.
