### ISSUE TITLE
Complete CNCF project on-boarding for OSM

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1703]
https://github.com/cncf/toc/issues/535

**Comment by michelleN** [comment]
@lachie83  - are you working on this? May I assign you?

**Comment by bridgetkromhout** [comment]
@michelleN I'll follow this through - thanks!

**Comment by bridgetkromhout** [comment]
Adding the community meetings: https://github.com/openservicemesh/osm/pull/1786

**Comment by bridgetkromhout** [comment]
Finishing up https://github.com/cncf/toc/issues/535 - almost done.

**Comment by bridgetkromhout** [comment]
Holding pattern, but close to done.

**Comment by bridgetkromhout** [comment]
Tracking in https://github.com/cncf/toc/issues/535 - all tasks complete.
