### ISSUE TITLE
Use Go std testing library for unit tests

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1704]
**Background:**
Historically, we leveraged [Ginkgo](https://onsi.github.io/ginkgo/), a BDD style testing framework,  and [Gomega](https://onsi.github.io/gomega/), an assertion/matcher library best paired with Gingko, for unit tests but after using it for a while we discovered:

- This is a heavier and more verbose framework than we really need
- Using the Go standard testing package is easier to work with when writing table-style tests and works well for most places in this codebase.
- Learning Gomega and Gingko also comes at a learning curve and may prove to be a barrier to entry when first contributing to this repository.

**Proposal:**
Let's move back to using the Go standard testing package for unit tests in this repository. Over time, we'll convert the Gingko tests back to using the testing package but that is not a high priority any time soon. We can and should leverage Gingko/Gomega for e2e tests like Kubernetes and other projects do. 

**Open Questions:**
Assertion/matcher libraries like Gomega and [Testify](https://github.com/stretchr/testify) help make it easier to write tests and more cleanly assert equality, replacing if/else statements. [Testify](https://github.com/stretchr/testify) is a toolkit that offers more tools outside of just their assert package. We use both Gomega and Testify in our project today. A question for the maintainers/community: _**should we continue using both assertion type libraries or move toward one or none?**_ 

When thinking about this it might be helpful to think about what is important to you. When discussing with the team, a things that bubbled up as important:
- making tests easier to read/write (simplicity is key) but not increasing the barrier to entry too much
- asserting object equality (although I think we might be able to argue that reflect.DeepEqual is enough)
- pretty output when objects are not equivalent

**_What are other factors that are important when deciding which assertion library to pick?_**

**Comment by codefromthecrypt** [comment]
FYI I felt your issue helpful, so thanks for capturing rationale. I also built more rationale here in case it is useful to you. cheers https://github.com/tetratelabs/getenvoy/pull/130

**Comment by snehachhabria** [comment]
OSM has been using Go std library as the default for unit testing for some time, closing this issue as all new code has been using the same. We can reopen another issue when we need to clean up old test code.
