### ISSUE TITLE
Remove instances of log.Fatal in Ginkgo tests

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1707]
Using `log.Fatal` and other functions that call `os.Exit(1)` under the hood forces Ginkgo to exit early. `go test` still registers the tests as failures in that scenario, but Ginkgo's pretty error output is missing which can make spotting the specific failures a bit harder.

Instead of `log.Fatal`, prefer either a different log level followed by `GinkgoT().FailNow()` or `GinkgoT().Fatal()`.

**Comment by JosephWoodward** [comment]
I presume this issue can now be closed as it's covered by #1784 ?

**Comment by nojnhuh** [comment]
That PR may not have covered every case, so there might be a few lingering instances to touch up. I will take a look and document any other cases I find in a follow-up comment here or close this issue if I don't find any.

**Comment by nojnhuh** [comment]
I only found one other instance: https://github.com/openservicemesh/osm/blob/9a51c5b01c678eec650868e222ac05dd1d03b4f0/pkg/kubernetes/events/events_test.go#L32-L35

**Comment by JosephWoodward** [comment]
This addresses the last test you mentioned @nojnhuh https://github.com/openservicemesh/osm/pull/1819

**Comment by nojnhuh** [comment]
Since that call to `log.Fatal` is only run as test setup, not even inside any particular test, then using it there should be ok. My mistake, sorry for giving you the runaround @JosephWoodward.
