### ISSUE TITLE
create an e2e framework for osm

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1711]
This issue is to create and end-to-end testing framework for OSM.  The goal is to have a mechanism by which we can quickly and easily add new test scenarios. The tool should allow a user to spin up a Kubernetes cluster (via Kind) and run all the scenarios with one command.  

### Further exploration required: 
  - The tests can be potentially written/defined using Ginkgo/Gomega but this is not required and up for discussion. Compare to bats framework. 
  - We may want to explore writing our own DSL (maybe starting with reusable helper functions) for setting up tests (create a bookstore application and apply X SMI policies) to be used in addition to whatever framework we choose. 
  - Are there parts of other tools (like Prow) we could leverage? 

### Sample scenarios: 
  - bookbuyer can purchase books from bookstore with an SMI policy X 
  - bookthief is not able to steal books from bookstore with SMI policy X 

### Requirements: 
  - must run locally with Kind 
  - run many scenarios in parallel (tests may not take more than 1 hour) 

### Current status: 

There is an automated demo that runs as part of CI as a PR gate in conjunction with a tool called maestro that conducts a series of tests. This is something we can extend/refactor/build on to get to the goal outlined above. To move forward, we'll need to start with resolving #1710.

### Next steps: 

This issue requires further design before complete implementation.  

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [x]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [x]
- Project Release            [ ]

**Possible use cases**

**Comment by ritazh** [comment]
Should enable deployment with `helm install`. Currently e2e uses osm cli to install.
