### ISSUE TITLE
Ingest the TCP Route SMI for TrafficTarget;  Configure Envoy w/ TCP traffic to endpoints

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1715]
This issue is to ingest SMI TCPRoute spec and configue Envoys with the appropriate TCP configuration.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [X]
- SMI Traffic Specs Policy   [X]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

As a user I want to define access control on services, which require TCP communication (for example an app connecting to a Redis server within the OSM service mesh)

**Comment by draychev** [comment]
This is partially implemented by https://github.com/openservicemesh/osm/pull/1651

**Comment by shashankram** [comment]
@draychev I believe https://github.com/openservicemesh/osm/issues/1521 is used to track this. How is this one different?

**Comment by draychev** [comment]
Merged into https://github.com/openservicemesh/osm/issues/1521
