### ISSUE TITLE
Add a validation ensuring we are not adding Envoy sidecar to an already meshed pod

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1717]
This issue is to create / add a validation (maybe in the Webhook server) which makes sure that OSM is not adding a sidecar to pods that are already part of another mesh (OSM or other).

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
This validation already exists: https://github.com/openservicemesh/osm/blob/78342c9624f3daee6c2d190e20b67dd50f7a3433/pkg/injector/webhook.go#L226

We only allow to inject sidecars to pods if the namespace is monitored by the osm-controller who's webhook is invoked. Moreover, the webhook also has a namespace selector that will prevent pods in other meshes from triggering webhooks that manage other namespaces:

https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/mutatingwebhook.yaml#L19

@draychev please let me know if this makes sense.

**Comment by shashankram** [comment]
Didn't mean to close, leaving it open till @draychev acknowledges.

**Comment by shashankram** [comment]
Closing based on https://github.com/openservicemesh/osm/issues/1717#issuecomment-702368534.
