### ISSUE TITLE
Create an endpoint returning mesh data plane health

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1718]
This issue is to add an HTTP endpoint on OSM Controller's debug server, which returns the health of the data plane of the mesh. This is to be used to quickly debug the mesh. 

For instance:
- list all pods that are in a meshed namespace
- list the pods in the meshed namespace without an Envoy
- list pods with Envoys *not* connected to OSM control plane
- list current applied xDS version for all Envoys participants
- list Envoys with expired certificates etc.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [X]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by michelleN** [comment]
Let's further refactor this to implement just the pods that are in a namespace.
