### ISSUE TITLE
validating webhook for smi specs

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#172]
may need to be done in SMI. will prioritize later once we have the whole smc service mesh running.

**Comment by shashankram** [comment]
@michelleN this seems very important to me. It will prevent misconfigured/incorrect policies from being applied giving users instant feedback, versus an incorrect policy being applied and traffic not working as expected.

Can we add this to the roadmap?

**Comment by michelleN** [comment]
Yea let's do it

**Comment by shashankram** [comment]
Since the SMI project does not support validating SMI resources, OSM will be validating SMI resources as a part of its validating webhook. The validating webhook is already handling SMI resources.
