### ISSUE TITLE
Use FluentBit to aggregate control plane logs and forward to a sink

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1721]
This issue is to collect logs in a non vendor specific way and push it to a log sink like Microsoft Log Analytics or any other log provider.  

This is experimental work so we're just trying to get to alpha level functionality here. Whatever changes made should be configured via the osm helm chart and should be able to be toggled on and off.

**Comment by SanyaKochhar** [comment]
- Ensure that logs being sent to the sink are at error log level
- Enable conditionally, default to disabled
- Add documentation including an example of forwarding to a sink

**Comment by SanyaKochhar** [comment]
Resolved by PR #1875
