### ISSUE TITLE
Measure performance and scalability of OSM control plane

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1723]
This issue is to measure the performance and scalability of OSM control plane.
We need to document the measurements and then recommend improvements.

As part of this issue we need to:
  - [x] create a benchmarking tool / framework:  https://github.com/openservicemesh/osm/issues/1916
  - [x] document the findings of the tool and publish in the OSM repo
  - [x] define test scenarios and benchmarking metrics to collect from these scenarios (for example how many services, how many pods OSM etc. / CPU, RAM etc.)

**Comment by draychev** [comment]
@eduser25 I hear that you have already ran tests for this. Would you be able to document your methods and discoveries so far?

**Comment by ritazh** [comment]
Let's make sure this also includes recommendations for resource specifications (limits and requests) based on the number of pods and policies.

**Comment by eduser25** [comment]
Doc available: https://github.com/openservicemesh/osm/blob/main/docs/content/docs/scale.md
