### ISSUE TITLE
Add a flag to OSM install to enable Envoys to send data plane logs to OSM Control Plane

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1724]
This issue is to add a new flag to the OSM install command, which will make it so Envoy proxies send their logs to the OSM control plane instead of stdout. This will also become a ConfigMap key.
Default should be - Envoys send logs to stdout (do not send to control plane).

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [X]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by rushivarun** [comment]
Hello,
I went through the cmd/cli/install.go file. I wanted to understand what where is the "settings" declared?
`installClient.Namespace = settings.Namespace()`
I am a first time contributor. Guidance would be greatly appreciated.

**Comment by draychev** [comment]
This is no longer needed.
