### ISSUE TITLE
 --enable-sidecar-injection flag in the osm namespace add cli command doesnt work

### ISSUE THREAD

**Issue by aanandr** [openservicemesh/osm#1726]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          **[X** ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**: Expected this flag to enable sidecar injection for all pods in the specified namespaces but got an error

**Steps to reproduce the bug (as precisely as possible)**: The demo instructions (under https://github.com/openservicemesh/osm/blob/main/docs/example/README.md#deploying-the-bookstore-demo-applications) provide the following command to enable sidecar injection at the time of adding namespaces to the mesh but it doesnt work
osm namespace add bookstore bookbuyer bookthief bookwarehouse --enable-sidecar-injection

Saw the following error: Error: unknown flag: --enable-sidecar-injection
It looks like this flag hasnt been implemented yet. So maybe its a matter of changing the documentaiton

**How was OSM installed?**: osm install

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@aanandr please fill in the bug template with the appropriate version details
```
OSM version (use osm version):
Kubernetes version (use kubectl version):
```

You are likely using an older build, because this works with the demo.

**Comment by wenxinnnnn** [comment]
Yesterday, I also encountered this problem on win10, but macbook does not have this problem.
OSM version (use osm version): v0.3.0+
Kubernetes version (use kubectl version):  v1.16
@shashankram

**Comment by shashankram** [comment]
> Yesterday, I also encountered this problem on win10, but macbook does not have this problem.
> OSM version (use osm version): v0.3.0+
> Kubernetes version (use kubectl version): v1.16
> @shashankram

There is no release cut with this this change included., you need to build from source since we don't have a release with this change.

**Comment by shashankram** [comment]
> Yesterday, I also encountered this problem on win10, but macbook does not have this problem.
> OSM version (use osm version): v0.3.0+

What is `v0.3.0+`? Where did you get the cli binary from?

**Comment by wenxinnnnn** [comment]
On win10 system, this problem can be reproduced using the binary release version v0.3.0.
Is it the cobra problem?
v0.3.0+, I mean the current master branch.

**Comment by shashankram** [comment]
> On win10 system, this problem can be reproduced using the binary release version v0.3.0.
> Is it the cobra problem?
> v0.3.0+, I mean the current master branch.

Could you open a new bug for windows build? What error are you seeing?
Also please specify the version as requested:
```
OSM version (use osm version):
Kubernetes version (use kubectl version):
```

**Comment by wenxinnnnn** [comment]
Need to wait until the working day, because the company's computer is win10.
---
Just because I was discovering other bugs at that time, I clearly remember the same bug he found.
Error: unknown flag: --enable-sidecar-injection
OSM version (use osm version): v0.3.0    （Binary release downloaded from github）
Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shashankram** [comment]
> Error: unknown flag: --enable-sidecar-injection
> OSM version (use osm version): v0.3.0 （Binary release downloaded from github）

The binary available on github does not have the `--enable-sidecar-injection` option. It will be available in the next release.
