### ISSUE TITLE
Unsetting sidecar injection annotation when the `namespace add` command is rerun without the flag

### ISSUE THREAD

**Issue by wenxinnnnn** [openservicemesh/osm#1727]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
When you execute the **osm namspace add xxx** command, you need to remove the annotations related to --enable sidecar injection

**Steps to reproduce the bug (as precisely as possible)**:
execute cli:
> osm namespace add bookstore  --enable-sidecar-injection
> osm namespace add bookstore 

```
>kubectl describe ns bookstore
Name:         bookstore
Labels:       openservicemesh.io/monitored-by=osm
Annotations:  openservicemesh.io/sidecar-injection: enabled
Status:       Active
```
The namespace should not have annotations: **openservicemesh.io/sidecar-injection: enabled**

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): v0.3.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
The behavior where the annotation is not removed is intended. If you want to remove the namespace from sidecar injection you need to first remove the namespace using `osm namespace remove` command, or manually remove the annotation.

The `osm namespace add` command is a command to add a namespace to the mesh, but optionally provides a way to annotate namespaces for sidecar injection using `--enable-sidecar-injection`. If you want to remove a namespace from sidecar injection, you must explicitly annotate the namespace. Currently there is no osm cli command for doing so.

**Comment by shashankram** [comment]
Accidentally closed.

**Comment by shashankram** [comment]
When the following 2 commands are run in order, the question is whether we  want to disable the sidecar injection configured by command 1 because the `enable-sidecar-injection` flag is missing in command 2, both for the same namespace.
The current behavior does not unset the sidecar injection annotation set by the first command, and only can be unset using `osm namespace remove` command.

```
osm namespace add bookstore --enable-sidecar-injection
osm namespace add bookstore
```

@michelleN what do you think?

**Comment by ksubrmnn** [comment]
Perhaps --enable-sidecar-injection could take an optional parameter for true/false (default is true)

**Comment by shashankram** [comment]
> Perhaps --enable-sidecar-injection could take an optional parameter for true/false (default is true)

We wanted the default to be false. The question is whether running the `namespace add` command multiple times should alter the state of sidecar injection configuration. The `--enable-sidecar-injection` flag is a convenience, so I am not very comfortable on unsetting previously set annotations.

**Comment by ksubrmnn** [comment]
I meant something like this

```
osm namespace add bookstore # Do not enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection true # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection false # Do not enable sidecar injection


```

Should be possible using: https://godoc.org/github.com/spf13/pflag#FlagSet.Changed

**Comment by shashankram** [comment]
> I meant something like this
> 
> ```
> osm namespace add bookstore # Do not enable sidecar injection/ Do not change sidecar annotation label
> osm namespace add bookstore --enable-sidecar-injection # Enable sidecar injection
> osm namespace add bookstore --enable-sidecar-injection true # Enable sidecar injection
> osm namespace add bookstore --enable-sidecar-injection false # Do not enable sidecar injection / Remove label
> ```
> 
> Should be possible using: https://godoc.org/github.com/spf13/pflag#FlagSet.Changed
> 
> Just something to consider.

I don't quite get this, but one can still pass `--enable-sidecar-injection=<true|false>` with the existing code.
The question is whether a `namespace add` command should unset a previously set sidecar injection configuration, which I don't think is a good idea.

**Comment by ksubrmnn** [comment]
After syncing with @shashankram, we've both agreed that the workflow in the [above comment] (https://github.com/openservicemesh/osm/issues/1727#issuecomment-695110220) will work for this issue.

You can use 

```
isFlagSet := cmd.Flags().Changed("enable-sidecar-injection") {
```

**Comment by wenxinnnnn** [comment]
> After syncing with @shashankram, we've both agreed that the workflow in the [above comment] ([#1727 (comment)](https://github.com/openservicemesh/osm/issues/1727#issuecomment-695110220)) will work for this issue.
> 
> You can use
> 
> ```
> isFlagSet := cmd.Flags().Changed("enable-sidecar-injection") 
> ```

The final result of the discussion is whether the label is deleted when the namespace add command is executed?
