### ISSUE TITLE
The enableDebugServer is constant for the life of a pod; Move this to ConfigMap to make this dynamic

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1740]
This issue is to move the `enableDebugServer` from the OSM controller CLI params to the ConfigMap.
As a OSM Controller CLI param to enable or disable debug server one would have to change the Deployment spec and redeploy.
As a ConfigMap the osm controller would not have restart.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [X]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by wenxinnnnn** [comment]
I think there are more parameters in configmap that are suitable for hot reloading. For example: tracing_enable, prometheus_scraping, etc.
In addition, after each parameter is changed, it needs to be monitored by multiple users, so it is a burden to the user.
Is it better to automatically redeploy the pod after monitoring the configmap change?

**Comment by shashankram** [comment]
> I think there are more parameters in configmap that are suitable for hot reloading. For example: tracing_enable, prometheus_scraping, etc.
> In addition, after each parameter is changed, it needs to be monitored by multiple users, so it is a burden to the user.
> Is it better to automatically redeploy the pod after monitoring the configmap change?

Except for `envoy_log_level`, all other parameters in the ConfigMap support hot reloading. 

Eventually we would like the capability to turn on/off debug server without having to redeploy. For ex. we might need to turn the debug server on to troubleshoot an issue where we can't afford to redeploy causing traffic disruption. Something of this sort should not require redeployment just to enabling debug configurations at runtime.

**Comment by michelleN** [comment]
The PR to add this has not been merged yet. There are some tests we still need to write. Re-opening this and adding it to the next milestone.
