### ISSUE TITLE
OSM controller assumes services are backed by Deployments

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1744]
**Bug description**: In [GetServicesForServiceAccount](https://github.com/openservicemesh/osm/blob/0b25a309406ae9a18e9ab40a0881c900f58133a5/pkg/endpoint/providers/kube/client.go#L109), service accounts are looked up only in Deployment objects, so applications deployed as bare pods (and presumably other workload kinds) will not be configured properly via ADS. Here are the specific errors I saw in the osm-controller logs:

```
{"level":"error","component":"kube-provider","time":"2020-09-23T16:15:50Z","file":"client.go:153","message":"Did not find any service with serviceAccount = server in namespace e2e"}
{"level":"warn","component":"mesh-catalog","time":"2020-09-23T16:15:50Z","file":"service.go:14","message":"Error getting K8s Services linked to Service Account Kubernetes from provider e2e/server: no service exists for the service account"}
{"level":"error","component":"mesh-catalog","time":"2020-09-23T16:15:50Z","file":"routes.go:270","message":"TrafficTarget e2e/test-target could not get destination services for service account e2e/server"}
{"level":"error","component":"mesh-catalog","error":"no service found for service account with any of the mesh supported providers","time":"2020-09-23T16:15:50Z","file":"routes.go:43","message":"Could not get all traffic policies"}
{"level":"error","component":"mesh-catalog","error":"no service found for service account with any of the mesh supported providers","time":"2020-09-23T16:15:50Z","file":"routes.go:56","message":"Failed listing traffic routes"}
{"level":"error","component":"envoy/sds","error":"no service found for service account with any of the mesh supported providers","time":"2020-09-23T16:15:50Z","file":"response.go:178","message":"Error getting server names for inbound allowed Services e2e/server"}
{"level":"error","component":"envoy/sds","error":"no service found for service account with any of the mesh supported providers","time":"2020-09-23T16:15:50Z","file":"response.go:111","message":"Error creating cert root-cert-for-mtls-inbound:e2e/server for proxy e6424e83-55ca-419a-b368-d4f1c4ef73fb.server.e2e for service e2e/server"}
{"level":"error","component":"envoy/ads","time":"2020-09-23T16:15:50Z","file":"stream.go:70","message":"[NACK] Discovery request error from proxy e6424e83-55ca-419a-b368-d4f1c4ef73fb.server.e2e: code:13 message:\"Error adding/updating listener(s) outbound_listener: envoy.tracers.zipkin: unknown cluster 'envoy-tracing-cluster'\\ninbound_listener: envoy.tracers.zipkin: unknown cluster 'envoy-tracing-cluster'\\ninbound_prometheus_listener: route: unknown cluster 'envoy-metrics-cluster'\\n\" "}
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**: Applications deployed as pods not controlled by a deployment can have their services mapped to service accounts without errors.

**Steps to reproduce the bug (as precisely as possible)**:
1. Install control plane as described below.
1. Create and add an `e2e` namespace to the control plane.
1. Install [SMI policies](https://github.com/nojnhuh/osm/commit/184477269ccb6d72e5445cb8ea179b57d52d087b#diff-73e5e9c0da0e2289b47565142c011a9b) to the `e2e` namespace (changing the source and destination namespace of the traffic target to the `e2e` namespace).
1. Install a [simple HTTP server](https://github.com/nojnhuh/osm/commit/184477269ccb6d72e5445cb8ea179b57d52d087b#diff-6800bbf6c776f934c3bf6515504cf48a) to the `e2e` namespace.
1. See errors in the server's local Envoy config or the ones shown above from the osm-controller.

**How was OSM installed?**: Using the CLI built from [my fork](https://github.com/nojnhuh/osm/commit/184477269ccb6d72e5445cb8ea179b57d52d087b) with locally built images.
```
bin/osm install --container-registry=localhost:5000 --osm-image-tag=latest --osm-image-pull-policy="" --enable-debug-server
```

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: 184477269ccb6d72e5445cb8ea179b57d52d087b; Date: 2020-09-23-10:35`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:58Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): Single-node kind cluster created with `make kind-up`
- Others:

**Comment by shashankram** [comment]
Related: https://github.com/openservicemesh/osm/issues/1180
@nojnhuh if its the same, please consolidate, thanks.

**Comment by nojnhuh** [comment]
Thanks @shashankram, I didn't find anything like this after a cursory search but figured there must've been something related. I think I can fix this issue independent of that one, but we find a solution that fixes both we can certainly combine these.
