### ISSUE TITLE
Look into using containerd for the container runtime

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#1746]
**Please describe the Improvement and/or Feature Request**
Requesting the option of using containerd as the container runtime.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Benefit from community work on the containerd runtime.

**Comment by draychev** [comment]
OSM has no preference for the container runtime environment.
