### ISSUE TITLE
osm namespace add NAMESPACE does not enable automatic sidecar injection by default

### ISSUE THREAD

**Issue by patricekrakow** [openservicemesh/osm#1749]
**Bug description**:
`osm namespace add NAMESPACE` does not enable automatic sidecar injection by default

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
`osm namespace add NAMESPACE` should enable automatic sidecar injection by default as documented

**Steps to reproduce the bug (as precisely as possible)**:

```text
$ osm namespace list
No namespaces in any mesh
$ osm namespace add demo
Namespace [demo] successfully added to mesh [osm]
$ osm namespace list
NAMESPACE   MESH   SIDECAR-INJECTION   
demo        osm    -                   
$ osm namespace add --help

This command will add a namespace or a set of namespaces
to the mesh. Optionally, the namespaces can be configured
for automatic sidecar injection which enables pods in the
added namespaces to be injected with a sidecar upon creation.

Usage:
  osm namespace add NAMESPACE ... [flags]

Flags:
      --enable-sidecar-injection   Enable automatic sidecar injection (default true)
  -h, --help                       help for add
      --mesh-name string           Name of the service mesh (default "osm")

Global Flags:
  -n, --namespace string   namespace for osm control plane (default "osm-system")
$ osm namespace add demo --enable-sidecar-injection
Namespace [demo] successfully added to mesh [osm]
$ osm namespace list
NAMESPACE   MESH   SIDECAR-INJECTION   
demo        osm    enabled
```

**How was OSM installed?**:

```text
$ wget https://github.com/openservicemesh/osm/releases/download/v0.4.0/osm-v0.4.0-linux-amd64.tar.gz
...
$ osm version
Version: v0.4.0; Commit: 69d1d54fe4cf5883ad72852e3ceaf5efbbe959f1; Date: 2020-09-24-20:36
```

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
```text
Version: v0.4.0; Commit: 69d1d54fe4cf5883ad72852e3ceaf5efbbe959f1; Date: 2020-09-24-20:36
```
- Kubernetes version (use `kubectl version`):
```text
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster):
```text
NAME                                STATUS   ROLES   AGE    VERSION
aks-nodepool1-14300836-vmss000000   Ready    agent   125m   v1.17.11
aks-nodepool1-14300836-vmss000001   Ready    agent   125m   v1.17.11
aks-nodepool1-14300836-vmss000002   Ready    agent   125m   v1.17.11
```
- Others:

**Comment by wenxinnnnn** [comment]
Do you think it is an unreasonable design or a bug?
The current design does not take the --enable-sidecar-injection command to add namespace, only add monitoring.

The steps you provide to reproduce the error, are the results achieved like this?For details, please see #1727 
osm namespace add bookstore # Do not enable sidecar injection/ Do not change sidecar annotation label
osm namespace add bookstore --enable-sidecar-injection # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection=true # Enable sidecar injection
osm namespace add bookstore --enable-sidecar-injection=false # Do not enable sidecar injection / Remove label

**Comment by patricekrakow** [comment]
The help of `osm` says that `--enable-sidecar-injection   Enable automatic sidecar injection (default true)`, and I was understanding the `(default true)` as the sidecar injection being done by default. But, thanks to your full explanation, I am starting to understand my misunderstanding...
However, now I am not understanding the purpose of `osm namespace add bookstore` if it does not inject the sidecar. You said it only adds monitoring, but you can't have "monitoring" if you don't inject a sidecar proxy, or am I mixing "monitoring" with the "observability" feature of a mesh?

**Comment by wenxinnnnn** [comment]
Sidecar injection is only related to end-to-end distributed tracking.
For [observability](https://github.com/openservicemesh/osm/blob/main/docs/patterns/observability.md), you can look at the document here.

**Comment by wenxinnnnn** [comment]
Sorry, I should describe in more detail.
`osm namespace add bookstore` or `osm namespace add bookstore --enable-sidecar-injection=false` only means that the pod under the namespace does not automatically inject the sidecar. But you can pass `kubectl annotate pod <pod> openservicemesh.io/sidecar-injection=enabled`, enable sidecar injection on a pod.
About `osm namespace add bookstore`,i think that the namespace is monitored by osm. If the namespace is not monitored, osm will not do anything to it.

**Comment by patricekrakow** [comment]
Thanks for your explanation. I am still wondering what _the namespace is monitored by osm_ actually means. It's just that in order to answer your question _Do you think it is an unreasonable design or a bug?_ I would like to understand what `osm namespace add bookstore` actually does. Because if it turns out that `osm namespace add bookstore` is doing nothing, then yes I would even question the utility of the `--enable-sidecar-injection` flag. On the other hand, if `osm namespace add bookstore` does not inject the sidecar proxy, but actually does something else (that I just currently don't understand), then it makes sense and I just want to close this issue.

**Comment by shashankram** [comment]
> Thanks for your explanation. I am still wondering what _the namespace is monitored by osm_ actually means. It's just that in order to answer your question _Do you think it is an unreasonable design or a bug?_ I would like to understand what `osm namespace add bookstore` actually does. Because if it turns out that `osm namespace add bookstore` is doing nothing, then yes I would even question the utility of the `--enable-sidecar-injection` flag. On the other hand, if `osm namespace add bookstore` does not inject the sidecar proxy, but actually does something else (that I just currently don't understand), then it makes sense and I just want to close this issue.

By design, OSM requires you to first enroll name namespaces in a mesh. When you enroll a namespace via the `osm namespace add` command, it informs osm-controller to start monitoring k8s resources in that namespace. This allows multiple instances of osm-controller to exist within the same cluster without interfering with each other, as would be the case if 2 instances of osm-controller end up mutating the same resources in the same namespace.

I do see why you are confused though
```
--enable-sidecar-injection   Enable automatic sidecar injection (default true)
```

@wenxinnnnn would you mind updating the help text to convey this option needs to be explicitly set.

**Comment by shashankram** [comment]
I opened https://github.com/openservicemesh/osm/issues/1750 to resolve the help text ambiguity 
```
--enable-sidecar-injection   Enable automatic sidecar injection (default true)
```
