### ISSUE TITLE
Update help text for the `--enable-sidecar-injection` flag in the osm install command

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1750]
**Bug description**:
For sidecar injection to be enabled as a part of `osm namespace add`, it must be explicitly set using 
```
--enable-sidecar-injection   Enable automatic sidecar injection (default true)
```

However, since the default is true in the help text, the flag needs to be explicitly passed in, without which sidecar injection would be disabled. This is confusing.  

The change in the help text is as a result of https://github.com/openservicemesh/osm/pull/1728.

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
`Version: dev; Commit: 3b50aac04217ee62b5b2ec7f5b6d456961a32289; Date: 2020-09-21-16:11`

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (number of worker nodes in the cluster): 1

**Comment by shashankram** [comment]
@wenxinnnnn would you mind looking into this.

**Comment by wenxinnnnn** [comment]
ok
