### ISSUE TITLE
Enforce a single OSM controller per cluster via a feature flag

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#1754]
Provide a way to constrain OSM to a single mesh per cluster.

Reason: External addons might only want to run a single instance of OSM in their cluster at all times.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by shashankram** [comment]
We already have validations for detecting existing osm-controller.

```
$ kc get pods -n osm-system 
NAME                              READY   STATUS    RESTARTS   AGE
jaeger-547d9c8b5c-gbcpp           1/1     Running   0          23m
osm-controller-5f4f9495dc-9mv8s   1/1     Running   0          23m
osm-prometheus-85bd64f775-brsvj   1/1     Running   0          23m

$ ./bin/osm install
Error: Mesh osm already exists in cluster. Please specify a new mesh name using --mesh-name

$ ./bin/osm install --mesh-name foo
Error: Namespace osm-system has an osm controller. Please specify a new namespace using --namespace
```

What we need from this feature request is to ensure we can program OSM in a way that prevents multiple meshes from being installed in certain environments.

**Comment by draychev** [comment]
The goal of this issue is to ensure that when a feature flag or an option is enabled OSM ensures that it is the only OSM controller on a givne cluster.

P1: Document this
P2: Create the validation
