### ISSUE TITLE
enable serviceCertValidityMinutes in the configmap to make it dynamic

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#1757]
As of today the `serviceCertValidityMinutes` is configurable only at the time of install, we want to make this configurable at any time. Hence this needs to be added to the configmap for osm

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by wenxinnnnn** [comment]
Assign this to me?

**Comment by shashankram** [comment]
Why is this a `P1` @snehachhabria. What is the use case for users to start tweaking cert validity period at run time?

**Comment by snehachhabria** [comment]
By default we will install OSM with a validity of 1 day but if users  want a different validity for their version of osm we want it configurable

**Comment by shashankram** [comment]
> By default we will install OSM with a validity of 1 day but if users want a different validity for their version of osm we want it configurable

Question was more regarding what is the use case to change the validity period? Should this be a P1?

**Comment by draychev** [comment]
We need to validate input and ensure that the value is within some reasonable ranges. (For example a fraction of a minute may not be reasonable as it would cause too frequent of a cert renewal.)
