### ISSUE TITLE
Provide a way to prohibit certain namespaces from being enrolled in the service mesh (block injection)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1759]
This issue is to develop the feature to provide a list of namespaces which will never be part of the service mesh and pods in these namespaces should never be injected with an Envoy side-car.  The list of namespaces should be left to the OSM operator.
One such namespace MUST be the namespace in which the OSM Controller is installed.

**Scope (please mark with X where applicable)**
- New Functionality          [x]
- Install                    [x]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
Reopening this issue to think about how to deal with situations where some namespaces cannot be annotated w/ a label.

**Comment by shashankram** [comment]
> Reopening this issue to think about how to deal with situations where some namespaces cannot be annotated w/ a label.

@draychev  Could you share more information for such a use case? The mutatingwebhookconfiguration can only ignore namespaces based on a namespaceSelector which is limited to selector matching on labels.

**Comment by shashankram** [comment]
This can be closed, new requirements to label namespace is tracked in https://github.com/openservicemesh/osm/issues/1817
