### ISSUE TITLE
Validating webhook to validate user-provided values

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1788]
**Please describe the Improvement and/or Feature Request**

For user configurable values, e.g via osm configmap, we need a validating webhook to reject updates if not within the tested limits.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Related https://github.com/openservicemesh/osm/issues/1757

**Comment by ritazh** [comment]
Question: what are other user configurable values and how are they introduced (other than the osm configmap)?

**Comment by shashankram** [comment]
> Question: what are other user configurable values and how are they introduced (other than the osm configmap)?

SMI policies.

**Comment by draychev** [comment]
Related https://github.com/openservicemesh/osm/issues/1740
