### ISSUE TITLE
Investigate using Helm chart releaser for releases

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1800]
**Please describe the Improvement and/or Feature Request**
Investigate using https://github.com/helm/chart-releaser-action to release Helm charts as a part of releases.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [X]

**Comment by nojnhuh** [comment]
Looks like that action will always create a new GitHub release for the chart, which probably isn't what we want, but seems like it would be simple to change:
https://github.com/helm/chart-releaser-action/blob/06d81fa7f63ab865cf0ed2045bde38529c392845/cr.sh#L77-L78

Still curious as to why the existing action is never even started vs. starting and failing.

**Comment by shashankram** [comment]
> Looks like that action will always create a new GitHub release for the chart, which probably isn't what we want, but seems like it would be simple to change:

Isn't a new github release for the chart what we want to accomplish when we release a chart?

**Comment by nojnhuh** [comment]
I think the main thing we want is to publish the packaged chart onto the gh-pages branch which serves as a Helm repo, which wouldn't require a GitHub release. It might be a little confusing to have both chart releases and regular CLI releases on the releases page.

**Comment by shashankram** [comment]
> I think the main thing we want is to publish the packaged chart onto the gh-pages branch which serves as a Helm repo, which wouldn't require a GitHub release. It might be a little confusing to have both chart releases and regular CLI releases on the releases page.

I see what you mean. Would it be possible to combine this into 1 release?

**Comment by nojnhuh** [comment]
The GH action uses this under the hood to do most of the work: https://github.com/helm/chart-releaser. I don't see any way to point it to an existing release. Even if it could, the action doesn't seem to accept any parameters besides a GitHub token.

**Comment by nojnhuh** [comment]
The GH action we already had was working after all, the real issue was fixed with #1802.
