### ISSUE TITLE
Add support for Kiali

### ISSUE THREAD

**Issue by ivanfarkas2** [openservicemesh/osm#1810]
**Add Kiali**
To be on par with Istio, Kiali is essential.

**Scope (please mark with X where applicable)**
- New Functionality          [ X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Debug inter Microservice traffic.

**Comment by shashankram** [comment]
It doesn't seem like Kiali intends to support service meshes other than Istio, see https://github.com/kiali/kiali/discussions/4166, https://github.com/kiali/kiali/discussions/4473.

**Comment by raj13aug** [comment]
Which tool is used for visualization in OSM? Looking at similar features like that available in Kiali?
