### ISSUE TITLE
Add a namespace resource for osm deployment

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1817]
**Please describe the Improvement and/or Feature Request**

Per https://github.com/openservicemesh/osm/pull/1777/files#r502142284, we need to create the namespace resource as part of the deployment manifests and the chart. This namespace resource should include the `openservicemesh.io/ignore` label.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
We don't necessarily need the ignore label on a namespace we create. We could also create a ns with a label `name` with value being the namespace.

https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/mutatingwebhook.yaml#L25

@ritazh could you list the different scenarios you'd like to achieve with labeling the namespace with the ignore label? As long as the namespace is created by Helm, it will be ignored based on https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/mutatingwebhook.yaml#L25.

If a namespace is pre-created, whoever creates it needs to ensure that the requirements to ignore a namespace are met.

**Comment by ritazh** [comment]
Sure if we are explicitly deploying this namespace resource, then we could set the `name` label to be consistent with `--create-namespace` if the label gets set thru that flag. 

For existing namespaces that we do want to exclude, e.g. kube-system, I think the recommendation is to use the `openservicemesh.io/ignore` label right?

**Comment by shashankram** [comment]
> Sure if we are explicitly deploying this namespace resource, then we could set the `name` label to be consistent with `--create-namespace` if the label gets set thru that flag.
> 
> For existing namespaces that we do want to exclude, e.g. kube-system, I think the recommendation is to use the `openservicemesh.io/ignore` label right?
> 

This is correct, for existing namespaces that need to be excluded the ignore label is required.

> The `name` label will only be added if users did `helm install -create-namespace`, which is not ideal. This issue suggests creation of a namespace resource as part of the chart and deployment yamls such that the name of the namespace will be passed thru via `values.yaml` or default to `osm-system`. WDYT?

There are a few scenarios here:
1. namespace is created by osm cli using Helm: here the `name` label on the namespace will always be present
2. namespace is created by OSM Helm chart directly from a manifest: either name or ignore label should be added
3. namespace exists prior to OSM install

Are you suggesting we `update` the namespace with a label if it already exists (3 above)? Or are you suggesting to always create a namespace for osm-system via a manifest file instead of using the auto-create namespace option with helm?

**Comment by ritazh** [comment]
> There are a few scenarios

1: I believe the cli already does this.
2: This issue should take care this scenario. I think we should create a namespace resource via a manifest file with those labels and default to `osm-system` in values.yaml.
3: This could be taken care of by a pre-install hook. The same logic in this [PR](https://github.com/Azure/osm-azure/pull/9) can also be added in this repo. WDYT?

**Comment by shashankram** [comment]
> > There are a few scenarios
> 
> 1: I believe the cli already does this.

This is correct, but if we want to create the namespace via a manifest then we should potentially remove the code to auto create the namespace.

> 2: This issue should take care this scenario. I think we should create a namespace resource via a manifest file with those labels and default to `osm-system` in values.yaml.

This makes sense, and would obviate the need to auto create namespace via the helm library without a manifest, correct?

> 3: This could be taken care of by a pre-install hook. The same logic in this [PR](https://github.com/Azure/osm-azure/pull/9) can also be added in this repo. WDYT?

A pre-install hook would work, whoever I am unsure if in some environments if mutating an existing namespace (adding labels) will be permitted.

**Comment by ritazh** [comment]
> if we want to create the namespace via a manifest then we should potentially remove the code to auto create the namespace

That makes sense to me.

> obviate the need to auto create namespace via the helm library without a manifest

Right

> I am unsure if in some environments if mutating an existing namespace (adding labels) will be permitted

If the user has the cluster-admin role to create the namespace, then they should be able to update existing namespaces to apply these labels. The next question is what about namespaces that are created _after_ osm is deployed.

**Comment by shashankram** [comment]
> If the user has the cluster-admin role to create the namespace, then they should be able to update existing namespaces to apply these labels. The next question is what about namespaces that are created _after_ osm is deployed.

We do not need to worry about namespaces other than the control plane namespace, because I believe we already have a solution for this - either add the ignore label on the user namespace or use osm cli to do it.

**Comment by shashankram** [comment]
Based on our discussions, some of the concerns regarding what namespaces get enabled for sidecar injection originally raised in this issue were alleviated.

The only remaining decision to make is to whether have OSM manage its own namespace, or let Helm manage it.

**Comment by ritazh** [comment]
To add more context, the original concern was around if a user created a namespace for helm install to install osm components to and if the namespace does not have the `openservicemesh.io/ignore` label, then it will not be exempted. This is alleviated by the mutatingwebhookconfig [matching on the existence of the `openservicemesh.io/monitored-by` label](https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/mutatingwebhook.yaml#L19) on the namespace as well. 

I will close this issue for now and can reopen if anyone feels strongly about installing the namespace resource as part of the chart.
