### ISSUE TITLE
Join Envoy security disclosure mailing list

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1818]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by bridgetkromhout** [comment]
Quick question - do we want to provide a link somewhere so people can subscribe to the desired list? Or are we looking to have several individuals subscribe? We won't want to subscribe a mailing list to another mailing list.

**Comment by ritazh** [comment]
This issue is to ensure osm maintainers are part of Envoy's embargo CVE disclosure mailing list to make the necessary Envoy updates and tests in osm before cutting a new osm release.

**Comment by shashankram** [comment]
> This issue is to ensure osm maintainers are part of Envoy's embargo CVE disclosure mailing list to make the necessary Envoy updates and tests in osm before cutting a new osm release.

Maintainers have been asked to join the envoy security mailing list.
