### ISSUE TITLE
Envoy OSM release and feature compatibility

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1820]
**Please describe the Improvement and/or Feature Request**

As a new version of Envoy is added to OSM, how do we keep track of its capabilities as relate to OSM features?

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
It's fair to say core features in Envoy are not deprecated as easily between releases. When there is an impact on OSM, the OSM team documents the behavior change in the release notes and provides an alternative workflow to users if possible. At the moment, we do not have the need to audit Envoy releases beyond gating the Envoy version updates through our regular CI suite.
