### ISSUE TITLE
Remove hard-coded values from end to end tests

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1825]
Some of the E2E introduced recently have some values hardcoded, most notably and since some of the tests might run at different speeds depending directly on the Kubernetes deployment type, we'd want to make sure those are parametrizable and can be easilly changed when running the test. Some of the values:

- [Wait times to wait for pods](https://github.com/openservicemesh/osm/pull/1801/files#diff-70174cb01ef0307525125f366f83690424d08729a051445ea69d9284c3fbdc05R23). This could be a (parametrized) framework provided value, with potential for the test to knob this around depending on expectations. 
- [Success values](https://github.com/openservicemesh/osm/pull/1801/files#diff-70174cb01ef0307525125f366f83690424d08729a051445ea69d9284c3fbdc05R115). This are per test, potentially do not need to be parametrized, but at least set into variables and not hardcoded.

**Area of effect:**
- Tests                      [X]

**Comment by draychev** [comment]
@eduser25 What's the status on this? I see 3 merged PRs - are we ready to close this issue?

**Comment by eduser25** [comment]
Closing, stale.
