### ISSUE TITLE
update chart README as part of the release pipeline

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1830]
**Please describe the Improvement and/or Feature Request**
Update the chart README as part of the release pipeline / GitHub Action

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [X ]

**Possible use cases**
So people have to up to date info about chart values

**Comment by shashankram** [comment]
This is no longer necessary because the Helm chart readme now needs to be updated every time the charts are updated. This is enforced in the CI: 

https://github.com/openservicemesh/osm/blob/76c6843ce8dd04e53bd809229a331e2d93c9a619/.github/workflows/main.yml#L67-L74
