### ISSUE TITLE
CLI delete behavior undefined when more than one OSM w same name on cluster

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1839]
This GitHub Issue is a request to improve the `osm mesh delete` experience. The CLI tool must provide **additional context** for the user to understand exactly which OSM deployment is going to be deleted.

## Current State
For example -- on the same cluster I have 2 OSM controllers installed. The OSMs have the **same mesh name** but in *different namespaces* (perhaps that should not be allowed):
```bash
$ ./bin/osm mesh list 

MESH NAME   NAMESPACE
osm         mesh-system
osm         osm-system

```

Issuing the `osm mesh delete` command  - I am asked whether I want to delete `osm` - but  I am unclear exactly which instance is going to be deleted:
```bash
$ ./bin/osm mesh delete

Uninstall OSM [mesh name: osm] ? [y/n]: y
OSM [mesh name: osm] uninstalled

````

Outcome

```bash
$ ./bin/osm mesh list

MESH NAME   NAMESPACE
osm         mesh-system
```

It seems that the `osm` deleted was the one in the `osm-system` namespace.

## Suggested Improvement

To improve this I suggest we change the behaviour of the `osm mesh delete` command.  It should list all OSM meshes on the current Kubernetes cluster and ask for a particular index / row number to be deleted.

For example:

```bash
$ osm mesh delete

There are 2 OSM controller deployments running on cluster osm-abcd.westcentralus.azmk8s.io
 
N:  MESH NAME   NAMESPACE      CONTROLLER PODS
1:  osm         mesh-system    osm-controller-abc,osm-controller-efg
2:  osm         osm-system     osm-controller-xyz

Which one [1, 2]: 

Uninstall OSM [mesh name: osm in namespace mesh-system] ? [y/n]: y
OSM [mesh name: osm in namespace mesh-system] uninstalled

````

I would like to see:
1. Cluster which I am about to affect
2. OSM Name 
3. Namespaces where these OSM Controllers
4. Pod(s) of the OSM Controller to be deleted

With this context there would be no ambiguity which mesh I am deleting.

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [x]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by michelleN** [comment]
I don't think this should be possible in the current state because the mutatingwebhookname relies on the mesh name and it is a cluster scoped resource. If you try to install a control plane with the same name, the installation will fail. However, this issue exposes ambiguity around mesh name that can be cleaned up. What do you think about adding validation to ensure that a control plane should be unique to a cluster?


cc/ @shashankram @ksubrmnn

**Comment by draychev** [comment]
+1 on "adding validation to ensure that a control plane should be unique to a cluster" - would solve this issue
