### ISSUE TITLE
CLI to list meshes should show additional context: k8s cluster, controller pods

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1841]
The `osm mesh list` command currently only shows mesh name and namespace.

For example:

```bash
$ ./bin/osm mesh list

MESH NAME   NAMESPACE
osm         osm-system
```

## Improvement Proposal

I would like to also see the following pieces of context:
1. Pods of the OSM Controller
2. Kuberenetes cluster
3. Namespaces joined to the service mesh

```bash
$ ./bin/osm mesh list

OSM Deployments on cluster osm-abc.westcentralus.azmk8s.io

MESH NAME   NAMESPACE     CONTROLLER PODS     JOINED NAMESPACES
osm         osm-system    osm-abc,osm-xyz     ns1,ns2
```

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by mudit-01** [comment]
hi @draychev I would like to work on it.

**Comment by draychev** [comment]
@mudit-01 Thank you so much for joining us!

This is all yours!  


Reach out if you have any questions - my e-mail is on my GitHub profile!
Also join us if you want and can make it for your community calls:  https://github.com/openservicemesh/osm#community

**Comment by mudit-01** [comment]
@draychev PR for this issue #2596

**Comment by shashankram** [comment]
> @draychev PR for this issue #2596

Resolved by https://github.com/openservicemesh/osm/pull/2596
