### ISSUE TITLE
Verify cleanup in e2e test suite

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1851]
**Please describe the Improvement and/or Feature Request**

I don't have a clear idea of exactly what we should test for, but to catch issues like #1829 we could start with the following steps:

1. Install OSM.
1. Verify OSM pod(s) are running.
1. Delete OSM using `osm mesh uninstall` or `helm delete`.
1. Install OSM in the same location with the same parameters.
1. Verify OSM pod(s) are running.

These steps could either make up their own test or be integrated into an existing test. They also aren't meant to be complete in that they cover everything related to cleanup, just an example of one scenario. I expect we'll think of more.

---
Use cases:
- [ ] Verify no resources are left behind unintentionally
- [ ] Verify OSM can be reinstalled after being uninstalled

**Comment by eduser25** [comment]
I think this could very well be a test on its own.
We don't have graceful uninstall/cleanup calls in the framework though, cleanup takes nuclear approach and blows up the namespace altogether.
