### ISSUE TITLE
OSM CLI: provide a way to toggle ConfigMap permissive_traffic_policy_mode true/false

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1855]
At the moment one has to know how to switch from permissive trafic policy mode to observing SMI and back.
This happens via the `osm-config` ConfigMap -- setting the `permissive_traffic_policy_mode` key to `true` or `false` and reapplying - [example](https://github.com/openservicemesh/osm/blob/10a8cc38a32b303f807c9e60d73b28308663a779/demo/deploy-smi-policies.sh#L23).

It would be great to implement this functionality in the OSM CLI so that one colud easily issue a command to a) check the current mode of the service mesh and b) change it

Also - the following Issue will document all ConfigMap values and what they do: https://github.com/openservicemesh/osm/issues/1842
Once we implement a CLI command to change config map values we should add it to the outcome of https://github.com/openservicemesh/osm/issues/1842

---

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

---

Use cases:  

  - `osm configure --mesh=osm --policy-mode=permissive`  -- sets `permissive_traffic_policy_mode` to `true`
  - `osm configure --mesh=osm --policy-mode=smi` -- sets `permissive_traffic_policy_mode` to `false`

**Comment by michelleN** [comment]
agree we totally need this. This should be handled by the `osm mesh update` command imo. #1474

**Comment by shashankram** [comment]
OSM ConfigMap was deprecated several releases ago, and the formal way to update the mesh configuration is via the MeshConfig custom resource using native k8s tools/API.
