### ISSUE TITLE
Converge on uniform terminology for destination / remote / outbound / downstream / server

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1860]
In sections of the OSM repo we refer to the `other side` in various terms:

  - destination service
  - remote service
  - outbound service 
  - downstream service
  - server

For example in `pkg/envoy/cds/response.go`: https://github.com/openservicemesh/osm/blob/release-v0.4/pkg/envoy/cds/response.go#L40-L47

We see `dstService`, `outboundServices`, `getRemoteServiceCluster` - in all of these we are referring to a service on the other side.

It would be great to converge on a single term and use that across the repo for disambiguation.

--- 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
We decided that we would use the following terminology:
- downstream: when referring to the source service initiating the request
- upstream: when referring to the destination/remote service accepting the request

**Comment by draychev** [comment]
related issue:  https://github.com/openservicemesh/osm/issues/979
