### ISSUE TITLE
Describe if metrics stack is enabled and if not how to, with the demo documentation

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1893]
**Please describe what should be documented
Describe in the demo readme whether Prometheus and Grafana are enabled by default, and link to https://github.com/openservicemesh/osm/blob/main/docs/patterns/observability.md#automatic-bring-up on how to automate this with the manual demo.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/docs/example/README.md

**Comment by ksubrmnn** [comment]
Fixed by #1868
