### ISSUE TITLE
add a log forwarding example to docs

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1898]
**Please describe what should be documented
Add how to forward logs to a sink via fluent bit in osm (log sink example can be Azure log analytics)

**Please suggest where in the repo the document should be located
docs/patterns/observability/log-forwarding.md

cc @SanyaKochhar

**Comment by SanyaKochhar** [comment]
@michelleN I can merge this for v0.5.0, just waiting on one more review
