### ISSUE TITLE
Add helm uninstall to e2e

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1907]
**Please describe the Improvement and/or Feature Request**

We should test `helm uninstall` to ensure clean uninstall experience.
This will also help us:
- document what resources are expected to be left behind in the cluster post uninstall e.g. crd
- identify issues when resources are stuck in terminating state or not cleaned up correctly e.g. namespace, secret

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by nojnhuh** [comment]
@ritazh `helm uninstall` is currently being executed by the same test that does `helm install`: https://github.com/openservicemesh/osm/blob/57aad53279ed0a90e85e0ff13fe7544e7f4f9d1f/tests/e2e/e2e_helm_install_test.go

The exact effects of `helm uninstall` aren't explicitly validated, but this test runs in sequence with several other tests against the same kind cluster in CI. Is there something more specific we should add to the test suite for this?

**Comment by shashankram** [comment]
Since Helm uninstall is already being tested by `e2e_helm_install_test.go`, this issue should be taken care of.
For additional enhancements to the uninstall test, kindly open a new issue with more details.
