### ISSUE TITLE
Refactor e2e `InstallOSM` to to support helm install too

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1908]
https://github.com/openservicemesh/osm/pull/1889
`helm install` APIs were added to e2e, however it happens to separate apis to specifically just test the install.

It'd be a benefit in the long run that installing through helm was just an option for the test suite and used the available
APIs, so all tests could potentially run with helm installation instead of CLI installation just with a toggle/switch change.

- Tests                      [X]

Use cases:
Running the entire suite with helm install/CLI agnostically, using the same test APIs.

**Comment by shashankram** [comment]
There's little value in running the entire suite with and without Helm, as the CLI internally leverages the Helm API. We have a test that installs and uninstalls using Helm, so I hope this suffices.
