### ISSUE TITLE
Add reconciler for osm resources

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1909]
**Please describe the Improvement and/or Feature Request**

- webhook mutatingwebhookconfiguration and secret
   Watch for changes in osm-webhook mwhc and secret resources to reconcile/ensure the CA cert in the mwhc is using the most recent CA cert from the secret.
- configmap
- custom resources

## Definition of **done**: 
This issue should result in a documentation that describes what resources osm owns and wants to reconcile. Then we can create followup issues for any reconcilers.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [X]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
> Watch for changes in osm-webhook mwhc and secret resources to reconcile/ensure the CA cert in the mwhc is using the most recent CA cert from the secret.

The CA bundle in the mutatingwebhookconfigration gets patched as a part of the webhook's initialization: https://github.com/openservicemesh/osm/blob/0be40ed8bdb7dd64866f3c6812d73eb0380f5d15/pkg/injector/webhook.go#L80

The CA bundle gets created at the time of osm-controller startup, at which time the webhook gets initialized. So I am unsure why a reconciler is neccessary for this. 

@ritazh could you clarify where this would be applicable?

**Comment by ritazh** [comment]
@shashankram sure. for example, you can modify the mutatingwebhookconfigration resource by using `kubectl edit`

**Comment by shashankram** [comment]
> @shashankram sure. for example, you can modify the mutatingwebhookconfigration resource by using `kubectl edit` directly to updat/remove the caBundle.

If someone has permissions to mutate cluster wide resources, they can do a lot more than just update the mutatingwebhookconfiguration. The mutatingwebhookconfiguration is not the only resource OSM creates, there are several of them which the controller depends on for control plane logic - ConfigMaps, Secrets, CRDs etc. Any of those can be changed using `kubectl edit`. I don't see value in handling this in isolation given other resources can be subject to the same.

If the goal used to introduce a reconciler, it would likely be better to introduce this as a separate component outside of the osm-controller to avoid creating circular dependencies.

This issue definitely needs more though and discussion before proceeding.

**Comment by ritazh** [comment]
> I don't see value in handling this in isolation given other resources can be subject to the same.

+1

This issue just starts with the mwhc resource, but definitely need to reconcile all the resources that osm creates.

**Comment by shashankram** [comment]
> > I don't see value in handling this in isolation given other resources can be subject to the same.
> 
> +1
> 
> This issue just starts with the mwhc resource because it can break the webhook and potentially the cluster, but definitely need to reconcile all the resources that osm creates.

Maybe we should update the description to describe the long term goals as well, so that we consider this when we design and discuss the bigger solution.

**Comment by shashankram** [comment]
Some notes on reconciling certain resources:
- For resources created by Helm and later patched by the controller (such as mutatingwebhookconfiguration), the reconciling will have to take care of updating the resource to its latest state. Since such a resource was managed by Helm before, should the recreation be triggered by Helm so that it can manage it as initially intended? 
- With a reconciler, a malicious user that somehow manages to get access to deleting/mutating a resource could bring the system down by repeatedly mutating the resource and triggering the reconciler, which could easily result in wastage of resources.

**Comment by shashankram** [comment]
> Some notes on reconciling certain resources:
> 
> * For resources created by Helm and later patched by the controller (such as mutatingwebhookconfiguration), the reconciling will have to take care of updating the resource to its latest state. Since such a resource was managed by Helm before, should the recreation be triggered by Helm so that it can manage it as initially intended?
> * With a reconciler, a malicious user that somehow manages to get access to deleting/mutating a resource could bring the system down by repeatedly mutating the resource and triggering the reconciler, which could easily result in wastage of resources.

@ritazh this needs more thought.

**Comment by snehachhabria** [comment]
Based on an offline sync, we will use this issue to track the reconciliation of the CA bundle for the mwhc. The CA bundle reconciliation will take place only if the CA bundle is generated by OSM, Created another issue https://github.com/openservicemesh/osm/issues/1974 to extend out OSM to give mesh owners/ creators to bring their own CA bundle and hence own the management of the mwhc.
