### ISSUE TITLE
Proposal: Modify "osm install" command to only set values when overriding the default

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1911]
**Please describe the Improvement and/or Feature Request**

Following up from discussion in #1889.

Currently, `osm install` explicitly sets every value for the chart that can be set from flags. This causes issues like the one solved by #1765 where a misspelled value name in values.yaml causes problems with `helm install` but not `osm install`. Only setting values when necessary will more closely match the behavior of installing with Helm directly.

I propose we clear the default values for the `osm install` command and only set them when we invoke Helm when the value has been set with a flag. We could still document the default values by showing values.yaml for the embedded chart in `osm install --help` or directing users with a different chart to use `helm show values`.

This change has the added benefit of eliminating the overhead of keeping the defaults in values.yaml in sync with the install flags.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

- More closely match `helm install` default behavior

**Comment by shashankram** [comment]
This issue should not be relevant anymore given that `osm install` leverages the `--set` option instead of custom flags to override default chart values.
