### ISSUE TITLE
Definition of "stable"

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#1912]
Produce a documentation that describes what we mean by "stable" for the osm project. 
This should be used as a guidance for v1.0.0 release.

**Comment by phillipgibson** [comment]
Document has been drafted and is under review.

**Comment by ritazh** [comment]
We can use this as a guide: https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/README.md#production-readiness-review-questionnaire

**Comment by michelleN** [comment]
v1 proposal here: https://docs.google.com/document/d/128x88vEM8gga0bg4vXDgyy45y3iC5EQb464zfpkg_e0/edit?usp=sharing 

We'll need to make sure that each of these items has an issue attached to it. Many of these have already been completed.

**Comment by draychev** [comment]
This task was completed with  https://docs.google.com/document/d/128x88vEM8gga0bg4vXDgyy45y3iC5EQb464zfpkg_e0/edit?usp=sharing

Thank you @michelleN
