### ISSUE TITLE
Introduce publish subscribe interface for channels

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#1914]
Channels are implemented as a FIFO, with the first reader being able to read from the channel when there are multiple readers for the same channel.

See https://github.com/openservicemesh/osm/pull/1871#discussion_r510299374 on why such an interface will be useful.

With a generic interface to publish and subscribe for events based on channels, there would be no issue when a single channel has multiple readers/writers.

**Comment by draychev** [comment]
This project seems relevant and very interesting: https://github.com/grafov/bcast

**Comment by shashankram** [comment]
> This project seems relevant and very interesting: https://github.com/grafov/bcast

Thanks for sharing, there are few other implementations such as https://github.com/dustin/go-broadcast
