### ISSUE TITLE
Milestone v0.6.0 Prep

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1915]
Please leave a comment with things/issues you think we should work on during the v0.6.0 milestone

**Comment by ritazh** [comment]
https://github.com/openservicemesh/osm/issues/1912
https://github.com/openservicemesh/osm/issues/1909
https://github.com/openservicemesh/osm/issues/1907
https://github.com/openservicemesh/osm/issues/1797
https://github.com/openservicemesh/osm/issues/1895
