### ISSUE TITLE
create a framework for measuring performance and scalability of an osm control plane

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1916]
As an initial metric, we should be able to run this tool and have it tell us how many gRPC streams (or Pods essentially) one osm control plane can support.

**Comment by michelleN** [comment]
@eduser25 - can you help us figure this out?

**Comment by shashankram** [comment]
There a few popular benchmarking and load testing frameworks available (ex. fortio) that can be used for perf testing. Is there a need to create a new framework for this?

**Comment by ritazh** [comment]
Highly recommend https://github.com/kubernetes/perf-tests/tree/master/clusterloader2 as we have used it for other projects in the past.

**Comment by eduser25** [comment]
Discussed with @ritazh, we've reviewed a number of frameworks and discussed both pros/cons of integrating a 3rd party framework vs extending our current one.

Based on discussion, these are at least some of the items we immediately want to qualify the control plane:

Control plane profiling - Given a single control plane and with set Mem and CPU limits:
- CPU trends
- Memory trends (mem increase per pod, test dependant)
- Control plane profiling (cpu & mem)
- Envoy config latency trends (time to create an envoy config on OSM, latency increase per pod, test dependant)
- Envoy config latency apply trends (from `SMI apply` to `200` network requests)

These are however bound to be horizontally scalable with additional OSM instances; the intention of this effort however is to fully assess how a single control plane instance behaves in different load sizes and explore perf ceilings.

For the tests and framework to use, for specifically control plane testing, some of the scenarios we are interested in are readily available in E2E framework and tests, which already include network logic and correctness checks, OSM and SMI deployment specifics, and metrics gathering out of the box. 

Dataplane qualification is meant to come after, and possibly subject to re-asses different tools or frameworks if necessary.

**Comment by draychev** [comment]
Sample of the progress on the tool measuring OSM Controller: https://github.com/eduser25/osm/pull/16#issuecomment-747661973

**Comment by snehachhabria** [comment]
Initial framework already exists, for anything new we will create new issues
