### ISSUE TITLE
Implement distributed tracing w/ Jaeger and Envoy header forwarding

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1921]
Implement distributed tracing w/ Jaeger and Envoy header forwarding

---

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

When bookbuyer makes a request to bookstore, bookstore makes a request to warehouse. The 2 requests are not linked. This issue is to implement Envoy header forwarding and document this so that the bookbuyer -> bookstore and bookstore --> warehouse requests could be related.
Documentation: https://github.com/openservicemesh/osm/issues/1919

**Comment by allenlsy** [comment]
Is this an Envoy configuration issue?

I did some research, and so far what I found is, Envoy can only generate new request ID, but it is the application's responsibility to propagate it. 

Also from Envoy documentation:

> One of the most important benefits of tracing from Envoy is that it will take care of propagating the traces to the Jaeger service cluster. However, in order to fully take advantage of tracing, the application has to propagate trace headers that Envoy generates, while making calls to other services. 

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_tracing

Thus, I think we need to update demo application in order to see multi-span tracing on Jaeger.

**Comment by shashankram** [comment]
> Is this an Envoy configuration issue?
> 
> I did some research, and so far what I found is, Envoy can only generate new request ID, but it is the application's responsibility to propagate it.
> 
> Also from Envoy documentation:
> 
> > One of the most important benefits of tracing from Envoy is that it will take care of propagating the traces to the Jaeger service cluster. However, in order to fully take advantage of tracing, the application has to propagate trace headers that Envoy generates, while making calls to other services.
> 
> https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_tracing
> 
> Thus, I think we need to update demo application in order to see multi-span tracing on Jaeger.

@allenlsy your understanding is correct regarding applications needing to propagate headers for related requests so the requests span can be calculated by Envoy.
