### ISSUE TITLE
Netlify bot causing PR check failures 

### ISSUE THREAD

**Issue by flynnduism** [openservicemesh/osm#1930]
The addition of a docs website in #1840 is causing issues across other recent PRs on this project:  

![Screen Shot 2020-10-27 at 1 06 36 PM](https://user-images.githubusercontent.com/686194/97356344-5c043b00-1855-11eb-89e5-1b3b4a7aa528.png)

Apologies for this, the deploy preview bot is resulting in failures ❌  as it tries to build a website that does not yet exist in `main`. 

To quickly resolve this, I've removed the Github responses from the Netlify config - but one additional change needs to happen to get those PR checks back to ✅:

* remove the Netlify app from the OSM Github org [here](https://github.com/organizations/openservicemesh/settings/apps) (requires an admin)  
* or #1840 gets merged - then any progress PRs would need a rebase to pass the Netlify bot check

**Comment by bridgetkromhout** [comment]
Hmm... if we remove the Netlify app, won't that disrupt your ability to work on the website? So that seems like a short-term fix at best. (I can do it if you think I should.)

Maybe we want to merge the PR to add the docs to the website but hide the link until it's the way we want it?

**Comment by bridgetkromhout** [comment]
After conferring with @flynnduism I have temporarily removed the Netlify integration for this repo. (This doesn't remove the integration for the website repo.)

**Comment by flynnduism** [comment]
PR checks should be back to normal now. Thank you @bridgetkromhout! 

Closing this.
