### ISSUE TITLE
Make certificate key bit size configurable

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1933]
https://github.com/openservicemesh/osm/issues/1931 requests to lower the key bit size by default; we would like to have a mechanism to configure the key bit size on OSM, as opposed to a hardcoded value.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Envoy Control Plane        [X]
- Certificate Management     [X]

**Possible use cases**
Current default-only behavior won't do for users which require different key bit-size.

**Comment by irbekrm** [comment]
Hi @eduser25, could I work on this?

**Comment by shashankram** [comment]
> Hi @eduser25, could I work on this?
>
 
Hey @irbekrm, you are welcome to work on this issue. 

> Is this intended to be just for the certs generated by the internal `tresor` package or also for the external certificate issuers like `cert-manager`?

It would be good to make the bit size configurable irrespective of the certificate provider being used (tresor, cert-manager, vault etc.). Both cert-manager and tresor providers in OSM expose the key size as constants at the moment. To make this configurable, you will need to hook this config option via the `osm-config` ConfigMap.

ConfigMap: 
https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/osm-configmap.yaml
https://github.com/openservicemesh/osm/blob/main/docs/osm_config_map.md

Controller code parsing ConfigMap:
https://github.com/openservicemesh/osm/tree/main/pkg/configurator

**Comment by irbekrm** [comment]
Thank you! I will look at making it configurable for either certificate provider (I guess probably with the same CLI flag).

/assign

**Comment by draychev** [comment]
@irbekrm Have you had a chance to take a stab at this?

**Comment by irbekrm** [comment]
Apologies, I should have unassigned myself from this ages ago. Unfortunately I will not have a chance to work on this now :(

/unassign
