### ISSUE TITLE
OSM CLI emits validation error when using --osm-namespace option

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1937]
While trying to run the following command

```bash
./osm install --osm-namespace osm-aaa --mesh-name osm-aaa
```

Got this error:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "osm-aaa" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "osm-aaa": current value is "osm-system-aaa"
```
Version (`$ osm version`)
```
Version: dev; Commit: f5499fbc19f86bc15937f58f8f748174eeb4145d; Date: 2020-10-27-14:23
```

---

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by ksubrmnn** [comment]
My guess is that this issue arises when osm is installed with one namespace, the controller gets cleaned up but some resources are leaked, then those resources cause a conflict when installing with a new namespace.

It would be good if we could modify `osm mesh uninstall` to be able to clean up these resources even if there is no osm-controller present.

**Comment by snehachhabria** [comment]
Attempted to reproducer the issue based on the scenario explained above but was unable to. I verified with @draychev too and he is no longer seeing the issue as well.
