### ISSUE TITLE
Webhook/certificate generation split from XDS control plane

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1939]
Some discussions suggested we could separate the XDS control plane to the webhook and certificate generation for envoy onboarding. 

This would ease up and decouple the system into finer responsibilities, potentially simplifying the later scalability, possible sharding and fine tuning the individual components at scale.

This issue tracks potential conversation over this matter.

- New Functionality         [X]
- Envoy Control Plane        [X]
- Certificate Management  [X]
- Sidecar Injection           [X]

**Comment by draychev** [comment]
Could be positively impacted by #1974

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/2505
