### ISSUE TITLE
Create an e2e test for pod without service

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1946]
As a follow-up to https://github.com/openservicemesh/osm/pull/1932 - create an end-to-end test to ensure that a pod without a dedicated Kubernetes Service can cURL bookstore.

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [X]
- Project Release            [ ]

**Possible use cases**

**Comment by eduser25** [comment]
@nojnhuh had already fixed this, and we already have a test for it if not mistaken (_e2e_pod_client_server_test.go_)

**Comment by nojnhuh** [comment]
@eduser that test still creates a service on the client side. I hadn't made this change yet since I knew it was going to fail without the service. It would be like a 3 line change to get rid of it though.
