### ISSUE TITLE
Apex service of traffic split selecting a pod is programmed as a cluster by RDS

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#1979]
**Bug description**:

When the `spec.selector` of the apex service of a traffic split matches the labels of a pod, RDS configures the apex service as a cluster alongside the backends of the traffic split, leading to intermittent HTTP 503 errors when making requests to the apex service.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
Either the misconfiguration is fixed on the fly or an error or log message is surfaced pointing out the misconfiguration of the apex service or traffic split.

**Steps to reproduce the bug (as precisely as possible)**:

1. Run the demo with demo/run_demo.sh with default .env
1. `kubectl edit svc -n bookstore bookstore`
1. Change `spec.selector["app"]` to `bookstore-v1`
1. Save and exit
1. Check the bookbuyer pod's proxy config, look for the `bookstore/bookstore` cluster in the `RDS_Outbound` route config.

**How was OSM installed?**: Compiled from source via run_demo.sh

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: bf8c5a93596ff077ff6b20581030b0eb9f8594a0; Date: 2020-11-03-13:29`
- Kubernetes version (use `kubectl version`):

        Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
        Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (number of worker nodes in the cluster): 1 node Kind cluster
- Others:

**Comment by draychev** [comment]
Here is a script to help repro the bug:  https://gist.github.com/draychev/e1de72642abd8607ea4ae3002373640c#file-osm-demo-sh
Wait for the script to finish deploying all the resources.
Notice:
```
Identity: bookstore-v1
Status: 200 OK
Identity: bookstore-v1
Status: 200 OK
Identity: n/a
Status: 503 Service Unavailable
Identity: bookstore-v2
Status: 200 OK
```

**Comment by draychev** [comment]
I am working on a test to capture this scenario: https://github.com/openservicemesh/osm/pull/1982

**Comment by draychev** [comment]
This may get resolved w/ #2035

**Comment by michelleN** [comment]
I believe this has been addressed with #2274. @draychev - can you confirm?

**Comment by snehachhabria** [comment]
Reopening this issue cause of bug #2578, I will work on the correct implementation once the bug has been addressed

**Comment by snehachhabria** [comment]
OSM requires that the apex service of a traffic split doesn't have labels matching a pod we will not hit this scenario,  which will be address by documentation captured in issue #2532
