### ISSUE TITLE
Allow a way to not enforce client side routes to simplify gradual migration of applications into the mesh

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2012]
**Please describe the Improvement and/or Feature Request**

Support features to gradually onboard new applications into a mesh. These include:
- optional mTLS based authentication (https://github.com/openservicemesh/osm/issues/2097)
- support to route HTTP traffic based on ip:port/ip HOST header (https://github.com/openservicemesh/osm/issues/2097)
- Granular policy enforcement to be able to support communication between: 1. meshed to unmeshed pod, 2. unmeshed pod to meshed pod, 3. meshed pod to meshed pod

Note that this issue is a subset of https://github.com/openservicemesh/osm/issues/2172 which also lists some of these items.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [X]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

As our case, we are facing to migrating common microservice architech to mesh. Usually it's not good practice to migrate all service to mesh at one time, but part by part gradually.

In this case, we can't rely on client side routing if we want to provide canary feature. Such as A depends on B and B is in canary release stage, it is better to implete routing within ingress listener on B side. Bcoz A or other service consumers may not be migrated to mesh yet.

With ingress routing, will help system migrate to mesh architech smoothly.

If not explained clearly, will provider more info.

**Comment by shashankram** [comment]
@addozhang currently OSM programs both client side and server side routes. Client side routes are programmed for TrafficSplit scenarios which require the client to load balance traffic. Server side routes are programmed based on SMI policies as well.

Could you share more details on what is it that you think is not correct?

**Comment by addozhang** [comment]
@shashankram sorry for late reply.

Currently our system built with Spring cloud framework (Edgware) and running on Openshift (3.11, which kubernetes is 1.11). Service discovered is via Netflx Eureka and service accessing is via Feign which using pod ip and port directly.

We hope to migrate to mesh smoothly and implement Cancary release with power of envoy. Smooth requires we MUST upgrade microservice partially, even no one needs to do SDK upgrading. This results that there will be one case that client(service consumer) is still in old generation architech and server (service provider) is running in mesh architech. The client still access service with pod id and port (**no HOST in HTTP header, and `domains` won't work in `virtual_host` and `server_names` not work in `filter_chain_match`**).

With this requirement, we want to implete traffic split in server side. This means we need to:

- [√] enable egress in system which will open ORIGINAL DST filter to allow client which in mesh architech access others with pod ip and port directly.
* inbound listener support both TLS and non-TLS filter chain. I have already implement on my local, is it compliant to involved in osm as PR?
* RDS_Inbound provied one more `virtual_host` with wildcar `*` domain at end of list, then weighted and http route are implemented there. 

Hoping my explanation clear.

**Comment by shashankram** [comment]
@addozhang thanks for providing more details.

Would your problem where the HOST header contains IP:Port be addressed if we program IP:Port in the `virtual_host` domains?

We do not want to open inbound listener for non-TLS traffic for in-mesh traffic. We do support non-TLS only for ingress traffic via Kubernetes ingress resource. At the moment, in-mesh inbound filterchain should not allow non-TLS traffic.

RDS_Inbound virtual_host can be updated to use IP:Port instead of wildcard. We want to enforce HOST headers without wildcarding it.

**Comment by addozhang** [comment]
> Would your problem where the HOST header contains IP:Port be addressed if we program IP:Port in the virtual_host domains?

Currently we need to upgrade sdk in all microservices if we need HOST appear in HTTP header, it will be huge cost.

If not upgrade, client out traffic is sent by the `passthrough-outbound`, the `ORIGINAL_DST` filter. (this filter will handle the trffic like mysql .etc). It is configured as `protocol_selection: USE_DOWNSTREAM_PROTOCOL` in `passthrough-outbound` cluster. This means request will be sent as non-TLS one with original protocol (it's http in our case).

Then the  non-tls request reaches service side. In order to selet a desired listener fitler chain to handle it, like `inbound_prometheus_listener`.

> We do not want to open inbound listener for non-TLS traffic for in-mesh traffic. We do support non-TLS only for ingress traffic via Kubernetes ingress resource. At the moment, in-mesh inbound filterchain should not allow non-TLS traffic.

How about provide a switch to handle this? With swtich on, it accepts non-TLS traffic. This will help system to perform migration to mesh with low cost. Once all service migrated, the switch will be off.

> RDS_Inbound virtual_host can be updated to use IP:Port instead of wildcard. We want to enforce HOST headers without wildcarding it.

I think it will be ok with ip:port in virtual_host instead of wildcard, but not sure `domains` field can hold ip:port.

**Comment by shashankram** [comment]
> > Would your problem where the HOST header contains IP:Port be addressed if we program IP:Port in the virtual_host domains?
> 
> Currently we need to upgrade sdk in all microservices if we need HOST appear in HTTP header, it will be huge cost.
> 
> If not upgrade, client out traffic is sent by the `passthrough-outbound`, the `ORIGINAL_DST` filter. (this filter will handle the trffic like mysql .etc). It is configured as `protocol_selection: USE_DOWNSTREAM_PROTOCOL` in `passthrough-outbound` cluster. This means request will be sent as non-TLS one with original protocol (it's http in our case).
> 

`passthrough-outbound` is only meant for `egress` traffic, not traffic within the mesh. For traffic within the mesh, you either need to use permissive mode by setting `permissive_traffic_policy_mode=true` in the `osm-config` ConfigMap, or explicitly add SMI policies.


> Then the non-tls request reaches service side. In order to selet a desired listener fitler chain to handle it, like `inbound_prometheus_listener`.
> 
> > We do not want to open inbound listener for non-TLS traffic for in-mesh traffic. We do support non-TLS only for ingress traffic via Kubernetes ingress resource. At the moment, in-mesh inbound filterchain should not allow non-TLS traffic.
> 
> How about provide a switch to handle this? With swtich on, it accepts non-TLS traffic. This will help system to perform migration to mesh with low cost. Once all service migrated, the switch will be off.
> 

Here is a related issue: https://github.com/openservicemesh/osm/issues/1001 (disable mTLS using a flag). Will this address the TLS problem for you?

> > RDS_Inbound virtual_host can be updated to use IP:Port instead of wildcard. We want to enforce HOST headers without wildcarding it.
> 
> I think it will be ok with ip:port in virtual_host instead of wildcard, but not sure `domains` field can hold ip:port.

`ip:port` is allowed in `virtual_host.domains`, so this should work for you. I can create an issue for this.

Let me know your thoughts @addozhang.
