### ISSUE TITLE
add rate limiting functionality

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2018]
**Please describe the Improvement and/or Feature Request**
Design and implement rate limting.

- [x] Local rate limiting (Phase1)
    - [x] [Design doc](https://docs.google.com/document/d/1VTdte9v0JpX7odMtXlGsLlGwDlnXBAEZAf8PMJ_EyY4/edit?usp=sharing)
    - [x] Implementation
    - [x] Documentation
    
- [ ] Global rate limiting (Phase 2)
    - [x] [Design doc](https://docs.google.com/document/d/1fNfDvOV0p93DxP0vLGJmP4FTqd4ZgggI9PnA-sZWnWI/edit?usp=sharing)
    - [x] Implementation
    - [x] Documentation

**Possible use cases**
Users should be able to specify rate limiting policies for traffic.

**Comment by shashankram** [comment]
The core functionality is now complete.
