### ISSUE TITLE
Running reconciler unit test locally fails

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2020]
**Bug description**:
Running the reconciler unit test locally fails with the following error:
```
osm/pkg/reconciler/mutatingwebhook/suite_test.go:34

  Unexpected error:
      <*fmt.wrapError | 0xc00000e560>: {
          msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: {
              Op: "fork/exec",
              Path: "/usr/local/kubebuilder/bin/etcd",
              Err: 0x2,
          },
      }
      failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred

```

This is occurring after PR https://github.com/openservicemesh/osm/pull/1976 was merged.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]

**Comment by snehachhabria** [comment]
You will need to download the kubebuilder package locally for the test to run. The steps are as follows : 

os=$(go env GOOS)
arch=$(go env GOARCH)
curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/
sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
export PATH=$PATH:/usr/local/kubebuilder/bin

**Comment by shashankram** [comment]
@snehachhabria please automate this as a part of the test run, and move this outside of the unit tests suite to be under `tests/scenarios`. The reconciler tests are testing against an actual etcd server, so its better to add this as a part of our the additional suites under `tests/scenarios`.
