### ISSUE TITLE
Parameterize chart templates

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#2025]
**Please describe the Improvement and/or Feature Request**

Use templating and parameterization with values.yaml to make it easier to modify chart in the future. 
**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by michelleN** [comment]
Closing this as it is complete. @nshankar13 - please add details when you can. Thank you.

**Comment by nshankar13** [comment]
Parameterized fields to make it easier for values-override in templates. Ex: fluent-bit output, webhook-config-name-prefix, etc.
