### ISSUE TITLE
Enhanced debugging and troubleshooting abilities for the OSM control plane

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#2084]
**Please describe the Improvement and/or Feature Request**
Higher fidelity of logging on control plan components to enhance debugging scenarios

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [X]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Troubleshooting scenarios where OSM policies are not being applied or applied correctly.

**Comment by shashankram** [comment]
Pretty much the same as https://github.com/openservicemesh/osm/issues/2879. Closing this one in favor of https://github.com/openservicemesh/osm/issues/2879.
