### ISSUE TITLE
Program ip:port combinations as possible host headers in virtual_host.domains for HTTP routes

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2097]
**Please describe the Improvement and/or Feature Request**
Currently, OSM only programs service FQDNs (foo.bar.svc.cluster.local, foo.bar, etc.) as a part of `virtual_host.domains` in the route configuration. However, the HTTP request could have a host header corresponding to the IP:Port combination (ip:port, ip), in which case traffic will not be allowed because of `ip:port` not being programmed as acceptable domains. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Allows HTTP requests to a service when the host header is not based on the service's FQDNs, but rather `ip:port` combination.

**Comment by michelleN** [comment]
What would the SMI policies look like in this scenario?

**Comment by shashankram** [comment]
> What would the SMI policies look like in this scenario?

The SMI policies would not influence the IP:Port combinations that a client could use to access the destination. This issue was more applicable to ingress than SMI, where ingress controllers can route HTTP traffic directly to service endpoints rather than the service IP (clusterIP).  However, with the latest Ingress implementation, this capability is no longer necessary. 

It's also possible that clients use an IP address to access a destination, such as when they configure probes (not necessarily k8s probes) to check if the endpoint is alive, in which case they are going to have to use the endpoint IP instead of service FQDN to route it directly to a service's endpoints.
