### ISSUE TITLE
OSM consistency checker for mesh health and mesh configuration on the proxies.

### ISSUE THREAD

**Issue by fredstanley** [openservicemesh/osm#2099]
Wondering if there is anyway in OSM controller to check for consistency of the mesh. By consistency i mean is there a way to check if envoys on each containers are properly configured with the cluster informations of all other available services in the k8 cluster ? More in lines with a health check of the mesh configuration 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by SanyaKochhar** [comment]
I believe [osm-health](https://github.com/openservicemesh/osm-health) addresses this. @snehachhabria can I close this? Potentially related: https://github.com/openservicemesh/osm/issues/85
