### ISSUE TITLE
Make OSM control plane instances upgradeable

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#2100]
**Please describe the Improvement and/or Feature Request**

OSM should support upgrading the control plane to a newer version without a complete reinstallation.

**Sub-tasks** (will link to open issues as they are defined)
- [ ] Tests (#2125)
- [ ] CLI Command (#1139)
- [ ] Documentation (#2151)

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

- Upgrading to a newer version of OSM with minimal downtime

**Comment by michelleN** [comment]
Link to working document with upgrade strategy: https://docs.google.com/document/d/1WbZjV7wbar-taylAABn3NpHoHqVMXi_j13sXQgaXQRE/edit#heading=h.fxfa8dk0y5zy
