### ISSUE TITLE
Add runtime config/osm boot flags to configure ticker/resyncs

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#2103]
With on-event updates model, we do not rely on arbitrary resynchronization
mechanisms to detect and apply config chanes, so ticker was disabled and
kubernetes resyncs have been spaced in the order of minutes.

We would however want to be able to enable ticker on configmap updates, or
allow booting OSM with a certain k8s resync value, so both have to be intrumented
to be configurable.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Envoy Control Plane        [X]

Use case:
Allow enabling extra-guarantees or checks, to enforce propagating configuration at
time intervals.

**Comment by draychev** [comment]
@eduser25 I'm going to reopen this so we don't forget to add a OSM Controller argument for this so it is configurable.

**Comment by draychev** [comment]
Reopening this so we don't forget to cherry-pick into 0.8.1

**Comment by draychev** [comment]
This is done and merged in main and release-v0.8 with https://github.com/openservicemesh/osm/pull/2976
