### ISSUE TITLE
multicluster: Add support for Azure-Arc

### ISSUE THREAD

**Issue by ezYakaEagle442** [openservicemesh/osm#2111]
Add OSM support to Azure Arc for server + Azure Arc for K8S to manage the Service-Mesh in a Multi-Cluster providers scenario.

**Scope (please mark with X where applicable)**
- New Functionality          [ X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

see also #1892

**Comment by shashankram** [comment]
@ezYakaEagle442 could you describe in more detail specifically what else is required apart from multi cluster support for this?

/cc @ritazh

**Comment by ezYakaEagle442** [comment]
Service A runs in AKS
Service B runs in ARO
Service C runs in K3S
Service D runs in GKE

example of allowed services to services communication (any other call is denied) :
Service A ==> Service B
Service C ==> Service A  

The idea would be to have OSM deployed through Azure Arc for K8S to all clusters connected through Arc,, Arc/OSM aware of the list of services deployed in all clusters and filtering (allow/deny) the service calls acting as a gateway like :
https://linkerd.io/2/features/multicluster/
https://istio.io/latest/docs/concepts/traffic-management/#gateways

**Comment by draychev** [comment]
Hi @ezYakaEagle442, we have a [Multicluster Design Doc](https://docs.google.com/document/d/1O3XcG27uryBxCHX719qYUUzAo913GoFv3LOwdnfNudQ/edit) via #1892

Would love to get your feedback on [that design](https://docs.google.com/document/d/1O3XcG27uryBxCHX719qYUUzAo913GoFv3LOwdnfNudQ/edit).
Would be great to find out whether the proposed design fits your needs.

**Comment by ezYakaEagle442** [comment]
@draychev  it sounds good. 2 remarks : 

- about the Gateway scalability: we need to ensure it does not becomle a SPOF indeed
- this document ia only about OSM, not about intregration with Azure Arc. Could you please include this integration into the document scope ? As in such multi-cluster scenarios,  the IMPOORTANT ask from customers is the ability to  deploy OSM through Azure Arc for K8S **automatically  to all clusters connected through Arc**

**Comment by ezYakaEagle442** [comment]
I see OSM integration with Azure Arc is now in [public Preview](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-arc-enabled-open-service-mesh), so the ask from customers is "OSM auto-deployment" to all K8S clusters connected to Azure Arc.
