### ISSUE TITLE
Retest HTTPS ingress and update documentation

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2115]
**Please describe what should be documented
The documentation for HTTPS ingress needs to be updated to reflect changes made to the CN in service certificates.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/docs/content/docs/patterns/ingress.md

**Comment by shalier** [comment]
Update link as markdown has moved https://github.com/openservicemesh/osm/blob/main/docs/content/docs/patterns/ingress.md

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/2602
