### ISSUE TITLE
Implement OSM upgrade test scenarios

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#2125]
Part of #2100 

OSM should have e2e tests that perform control plane upgrades.

Tests will probably mostly look something like:
1. `osm install`
1. Install a sample workload within the mesh.
1. Verify the workload/control plane behavior.
1. Upgrade the OSM control plane.
1. Verify the workload/control plane behavior.

**Comment by ritazh** [comment]
Adding one more scenario to test:
- Does the upgrade guarantee use-provided values in osm-config stay the same?
