### ISSUE TITLE
Upgrading osm-controller from v0.5.0 to commit 388f8282 causes HTTP 503

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#2131]
**Bug description**: After installing OSM v0.5.0 and verifying two services can communicate when configured via SMI, upgrading the osm-controller to commit 388f8282 causes the client service to receive HTTP 503 errors with the following reason from Envoy: 

```
"response_code_details":"upstream_reset_before_response_started{​connection failure,TLS error: Secret is not supplied by SDS}​"
```

Came across this while looking into #2125.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**: After upgrading the controller image, the services can still communicate with each other.

**Steps to reproduce the bug (as precisely as possible)**:

- I've added an e2e test on my fork: e0963b0608d15e253e34e2b946447461b75c350c

- Run with `go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus=Upgrade -cleanupTest=false`, no CLI or local images needed.

**How was OSM installed?**: Helm CLI

**Anything else we need to know?**:
- The version I'm upgrading to is not necessarily the first commit that exhibits the issue, that's just the latest on `main` since I started testing.
- No errors reported in proxy sidecar or osm-controller logs that I found.
- This problem doesn't exist when the newer version is installed initially and restarted, only when the restart involves the vrsion change.

**Environment**:
- OSM version (use `osm version`): v0.5.0 -> 388f82824545ae4460570625b373364713866565
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): Single node, kind (`make kind-up`)
- Others:

**Comment by eduser25** [comment]
I believe the resyncs/ticker that were dropped last week (#2095) broke this.

I think the issue is around the fact that the k8s cache might synchronize _before_ pubsub and event handlers are registered, so dispatcher doesn't trigger updates for the existing envoys. If I'm correct, the solution has to register first the pubsub hooks and event handlers first, and then synchronize the caches, which will trigger all the update notifications for the relevant envoys.

https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L102
```
 A client added
// after `Run()` starts gets a startup batch of notifications of
// additions of the objects existing in the cache at the time that
// client was added
```

**Comment by draychev** [comment]
@eduser25 @nojnhuh I am curious if the `Secret is not supplied by SDS` error goes away at some point?  I'd expect to see this if everything else is set-up on an Envoy proxy, but OSM Controller has not had a chance to send the required certificates *yet*. Given that this is eventually consistent system - this would be possible. But if the error never goes away - (a) it may be an indication (as Edu pointed out) that SDS is never told to send certs OR (b) alternatively there may be an issue with the SDS/xDS state machine (version numbers etc)

**Comment by nojnhuh** [comment]
@draychev The test I was running made HTTP requests for a minute before timing out. I didn't check to see that the SDS error was the same throughout that minute. Do you expect the responses to start succeeding after a certain period of time or fail with a different error? What's a reasonable timeout to set to see if the SDS error will never go away?

**Comment by shashankram** [comment]
I see this issue manifest when the controller pod is restarted:
```
[2020-12-16 00:22:27.839][13][debug][http] [source/common/http/conn_manager_impl.cc:1520] [C166][S8227018607628324364] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: Secret is not supplied by SDS}
[2020-12-16 00:22:27.839][13][debug][http] [source/common/http/conn_manager_impl.cc:1777] [C166][S8227018607628324364] encoding headers via codec (end_stream=true):
':status', '503'
'content-length', '91'
'content-type', 'text/plain'
'date', 'Wed, 16 Dec 2020 00:22:27 GMT'
'server', 'envoy'
```

**Comment by shashankram** [comment]
> @draychev The test I was running made HTTP requests for a minute before timing out. I didn't check to see that the SDS error was the same throughout that minute. Do you expect the responses to start succeeding after a certain period of time or fail with a different error? What's a reasonable timeout to set to see if the SDS error will never go away?

Based on my testing, I don't see it being a transient error, it remains stuck at 503 indefinitely:

```> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req succeeded: 200
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
> (client/client -> server.server) HTTP Req failed 503 <nil>
...
...
```
