### ISSUE TITLE
cluster_not_found occurs when multi services existing of one application

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2134]
**Bug description**:

Described in traffic split [workflow](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md#workflow) in smi spec, there are two services form `foobar-v1` deployment: `foobar` and `foobar-v1`.

>   * Deployment named `foobar-v1`, with labels: `app: foobar` and `version: v1`.
>  * Service named `foobar`, with a selector of `app: foobar`.
>  * Service named `foobar-v1`, with selectors: `app:foobar` and `version: v1`.
>  * Clients use the FQDN of `foobar` to communicate.

Before create any TrafficSplit for `foobar` service, the root service will be not filtered out from service list, in logic of `catalog.GetServicesFromEnvoyCertificate`.

It will return two list, and in many invocations the logic will choose the index 0 one. But sometimes the one with 0 index are **not same**.

Such as in `RDS_Inbound` logic of `rds`, the one with 0 index is `foobar`, the local cluster name in route config is `foobar-local`.
And in logic of `cds`, the one with 0 index is `foobar-v1`, then the local cluster name is `foobar-v1-local`.

So, `cluster_not_found ` occurs.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

the local cluster name in RDS_Inbound should be same the one return by cds

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by addozhang** [comment]
Solution, if the multi services founded, create local clusters with all services. The redundant one won't effect anything.

**Comment by shashankram** [comment]
> Solution, if the multi services founded, create local clusters with all services. The redundant one won't effect anything.

@addozhang this will be fixed by @michelleN soon, where if multiple services are associated with a single proxy, multiple local cluster will be created.

**Comment by addozhang** [comment]
@shashankram  that's great, thanks.

**Comment by addozhang** [comment]
@michelleN Will the same logic include in lds? coz there are multi services existing and root service won't be excluded before split created. The client may access with root service as authority.

**Comment by michelleN** [comment]
depends on #2064

**Comment by michelleN** [comment]
related to #2610

**Comment by shashankram** [comment]
This issue has been resolved by PR #2619. If multiple services have the same label selectors matching a pod, osm-controller will correctly create multiple local clusters for each of them. 

In the inbound route configuration of the pod, there will be a `virtual_host` corresponding to each service associated with the pod, with the routes for those virtual hosts mapped to their corresponding local clusters `<service-name>-local`.

Changes from #2619 will be available in version v0.8.0.
