### ISSUE TITLE
Make osm component namespaces separate from Helm release namespace

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2141]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

By making the osm-controller namespace separate from the helm namespace, users can hardcode the namespace of osm components to make deployments more predictable.

**Comment by nojnhuh** [comment]
I'm not sure I understand the use case here. If a user knows the namespace of the helm release, then they also know the namespace of all the namespaced resources. How does it make deployments more predictable? To me it looks like this would only make it possible to store the release in a different namespace than the other resources. Is there a use case for that?

**Comment by ksubrmnn** [comment]
@nojnhuh users can use the osmNamespace field in the values file to optionally hardcode the namespace of the osm-controller while still using the helm cli to specify the helm release namespace.
