### ISSUE TITLE
Can we keep tracking the update of main branch and raise issue?

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2148]
Dear,

our team is working on the mesh migration for system, and are tracking the update in main branch like requirement what we raised before. 

During tracking, we found some bugs. Can we create issue for them?

**Comment by snehachhabria** [comment]
@addozhang yes please go ahead and create issues of type bugs

**Comment by addozhang** [comment]
@snehachhabria thanks

**Comment by shashankram** [comment]
@addozhang you can also join our Slack channel for general questions: https://github.com/openservicemesh/osm#community

**Comment by addozhang** [comment]
@shashankram joined.
