### ISSUE TITLE
original_dst specified in inbound listener, but no original destination cluster specified

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2149]
**Bug description**:

`original_dst` filter configured in inbound_listener, but there is not filter chain to config original destination cluster.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

There should be a filter chain with destination port match and configured with original destination cluster.

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

Build from latest main commit

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): Build from latest main commit
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
The `original_dst` listener filter configured on the inbound listener is only used for 1 purpose:
- to restore the original destination address upon redirection of traffic from iptables.

https://github.com/openservicemesh/osm/blob/main/pkg/envoy/lds/listener.go#L64-L69

Currently OSM does not require any other use of the orignal_dst listener filter in the inbound listener.
