### ISSUE TITLE
install readarray dependency being used in scripts/test-w-coverage.sh 

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2152]
There should be instructions or a make command to install the `readarray` utility being used in scripts/test-w-coverage.sh

**Comment by nojnhuh** [comment]
`readarray` is a bash builtin added in bash 4.0. On my Mac I have version 3.2 is preinstalled, but 5.0 is available on Homebrew. That script is simple enough that there is probably a reasonable way to refactor it to remove `readarray` entirely.
