### ISSUE TITLE
document process related to cutting a release candidate

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2167]
**Please describe what should be documented
document process related to cutting a release candidate

**Please suggest where in the repo the document should be located
docs/release_guide.md

**Comment by bridgetkromhout** [comment]
Thanks for the demo today in the community call, @nojnhuh! We discussed the signing of assets as seen on https://github.com/openservicemesh/osm/releases and talked about documenting the process to produce a "verified" release as seen in 0.6.0, instead of an unverified one as seen in 0.6.1.

![image](https://user-images.githubusercontent.com/2104453/104359562-6db0c280-54d5-11eb-8e3a-5b665b5dbdb6.png)

**Comment by nojnhuh** [comment]
@michelleN The mechanics of cutting a release are the same between RCs and regular releases aside from the tag name. For this issue, did you mean we should document that we should be cutting an RC before each minor release, test it for about a week, then cut the "real" release?

Do we have any docs that describe our current release cadence (i.e. monthly minor releases, patches as-needed, etc.)? RC-specific info may fit better there. If not, is the release guide the best place for that? Currently, the release guide is just the steps to cut a release, but doesn't mention things like when to cut a release, what the tag should be, or what code changes it should include. We could reorganize it to include that info, but I worry that including RC-specific info at that level may not make sense without that sort of context.

**Comment by nojnhuh** [comment]
@bridgetkromhout Could you open a separate issue to track signing the releases? I did a cursory look and didn't see one already.

**Comment by michelleN** [comment]
>The mechanics of cutting a release are the same between RCs and regular releases aside from the tag name. For this issue, did you mean we should document that we should be cutting an RC before each minor release, test it for about a week, then cut the "real" release?

Let's document that we should be cutting an RC, sending a notification email about the RC on the mailing list, testing for a week and then cutting the real release. 👍 

On documenting release cadence, I think we should add a section on releases to the README and continue using the release guide as the place to document steps to cut the release.
