### ISSUE TITLE
Annotation to enable metrics collection should be user-configurable

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2201]
To allow for different metrics collectors to work w/ OSM, we need to make the annotation enabling scraping to be configurable.

Annotation: https://github.com/openservicemesh/osm/blob/83a0320ce210b3bcce0898080b3b8d8db6ca3770/pkg/constants/constants.go#L148

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@draychev could you describe the use case a bit more with an example. I recollect discussions around making the annotation configurable in the past but it wasn't required back then.

**Comment by draychev** [comment]
> 
> 
> @draychev could you describe the use case a bit more with an example. I recollect discussions around making the annotation configurable in the past but it wasn't required back then.

Gathering some context on a tool I want to integrate with -- will update the Issue when I have more. (I assigned it to myself for the time being)

**Comment by draychev** [comment]
This is no longer needed.
