### ISSUE TITLE
When a namespace is annotated for metrics - annotate all existing pods with prometheus annotations

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2206]
When a namespace is enabled for metrics, only new pods will get the Prometheus annotations.

Example:
```sh
osm metrics enable --osm-namespace bookstore
```

Would annotate the `bookstore` namespace with `openservicemesh.io/metrics`. 

According to the code below - only new patches (now pods) will get the prometheus annotations.

https://github.com/openservicemesh/osm/blob/5e4d3404156e79c3f6d9386ad6211f9e5b6994a9/pkg/injector/patch.go#L87

This task is a request to annotate all existing pods with 
https://github.com/openservicemesh/osm/blob/5e4d3404156e79c3f6d9386ad6211f9e5b6994a9/pkg/injector/patch.go#L95-L97
when a namespace is annotated with `openservicemesh.io/metrics`

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@draychev that isn't true because metrics must be enabled via `osm cli`, which enables metrics for existing pods as well:
https://github.com/openservicemesh/osm/blob/dcfaf0678b787f95ebd922c650fdce321688dcdb/cmd/cli/metrics_enable.go#L103-L105

**Comment by draychev** [comment]
@shashankram thanks for pointing this out - this is done then!
