### ISSUE TITLE
Add e2e testing for validating webhook

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#2216]
**Please describe the Improvement and/or Feature Request**

The validating webhook should be tested in e2e, particularly testing for when the webhook fails

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ X]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by snehachhabria** [comment]
validating webhook is being deleted : https://github.com/openservicemesh/osm/pull/3383. This is no longer needed
