### ISSUE TITLE
multi exposed ports service resulting in lds error

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2237]
**Bug description**:

Two ports defined in service, and it contains one filter match which holding two same address_prefix.

Two same address_prefixs exists in one match with same prefix_len two.

```
error adding listener '0.0.0.0:15001': multiple filter chains with overlapping matching rules are defined
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

It should remove duplicated endpoint during constructing match of filter chain. (target in `inmesh.go`)

**Steps to reproduce the bug (as precisely as possible)**:

Service with multi ports.

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
Multiple ports per service is not yet supported and tested. Could you kindly open a feature request for this @addozhang. 
This will likely be more work than just the LDS change.

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/2239
