### ISSUE TITLE
injector: Generate init/init-iptables.sh dynamically from Go code and constants

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2243]
The init container executes the `init/init-iptables.sh` script which is a static bash script.  The bash script contains constants that are duplicated in Go code. A mismatch between these constants (port numbers) would cause breakage. These constants are currently synced manually. To prevent issues arising from inconsistencies between the bash and Go code - we should dynamically generate the `init/init-iptables.sh` file.

For example:
  - in bash Envoy admin port is hard-coded as 15000:  https://github.com/openservicemesh/osm/blob/release-v0.6/init/init-iptables.sh#L5
  - in Go we have the `EnvoyAdminPort ` constant: https://github.com/openservicemesh/osm/blob/release-v0.6/pkg/constants/constants.go#L13

We can delete `init-iptables.sh` from the repo and generate it on the fly from the already defined constants such as `EnvoyAdminPort`

---

### Sub-task

Skip irrelevant iptables commands when certain features are not configured for the given instance of OSM. For example a customer may decide to disable Admin port: https://github.com/openservicemesh/osm/blob/release-v0.6/init/init-iptables.sh#L5

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [x]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by ksubrmnn** [comment]
Whoever, takes this up, it would be great if they could also address https://github.com/openservicemesh/osm/issues/2106 when writing the docs for this PR

**Comment by shashankram** [comment]
Fixed by https://github.com/openservicemesh/osm/pull/2343
