### ISSUE TITLE
Move to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2271]
**Please describe the Improvement and/or Feature Request**

As of Kubernetes 1.16, CRDs have been promoted to GA. 
OSM currently uses `apiextensions.k8s.io/v1beta1`, which is deprecated in 1.19 and will be removed in 1.22: kubernetes/kubernetes#82022.
- Update the CRD yaml
- Update docs with supported Kubernetes version 1.16+, so we can default to `apiextensions.k8s.io/v1`
- Might also need to update kubernetes version used for e2e
- Need to document known issues/workaround if there are existing `apiextensions.k8s.io/v1beta1` CRDs for upgrade scenarios

Question: Should we also bump this for the SMI sdk? e.g. https://github.com/servicemeshinterface/smi-sdk-go/blob/master/crds/access.yaml

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by ksubrmnn** [comment]
A note: this work also is required for https://github.com/servicemeshinterface/smi-sdk-go/issues/37#issuecomment-577850688 which is necessary for proper CRD upgrades

**Comment by michelleN** [comment]
resolved via https://github.com/openservicemesh/osm/pull/2921

**Comment by michelleN** [comment]
What is left here is documenting the experience for upgrading from v1beta1 to v1

**Comment by draychev** [comment]
@michelleN it looks like we completed this with #2921
