### ISSUE TITLE
OSM CLI prompt to upgrade

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2294]
**Please describe the Improvement and/or Feature Request**

OSM CLI should have a way to detect its own version compared to the installed chart version and prompt user to upgrade the CLI.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
From my shell scripts - I use this to get the latest release for certain automation tasks:
```bash
curl --silent "https://api.github.com/repos/openservicemesh/osm/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
```
The Go version of this in the OSM CLI would be great.

The second step would be to compare the latest available with what's running in the Kubernetes cluster.
 - we could get that from the Deployment spec: `kubectl get deployment -n osm-system osm-controller -o json | jq '.spec.template.spec.containers[0].image'`
 - or the running OSM Controller itself (logs or debug endpoint)

**Comment by mudit-01** [comment]
I can work on it pls assign it to me

**Comment by mudit-01** [comment]
Hi pls assign it to me.

**Comment by mudit-01** [comment]
can be fixed by https://github.com/openservicemesh/osm/pull/5266

**Comment by mudit-01** [comment]
We can close this now fixed by https://github.com/openservicemesh/osm/pull/5266
