### ISSUE TITLE
Remove log lines where xDS request/response body is logged

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2309]
The xDS request/response could contain sensitive information. To lower the security risk we need to remove all log statements where xDS request or response is logged.

Examples:
 - https://github.com/openservicemesh/osm/blob/main/pkg/envoy/ads/response.go#L156-L160  (we should remove the conditional and keep [the 1st log line](https://github.com/openservicemesh/osm/blob/main/pkg/envoy/ads/response.go#L157), remove the rest)

**Comment by shashankram** [comment]
@draychev , for context, what is the downside to logging the request body? What kind of sensitive info are you concerned about to be present in the XDS request body?
