### ISSUE TITLE
Implement GetSerialNumber from the Certificater interface for the pkg/certificate/providers/tresor component 

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2312]
For GitHub Issue https://github.com/openservicemesh/osm/issues/2311 we need to use `GetSerialNumber()`, which is not implemented for `./pkg/certificate/providers/tresor`

Here is the current implementation of the function with a `panic`: https://github.com/openservicemesh/osm/blob/1e0ba082581eff0c11d72098dbec5ce3267263ce/pkg/certificate/providers/tresor/certificate.go#L43

The SerialNumber is generated here:  https://github.com/openservicemesh/osm/blob/7944a11844f2f01b97880e4369cc488cacc27e71/pkg/certificate/providers/tresor/certificate_manager.go#L29

We can add it to the Certificate struct here:  https://github.com/openservicemesh/osm/blob/7944a11844f2f01b97880e4369cc488cacc27e71/pkg/certificate/providers/tresor/certificate_manager.go#L80-L86

But before that we need to actually add the field to the `Certificate` struct: https://github.com/openservicemesh/osm/blob/1e0ba082581eff0c11d72098dbec5ce3267263ce/pkg/certificate/providers/tresor/types.go#L49-L62

I (@draychev) would vote for the `SerialNumber` field to be `string`.

**Comment by SanyaKochhar** [comment]
> I (@draychev) would vote for the `SerialNumber` field to be `string`.

@draychev serial number is currently generated as *Big.Int, do you mean we should convert it to string as it is generated or assigned as a field in cert or have getSerialNumber return it as a string?
