### ISSUE TITLE
injector: Allow for customizations of iptables config based on OSM Controller observed context

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2344]
With GitHub Issue https://github.com/openservicemesh/osm/issues/2243 we are going to make iptables config from a static bash script to dynamicly generated in Go.

This task is to take this a step further and provide a way for specific traffic to bypass Envoy proxy.

For instance certain kinds of payload may need to access local [node's metadata service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows). In these Kubernetes configurations, we need to configure OSM so that this kind of traffic is allowed / unaffected through Envoy.  This could be done via the OSM ConfigMap, command line arguments, CRD etc.

**Comment by draychev** [comment]
related issue:  https://github.com/openservicemesh/osm/issues/1670

**Comment by shashankram** [comment]
I'll look into this, should be straightforward.
