### ISSUE TITLE
Proposal to update pull request workflow

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2347]
**Please describe what should be documented
This issue is to discuss a proposal to change the way pull requests should be created are merged.

Per the new proposal, contributors are expected to do the following:
1. Fork the osm repo
2. Get your local branch up to date with upstream's `main` branch (`git pull --rebase upstream main` or `git fetch upstream && git rebase upstream/main`). Please *do not use `git pull`* as it does a merge that makes the commit history messy.
3. Push changes to fork and open a pull request against the `main` branch from fork
4. Get code reviewed
5. After review approvals, rebase to main branch as described in step 2 (`git pull --rebase upstream main` or `git fetch upstream && git rebase upstream/main`) and squash commits in the PR to a single commit that follows the commit message guidelines (signoff etc.)
6. Force push your changes (`git push -f`)
7. Once your PR is approved and commits are squashed, a maintainer will merge your change using the `merge pull request` option as a merge commit to main. Maintainers will ensure the PR has not changed/added functionality after step 6.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md

**Comment by michelleN** [comment]
Maybe we should ask folks to have their commits squashed and rebased before the review process? Then, we could just require folks to rebase if there is a notification of merge conflicts with main.

**Comment by michelleN** [comment]
Maybe we should also ask folks to squash commits before the review phase in step 2?

**Comment by shashankram** [comment]
> Maybe we should also ask folks to squash commits before the review phase in step 2?

I am not against that, that's the way I create my PRs. For authors, we can incorporate this as a recommendation. Is there a reason this must happen at pull request creation time?

**Comment by michelleN** [comment]
>I am not against that, that's the way I create my PRs. For authors, we can incorporate this as a recommendation. Is there a reason this must happen at pull request creation time?

👍  Just so there is less churn between review approval and PR merge.
