### ISSUE TITLE
update go version to 1.15.7

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2363]
https://groups.google.com/g/golang-announce/c/mperVMGa98w

This is a full explanation of the issue: https://blog.golang.org/path-security
Because we use exec.Command in the e2e test framework, we should upgrade to 1.15.7 to be safe.

**Comment by nojnhuh** [comment]
We have CI configured to use "1.15" without specifying a patch level. This recent CI run shows it using v1.15.7: https://github.com/openservicemesh/osm/runs/1751901491?check_suite_focus=true#step:6:11. Are there other places we specify a patch-level version of Go? I didn't find any with a quick look.

**Comment by michelleN** [comment]
oh that's great. We should add Go v1.15.7 as a prerequisite to this repo in the documentation as well.
