### ISSUE TITLE
Ensure these failures and important events are being logged by osm-controller

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2364]
Ensure the following events are being logged by osm-controller:

1. Certs issuance, expiry with any failures
2. SMI configuration CRUDs with any failures
3. Addition/removal of namespaces
4. Changes in ConfigMap

Some of these are already being logged but this list requires an audit and completion of any missing events.

**Comment by shashankram** [comment]
I believe scenarios described in the issue are logged.
