### ISSUE TITLE
Need a way to enable metrics on all namespaces

### ISSUE THREAD

**Issue by rashmichandrashekar** [openservicemesh/osm#2385]
**Please describe the Improvement and/or Feature Request**
osmcli provides a way to enable metrics from a namespace or a list of namespaces today. It would be helpful if there is a way to enable metrics across all namespaces probably with a flag.

**Scope (please mark with X where applicable)**
- New Functionality          [ X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X ]
- Metrics                    [X ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Would provide a way to enable metrics across all namespaces, instead of individually listing out namespaces.

**Comment by eduser25** [comment]
Thanks Rashmi, I think this is all not so unreasonable and could ease simple deployments that expect simple mesh.
We'll discuss what/how and come back.

**Comment by shashankram** [comment]
@trstringer we could very well do something similar to what you did in the bug-report tool to wildcard all meshed namespaces.
