### ISSUE TITLE
helm upgrade overrides manual edits in osm-config

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2386]
`helm upgrade` will override user edits 
This is an expected behavior of `helm upgrade`. What are some alternatives to address this behavior?

**Comment by ksubrmnn** [comment]
Helm upgrade will override user edits to the config map.

Helm upgrade doesn't work well with --reuse-values since it'll reuse the old imageTag and the controller won't be upgraded.

**Comment by nojnhuh** [comment]
In our CLI, we could use `--reuse-values` and still override the new image tag by default so the images get updated.

`--reuse-values` also doesn't take the new chart's values.yaml into account at all, so if a required entry in values.yaml has been added, `helm upgrade --reuse-values` will error saying the required value is missing. It doesn't seem like Helm has a way to use (in increasing order of precedence):

- The new chart's default values
- The user-provided values for the old release
- The user-provided values for the new release

We could certainly add something like that to our own CLI, but it would be nice if Helm could do that by itself.

**Comment by draychev** [comment]
It seems to me that Helm owning and overwriting the `osm-config` ConfigMap is causing an array of issues. I see this coupling between Helm and the ConfigMap affects the design choices we make for OSM CLI, UX for toggling options, and of course it permeates through demos and docs for the project.

One [such example is](https://github.com/openservicemesh/osm/blob/6d44d0f8a82f47e211ed07db8f5803a1788b6d07/docs/content/docs/tasks_usage/traffic_management/egress.md#enabling-egress) `osm mesh upgrade --enable-egress=false`.

A solution would be to remove the `osm-config` ConfigMap from Helm's purview. Helm won't create the ConfigMap, Helm won't overwrite the ConfigMap. OSM Controller can function without a ConfigMap. With this setup ConfigMap can be changed via OSM CLI and kubectl. The config map itself is the source of truth regardless of who modifies it. On upgrade it remains the same. 

Question perhaps is - what happens on `helm delete` - how do we clean up all OSM artifacts? Who's responsible for the deletion of the ConfigMap. A simple way to perform a total OSM cleanup would be:
```bash
kubectl delete all -A --selector app=osm-controller
```
... as long as everything is labelled (https://github.com/openservicemesh/osm/issues/2925).

I propose we move ownership of the `osm-config` ConfigMap from Helm to OSM Controller. OSM Controller's responsibilities will be to a) ensuring `osm-config` exists, b) is always labeled with `app=osm-controller` (or whatever the common label is #2925) and c) create `osm-config` and fill with the current default values. The only reason for the ConfigMap to exist post-install is to add clarity on what current options are and where these can be changed (empathy). Operators don't have to know how to create `osm-config` when they need to toggle an option. OSM Controller has default values for all Configmap values - these can be populate in the newly created `osm-config`. If we get to this point we can change the semantic meaning of `osm install --enable-permissive-traffic-policy` to mean - use "permissive_traffic=true" as a default ConfigMap value. At that point I'd remove `osm upgrade --enable-permissive`, which narrows the purpose of `osm upgrade` to be exclusively upgrading from 0.5 to 0.8 (for example).

**Comment by ritazh** [comment]
> how do we clean up all OSM artifacts? Who's responsible for the deletion of the ConfigMap

We can consider setting this configmap object's `ownerReference` to the osm controller deployment object. BUT the issue there is a new install will wipe user configurations. 

Another idea is to create a new CRD for osm configs and user configurations will be provided via a custom resource of this new CRD type. OSM will manage the lifecycle of osm resources, but not the user-created custom resource. Another benefit is watch/list of this CRD type will have smaller impact on the api server than the `ConfigMap` kind.

**Comment by ritazh** [comment]
Same idea was suggested in https://github.com/openservicemesh/osm/issues/2738

**Comment by draychev** [comment]
Closing this GitHub issue since we are a) converting the ConfigMap to a CRD (##3039) and b) tracking upgradability in #3019
