### ISSUE TITLE
BYO Grafana instance - Steps are incomplete

### ISSUE THREAD

**Issue by mayurigupta13** [openservicemesh/osm#2390]
I used an existing Prometheus and Grafana instance. I'm able to get the Prometheus working. It is scraping the metrics after I amended the configmap as documented. I also imported the dashboards into Grafana using web json load. However, Grafana dashboards are not showing any data. It throws an error on the UI saying 'Error updating options: Bad Gateway'.

Document: https://github.com/openservicemesh/osm/blob/release-v0.6/docs/patterns/observability/metrics.md

**Comment by shashankram** [comment]
@eduser25, any pointers?

**Comment by eduser25** [comment]
> It throws an error on the UI saying 'Error updating options: Bad Gateway'.

You have to add prometheus as data source in grafana.
https://grafana.com/docs/grafana/latest/datasources/add-a-data-source/

This is a pretty standard procedure for grafana.

**Comment by eduser25** [comment]
based on offline comms, I think this is resolved (@mayurigupta13 reopen if otherwise).
