### ISSUE TITLE
Create soak test environment for project

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2392]
Run all e2e tests repeatedly on long living cluster

**Comment by allenlsy** [comment]
As we have moved forward, we now have two categories for our e2e tests. In our terminology:

1. Traditional e2e tests: they are placed in OSM repo, executed with `go test` command.
2. Soak test cases: long running test (can be more than 1 day), in order for us to watch resource consumption, stability and robustness etc.

For the first category, if we want to have a separate cluster for these test, I suggest start a new tab on https://k8s-testgrid.appspot.com/. 

For the second category, we are building a platform to schedule this type of tests.

cc. @trstringer
