### ISSUE TITLE
Code clean up for routes v2

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#2397]
**Please describe the Improvement and/or Feature Request**
This issue is to track all the code that needed to be removed/cleaned up when we migrate to routes v2

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by michelleN** [comment]
We'll need to update the design docs as part of this work as well.
