### ISSUE TITLE
Add proxy/CN to metrics with config switch

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#2408]
We are removing the CN/proxy/pod labels from the control plane metrics as they cause heavy memory use
(and way heavier when queried) on Prometheus.

For 0.8, we should add a metric configuration such that smaller clusters that do not expect to have problems with
the memory use in this situation, can still make use of specific labels to classify information down to pod/CN/proxy
level.

- Metrics                    [X]
- Scalability/Perf        [X]

**Comment by shashankram** [comment]
@eduser25 Are we planning to add a switch for the namespace label as well?

**Comment by eduser25** [comment]
I will close this for the time being. It's too expensive even at realistic low numbers to implement, as prometheus mem consumption explodes due to the large number of unique labels.
