### ISSUE TITLE
[Question] Are/will OSM containers be located on MCR?

### ISSUE THREAD

**Issue by ckittel** [openservicemesh/osm#2410]
Today the various OSM container images are available via Docker Hub (ref: <https://hub.docker.com/r/openservicemesh/>). I'm curious if they are also available yet via MCR. If they are, can you provide the reference to it?  If not, do you expect them to be mirrored/hosted there as well at some point in the near future?

Obviously, consumers should be importing into/sourcing from their own auth'd registry. The reason I ask is that I've now dealt with AKS customers that restrict their images to MCR and their own private ACR instances exclusively. If they are taking a dependency on a public container registry (tsk tsk), the request is that MCR is that source.  This would likely be akin to other similar addons (or near add-ons) for AKS -- such as upstream CSI Secret Store Drivers (and also the azure key vault provider).

**Comment by michelleN** [comment]
hey @ckittel - yes great question. We do have osm images on MCR. See below:

- [mcr.microsoft.com/oss/openservicemesh](mcr.microsoft.com/oss/openservicemesh)
- [mcr.microsoft.com/oss/fluent](mcr.microsoft.com/oss/fluent)

**Comment by ckittel** [comment]
Perfect, thank you.

**Comment by snehachhabria** [comment]
@michelleN has shared the image with @ckittel, closing the issue
