### ISSUE TITLE
Traffic split doesn't work after deploying the example

### ISSUE THREAD

**Issue by sozercan** [openservicemesh/osm#2421]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [x]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:
- Deploy OSM on a cluster
- When trying to update bookstore example to split traffic to v2 only, it doesn't split any traffic after yaml is applied (v2 counter is never incremented)
https://github.com/openservicemesh/osm/blob/release-v0.6/docs/example/README.md#update-traffic-split
- After manually editing or re-applying the manifest, it starts working
- Even if split is set to 100/0 split, both v1 and v2 gets traffic

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by ritazh** [comment]
I was able to repro this issue using v0.6.1.
After building from source using 49bbd47 from main, I was not able to repro it anymore.

**Comment by ritazh** [comment]
Per @snehachhabria this was fixed by https://github.com/openservicemesh/osm/pull/2320
