### ISSUE TITLE
Add unit test for services with weight 0 in traffic split

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2424]
**Please describe the Improvement and/or Feature Request**

When trafficSplit resource has a weight of 0 is deployed, the test should validate the correct XDS config is generated.
Ref issue: https://github.com/openservicemesh/osm/issues/2421

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
Instead of an e2e, please add this is a part of the unit/scenario test suite. We only need to verify the correct XDS config gets generated, so this doesn't need an e2e test.
