### ISSUE TITLE
run-osm-demo.sh: make install and uninstall of control plane configurable via .env 

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2430]
**Bug description**:
Currently /demo/run-osm-demo.sh removes the osm installation at the end. It should only add/remove demo resources, not osm resources.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
`run-demo.sh` is meant to spin up the automated demo and cleanup all demo created resources from previous runs before starting the new run. It does not clean up the OSM installation at the end, but previously deployed installations at the beginning.

This was intentional so that users don't have to clean up previous run every time manually. 

@ritazh could you clarify the issue further.

**Comment by ritazh** [comment]
This is the issue:
https://github.com/openservicemesh/osm/blob/main/demo/run-osm-demo.sh#L55

**Comment by shashankram** [comment]
> This is the issue:
> https://github.com/openservicemesh/osm/blob/main/demo/run-osm-demo.sh#L55

That's not a bug, but rather intentional so that stale testbeds are cleaned up before the demo creates the new demo environment. If this is not desirable for some reason, we can provide a config option to skip cleanup.

**Comment by ritazh** [comment]
I agree cleaning up demo resources is the intent, but specifically this is not what I would expect from this script:
`bin/osm mesh uninstall -f --mesh-name "$MESH_NAME" --osm-namespace "$K8S_NAMESPACE"`

**Comment by shashankram** [comment]
@ritazh's proposal:
- Rename file to reflect control plane is being installed
- Break up the script into: 1. control plane install, 2. demo set up, 3. control plane uninstall 

My proposal:
- Provide an option in .env file to optionally not install the control plane
- Provide an option in .env file to optionally cleanup the control plane

Note that the automated demo is being used in the CI and to set up a testbed in local evironments.
