### ISSUE TITLE
Guidance for adding tests

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2440]
**Please describe the Improvement and/or Feature Request**

Test framework should be revisited to have clear guidance around when we need a unit test vs e2e and where to add a new test vs append to an existing one.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by mudit-01** [comment]
hi @ritazh
This doc https://github.com/openservicemesh/osm/tree/main/docs/development_guide#testing-your-changes can be helpful

**Comment by shashankram** [comment]
> hi @ritazh This doc https://github.com/openservicemesh/osm/tree/main/docs/development_guide#testing-your-changes can be helpful

Thanks @mudit-01 for sharing this info!
