### ISSUE TITLE
Make it clear that CLI uses osm-system as default namespace for various commands

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2455]
**Please describe the Improvement and/or Feature Request**

The CLI should clearly indicate to users when it is using osm-system as the default namespace
**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Users may not be aware that commands such as uninstall and policy use osm-system as the default namespace.

**Comment by ritazh** [comment]
Adding an example:

```sh
osm policy check-pods bookbuyer/bookbuyer-8465f7dfc-9nctv bookstore/bookstore-v1-6cfc68bdd4-jxms8

Error: Error checking if permissive mode is enabled
```
The returned error is misleading. 

For anyone who might hit this issue. 
The fix was to provide the namespace the mesh is installed in via `--osm-namespace`

**Comment by draychev** [comment]
@johnsonshi As you are working on this - please build on top of the PR @ksubrmnn already created here:  https://github.com/openservicemesh/osm/issues/2455

**Comment by johnsonshi** [comment]
Reference PR: https://github.com/openservicemesh/osm/pull/2838
