### ISSUE TITLE
osm CLI should check if mesh exists before adding namespace

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2494]
**Please describe the Improvement and/or Feature Request**

`osm namespace add` should check if the mesh exists before adding the namespace. Otherwise the user may be mislead into thinking that the namespace is part of a mesh despite forgetting to run the install command.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by johnsonshi** [comment]
Indeed this is a bug. Here's a k8s cluster without any OSM control planes/OSM meshes. The `osm namespace add` command succeeds even though it shouldn't.

![image](https://user-images.githubusercontent.com/13926417/116337358-d5da9a00-a78e-11eb-9812-c26fa3f229ec.png)
