### ISSUE TITLE
Link in development guide is not working

### ISSUE THREAD

**Issue by Vyom-Yadav** [openservicemesh/osm#2502]
https://github.com/openservicemesh/osm#development-guide
https://github.com/openservicemesh/osm/blob/main/docs/development_guide.md // this link is not working.
![image](https://user-images.githubusercontent.com/73882557/107488019-cfd01680-6bac-11eb-87ae-c1df4fd9aa40.png)

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/2522
