### ISSUE TITLE
Document the requirement of apex service not having any label selectors matching a pod as an OSM requirement

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2532]
+ document this

Gets around bug #1979 temporarily as we move forward to fix this

**Comment by snehachhabria** [comment]
The PR #2556 removes the label selector, we just need to document this to caution users

**Comment by michelleN** [comment]
@snehachhabria @shashankram - This issue I believe becomes obsolete since we now have support for multiple pods per service if I'm not mistaken.

**Comment by michelleN** [comment]
Running a manual test now to confirm.

**Comment by michelleN** [comment]
Closing as this is not really necessary and #2654 will take care of all the updates to the manual demo.
