### ISSUE TITLE
Traffic split does not work with routes-v2, no virtual_host for apex service in the inbound route at destination

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2545]
**Bug description**:
Traffic split does not work with routesV2 when run with the default demo `./demo/run-osm-demo.sh --enable-routes-v2-experimental=true`.

There needs to be a virtual_host corresponding to the apex service in the inbound route configuration at the destination service, but this is not being programmed as expected.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
Traffic split should work with routesV2.

**Steps to reproduce the bug (as precisely as possible)**:
1. Apply the following diff for spit policy to be processed correctly
```
--- a/demo/deploy-traffic-split.sh
+++ b/demo/deploy-traffic-split.sh
@@ -12,7 +12,7 @@ metadata:
   name: bookstore-split
   namespace: "$BOOKSTORE_NAMESPACE"
 spec:
-  service: "bookstore.$BOOKSTORE_NAMESPACE"
+  service: bookstore
   backends:
 
   - service: bookstore-v1
```

2. Run the demo:
./demo/run-osm-demo.sh --enable-routes-v2-experimental=true`

**Environment**:
- OSM version (use `osm version`):
`Version: dev; Commit: 1323707da19e7b8590dd06aaf91832c01a4ebb4d; Date: 2021-02-17-10:59`

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (number of worker nodes in the cluster): 1 node

**Comment by snehachhabria** [comment]
Reopening this issue as the previous implementation is not fully correct given this bug #2578
