### ISSUE TITLE
Docs site does not show latest release

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm#2549]
**Please describe what should be documented
When clicking on the Releases link at https://docs.openservicemesh.io/ , only v0.6.1 shows up. Clicking on v0.6.1 does not seem to navigate to a different version of the docs

**Please suggest where in the repo the document should be located

**Comment by flynnduism** [comment]
The release version shown on the Docs site _should_  state the current one, `0.7.0`.

The version shown is configured [here](https://github.com/openservicemesh/osm/blob/main/docs/config.toml#L77) - as per documentation for [Versioning the Docs Site](https://github.com/openservicemesh/osm/tree/main/docs#versioning-the-docs-site). I shall fix this now.

---

This step has been added to the project [Release Guide](https://docs.openservicemesh.io/docs/release_guide/), so when the next release is cut this will be addressed in the process going forward.
