### ISSUE TITLE
Fix Certificate creation and histogram for OSM 

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#2606]
Due to the multiple certificate providers and varying implementations, implementing a wrapper around to catch (generate) when a specific certificate is generated might require changes on each provider to have the logic properly added, as some of them might have caching mechanisms around the `issue()` call, hence not really generating a certificate at a given time.

- Metrics                    [x]
- Certificate Management     [x]

**Comment by shashankram** [comment]
We have a reasonably simple approach to cert creation and no immediate need to alter metrics. Will re-open when this becomes a need.
