### ISSUE TITLE
Update manual demo documentation to reflect routesV2 behavior

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2654]
**Please describe what should be documented
There are some behavior changes with routesV2 which means the existing manual demo documentation must be updated.

Following need to be updated:
- Due to existing routesV2 implementation, `spec.service` in a traffic split must be the service name without its namespace and not the FQDN. This behavior will be updated later on in routesV2 to accept an FQDN for a service.
- Since traffic split policy is no longer required to allow access to a service, document access policies without dependency on traffic split policy
- Provide clear guidance on how the root and leaf services and pods need to be deployed before traffic splitting and for traffic splitting to work.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/docs/content/docs/install/manual_demo/_index.md

**Comment by michelleN** [comment]
>Due to existing routesV2 implementation, spec.service in a traffic split must be the service name without its namespace and not the FQDN. This behavior will be updated later on in routesV2 to accept an FQDN for a service.

just an update: #2794 removes the constraint described in the first bullet.
