### ISSUE TITLE
Intermittent e2e failures

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#2661]
**Bug description**: E2E tests arbitrarily fail in the CI for this repo as well as downstream in osm-azure. For instance, on one CI run, all the e2es could be passing. But if we rerun the CI on the exact same setup, leaving osm chart untouched, one of the e2es might fail. This usually happens for the e2e_controller_restart, e2e_tcp_client_server, e2e_tcp_egress, and e2e_grpc_client_server_test, but is not limited to these. Moreover, the e2e that fails is usually the first one in the suite to run, so this is likely due to a timing issue. Note, using `kubectl wait` until the osm-controller pod is ready before running the tests doesn't prevent the e2es from failing intermittently. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [X]

**Expected behavior**:

E2E tests should pass and fail consistently - if all the e2es pass for one run on a specific osm-setup, then they should always pass for that particular setup. If this is a timing issue, then success/failure should not be dependent on timing of when osm is installed on the cluster.

**Steps to reproduce the bug (as precisely as possible)**: Run the e2e test suite, preferably with the `NoInstall` option on a cluster that already has osm installed. Try to run the tests as soon as the osm-controller pod shows all containers as ready. 
 
`go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -installType=NoInstall`

**How was OSM installed?**:

**Anything else we need to know?**:

It is possible to reproduce this locally by running the e2es on a cluster with osm already installed with the no-install option. However, if a test fails at first, it will eventually succeed it if is run again after 2-3 minutes or so. The logs from osm-controller pod, and other pods/containers used during the test, did not provide any specific info as to why the test was failing. Moreover, the error-level logs gathered by fluent-bit from the osm-controller were identical for setups that were passing the tests and setups that were failing the tests. 

Here is an example of an arbitrary e2e failure from the osm-azure repo: 

https://dev.azure.com/AzureContainerUpstream/OpenServiceMesh/_build/results?buildId=18045&view=logs&j=9de9e2b7-8af7-5276-a88f-b4157127a375&t=6e4190ee-fa8b-5d21-648f-82f5576fef22

https://dev.azure.com/AzureContainerUpstream/OpenServiceMesh/_build/results?buildId=18048&view=logs&j=9de9e2b7-8af7-5276-a88f-b4157127a375&t=6e4190ee-fa8b-5d21-648f-82f5576fef22

Between these two runs, the osm-arc and osm charts remained unchanged, and the same setup of an AKS arc-enabled cluster was used - yet in one case, all the e2es are passing, and in another, one of them fails. 

**Environment**:
- OSM version (use `osm version`): v0.7.0 
- Kubernetes version (use `kubectl version`): 1.18.6
- Size of cluster (number of worker nodes in the cluster):
- Others: Running e2es from branch v0.7.0.

**Comment by eduser25** [comment]
We did some analysis over the logs and behavior of the issue.
It seems related to DNS not responding at all for any requests that happen in the client/server applications. They can't resolve each other, and what's more, envoys are unable to resolve the `osm-controller` cluster IP either.

This has been confirmed by both envoy logging and manual `nslookup` intervention during the blackout time.

The first logs of envoy start around `51:07`. `osm-controller` cluster IP confirmed `10.0.239.106`.
```
[2021-03-04 19:51:07.976][1][info][main] [source/server/server.cc:327]
```
For the next rougly 2 minutes (consider the test fails traffic at 90s), envoy tries to resolve `osm-controller.arc-osm-system.svc.cluster.local`. (Notice `failure`) 
```
[2021-03-04 19:51:07.997][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:109] async DNS resolution complete for osm-controller.arc-osm-system.svc.cluster.local
[2021-03-04 19:51:07.997][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:161] DNS refresh rate reset for osm-controller.arc-osm-system.svc.cluster.local, (failure) refresh rate 5000 ms
[2021-03-04 19:51:12.998][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:101] starting async DNS resolution for osm-controller.arc-osm-system.svc.cluster.local
``` 
At around `52:43` there's the first success resolution. First Connection to osm-controller happens around `52:50`
```
[2021-03-04 19:52:43.570][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:109] async DNS resolution complete for osm-controller.arc-osm-system.svc.cluster.local
[2021-03-04 19:52:43.570][1][debug][upstream] [source/common/upstream/upstream_impl.cc:278] transport socket match, socket default selected for host with address 10.0.239.106:15128
[2021-03-04 19:52:43.570][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:155] DNS refresh rate reset for osm-controller.arc-osm-system.svc.cluster.local, refresh rate 5000 ms
[2021-03-04 19:52:48.567][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:101] starting async DNS resolution for osm-controller.arc-osm-system.svc.cluster.local
...
[2021-03-04 19:52:50.925][1][debug][connection] [source/common/network/connection_impl.cc:860] [C1] connecting to 10.0.239.106:15128
```

We confirmed through nslookup `server.server`, `server.server.svc.cluster.local`, `osm-controller.arc-osm-system`, nor `osm-controller.arc-osm-system.svc.cluster.local` are resolvable during this time. Verified `resolv.conf`, appeared to be fine (with correct domains and valid dns server addr).

CoreDNS shows some errors quite close to the time where resolutions start to happen. Additionally, the errors look awfully related to the 2 services, 2 endpoints and 2 namespaces being created for the test (client and server), but further away in time. Suspicious but inconclusive:
```
W0304 19:52:35.679543       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
W0304 19:52:35.679543       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
W0304 19:52:35.679546       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
W0304 19:52:35.679546       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
W0304 19:52:35.679567       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
W0304 19:52:35.679567       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 10.244.0.3:47248->52.149.173.30:443: read: connection timed out") has prevented the request from succeeding
```

Timeline:
```
[51:07] Envoy: first log emitted
... <dns blackout, envoy just keeps async retrying every 5000milisec>
[52:35] CoreDNS: errors (timeouts against k8s?)
[52:38] Envoy: still fails DNS
[52:43] Envoy: osm-controller resulution succeeds
```

**Comment by draychev** [comment]
@eduser25 @nshankar13 Thanks for the thorough root-cause analysis.  It sounds like we are getting closer.
It would be interesting to understand why CoreDNS is not doing what it is supposed to.
> CoreDNS shows some errors
I wonder if these errors have some hints.

My intuition would have been:
 - we may be [launching the test](https://github.com/openservicemesh/osm/blob/release-v0.7/tests/e2e/e2e_tcp_client_server_test.go#L122) too soon after the [services are created](https://github.com/openservicemesh/osm/blob/release-v0.7/tests/e2e/e2e_tcp_client_server_test.go#L71) - not allowing enough time for CoreDNS to create these records; On the other hand this test does wait for [90 seconds](https://github.com/openservicemesh/osm/blob/release-v0.7/tests/e2e/e2e_tcp_client_server_test.go#L138) - this seems like should be enough.
 - perhaps the root cause is a matter of timing, which it tokes too long to create the DNS records because the test cluster is under-provisioned
 - @nshankar13 and I did also notice client's Envoy was not provisioned during one of these failures; this makes sense if Envoy could not resolve OSM Controller's FQDN - this points back to timing
 
Thank you @nshankar13 and @eduser25 for looking into this!

**Comment by eduser25** [comment]
> perhaps is a matter of timing

I would almost certainly rule out this one. The test is flaky, when works there are no delays, things work instantly. Now, when it fails, it fails for an astounding +90s. That much delta sounds too much for it to be timing.. Let's see however if I'm proven wrong though.

**Comment by shashankram** [comment]
> > perhaps is a matter of timing
> 
> The test is flaky

@eduser25 which set of tests are flaking? Is this one within the same set of tests each time?

**Comment by nshankar13** [comment]
@shashankram this was just on the tcp_client_server test, but these types of errors with arbitrary failed requests are common in some of the aforementioned ones: e2e_tcp_client_server, e2e_tcp_egress, and e2e_grpc_client_server_test. and e2e_trafficsplit_same_sa_test.

**Comment by shashankram** [comment]
> @shashankram this was just on the tcp_client_server test, but these types of errors with arbitrary failed requests are common in some of the aforementioned ones: e2e_tcp_client_server, e2e_tcp_egress, and e2e_grpc_client_server_test. and e2e_trafficsplit_same_sa_test.

Thanks for sharing. So it seems to me that tests fail regardless of the traffic type - TCP, HTTP, gRPC.

**Comment by nshankar13** [comment]
@eduser25 @shashankram I just checked the logs from the coredns pod on an instance where the test passes, and I was not seeing the coredns error message that Edu linked above.
