### ISSUE TITLE
Output logs to debug e2e failures in the CI

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#2665]
**Please describe the Improvement and/or Feature Request**

The CI system should output more descriptive error messages and logs if a test fails. For instance, in the e2e_egress_test, the test should also give some additional information, such as dumping all the logs from the client, server, and osm-controller pods/containers for the past 5-10 mins (since the test was run), as opposed to just outputting that the test failed. This will involve enhancing the current testing and log collection framework. 

One potential option is to record the timestamp of when the test started, and use `kubectl logs --since-time` to collect logs from the specific containers and pods used in that test, as well as from the osm-controller. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [X]
- Debugging                  [X]
- Tests                      [X]
- CI System                  [X]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
The e2e framework supports log collection on failure:
https://github.com/openservicemesh/osm/blob/6d6db5671ebd1c55eb7b0e4fb24d44c5958c320f/tests/framework/common.go#L1307-L1313
