### ISSUE TITLE
Support TCP traffic splitting

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2666]
**Please describe the Improvement and/or Feature Request**
OSM does not have the capability to split TCP traffic.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [X]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Traffic splitting for TCP based applications.

**Comment by michelleN** [comment]
Would this be blocked on SMI since the latest SMI traffic split API doesn't support TCP Route at the moment?

**Comment by shashankram** [comment]
> Would this be blocked on SMI since the latest SMI traffic split API doesn't support TCP Route at the moment?

The latest traffic split v1alpha4 spec can be used to perform TCP traffic splitting without route matching for the split configuration. This can be used for the canary use case. For A/B testing we will need to extend the traffic split API to allow route matching on ports. A/B testing is going to be uncommon for TCP routes, but canary based splitting is going to be a lot more common and something easy to support.
