### ISSUE TITLE
pkg/envoy: PodMetadata's ServiceAccount field of type string should be of type service.K8sServiceAccount instead

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2681]
The struct `PodMetadata` has a field `ServiceAccount` which is of type `string`: https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/proxy.go#L48

A better type for this is `K8sServiceAccount`: https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/service/types.go#L22-L25

**Comment by sheetalsingala** [comment]
Hi, 
How would this change affect - https://github.com/openservicemesh/osm/blob/739b490509ac3551ca9716558bead68d42222852/pkg/envoy/xdsutil.go#L313 ?

**Comment by shashankram** [comment]
> Hi,
> How would this change affect -
> 
> https://github.com/openservicemesh/osm/blob/739b490509ac3551ca9716558bead68d42222852/pkg/envoy/xdsutil.go#L313
> 
> ?

This will look something like
```
meta := &PodMetadata{
		UID:            chunks[0],
		Namespace:      chunks[1],
		IP:             chunks[2],
		ServiceAccount: service.K8sServiceAccount{Name: chunks[3], Namespace: chunks[1]},
		EnvoyNodeID:    chunks[4],
	}
```
