### ISSUE TITLE
test: pkg/envoy/ads recordEnvoyPodMetadata()

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2701]
In `pkg/envoy/ads` `recordEnvoyPodMetadata()` does not have good unit test coverage.
It would be great to write a small test for this function.

![image](https://user-images.githubusercontent.com/49918230/109853611-ecd79280-7c0a-11eb-89e8-9cd209ed8093.png)

**Comment by draychev** [comment]
ref #1489

**Comment by SanyaKochhar** [comment]
Consolidated in #3408
