### ISSUE TITLE
test: pkg/envoy/ads profiling tool

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2703]
In `pkg/envoy/ads/profile.go` an anonymous function does not have good unit test coverage.
It would be great to write a small test for this function.

We could carve out the manipulation of `timeSlice` in another (non-anonymous) function and test it separately.

![image](https://user-images.githubusercontent.com/49918230/109853983-5f487280-7c0b-11eb-886a-147726bb9cf8.png)

**Comment by draychev** [comment]
ref #1489

**Comment by SanyaKochhar** [comment]
Coverage for this is now 100%
