### ISSUE TITLE
debug: tool to check for DNS resolution from meshed Pod

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2729]
Augment tests to first perform a DNS lookup (`nslookup`, `dig`) for the service a client needs. For example `dig bookstore.bookstore`

This guarantees that required service has been registered with the Kubernetes DNS.

This check needs to happen after a Service has been created and before the e2e tests log-into the pod and run the test commands.
For example: https://github.com/openservicemesh/osm/blob/release-v0.8/tests/e2e/e2e_tcp_client_server_test.go#L71

---

Similar task: https://github.com/openservicemesh/osm/issues/2728

---

Update: let's introduce this new functionality in a new `pkg/troubleshoot` (name TBD). From that package we can use it in e2e or any tests. This new package should also eventually become a CLI for troubleshooting OSM.

**Comment by shashankram** [comment]
We haven't seen a need to integrate DNS lookups in test. The existing logic has been working well lately. Closing this for now.
