### ISSUE TITLE
SMI conversion webhook to upgrade to newer SMI API versions

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2737]
**Please describe the Improvement and/or Feature Request**
Currently OSM does not support backward compatibility with SMI CRDs released in previous versions. This results in breaking changes when the SMI CRDs are upgraded and existing deployments that are leveraging a previous version of the custom resources (TrafficTargets, Splits, HTTPRouteGroups, TCPRoutes) can no longer function with a newer version of osm-controller that only supports the newer SMI API versions.

To mitigate this issue during upgrades, OSM must use a conversion webhook to convert older SMI resource versions to newer ones, and gradually migrate the deployments to use the newer versions before deprecating older ones in the cluster.

Since SMI does not provide a conversion webhook at this moment, we have the following options:
1. Implement the SMI conversion webhook to the SMI SDK repo
2. Implement the SMI conversion webhook in OSM and contribute it to SMI later on

Conversion webhook ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Support gradual migration of older SMI versions in the cluster.

**Comment by draychev** [comment]
This issue could be resolved via **investigate smi-controller-sdk for osm project** #3063

**Comment by snehachhabria** [comment]
With issue #3396 we have decided to go with the option of : Implementing the SMI conversion webhook in OSM

**Comment by snehachhabria** [comment]
Closing issue for now as all the necessary code to support a conversion webhook for CRDs in OSM has been added
