### ISSUE TITLE
Don't expose envoy log level to end users

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2754]
**Please describe the Improvement and/or Feature Request**
Per Envoy proxy documentation https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-l:
**Non developers should generally never set this option**

This is because Envoy is not meant to operate in production at debug or lower levels, and might result in slowness/races resulting from verbose logging.

Since OSM exposes Envoy's log level as a cli option `--envoy-log-level` and in the `osm-config` ConfigMap via the key `envoy_log_level`, this goes against the recommendation above where it should only be used by developers. However since verbose logging is required to debug issues, not being able to enable verbose debugging seems to be a hard tradeoff.

The issue proposes to do the following:
1. Avoid exposing Envoy log level configuration on `osm cli and ConfigMap`
2. Allow configuring Envoy via the debug HTTP server via a `/put` request. This adds an additional layer to being able to configure it if the need arises, and ensures that this setting is only required in debugging mode with the debug server turned on.

**Comment by jaellio** [comment]
For now, the envoy LogLevel will remain in the mesh config. The ability to easily modify the log level will be essential for assisting OSM users. The documentation for the envoy LogLevel will reflect the Envoy documentation which states that non-developers should not modify the log level. 

Removing the envoy LogLevel from the mesh config should be revisited in the future.
