### ISSUE TITLE
Make bookstore app ports configurable in automated demo

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2755]
Make demo app ports configurable. This will help users customize the demos to suit their environments.

**Comment by addozhang** [comment]
+1, 80 is not acceptable in openshift.

**Comment by allenlsy** [comment]
Are we talking about configuring the port forwarding port in auto demo? I think they are configurable now.

E.g. https://github.com/openservicemesh/osm/blob/main/scripts/port-forward-bookstore-ui.sh#L18

Or do I misunderstand the issue?

**Comment by ksubrmnn** [comment]
This issue is for this port: https://github.com/openservicemesh/osm/blob/94fc23d4d6e063eef871af8f44fcece576af4e15/docs/example/manifests/apps/bookstore-v2.yaml#L11

**Comment by draychev** [comment]
This GitHub Issue would also provide great value in instrumenting end-to-end tests where we can **randomize app ports** (within some ranges).
This will ensure that we are not accidentally hard-coding ports in Envoy configs etc.

**Comment by shashankram** [comment]
> This GitHub Issue would also provide great value in instrumenting end-to-end tests where we can **randomize app ports** (within some ranges).
> This will ensure that we are not accidentally hard-coding ports in Envoy configs etc.

The bookstore apps are not used in e2e tests, we use a combination of `curl` and `httpbin`. I agree some sort of fuzzing around the values used in e2e tests is valuable, but I don't see a benefit to complicating the existing bookstore demo apps to perform this sort of fuzz testing. Moreover, the automated demo (`run-osm-demo.sh`) is already getting complicated with the number of permutations being introduced.

@draychev Do you think this is still necessary?

**Comment by draychev** [comment]
@shashankram This does not seem too critical.
@allenlsy If you already have a PR for this change (I understand this to be the case) - I would not be opposed to merging it.

**Comment by allenlsy** [comment]
PR reopened. PTAL.

https://github.com/openservicemesh/osm/pull/3619

**Comment by allenlsy** [comment]
Feature is not needed any more as we want to keep our demo application simple.
