### ISSUE TITLE
Avoid to faill with missing ingress in Openshift

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2758]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [x]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

Checked 0.8.0 code, the control plane initiates Ingress client when starting. 
But in openshift env, there is not Ingress resource exist.

```
{"level":"error","component":"kube-ingress","error":"Failed initial cache sync for Ingress informer","time":"2021-03-06T06:15:38Z","file":"client.go:42","message":"Could not start Kubernetes Ingress client"}
{"level":"fatal","component":"kube-events","error":"Failed initial cache sync for Ingress informer","reason":"FatalInitializationError","time":"2021-03-06T06:15:38Z","file":"events.go:138","message":"Error creating Ingress monitor client"}
```

**Comment by addozhang** [comment]
@shashankram how about this requirement? On my local, I implemented a boop ingress client to simulate one.

**Comment by shashankram** [comment]
> @shashankram how about this requirement? On my local, I implemented a boop ingress client to simulate one.

Is the ingress API optional in Openshift clusters?

Since OSM relies on k8s ingress to expose a service within the cluster externally, disabling ingress on Openshift would mean this is no longer possible with the existing ingress implementation in OSM.

@ksubrmnn are you aware of an issue with osm-controller not starting up because of ingress initialization failing in Openshift?

**Comment by addozhang** [comment]
@shashankram just checked. I think it's issue with Ingress version what we are using is `extensions/v1beta1`.

**Comment by shashankram** [comment]
> @shashankram just checked. I think it's issue with Ingress version what we are using is `extensions/v1beta1`. It's moved to `networking.k8s.io` in 0.8.0. 😅

extensions/v1beta1 is deprecated in k8s 1.16 and we no longer support deprecated k8s versions. Please switch to `networking/v1beta1` for now. Soon, `networking/v1beta1` will be deprecated in OSM (already deprecated in k8s 1.19) and OSM will only support `networking/v1`.

**Comment by shashankram** [comment]
> > @shashankram just checked. I think it's issue with Ingress version what we are using is `extensions/v1beta1`. It's moved to `networking.k8s.io` in 0.8.0. 😅
> 
> extensions/v1beta1 is deprecated in k8s 1.16 and we no longer support deprecated k8s versions. Please switch to `networking/v1beta1` for now. Soon, `networking/v1beta1` will be deprecated in OSM (already deprecated in k8s 1.19) and OSM will only support `networking/v1`.

Closing this, since OSM no longer supports the deprecated ingress `extensions/vebeta1`. Please use `networking/v1beta1` API group for ingress with v0.8.
