### ISSUE TITLE
Document required network flows for routine mesh operations

### ISSUE THREAD

**Issue by ckittel** [openservicemesh/osm#2762]
In a cluster that starts with a zero-trust NetworkPolicy in place for each namespace, having documented network requirements would be handy for OSM control plane + proxy (xDS, etc).

So far I've deduced that a pod that contains the injected Envoy proxy must at least be able to connect to `15128` (default) on `osm-controller` to establish xDS.  Beyond that I'm not sure what else is required.  I do know that in just this configuration, after 24 hours (default), the mesh falls apart, as TLS certificates have expired and Envoy doesn't seem to get new certificate data, so there are maybe some necessary support for "announcement" traffic from osm-controller to known envoy proxies that I haven't accounted for here?  While I'd love to know what that might be, I'd be more interested in just making sure that the normal/routine network traffic is documented (source, destination, port (name)) for mesh operations.

**Comment by shashankram** [comment]
> I do know that in just this configuration, after 24 hours (default), the mesh falls apart, as TLS certificates have expired and Envoy doesn't seem to get new certificate data

Hey @ckittel , I ran into this issue as well and addressed it in v0.8.0: https://github.com/openservicemesh/osm/issues/2786

**Comment by ckittel** [comment]
Thanks for the heads up there @shashankram -- great to see the rotation problem fixed. I admit that I don't have a full grasp on the networking requirements here for network policies. Using the new pub-sub solution here, does the rotation process end in a network request TO the pods, and if so what destination (port/proto)?  Or is that a "pull" model from the sidecar back to the osm controller?

**Comment by shashankram** [comment]
> Got it, so from a network policy perspective, osm-controller needs network line of sight TO the concerned proxy, in addition to the proxy needing network line of sight for XDS pulls. I'm sure this is gonig to sound like a dumb question to you, but which of the couple defined ports is used on the proxy (pod), for those pushs? (want to provide port descriptors in NetworkPolicy here.)

The list of reserved ports for traffic interception and redirection on the proxy pod is described in https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/iptables_redirection/#ports-reserved-for-traffic-redirection

The port on which the proxy connects to the controller is used as follows:
https://github.com/openservicemesh/osm/blob/6d8054ded5714f2bc0c43cadd9bbc0242fc5c2f3/pkg/injector/envoy_config.go#L113-L114

**Comment by ckittel** [comment]
Perfect, thank you.

**Comment by ckittel** [comment]
Sorry for missing that in your response. That's the information I was directly after.  Thank you. Sorry for being a big dense here, and taking this conversation in a direction slightly askew of the OP. :)

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/3607

Doc: https://github.com/openservicemesh/osm/blob/main/docs/envoy/traffic_flow.md
