### ISSUE TITLE
decouple traffic split root service from Kubernetes service

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2768]
The SMI [Spec](https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-split/v1alpha2/traffic-split.md#traffic-split-v1alpha2) states that a root service in a traffic split is an FQDN and does not require it to reference a Kubernetes service. The way traffic split it currently implemented, root service must be a kubernetes service. We should decouple these to follow the SMI spec for traffic split.

**Comment by michelleN** [comment]
may need to use coredns plugin to resolve hostname or use envoy as dns (there is an envoy github issue for this, not sure how far along this is) or put something in /etc/hosts

**Comment by shashankram** [comment]
> may need to use coredns plugin to resolve hostname or use envoy as dns (there is an envoy github issue for this, not sure how far along this is) or put something in /etc/hosts

Why can't we stick to supporting only service FQDNs? This seems pretty reasonable given mesh traffic uses k8s service to communicate?

Later on when we start supporting custom DNS entry for service FQDN we can remove the k8s service FQDN dependency (if the need arises)

**Comment by michelleN** [comment]
> Why can't we stick to supporting only service FQDNs? This seems pretty reasonable given mesh traffic uses k8s service to communicate?

We can and that will fix our initial issue. This issue captures more of a long term goal. I agree with you.
