### ISSUE TITLE
cli: Change uninstall command to match "osm install"

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2793]
We use `$ ./osm install` to install OSM.
Yet we have to use `$ ./osm mesh uninstall` to uninstall

It would be great if this was instead `$ ./osm uninstall` (i.e. skipping the `mesh` sub-command nesting)

---

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by bridgetkromhout** [comment]
Discussed in standup - docs changes also complete.
