### ISSUE TITLE
envoy secret clean up 

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2795]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

We have secrect count limit in quota, and the secret is not cleaned up automatically after pod terminated.

```
Warning   FailedCreate             replicaset-controller               Error creating: Internal error occurred: admission webhook "osm-inject.k8s.io" denied the request: secrets "envoy-bootstrap-config-e605c17a-6bcf-4bce-9684-2d47af3bf3a4" is forbidden: exceeded quota: xxxx-quota, requested: secrets=1, used: secrets=280, limited: secrets=280
```

**Comment by draychev** [comment]
A different way of provisioning the bootstrap config is explored here: https://github.com/openservicemesh/osm/pull/2234
We need to either change how we deliver the bootstrap config (find a better way) or find a way to clean-up secrets once a pod is terminated.
