### ISSUE TITLE
validate and process traffic split root service as fqdn

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2797]
The SMI Spec states that the root service in a traffic split should be an fqdn. Currently, we allow a service name with no namespaces suffix as a root service. We also allow a root service with a namespace suffix that is not the same namespace as the namespace where the traffic split is created (we drop the namespace suffix and use the namespace of the traffic split). We also do not validate anything beyond the first element in the root service string after splitting it. Ex. If the root service is "bookstore.foo.hello.world" and the namespace of the traffic split is "bar", we could use the bookstore service in the bar namespace as the root service (`bookstore.bar`). We also only support Kubernetes services as traffic split root services. This issue is to track the work to correctly process and validate a root service in a traffic split where the root service is a Kubernetes service.

**Comment by snehachhabria** [comment]
This has already been fixed with #2794
