### ISSUE TITLE
No version emitted as first log line of OSM Controller

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2818]
The very first line the OSM Controller emits is the version of the binary.

I downloaded 0.8 rc1 and observed this first log line missing the version number.

Here is the version from the CLI binary:
```bash
$ ./linux-amd64/osm version

Version: v0.8.0-rc.1; Commit: 739b490509ac3551ca9716558bead68d42222852; Date: 2021-03-02-22:49
```

Here is the version from the osm controller logs
```bash
$ kubectl logs -n osm-system --selector app=osm-controller --tail=999 | head -n1 | jq '.'

{
  "level": "info",
  "component": "osm-controller/main",
  "time": "2021-03-11T23:37:48Z",
  "file": "osm-controller.go:111",
  "message": "Starting osm-controller dev; 739b490509ac3551ca9716558bead68d42222852; 2021-03-02-22:52"
}
```

I would expect to see `v0.8.0-rc.1;` in the first log line.

**Comment by mudit-01** [comment]
@draychev I would like to work on it. I just need some guidance on where to start.
