### ISSUE TITLE
Add support for linux/arm64

### ISSUE THREAD

**Issue by shashankbarsin** [openservicemesh/osm#2821]
**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
Currently osm only has images for linux/amd64. Adding support for publishing linux/arm64 images would allow for running osm on clusters which have only linux/arm64 nodes

cc: @ritazh

**Comment by draychev** [comment]
@eduser25 I know you already did some work on amd64 compile target!
So exciting!
It seems that we could get an MVP of this going and @shashankbarsin can test it out on an arm64 machine.

**Comment by eduser25** [comment]
Hey @shashankbarsin, I did compile OSM in arm and basically execute the binary with no issues on an arm-based machine.
If I recall there were some dependency issues with some go libraries at the time, but I should recheck.

After that, we should add the build pipe and release the arm images.

**Comment by tbertenshaw** [comment]
Any update on arm64 support?

**Comment by draychev** [comment]
@nojnhuh Has agreed to take a stab at building ARM64 images.

**Comment by scottmalkie** [comment]
Hello! Now with v1.0.0 released (Congrats!) - could we have linux/arm64 builds as part of the release packages?
