### ISSUE TITLE
Document how to install nginx ingress controller

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2827]
**Please describe what should be documented**
Link to steps to install nginx ingress controller

**Please suggest where in the repo the document should be located**
https://github.com/openservicemesh/osm/blob/main/docs/content/docs/tasks_usage/ingress.md

**Comment by draychev** [comment]
# Additional documentation
Troubleshooting Guide:
  - [ ] Check Ingress resource for correctness and annotations (point to Nginx ingress controller docs for this)
  - [ ] Does the Ingress resource reference an existing Service?
  - [ ] Does the Service referenced by the Ingress resource have Pods backing it - list the Endpoints
  - [ ] Check Envoy configuration of one/all of the Endpoints referenced in the Ingress - to these Envoys have an HTTP ingress inbound opened?

**Comment by shashankram** [comment]
The ingress documentation has a sample demo that uses Kubernetes Nginx Ingress https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/ingress/#sample-demo.

It has a link to the Nginx installation guide which the user can follow based on their environment and preferences for installing:

![image](https://user-images.githubusercontent.com/21697719/119172477-ddeaca00-ba1a-11eb-98d2-96b005ac627f.png)
