### ISSUE TITLE
Certificate rotor rotates the same certificate multiple times in the same rotation cycle if the service cert validity duration is <= 1 minute

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2832]
**Please describe the Improvement and/or Feature Request**
Certificate rotation by rotor.go rotates the same certificate multiple times during the same rotation cycle if the service cert validity duration is <= 1 minute.

This happens as a consequence of renewing the cert before it actually expires, which is controlled by the following config:
```
// How much earlier (before expiration) should a certificate be renewed
	renewBeforeCertExpires = 30 * time.Second
```

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [X]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Comment by allenlsy** [comment]
Discussed about the solution offline. 

We are either make the `renewBeforeCertExpires` duration shorter for  short-lived cert, or use validating webhook to enforce a min value of cert valid period. Validating webhook is preferred.

**Comment by shashankram** [comment]
We don't have an immediate need to address this side effect.
