### ISSUE TITLE
http_ingress_test fails on AKS when OSM already installed. 

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#2835]
**Bug description**: http_ingress_test gives the following error when the test is run with the "no-install" flag after OSM v0.8.0-rc.2 is installed on AKS cluster. 

`Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready
Deployment is not ready: osm-system/ingress-nginx-controller. 0 out of 1 expected pods are ready`
**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [X]

**Expected behavior**: https_ingress_test should pass if OSM is already installed. 

**Steps to reproduce the bug (as precisely as possible)**: Install osm v0.8.0-rc.2 on AKS (default namespace), and then run: `go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -test.timeout 60m -installType=NoInstall -ginkgo.focus="allows HTTP ingress traffic"`

**How was OSM installed?**: /bin/osm install

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): v0.8.0-rc.2
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (number of worker nodes in the cluster): 
- Others:

**Comment by shashankram** [comment]
@nojnhuh assigning this one to you.
