### ISSUE TITLE
Integrate with Azure Key Vault

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#284]
This task has 2 sub tasks:

 -- Use Azure Key Vault to allow customers to bring their Digicert certificate and use it for mTLS (in this case Azure Key Vault would issue/sign mTLS certs)
 -- Use Azure Key Vault to store mTLS certificates issued by OSM; In this case Key Vault does not have the CA - CA is OSM; OSM will merely use Azure Key Vault as a persistent storage/cache

**Comment by cmendible** [comment]
Hi team, any news on this one? I have an FSI customer who stores all secrets and certs in Azure Key Vault and this could be a stopper for OSM adoption.
