### ISSUE TITLE
design doc: Per Service Filter Chains

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2858]
With #1725 we implemented filter chain per outbound service.

This GitHub issue is for documenting the the OSM documentation around per-service filterchains.

 - [ ] Document filterchoin per outbound service -- since this is not a standalone feature - we need to also as port of this issue find the best place for this.  Not sure whether this belongs to a design doc or as part of on existing doc around SMI policy (Traffic Target? TCP Route?)
 - [ ] Create a small demo with sample apps and SMI showing how this feature works
   - [ ] What are the SMI policies that affect this feature? What causes OSM to create these filter chains?
   - [ ] Give examples of Envoy configuration with and without these filterchains.
  
 - [ ] List Common Issues
   - [ ] Are there known issues that may arise from this design?
   - [ ] What happens if pods on the cluster churn quickly?
  
 - [ ] Create Troubleshooting Guide - what tools and techniques could be used to troubleshoot this? Can we use OSM CLI to fetch Envoy config and observe JSON then compare w/ actual Kubernetes context/services/endpoints?

 - [ ] Automate Troubleshooting Guide in `pkg/troubleshooter` (create appropriate functions) - alternatively create a GitHub Issue with the stub of the function that could be eventually created within `pkg/troubleshooter` package to automatically troubleshoot this feature.

**Comment by shashankram** [comment]
If we document this, kindly drop this in a design doc instead of user-facing docs. User's don't care about knowing the internals of Envoy configurations which can get quite complex based on configurations.

**Comment by eduser25** [comment]
We'll look forward to move it into docs if needed
https://docs.google.com/document/d/1LD0Ntc3arh2EJNoB8wCCmtIK0oSAqI2dYx8bZZDNtZg/edit
