### ISSUE TITLE
doc: Cleanup VM onboarding since this is not fully implemented in v0.8

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2863]
Please remove documents referencing VM onboarding since this is not fully implemented (or at all) in v0.8.
We will resurrect these documents from the git repo when we are ready for VMs.

**Comment by ksubrmnn** [comment]
Is it necessary to clean this up since it says WIP
https://github.com/openservicemesh/osm/blob/main/docs/content/docs/tasks_usage/onboard_vm.md#onboarding-vms-to-the-service-mesh

I'm okay either way since the change could easily be reverted via github. Just not sure what the timelines is for this

**Comment by draychev** [comment]
> 
> 
> Is it necessary to clean this up since it says WIP
> https://github.com/openservicemesh/osm/blob/main/docs/content/docs/tasks_usage/onboard_vm.md#onboarding-vms-to-the-service-mesh
> 
> I'm okay either way since the change could easily be reverted via github. Just not sure what the timelines is for this

I propose we remove it because it appears in a prominent place in our main docs site. This makes it look like we fully support VMs. This is no longer the case.  We deliberately removed code handling VMs a few months ago. Once SMI has the notion of non-Kubernetes payload we can come back and resurrect VM payloads code and documentation. (These removal commits should be easy to find and revert.)

![image](https://user-images.githubusercontent.com/49918230/111502453-13b1c080-8703-11eb-8425-a96d37810af5.png)
