### ISSUE TITLE
osm mesh upgrade command just hangs

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2867]
**Bug description**:
Using the `osm mesh upgrade` command to change the traffic policy mode just hangs on `main`.

```
$ osm mesh upgrade --enable-permissive-traffic-policy=true
^C
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
`osm mesh upgrade` should update the config map and not hang.

**Steps to reproduce the bug (as precisely as possible)**:
Checkout `main`, `./demo/run-osm-demo.sh`
`osm mesh upgrade --enable-permissive-traffic-policy=true`

**How was OSM installed?**: `./demo/run-osm-demo.sh`

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
```
Version: dev; Commit: 70d6bf25253d0384fd10167916c1be06d0285c28; Date: 2021-03-15-13:06
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (number of worker nodes in the cluster): 1 node
- Others: n/a

**Comment by nojnhuh** [comment]
When installing with non-default images (like the demo script does), the same `--container-registry` and `--osm-image-tag` should be passed to `osm mesh upgrade` if you don't want them to change. These are overridden by default for the new Helm release as documented in `osm mesh upgrade --help`. We haven't tested and don't plan to support "upgrading" to older versions of OSM yet.

The command instructs Helm to time out after 5 minutes if the control plane pods are not ready yet. If it was hanging for longer than that, feel free to reopen this.
