### ISSUE TITLE
doc: Integrate w/ Prometheus

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2874]
This GitHub issue is for fleshing out the OSM documentation around Prometheus:

 - [ ] Document Prometheus-- save the doc in ./docs/wip/integrate_prometheus.md (exact location is TBD - `wip` short term)
  0. [ ] What is Prometheus (link to external docs)? Why do we need it? How does it fit in OSM and SMI? 
  1. [ ] Describe how Prometheus works, why we need it, what it is, how Envoy exposes Prometheus endpoints
    1.1. [ ] What are the annotations used? Are these on Namespace or Pod? How can yuo apply the annotation? Give OSM CLI example and kubectl example.
    1.2. [ ] When are Prometheus endpoints exposed? Always? Or only when certain annotation is enabled?
    1.3. [ ] What data is exposed via these Envoy Prometheus endpoints? Provide samples of the data exposed (responses).
    1.4. [ ] Describe why we need WASM and what it does for OSM. Pointers to the code base. Pointers to samples of data created by WASM.
    1.5. [ ] Write about the Prometheus pod itself - how do we scale it? Make it resilient? Configure storage? (Please use external links where possible)
 2. [ ] What does the Envoy configuration look like w/ and without Prometheus
 3. [ ] Are there options in OSM CLI that affect Prometheus integration? What are they?

 - [ ] Create a small demo with sample apps showing Prometheus endpoints
   - [ ] Provide sample request/responses
 
 - [ ] List Common Issues

 - [ ] Create Troubleshooting Guide
   - [ ] Is OSM installed on the cluster? Is it in the expected namespace? Is it alive and healthy? How many times has it restarted?
   - [ ] Are the right versions of SMI (or at all) installed on the K8s cluster? 
   - [ ] Is Prometheus integration enabled?
   - [ ] Are expected namespaces enabled for metrics
   - [ ] Are expected namespaces and pods injected w/ Envoy proxies already? (No Envoy - no metrics)
   - [ ] Check if Ingress and Egress are enabled - could these be affecting Prometheus integration
   - [ ] Are Envoy proxies configured to expose Prometheus metrics?
   - [ ] Check Envoy for Prometheus metrics listener
   - [ ] Are expected Prometheus metrics appearing as expected?
   - [ ] Are there certain issues we need workarounds for for WASM?
   - [ ] Is traffic flowing between the pods expected to show some metrics?
   - [ ] Are there any SMI policies allowing traffic between pods?
   - [ ] Is the OSM cluster is SMI or Permissive Traffic Mode?

 - [ ] Automate Troubleshooting Guide in `pkg/troubleshooter` (create appropriate functions) - alternatively create a GitHub Issue with the stub of the function that could be eventually created within `pkg/troubleshooter` package to automatically troubleshoot this feature.

**Comment by nojnhuh** [comment]
@draychev It looks like some of this is already documented in the metrics doc: https://github.com/openservicemesh/osm/blob/fd5c366c4c35a571cb57a23a833a34f835873675/docs/content/docs/tasks_usage/metrics.md

Did you have an idea of how this new doc should relate to that? I don't mind adding to the existing doc or moving some info out of that doc into this new one, but just want to make sure each doc serves a distinct purpose.
