### ISSUE TITLE
doc: uninstalling OSM and removing all related components from a cluster

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2880]
This GitHub issue is for fleshing out the OSM documentation around uninstalling Open Service Mesh and removing all of its components from a cluster.

 - [ ] Document the OSM CLI tool and process of uninstalling OSM -- save the doc in ./docs/wip/uninstall_osm.md (exact location is TBD - `wip` short term)
   - [ ] How do you uninstall OSM? What CLI command does that?
   - [ ] What is expected to be deleted by using the CLI?
   - [ ] What is expected to remain on the cluster by using the OSM CLI?
   - [ ] Does the OSM CLI also remove Envoy sidecars from existing pods?
   - [ ] How do we remove the sidecars from existing pods?
   - [ ] Could this cause downtime?
   - [ ] How do we prevent downtime during removal of OSM from the cluster?
   - [ ] What happens to the CA?
   - [ ] Are there alternatives?

 - [ ] Create Troubleshooting Guide
   - [ ] How do you manually delete Mutating WebhookConfig, Validating WHc, OSM ConfigMap,
   - [ ] How do you backup SMI CRDs and delete Custom Resource Definitions (SMI) from the cluster
   - [ ] How do you remove the CA?
   - [ ] Are there any other artifacts that need to be manually removed?
   - [ ] List all artifacts related to OSM and provide a command to remove them
   - [ ] How do you manually perform rolling restart to remove Envoy sidecars?
   - [ ] How do you remove annotations from namespaces?
   - [ ] What namespaces are annotated? What are the annotations that need to be removed (monitor, inject, metrics)
   - [ ] How can we remove OSM Controller with 0-downtime?
      - [ ] Change MutatingWebhook first? Change to Ignore
      - [ ] Shutdown / delete controller?

**Comment by michelleN** [comment]
Should this doc live in /docs/content/docs/tasks_usage/?
