### ISSUE TITLE
doc: osm-config ConfigMap

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2886]
This GitHub issue is for fleshing out the OSM documentation around the `osm-system/osm-config` ConfigMap:

 - [x] Document `osm-system/osm-config` ConfigMap-- save the doc in ./docs/wip/osm_configmap.md (exact location is TBD - `wip` short term)
   - [ ] What's a ConfigMap?
   - [ ] Why do we need the `osm-system/osm-config` ConfigMap?
   - [ ] Why are CLI params not enough? What are the downsides of changing configuration by CLI args we pass to OSM binary?
   - [ ] How do I change the OSM Configmap? Is there a kubectl patch command? Is there an OSM CLI command
   - [ ] Where is the configmap? What is it called
   - [ ] What is in the config map?
   - [ ] Create a table with the keys, the possible values, what these change, what is the command that changes that (CLI), what is the corresponding kubectl patch command w/ JSON examlpe. 
   - [ ] Can OSM Controller function without an osm-config ConfigMap (actually run a test)
   - [ ] What would happen if a ConfigMap with some useful values is deleted via `kubectl delete Configmap -n osm-system osm-config` ? How would that change the behavior of the OSM controller?
   - [ ] What happens if the keys are wrong? For instance instead of `egress` we have entered `enable_igress` via kubectl command? How would OSM Controller react?
   - [ ] What happens if the values are wrong? For instance what would happen if we enter `egress` key and value `ture` or `fasle`
   - [ ] How does the ValidatingWebhookConfiguration work?
   - [ ] Why is the Validating Webhook needed?

 - [ ] Create a small demo with sample apps and SMI showing how this feature works

 - [x] List Common Issues

 - [x] Create Troubleshooting Guide
     - [ ] There should be an option to delete the ValidatingWebhook if we find it to not work as well as possible... ` kubectl delete ValidatingWebhookConfiguration $(kubectl get ValidatingWebhookConfigurations --no-headers | grep osm | awk '{print $1}' | grep -E '^osm')`

 - [ ] Automate Troubleshooting Guide in `pkg/troubleshooter` (create appropriate functions) - alternatively create a GitHub Issue with the stub of the function that could be eventually created within `pkg/troubleshooter` package to automatically troubleshoot this feature.

**Comment by draychev** [comment]
ref: https://github.com/openservicemesh/osm/issues/2386#issuecomment-801671109

**Comment by snehachhabria** [comment]
we no longer have a configmap in osm, closing this issue
