### ISSUE TITLE
doc: Update Scale and limits

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2893]
This issue is to update [the Scale and limits doc](https://github.com/openservicemesh/osm/blob/main/docs/content/docs/scale/_index.md) with the latest numbers as of v0.8

**Comment by eduser25** [comment]
I'll update this soon. I'm seeing some problems with the pipelines though.

**Comment by eduser25** [comment]
https://github.com/openservicemesh/osm-docs/pull/32 for the time being
