### ISSUE TITLE
add e2e tests for various mesh scenarious and document

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#290]
This project has two components
- [x] [create an e2e framework](https://github.com/openservicemesh/osm/issues/1711) (leveraging our existing e2e infrastructure - automated demo + maestro)
- [x] [define and implement a set of e2e test scenarios for OSM](https://github.com/openservicemesh/osm/issues/1714)

**Comment by SanyaKochhar** [comment]
@michelleN could you provide more details?

**Comment by michelleN** [comment]
added more details to the description.
