### ISSUE TITLE
doc: Update release guide to point docs w/ hardcoded OSM versions

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2908]
This GitHub issues is for the updating of the existing release guide to point docs w/ hardcoded OSM versions.

grep for `v0.8.0-rc.2`

See: https://github.com/openservicemesh/osm/pull/2907#discussion_r596131227

**Comment by shashankram** [comment]
v0.8 is no longer relevant, and osm-docs has been updated for several releases since this issue was created. Not required anymore.
