### ISSUE TITLE
Log pod name in XDS logs; internal IDs are not useful

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2924]
**Please describe the Improvement and/or Feature Request**
XDS logs are not convenient to debug because they do not log pod names and instead log internal IDs only the control plane is aware of:
```
Envoy with certificate SerialNumber=138883894336224235594180605532809107224 on Pod with UID=1989825e-6af9-4e20-b182-60e27b1350d2"}
```

There should be no downside to logging the pod name, because it is just another k8s resource name that controllers must log to be able to debug issues conveniently.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [X]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Logging improvements to debug issues faster.

**Comment by eduser25** [comment]
+1
In its current form debugging is unnecessarily hard, and the security tradeoff is IMHO arguable at worst

**Comment by draychev** [comment]
Working on a proposal for this here:  https://github.com/openservicemesh/osm/pull/2951

**Comment by shashankram** [comment]
With https://github.com/openservicemesh/osm/pull/3584, logs in pkg/envoy are more consistent and provide better info at debug/trace levels.

We might want to consider providing more info even at Info level.

**Comment by nojnhuh** [comment]
Planned remaining work for this issue:
- In pkg/envoy, log pod metadata regardless of global log level: https://github.com/openservicemesh/osm/blob/4757443cded5e346a8e11f59ee71f8a91c7c87ea/pkg/envoy/proxy.go#L55-L61
- Add context to osm-docs about what can be expected in OSM control plane logs

**Comment by nojnhuh** [comment]
Closing this now that https://github.com/openservicemesh/osm-docs/pull/177 is merged
