### ISSUE TITLE
Define deprecation process for Helm chart fields removal 

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2975]
**Please describe the Improvement and/or Feature Request**

When an existing Helm chart field is removed, it should go thru a deprecation process where the field is marked as [deprecated] for couple of releases before it is completely removed. This helps reduce impact for users to give them time to make the necessary changes in their ops workflow.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
Depends on #4330

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm-docs/commit/363eba59809ce0a51c6679c544d05f2875dd0d35.
