### ISSUE TITLE
Document data plane performance

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2993]
**Please describe the Improvement and/or Feature Request**

Document latency, throughput, and proxy's CPU and memory as connections increase 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by allenlsy** [comment]
The pending perf & scalability doc (will be published in early April 2022) will include latency, CPU and memory usage of data plane as RPS increases. It's not compared against connections. We will continue the work.
