### ISSUE TITLE
add --delete-namespace flag to osm mesh uninstall

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3000]
After a user runs `osm mesh uninstall`, the user has to manually delete the namespace osm was installed into with `kubectl`. It'd be helpful if there were a `delete-namespace` flag that also deleted the namespace once the control plane components were deleted as part of the uninstall command.

`osm mesh uninstall --delete-namespace` would uninstall control plane components AND delete the namespace the mesh was installed into.

**Comment by shashankram** [comment]
Hey @webmobiletraining , this issue has already been resolved by https://github.com/openservicemesh/osm/pull/3029.

Kindly take a look at our other [good first issues](https://github.com/openservicemesh/osm/labels/good%20first%20issue) to start contributing!
