### ISSUE TITLE
Bookthief expected response code should be 0

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#3059]
**Bug description**:
https://github.com/openservicemesh/osm/blob/main/docs/example/manifests/apps/bookthief.yaml#L39

This should be programmed as 0 for the demo.

I'm actually not really sure how much this is used so we could potentially remove it
**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [X]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
> This should be programmed as 0 for the demo.

This really depends on how the mesh is set up - traffic targets, splits, permissive mode etc. There is no fixed response code that will be consistent for all cases.

If bookthief doesn't have a policy to access the destination, it will be 0.
If it does but there is a route missing, it will be 404.
If it has the routes but the destination rejects it based in RBAC, it will receive a 403.

So there isn't one response code that's going to just work for different scenarios.

**Comment by shashankram** [comment]
> > This should be programmed as 0 for the demo.
> 
> This really depends on how the mesh is set up - traffic targets, splits, permissive mode etc. There is no fixed response code that will be consistent for all cases.
> 
> If bookthief doesn't have a policy to access the destination, it will be 0. If it does but there is a route missing, it will be 404. If it has the routes but the destination rejects it based in RBAC, it will receive a 403.
> 
> So there isn't one response code that's going to just work for different scenarios.

Closing based on the above update.
