### ISSUE TITLE
prometheus_scraping flag is set to false by default in the osm-config configmap

### ISSUE THREAD

**Issue by rashmichandrashekar** [openservicemesh/osm#3062]
**Bug description**:
The flag prometheus_scraping is set to false by default in the osm-config configmap. Because of this Azmon agent is unable to scrape the endpoints unless it is set to true and the deployments are recreated.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
prometheus_scraping should be set to true (https://github.com/openservicemesh/osm/blob/main/docs/content/docs/tasks_usage/metrics.md#list-of-prerequisites-for-byo-prometheus)

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:
AKS Addon

**Environment**:
- OSM version (use `osm version`): 0.8.2
- Kubernetes version (use `kubectl version`):1.18.14
- Size of cluster (number of worker nodes in the cluster):5 , 3-linux and 2 windows

**Comment by shashankram** [comment]
Hey @rashmichandrashekar , I see `prometheus_scraping` set to true by default:

https://github.com/openservicemesh/osm/blob/60b1a9282ceb35ff55cc21b82ac7bd192c5b9d7a/charts/osm/values.yaml#L69-L70

https://github.com/openservicemesh/osm/blob/60b1a9282ceb35ff55cc21b82ac7bd192c5b9d7a/charts/osm/templates/osm-configmap.yaml#L12

It's likely this has been set to `false` in your environment.

**Comment by shashankram** [comment]
Discussed with @rashmichandrashekar , the scraping option was set to false by default in their environment, but this is not a bug. Refer to https://github.com/openservicemesh/osm/issues/3062#issuecomment-812007007 for more details.

We have figured out the cause for this - the scraping was disabled by default in the Azmon test environment.

**Comment by rashmichandrashekar** [comment]
> Discussed with @rashmichandrashekar , the scraping option was set to false by default in their environment, but this is not a bug. Refer to [#3062 (comment)](https://github.com/openservicemesh/osm/issues/3062#issuecomment-812007007) for more details.
> 
> We have figured out the cause for this - the scraping was disabled by default in the Azmon test environment.

> This is a bug with the AKS OSM addon. I will follow up with an internal tracking bug. Thanks Shashank.

**Comment by rashmichandrashekar** [comment]
> > Discussed with @rashmichandrashekar , the scraping option was set to false by default in their environment, but this is not a bug. Refer to [#3062 (comment)](https://github.com/openservicemesh/osm/issues/3062#issuecomment-812007007) for more details.
> > We have figured out the cause for this - the scraping was disabled by default in the Azmon test environment.
> 
      > > This is a bug with the AKS OSM addon. I will follow up with an internal tracking bug. Thanks Shashank.

**Comment by rashmichandrashekar** [comment]
> > > Discussed with @rashmichandrashekar , the scraping option was set to false by default in their environment, but this is not a bug. Refer to [#3062 (comment)](https://github.com/openservicemesh/osm/issues/3062#issuecomment-812007007) for more details.
> > > We have figured out the cause for this - the scraping was disabled by default in the Azmon test environment.
> 
> ```
> > > This is a bug with the AKS OSM addon. I will follow up with an internal tracking bug. Thanks Shashank.
> ```

**Comment by rashmichandrashekar** [comment]
> > > > Discussed with @rashmichandrashekar , the scraping option was set to false by default in their environment, but this is not a bug. Refer to [#3062 (comment)](https://github.com/openservicemesh/osm/issues/3062#issuecomment-812007007) for more details.
> > > > We have figured out the cause for this - the scraping was disabled by default in the Azmon test environment.
> > 
> > 
> > ```
> >  This is a bug with the AKS OSM addon. I will follow up with an internal tracking bug. Thanks Shashank.
> > ```
