### ISSUE TITLE
investigate smi-controller-sdk for osm project

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3063]
https://github.com/servicemeshinterface/smi-controller-sdk

This project is useful for seamless upgrades and for removing controller boilerplate code and relying on the sdk for that.

**Comment by draychev** [comment]
ref:  **SMI conversion webhook to upgrade to newer SMI API versions** #2737

**Comment by snehachhabria** [comment]
OSM currently has its own CRD converter that is capable of handling SMI CRD's also. Once the smi-controller-sdk is fully developed and ready for use we will revisit its use case for OSM
