### ISSUE TITLE
Consolidate metric/scrapping configuration

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#3065]
Currently, to enable metric/scrapping config there are two steps to be taken:

1 - Enable `prometheus_scrapping` flag. This one mandates opening the listener to listen to Prometheus envoy  port
on the pods, and allowing/proxying traffic through to the expected Prometheus endpoint on Envoy.
2 - Enable metrics on the namespace: This is done through CLI, and will:
  (1) add the label on the namespace, and 
  (2) walk the namespace pods to add the Prometheus scrapping annotations to them.
By having the the namespace labeled with metrics label, new pods to come up in the namespace will be already patched
with the scrapping annotation by injector automatically.

This two steps could be coalesced under a single configuration story, such as enabling metrics on a Namespace. OSM could take care of both adding prometheus annotations, as well as issuing new configurations for the envoys to allow prometheus queries through.
There is the consideration of allowing individual envoys be annotated without having namespaces-metrics enabled, to support use cases where only individual envoys want to be scrapped on a namespace.

- New Functionality          [X]
- Envoy Control Plane        [X]
- CLI Tool                   [X]
- Metrics                    [X]

**Comment by snehachhabria** [comment]
osm-docs repo needs to be updated with the relevant changes
