### ISSUE TITLE
Incorrect testing instruction

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3081]
**Bug description**:

By following the testing instruction, the tests failed on master branch. 

* `make go-test` described [here](https://github.com/openservicemesh/osm/blob/41ba71255a0b0955279ac4217a19ddfb1cdd2829/docs/content/docs/dev_guide/_index.md#makefile). The test fails during e2e test.
* `make e2e-test` described [here](https://github.com/openservicemesh/osm/blob/3d6ab6344064620098b51b78aadf5254f34e0c3d/tests/e2e/README.md#running-the-tests). 

The issue I encountered was 10m timeout:

```
[Tier 2][Bucket 1] Test HTTP traffic from 1 pod client -> 1 pod server before and after osm-controller restart SimpleClientServer traffic test involving osm-controller restart: HTTP
  Tests HTTP traffic for client pod -> server pod

...

STEP: Creating SMI policies
STEP: [WaitForRepeatedSuccess] waiting 1m30s for 5 iterations to succeed
> (client/client -> server.server) HTTP Req failed 0 Remote exec err: command terminated with exit code 7 | stderr:
> (client/client -> server.server) HTTP Req failed 0 Remote exec err: command terminated with exit code 7 | stderr:
panic: test timed out after 10m0s
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

* `make go-test` should pass all tests on master.
* `make test-e2e` should pass all e2e tests on master

**Steps to reproduce the bug (as precisely as possible)**:

On master branch, run:

* `make go-test`, OR
* `make test-e2e`, OR
* `go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus="\bfrom 1 pod client -> 1 pod server before and after osm-controller\b"`

It can be reproduced using both local kind cluster or remote k8s cluster.

**How was OSM installed?**:

OSM was built from source locally.

**Anything else we need to know?**:

I traced the testing code, and it enters [here](https://github.com/openservicemesh/osm/blob/75dbedb3dd3263ad83e82a42289b584d1a170fac/tests/e2e/e2e_controller_restart_test.go#L93) ends up [here](https://github.com/openservicemesh/osm/blob/9d02a1c46919011b6dcbce9f5ffe1a0d0f3a15ee/tests/framework/common.go#L1127).

The test actually runs `/usr/bin/curl -o /dev/null -s -D - -I -w StatusWCode:%{http_code} -L server.server` command from client container. [Reference](https://github.com/openservicemesh/osm/blob/99adb2b6626419bec00f2e48c86b701e508a71fa/tests/framework/common_traffic.go#L87) 

Thus I manually curl'ed from the `client` pod:

```
kc exec -n client client -c client -i -t -- sh

/ $ /usr/bin/curl -o /dev/null -s -D - -I -w StatusWCode:%{http_code} -L server.server
HTTP/1.1 200 OK
server: envoy
date: Sat, 03 Apr 2021 00:23:50 GMT
content-type: text/html; charset=utf-8
content-length: 9593
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 4

/ $ /usr/bin/curl -o /dev/null -s -D - -I -w StatusWCode:%{http_code} -L server.server -X POST
HTTP/1.1 405 Method Not Allowed
server: envoy
date: Sat, 03 Apr 2021 00:23:55 GMT
content-type: text/html
allow: GET, HEAD, OPTIONS
content-length: 178
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3
```

Note that the GET request passed and POST request failed.  I think this blocks the test

**Environment**:

__OSM version (use `osm version`)__

`Version: dev; Commit: ada5046163f22b384d0476f80b8c8bc58e791448; Date: 2021-04-02-15:25`

__Kubernetes version (use `kubectl version`)__

```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
``` 

__Size of cluster (number of worker nodes in the cluster):__

3 nodes

**Comment by shashankram** [comment]
@allenlsy assigning this one to you since you already have enough context to address this.

**Comment by allenlsy** [comment]
Not happening again as I tested now. I'm going to close the issue for now
