### ISSUE TITLE
Consistent aliasing of deckarep/golang-set import  (alias with mapset, and not set)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3083]
OSM uses `deckarep/golang-set` extensively.  In some cases the import is aliased to `set`, in most to`mapset`.

This GitHub issue is a request to convert all such imports from `set "github.com/deckarep/golang-set"` to `mapset "github.com/deckarep/golang-set"`

I started to fix this with https://github.com/openservicemesh/osm/pull/3073

I'd prefer we change these one file at a time to avoid larger thrashing of the code base and it would make it easier to review the PRs - one file at a time.

I recommend we make 6 PRs for the 6 files listed below.

For instance:
```bash
grep -Iir "deckarep" | grep -v mapset
```
shows that the following are not consistently aliased with `mapset`
```
pkg/envoy/route/route_config.go:        set "github.com/deckarep/golang-set"
pkg/envoy/route/rbac_test.go:   set "github.com/deckarep/golang-set"
pkg/envoy/route/route_config_test.go:   set "github.com/deckarep/golang-set"
pkg/trafficpolicy/trafficpolicy_test.go:        set "github.com/deckarep/golang-set"
pkg/trafficpolicy/trafficpolicy.go:     set "github.com/deckarep/golang-set"
pkg/trafficpolicy/types.go:     set "github.com/deckarep/golang-set"
```

**Comment by nshankar13** [comment]
PRs https://github.com/openservicemesh/osm/pull/3086, https://github.com/openservicemesh/osm/pull/3087, https://github.com/openservicemesh/osm/pull/3088, and https://github.com/openservicemesh/osm/pull/3089 have been merged. Waiting on approval for https://github.com/openservicemesh/osm/pull/3085

**Comment by draychev** [comment]
This tells me there's no `golang-set` not aliased with `mapset` (pardon the double negative)
```bash
grep -Iir "deckarep" $(find . -name '*.go') | grep -v mapset
```

Thank you @nshankar13 !
