### ISSUE TITLE
catalog: delete interface function ListMonitoredNamespaces()

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3084]
The `ListMonitoredNamespaces()` function in the MeshCatalog interface is not used anywhere.  Here is the definition and the 2 lines that can be deleted:  https://github.com/openservicemesh/osm/blob/main/pkg/catalog/types.go#L117-L118

This can be safely deleted. (`go vet ./...` tells me it is safe)

We should also update the catalog mock at `./pkg/catalog/mock_catalog_generated.go`

**Comment by shashankram** [comment]
`ListMonitoredNamespaces()` was added to be able to list the monitored namespaces in the debug server, however the work was not complete, so it didn't make it to the debug server.

Please evaluate if this should be exposed in the debug server prior to removing it.

**Comment by nshankar13** [comment]
We decided to implement ListMonitoredNamespaces instead of deleting it.

**Comment by draychev** [comment]
The `ListMonitoredNamespace()` is already required by [MeshCatalogerDebugger](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/debugger/types.go#L41-L56).
So we don't need it in [MeshCataloger](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L117-L118).
