### ISSUE TITLE
Intermittent failures in CI with config-map trigger tests. 

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3090]
**Bug description**: Config-map trigger tests in the CI intermittently fail with the following message: 

```
8:17PM ERR Error converting ConfigMap -test-osm-namespace-/-test-osm-config-map- key tracing_port with value true to integer error="strconv.Atoi: parsing \"true\": invalid syntax" component=configurator file=client.go:326

    client_test.go:271: 
        	Error Trace:	client_test.go:271
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	TestConfigMapEventTriggers

--- FAIL: TestConfigMapEventTriggers (2.51s)
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [ ]
- CI System                  [X]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by eduser25** [comment]
https://github.com/openservicemesh/osm/pull/3091

**Comment by shashankram** [comment]
This test failed again on HEAD of main branch:

[configurator-failure.txt](https://github.com/openservicemesh/osm/files/6299573/configurator-failure.txt)

**Comment by eduser25** [comment]
it's actually a different test:
```
2021-04-12T19:58:14.6295190Z 	/home/runner/work/osm/osm/pkg/configurator/methods_test.go:270 +0x1190
2021-04-12T19:58:14.6295911Z testing.tRunner(0xc000103680, 0x186a280)
```

Original bug was on a test on `client_test.go`, this is `methods_test.go`

**Comment by shashankram** [comment]
> it's actually a different test:
> 
> ```
> 2021-04-12T19:58:14.6295190Z 	/home/runner/work/osm/osm/pkg/configurator/methods_test.go:270 +0x1190
> 2021-04-12T19:58:14.6295911Z testing.tRunner(0xc000103680, 0x186a280)
> ```
> 
> Original bug was on a test on `client_test.go`, this is `methods_test.go`

Feel free to close this issue and open a new one, thanks.

**Comment by eduser25** [comment]
It's fine, I'll fix it here. Seems distantly related still.
