### ISSUE TITLE
RFC: Carve Proxy Registry out of Mesh Catalog interface (removes RegisterProxy, UnregisterProxy, ExpectProxy)

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3105]
The [MeshCataloger ](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L62) interface grew over time and has more methods than it theoretically needs to perform the function of a "catalog".

One such example are these 3 functions:

- [RegisterProxy](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L106)
- [UnregisterProxy](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L109)
- [ExpectProxy](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L100)
- [GetConnectedProxyCount](https://github.com/openservicemesh/osm/pull/3076/files#diff-1695ed5765b08f4366c290109026c6d6d3ce15b7a0fc0a5ad86b6646c92e81a7R118)

I propose we carve out the 3 functions into a new package and a new interface and remove these from MeshCataloger.
The goal:  Mesh Catalog should not be aware of any proxies coming and going (abstractly speaking).

---

### Prerequisites
 - [ ] We may need to first carve out `mc.releaseCertificateHandler()` into its own `ReleaseCertificateHandler()` -- see #3106 (perhaps we should do this in a PR - first, then tackle this here #3105)

---

### Details
This issue is to:
1. Create a new package - perhaps `pkg/envoy/registry` (just a suggestion) 
2. Create a new interface - perhaps `ProxyRegistrar` (perhaps in `types.go`)  (name is just a suggestion - whatever works best)
3. Move [the 3 functions](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/proxy.go#L12-L48) out of `pkg/catalog/proxy.go` and into (maybe) `pkg/envoy/registry/registry.go`
4. The new interface may look like this:
```go
type ProxyRegistrar interface {
	RegisterProxy(*envoy.Proxy)
	UnregisterProxy(*envoy.Proxy)
	ExpectProxy(certificate.CommonName)
}
```
5. We'll need a new struct in `pkg/envoy/registry/types`.  I believe this would need the `podUID...` sync maps too:
```go
type ProxyRegistry struct {
	expectedProxies     sync.Map
	connectedProxies    sync.Map
	disconnectedProxies sync.Map
	podUIDToCN sync.Map
	podUIDToCertificateSerialNumber sync.Map
}
```
6. We will need to move [expectedProxy, connectedProxy, disconnectedProxy](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/types.go#L133-L148) structs out of `pkg/catalog/types.go` and into `pkg/registry/types.go` (or whatever the new package name is)
7. It might be nice to create `NewProxyRegistry`:
```go
func NewProxyRegistry() ProxyRegistrar {
	return &ProxyRegistry{}
}
```
8. in `osm-controller.go` somewhere around `catalog.NewMeshCatalog()` we could also create `proxyRegistry := registry.NewProxyRegistry()` 
9. We are going to have to regenerate mocks
10. More importantly - we will need to pass the new `proxyRegistry` and use it instead of `meshCatalog` in order to register/unregister proxies. For example [receive()](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/ads/grpc.go).  I propose we pass `proxyRegistry` as a param to `receive(proxyRegistry)`, which may no longer need `meshCatalog` any more.
11. To pass it to `receive()` we need to change [stream.go](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/ads/stream.go#L54) -- we will most likely need to add proxy registry to the [ads.Server](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/ads/types.go) struct.

12. And for the proxyRegistry to endup in `ads.Server{}` we'll need to tweak [ads.NewADSServer()](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/ads/server.go#L26-L44) and initialize it there (perhaps):
```go
func NewADSServer(meshCatalog catalog.MeshCataloger, enableDebug bool, osmNamespace string, cfg configurator.Configurator, certManager certificate.Manager) *Server {
	server := Server{
                .....
		proxyRegistry: registry.NewProxyRegistry(),
	}

	return &server
}
```

**Comment by draychev** [comment]
Another small cleanup of the MeshCataloger interface:
  - **Removing ListSMIPolicies() and ListMonitoredNamespaces() from MeshCataloger interface** #3109

**Comment by draychev** [comment]
#3076 adds `GetConnectedProxyCount` to the `MeshCataloger` interface, which can also be moved

**Comment by eduser25** [comment]
I will add to think of the necessary APIs or package interactions for this package to be usable as part of mesh config computation in the long run.
If the day of tomorrow we need to update a number of proxies associated to a service, we should be able to figure out the proxies related to that service easily and efficiently, without incurring in linear costs per proxy, just because of the way the packages decided to expose their APIs.

I don't have a proposal, but whatever we think should contemplate this use case if the proxy store is to be moved out from catalog.
