### ISSUE TITLE
catalog: Rename GetServicesFromEnvoyCertificate to GetServicesForProxy

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3117]
The [following line](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/rds/response.go#L26-L31) strikes me as not very easy to comprehend what it does and why it does it:
```go
services, err := cataloger.GetServicesFromEnvoyCertificate(proxy.GetCertificateCommonName())
```

I believe the readability would be much increased if this was
```go
svcList, err := meshCatalog.GetServicesForProxy(proxy)
```

---

To increase readability I propose we rename [GetServicesFromEnvoyCertificate](https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/catalog/xds_certificates.go#L19) to `GetServicesForProxy()`
and also change the signature of the function
### from:
```go
func (mc *MeshCatalog) GetServicesFromEnvoyCertificate(cn certificate.CommonName) ([]service.MeshService, error) {
```

### to:
(update: changed w/ @eduser25's proposal to use *Proxy)
```go
func (mc *MeshCatalog) GetServicesForProxy(p *Proxy) ([]service.MeshService, error) {
```
so passing the proxy, not the certificate's CN.

**Comment by eduser25** [comment]
arrived at this point,, why not
```go
func (mc *MeshCatalog) GetServicesForProxy(p *Proxy) ([]service.MeshService, error)
```
