### ISSUE TITLE
Envoy validation fails when method/path is not specified by user in Traffic Spec

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3128]
**Bug description**:

I modified the demo to remove the host header from the traffic  spec for bookwarehouse : https://github.com/openservicemesh/osm/blob/71b619c6ccedc6701f235a060786371d9a4b422a/demo/deploy-traffic-specs.sh#L47

This resulted in OSM demo failing and the following error message was observed on the osm controller pod : 
`DiscoveryRequest error from Envoy with xDS Certificate SerialNumber=39662084927345886212652764406508667970 on Pod with UID=59856b4d-ad9b-477d-a105-86cc4ac1841d: code:13 message:\"Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[i]: [\\\"embedded message failed validation\\\"] | caused by VirtualHostValidationError.Routes[i]: [\\\"embedded message failed validation\\\"] | caused by RouteValidationError.Match: [\\\"embedded message failed validation\\\"] | caused by RouteMatchValidationError.SafeRegex: [\\\"embedded message failed validation\\\"] | caused by RegexMatcherValidationError.Regex: [\\\"value length must be at least \\\" '\\\\x01' \\\" runes\\\"]): name: \\\"rds-inbound\\\"\\nvirtual_hosts {\\n  name: \\\"inbound_virtual-host|bookwarehouse.bookwarehouse\\\"\\n  domains: \\\"bookwarehouse\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc.cluster\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc.cluster.local\\\"\\n  domains: \\\"bookwarehouse:14001\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse:14001\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc:14001\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc.cluster:14001\\\"\\n  domains: \\\"bookwarehouse.bookwarehouse.svc.cluster.local:14001\\\"\\n  routes {\\n    match {\\n      headers {\\n        name: \\\":method\\\"\\n        safe_regex_match {\\n          google_re2 {\\n          }\\n          regex: \\\"POST\\\"\\n        }\\n      }\\n      safe_regex {\\n        google_re2 {\\n        }\\n      }\\n    }\\n    route {\\n      weighted_clusters {\\n        clusters {\\n          name: \\\"bookwarehouse/bookwarehouse-local\\\"\\n          weight {\\n            value: 100\\n          }\\n        }\\n        total_weight {\\n          value: 100\\n        }\\n      }\\n    }\\n    typed_per_filter_config {\\n      key: \\\"envoy.filters.http.rbac\\\"\\n      value {\\n        [type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute] {\\n          rbac {\\n            rules {\\n              policies {\\n                key: \\\"rbac-for-route\\\"\\n                value {\\n                  permissions {\\n                    any: true\\n                  }\\n                  principals {\\n                    or_ids {\\n                      ids {\\n                        authenticated {\\n                          principal_name {\\n                            exact: \\\"bookstore-v1.bookstore.cluster.local\\\"\\n                          }\\n                        }\\n                      }\\n                    }\\n                  }\\n                  principals {\\n                    or_ids {\\n                      ids {\\n                        authenticated {\\n                          principal_name {\\n                            exact: \\\"bookstore-v2.bookstore.cluster.local\\\"\\n                          }\\n                        }\\n                      }\\n                    }\\n                  }\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\\nvalidate_clusters {\\n}\\n\""}`

There is no path specified in the spec  and hence no path is build in the route configuration and envoy rejects the config. 

We weren't hitting this error so far because we had a header field in the spec and per the SMI documentation ( https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-specs/v1alpha4/traffic-specs.md#http-header-filters)

![image](https://user-images.githubusercontent.com/59101963/114252640-2ebacd80-995b-11eb-840c-aab2873762e3.png)
 we were wildcarding this (as the header was provided)

https://github.com/openservicemesh/osm/blob/71b619c6ccedc6701f235a060786371d9a4b422a/pkg/catalog/inbound_traffic_policies.go#L206

Users will face issues when they specify only a path or method and no header in OSM. My proposal is that when neither method or path is provided, we wildcard it to avoid envoy config errors

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [X]
- SMI Traffic Specs Policy   [X]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  []
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Envoy configuration should not error out and we program it with defaults 

**Steps to reproduce the bug (as precisely as possible)**: Run the demo as is and modify https://github.com/openservicemesh/osm/blob/main/demo/deploy-traffic-specs.sh to remove the host field from the `bookwarehouse-service-routes` HTTPRouteFroup resource

**How was OSM installed?**: 
Installed via the demo script 

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): Version: dev; Commit: 7caf6427bc83669e73c1986a0ff110c1af950502; Date: 2021-04-09-17:10
- Kubernetes version (use `kubectl version`): 1.18.14
- Size of cluster (number of worker nodes in the cluster): 
- Others:

**Comment by michelleN** [comment]
>Users will face issues when they specify only a path or method and no header in OSM. My proposal is that when neither method or path is provided, we wildcard it to avoid envoy config errors

Is an `HTTPRouteGroup` valid is there is not method or path provided? At the moment, it is valid. I think at an SMI level, it should not be valid. If we change this in SMI, then we can add validation to the HTTPRouteGroup to ensure it always has a path or method. If we did that, would it help with this issue? Also, what other bits would be left to figure out?

**Comment by snehachhabria** [comment]
@michelleN yes that's right not specifying a path/method or header is valid according to SMI. I am not sure if imposing a validation at SMI level is required as these fields can be optional, what we will need to determine is if either one isn't provided what the default should be. This could be determined at SMI level or could be something that a service mesh (e.g: OSM ) can specify.

We can definitely discuss this is an SMI call, until then I would recommend that we have a default for OSM when nothing is specified for either path or method (allow all). We can document this until a resolution is found at SMI level.

**Comment by michelleN** [comment]
sgtm
