### ISSUE TITLE
Cut release v0.8.3

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3133]
We plan to cut a new release v0.8.3 in OSM, this issue is used to track the release process and the changes that will be a part of this release. 

The changes that will be a part of this release are : 
1.  Update Envoy image to v1.17.2 (PR in OSM pending, issue : https://github.com/openservicemesh/osm/issues/3134)
2.  https://github.com/openservicemesh/osm/pull/2824
3. https://github.com/openservicemesh/osm/pull/3022 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [X]

**Possible use cases**

**Comment by bridgetkromhout** [comment]
Request: can the v0.8.3 release team closely follow https://github.com/openservicemesh/osm/blob/main/docs/content/docs/release_guide.md for the release, and PR in any updates if you see something is missing? Thanks!

**Comment by SanyaKochhar** [comment]
Please cherry-pick this commit for v0.8.3: https://github.com/openservicemesh/osm/commit/e3d44e130a2c6f4cf4d4bdcd105a95e008e7498a
It will help with ongoing logging work

**Comment by snehachhabria** [comment]
@SanyaKochhar that is a very big change, could it wait for milestone 0.9 ? It would be good if we can primarily scope 0.8.3 just for the envoy update. I will sync with you offline on this
