### ISSUE TITLE
dispatcher: isDeltaUpdate needs more robust implementation

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3162]
As of release-v0.8 `isDeltaUpdate` in `pkg/catalog/dispatcher` matches events String representation on "updated" suffix. This is fragile and may result in unintended side effects

This GitHub issue is for designing a more robust way to understand whether an event is an update.

https://github.com/openservicemesh/osm/blob/776a8756bf1825701fb0469d71251a114956c681/pkg/catalog/dispatcher.go#L22-L25

We should also break up the Boolean logic into a few steps (I can see 3) so that it is easier for humans reading this code to understand what it does and why.

**Comment by mudit-01** [comment]
I would like to work on it

**Comment by shashankram** [comment]
I am closing this one since the dispatcher will be reworked as a part of https://github.com/openservicemesh/osm/issues/4167.
@mudit-01 Please let us know if there's another issue that interests you.
