### ISSUE TITLE
certificates: Envoy xDS Certs should have a ServiceIdentity in the CN; not ServiceAccount

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3186]
From a comment/proposal @shashankram made on https://github.com/openservicemesh/osm/pull/3170#pullrequestreview-637876445:

***Directly retrieve the ServiceIdentity from the proxy XDS cert.**

This issue is to treat the Envoi xDS certificate's CN as a ServiceIdentity, not specifically Kubernetes Service Account.  In reality the xDS Cert CN would still be derived from a Kubernetes Service Account, but this is merely an implementation detail.

**Comment by draychev** [comment]
Another thought - we may need to create `EndpointIdentity` and have that be different that `ServiceIdentity`

So xDS certificate --> `EndpointIdentity`
Service certificate --> `ServiceIdentity`

**Comment by shashankram** [comment]
> Another thought - we may need to create `EndpointIdentity` and have that be different that `ServiceIdentity`
> 
> So xDS certificate --> `EndpointIdentity` (or `ProxyIdentity`)
> Service certificate --> `ServiceIdentity`

As it stands today, both XDS cert and workload certs are based on `service-account.namespace`. The only additional info in the XDS cert is the proxy metadata (Proxy UUID, Kind). 

I am inclined to keep this simple:
- XDS cert: `proxy-uuid.kind.svc-account.namespace.cluster.local`
- Client/Service certs: `svc-account.namespace.cluster.local`

This will allow the controller to correctly assign service identities that could be derived from the XDS cert.

**Comment by shashankram** [comment]
Resolved by https://github.com/openservicemesh/osm/pull/3657
