### ISSUE TITLE
Integrate SMI with Service Mesh Performance (SMP) tool

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3195]
**Please describe the Improvement and/or Feature Request**
Integrate OSM with SMP tool https://layer5.io/projects/service-mesh-performance

**Scope (please mark with X where applicable)**
- New Functionality          [X ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X ]
- CI System                  [ X]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Leverage SMP to measure performance of OSM in a way that is standard to the service mesh ecosystem.

**Comment by johnsonshi** [comment]
I'll try to integrate OSM with SMP.

**Comment by snehachhabria** [comment]
@johnsonshi is you are no longer working on this issue please unassign yourself
