### ISSUE TITLE
Investigate Grafana licensing changes understand implications

### ISSUE THREAD

**Issue by lachie83** [openservicemesh/osm#3208]
Grafana has changed license from Apache v2.0 to Affero General Public License (AGPL) v3. We'll need to check how our usage and dashboards are effected if at all.

ref - https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/

**Comment by draychev** [comment]
JSON file: https://github.com/openservicemesh/osm/blob/707593c3a291ec9ac4a3e92836d8776cb3d84ce3/charts/osm/grafana/dashboards/osm-mesh-envoy-details.json

Template: https://github.com/openservicemesh/osm/blob/707593c3a291ec9ac4a3e92836d8776cb3d84ce3/charts/osm/templates/grafana-deployment.yaml

**Comment by lachie83** [comment]
CNCF - allowed 3rd party licensing policy - https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md

**Comment by phillipgibson** [comment]
If I'm following the new license as long as we do not modify upstream it is similar to the GNU GP license. Ref links below

https://www.gnu.org/licenses/why-affero-gpl.en.html
http://gnugpl.org/

**Comment by phillipgibson** [comment]
From research, as long as there's no modification to the Grafana code base, the new licensing does not affect us. Ref https://grafana.com/blog/2021/04/20/qa-with-our-ceo-on-relicensing/ .

**Comment by phillipgibson** [comment]
Will go ahead and close this issue. From the ref link - https://grafana.com/blog/2021/04/20/qa-with-our-ceo-on-relicensing/ it states "Unmodified distributions are not affected. AGPL does not prevent customers from shipping Grafana as long as they follow the terms of the license. In the case of Openshift and CloudFoundry, that source is already open, so there is no issue."
