### ISSUE TITLE
Make Envoy AuthN filter configurable

### ISSUE THREAD

**Issue by Pindar** [openservicemesh/osm#3213]
**Please describe the Improvement and/or Feature Request**

Envoyproxy already contains the functionality to integrate 3rd party authentication provider.  From my point of view it would be helpful if this functionality is also made accessible as a configuration via OSM.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [X]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
Vielen Dank @Pindar! Wir werden dies prototypisieren. Ich werde diese Aufgabe aktualisieren, wenn ich fertig bin. 

### Andere ähnliche Aufgaben:
- OSM: [**Integrate OSM with OPA envoy plugin** #1874](https://github.com/openservicemesh/osm/issues/1874)
- SMI: [**Support custom authorization filter to allow delegating authorization logic to a third party component** #213](https://github.com/servicemeshinterface/smi-spec/issues/213)

**Comment by Pindar** [comment]
Thank you for your reply in German 😊 — I translated my question.

**Comment by draychev** [comment]
> Thank you for your reply in German 😊 — I translated my question.

Hey, I am sorry you felt like you had to translate it! I was excited to see a GitHub Issue in what appeared to be German!

**Comment by draychev** [comment]
Hi @Pindar, have you had a chance to try this?
Take a look at how -- https://github.com/openservicemesh/osm/issues/1874#issuecomment-837406810
Would love to get your feedback on this.
