### ISSUE TITLE
Update the status of the MeshConfig CRD w/ relevant info

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3217]
This is a GitHub issue to remind us to think about relevant information we can update the MeshConfig's Status field with.

---

### Related
  - Update SMI policy's status field w/ errors OSM may have found #3218

**Comment by snehachhabria** [comment]
We would not need a status field; we can add validations on the crd itself and if there's an error the custom resource won't get saved. Users will get an interactive error message.
