### ISSUE TITLE
[Dead code] Remove references to synthetic cluster code 

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3240]
**Please describe the Improvement and/or Feature Request**
Remove references to synthetic cluster which is no longer required or used.

https://github.com/openservicemesh/osm/search?q=getSyntheticCluster

**Comment by adithyaakrishna** [comment]
@shashankram Should I remove the lines marked in the image below?
![image](https://user-images.githubusercontent.com/23498248/116352468-d61c7900-a812-11eb-81cd-f8fba5532ebd.png)

**Comment by shashankram** [comment]
Hey @adithyaakrishna, yes those lines and also the associated functions `getSyntheticCluster` and corresponding tests. I'll assign this one to you, thanks

**Comment by adithyaakrishna** [comment]
Okay Sure :)
