### ISSUE TITLE
Provide custom expiration for the internal OSM CA / root cert

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3241]
This GitHub issue is to make it so the TTL of root cert created by OSM can be configured with an option.

# Why we need this?
This is coming as feedback from folks experimenting with OSM. Current TTL of root cert is hard-coded to a decade. This should be made configurable. 

# How
- [ ] Create a tiny proposal for how this could be implemented (should this be an OSM Controller `--argument` or a ConfigMap key?
- [ ] Implement

---

This task is part of a bigger story around Root Cert rotation:
- [ ] [Root Cert Rotation Story #1260](https://github.com/openservicemesh/osm/issues/1260)

---

Similar issues:
- [ ] [Make certificate key bit size configurable #1933](https://github.com/openservicemesh/osm/issues/1933)

**Comment by snehachhabria** [comment]
closing this we will be creating/tracking a new issue for certificate rotation
