### ISSUE TITLE
Explore the feasibility of OSM solely relying on xDS connected Envoys for Endpoint Discovery

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3244]
This GitHub issue is a request to explore whether it is feasible to implement an Endpoint discovery mechanism, which solely relies on Envoy proxies connected to the OSM Control Plane.

Current OSM (`release-v0.8`) relies on Endpoint and Pod informers to create an `Endpoint Provider`.  The https://github.com/openservicemesh/osm/blob/6fa4a5791cd70ec5eb2f0abaa0c09b7993c2fd34/DESIGN.md file shows how there could be many Endpoint providers within one OSM Controller.

![image](https://user-images.githubusercontent.com/49918230/116316638-19211280-a767-11eb-8dff-0b5aceedcfde.png)

The question this GitHub issue asks:  Is it feasible to have **one** endpoint provider, which only looks at xDS mTLS gRPC connections.

This would happen in `pkg/envoy/ads/stream.go` here: https://github.com/openservicemesh/osm/blob/6fa4a5791cd70ec5eb2f0abaa0c09b7993c2fd34/pkg/envoy/ads/stream.go#L42

---

Caveats: Currently we encode a UUID, Kubernetes Service Account and Namespace in the CN of the Certificate of an Envoy connecting to xDS: https://github.com/openservicemesh/osm/blob/b133a15a29800dd600cb1c9441caa15f6bc4f426/pkg/catalog/xds_certificates.go#L163-L166

At some point we need to know what Kubernetes Services this Pod belongs to, and that is a Kubernetes specific implementation, for which we still have to rely on listing Pods from the Kubernetes cluster the pod is on.

Another caveat: an Envoy disconnected from xDS may still be an Envoy that is capable of participating in the mesh.

---

# WHY?
We are exploring this to understand whether it is possible to simplify the endpoint discovery design. Having a single `Endpoint Provider` would simplify the design and implementation of OSM.

**Comment by draychev** [comment]
A small next step:  #3272

**Comment by draychev** [comment]
@eduser25 You have been thinking long and hard about event-driven pre-computation of state.  Would you be so kind to work with @nojnhuh on #3273, when time comes. This will leverage much of your designs, where instead of composing data structures on demand (configs demand by Envoys) we will pre-compute these structs ahead of time on arrival of Kubernetes event.

**Comment by eduser25** [comment]
Context: https://github.com/envoyproxy/go-control-plane/issues/399

**Comment by nojnhuh** [comment]
I took a look at this but never found a way to do this without relying on Kubernetes resources. I'm not planning to look into this anymore in the near future.
