### ISSUE TITLE
Add support for outbound port exclusion at per pod level 

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3251]
**Please describe the Improvement and/or Feature Request**
Create an annotation for pods `openservicemesh.io/outbound-port-exclusion=<port number>` such that if mesh joined pod annotated with this, would prevent any outbound traffic (with the specified port number) from being redirected and routed by the envoy proxy.

This would be an extension of the feature mentioned in issue #3249, restricting the exclusion to a pod rather than a global level (i.e. all pods in the mesh). This would be beneficial for integration with Dapr #2875 

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
This Github Issue is a quick follow up to #3249
