### ISSUE TITLE
Implement adding of tolerations to OSM deployments

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3253]
This GitHub Issue is to provide a way to customize the OSM Deployments (controller and injector) so that we can add custom tolerations.

This comes in handy when some k8s nodes have taints and the injector and controller need to tolerate these. 

Context: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by shashankram** [comment]
Needs documentation.

**Comment by shashankram** [comment]
> Needs documentation.

Already documented in `charts/osm/README.md`.
