### ISSUE TITLE
Event-driven Pre-computation of Services per Envoy/Pod

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3273]
With #3272 we moved https://github.com/openservicemesh/osm/blob/b133a15a29800dd600cb1c9441caa15f6bc4f426/pkg/catalog/xds_certificates.go#L21 from `MeshCataloger` interface into `ProxyRegistry`.

This function still relies on listing Pods and Services to output the `[]MeshService{}`.
This is done on-demand.
Another alternative is to explore @eduser25's proposal to have this list pre-computed. This precomputation would be triggered on events arriving from the Kubernetes system, informing us of changes to the the given Pod.

- [ ] Create a new field `[]MeshService` for the `Proxy{}` struct
- [ ] Create a way / function that updates the `[]MeshService{}` for a particular proxy
- [ ] We would need to create a new goroutine in ProxyRegistry (most likely), which subscribes to PubSub or Kubernetes Events
- [ ] When an event arrives for a Pod registered in ProxyRegistry - perhaps call `GetServicesForProxy()` on the given Proxy and update/cache the results.
- [ ] Schedule a new re-broadcast

---

This is where we watch for Pod changes: https://github.com/openservicemesh/osm/blob/0e9429bb9c44bb6b026719d895449e534c66a1ad/pkg/kubernetes/client.go#L37
This is where we transfer the Kubernetes event into the OSM pub/sub: https://github.com/openservicemesh/osm/blob/0e9429bb9c44bb6b026719d895449e534c66a1ad/pkg/catalog/dispatcher.go#L35
This eventually results in a re-broadcast to all proxies: https://github.com/openservicemesh/osm/blob/0e9429bb9c44bb6b026719d895449e534c66a1ad/pkg/catalog/dispatcher.go#L82

**Comment by eduser25** [comment]
My $0.02:
@draychev I think this is a step on the right direction but we have the wrong foundation.

Having `GetServicesForProxy` precomputed to go from Proxy->Services is great (4real), but I'm fairly confident that going from Service->Proxy will certainly be beneficial in the long run (ie, for a given change/update on a Service, list which proxies does it affect). Implementing this relation on a foreign/proxy package doesn't feel right knowing that if we want the opposite relation, some other module elsewhere will have to repeat the exact same code and process of linking them backwards.

When I initially warned about moving proxies out of catalog was to precisely avoid this situation, specially if we were advancing towards this direction.

If both proxies and services were to have a shared space (DM-like) where a central module (Catalog) can listen to events and relate these together, would avoid a lot of repeated and scattered code across individual modules.
I think you will also see this is also just one API of many that would benefit of this work model; as more APIs can be precomputed, it will be nonviable to keep pubsub listeners spread throughout our modules just to serve cherry-picked relations (apart from the complete lack of synchronization between those). 

Lmk what you think
