### ISSUE TITLE
Manual Demo not functioning as expected

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3300]
I have followed the steps for the manual demo till below link: -
https://github.com/openservicemesh/osm/blob/136d902c61b6c0fc2d4eb98215fe3aff0d0e73f7/docs/content/docs/install/manual_demo/_index.md#deploy-smi-access-control-policies

and after applying the SMI Traffic Target and SMI Traffic Specs the counters are not incrementing for bookbuyer and bookstore.
Is there any process to debug it?

**Comment by jaellio** [comment]
Hi @mudit-01!

I am unable to reproduce the bug you are experiencing by running through the manual demo myself.

My environment for testing:
- kind v0.10.0 go1.15.7 linux/amd64
- kubectl  v1.21.0
- osm Version: v0.8.3; Commit: 6fa4a5791cd70ec5eb2f0abaa0c09b7993c2fd34; Date: 2021-04-20-21:44

Could you please provide the following information?
- environment (cluster type/ kubectl version/ osm version/ system)
- output of  `kubectl describe traffictargets.access.smi-spec.io -n bookstore`
- output of  `kubectl describe httproutegroups.specs.smi-spec.io -n bookstore`
- output of `kubectl get pods -A`

Thank you!

**Comment by mudit-01** [comment]
Hi @jaellio 
I am using minkube for k8s 
😄  minikube v1.3.1 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=50000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"

I am testing at OSM version  8

I am getting this error now: 
kubectl get meshconfig osm-mesh-config -n osm-system -o jsonpath='{.spec.traffic.enablePermissiveTrafficPolicyMode}{"\n"}'
error: the server doesn't have a resource type "meshconfig"

Anything I am missing?

**Comment by shashankram** [comment]
> Hi @jaellio
> I am using minkube for k8s
> 😄 minikube v1.3.1 on Ubuntu 18.04
> 🔥 Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=50000MB) ...
> 🐳 Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
> 🚜 Pulling images ...
> 🚀 Launching Kubernetes ...
> ⌛ Waiting for: apiserver proxy etcd scheduler controller dns
> 🏄 Done! kubectl is now configured to use "minikube"
> 
> I am testing at OSM version 8
> 
> I am getting this error now:
> kubectl get meshconfig osm-mesh-config -n osm-system -o jsonpath='{.spec.traffic.enablePermissiveTrafficPolicyMode}{"\n"}'
> error: the server doesn't have a resource type "meshconfig"
> 
> Anything I am missing?

Since you are using version v0.8.x, you should also be referring to the manual demo guide from the v0.8 version of the documentation at https://release-v0-8.docs.openservicemesh.io/.

It seems like the documentation you are referring to is the latest (not v0.8).

You can retrieve versioned documentation from the docs website using the version dropdown:
![image](https://user-images.githubusercontent.com/21697719/119860566-4e866080-becb-11eb-85db-a5b82d2d8720.png)

**Comment by mudit-01** [comment]
@shashankram I used the new docs and updated minikube to use latest k8s still getting same error. Please guide if any other doc to refer?

```
kubectl get meshconfig osm-mesh-config -n osm-system -o jsonpath='{.spec.traffic.enablePermissiveTrafficPolicyMode}{"\n"}'
error: the server doesn't have a resource type "meshconfig"
```

**Comment by shashankram** [comment]
> @shashankram I used the new docs and updated minikube to use latest k8s still getting same error. Please guide if any other doc to refer?
> 
> ```
> kubectl get meshconfig osm-mesh-config -n osm-system -o jsonpath='{.spec.traffic.enablePermissiveTrafficPolicyMode}{"\n"}'
> error: the server doesn't have a resource type "meshconfig"
> ```

@mudit-01 If you are using v0.8, you need to refer to the corresponding documentation at https://release-v0-8.docs.openservicemesh.io/docs/install/manual_demo/

The command posted above is from documentation not meant for v0.8, but the `main` branch.
