### ISSUE TITLE
Create a unit test for recordEnvoyPodMetadata in pkg/envoy/ads/grpc.go

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3363]
With #3354 we added a check to `recordEnvoyPodMetadata` in pkg/envoy/ads/grpc.go

The function is not tested and needs a unit test - including one for the comparison of the Service Account in NodeID and xDS Certificate's Common Name.

**Comment by johnsonkarina11** [comment]
Hello

**Comment by draychev** [comment]
recordEnvoyPodMetadata no longer exists
