### ISSUE TITLE
Ensure CLI references compatible images

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#3371]
## Problem

Currently, the `main` branch references the latest tagged version for the default images used by the OSM chart (and therefore `osm install`):
https://github.com/openservicemesh/osm/blob/3fde0f12166148558c14bc5f1e05a16593954c68/charts/osm/values.yaml#L14

This causes version skew when the `main` branch is updated but the default image tag stays the same. This becomes an issue when following documentation corresponding to the `main` branch which refers to new features since the last release and instructions use `osm install` without overriding the images to images newer than the latest release that implement those features.

## Goal

The goal is to come up with a solution such that `make build-osm && bin/osm install` "just works" in all cases.

To do this, `make build-osm` would have to become dependent on building and pushing the images used by the control plane, then the CLI would refer to those images by default. The image tag must be unique to maintain a 1:1 mapping of CLI to images.

## Solution
Here's one possible implementation I can think of:

1. list `docker-push-{init,init-osm-controller,osm-controller,osm-injector}` as dependencies of `build-osm` in the Makefile:
    https://github.com/openservicemesh/osm/blob/b14458f9dd15d2a967e1ef8e4a0a0317ba753a6b/Makefile#L108
    - Ensure the `CTR_TAG` is set to some deterministic value. The current Git SHA might be close enough, though ideally it would differentiate between dirty and clean worktrees. `CTR_REGISTRY` can be set to 
2. create new package-scoped variables (likely in cmd/cli/install.go) for the tag and registry location of the built images and pass the values to them in the Makefile using the same method as we do for version info:
    https://github.com/openservicemesh/osm/blob/3fde0f12166148558c14bc5f1e05a16593954c68/Makefile#L21
3. In the install command, if `OpenServiceMesh.image.registry` or `OpenServiceMesh.image.tag` are not overridden via `--set`, override them with the values of the package-scoped variables defined above. This could be done in this function:
    https://github.com/openservicemesh/osm/blob/3fde0f12166148558c14bc5f1e05a16593954c68/cmd/cli/install.go#L154

    This would still allow users to override the images the standard way per-`osm install` invocation.

## Other things I haven't fully thought through yet
- Installing with `helm` instead of `osm`
- images stored in password-protected registries
- Upgrades
- Release builds and maintenance

/cc @shashankram

**Comment by nojnhuh** [comment]
I opened a draft PR implementing this idea that should be ready to try out: #3380

**Comment by shashankram** [comment]
Discussed offline with @nojnhuh and there isn't an immediate need for this as the default image tags in `main` refer to `latest-main`.
