### ISSUE TITLE
OSM Controller fatals on missing ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3373]
Summary: I don't think OSM Controller should fatal if the ValidatingWebhookConfiguration is missing here:  https://github.com/openservicemesh/osm/blob/3d923b3f2d72006f6cdaad056938c492c364196d/cmd/osm-controller/osm-controller.go#L207-L209
The OSM Controller will be able to continue to function even without this.

---

I fought with ValidatingWebhookConfiguration osm-webhook-osm and ended up deleting it.
Then restarted the OSM Controller. The new OSM Controller errored out.

Here are the OSM Controller log lines:
```json
{
  "level": "info",
  "component": "configurator",
  "time": "2021-05-18T22:57:07Z",
  "file": "validating_webhook.go:127",
  "message": "Starting configmap webhook server on port: 9093"
}
{
  "level": "error",
  "component": "configurator",
  "error": "validatingwebhookconfigurations.admissionregistration.k8s.io \"osm-webhook-osm\" not found",
  "time": "2021-05-18T22:57:07Z",
  "file": "validating_webhook.go:354",
  "message": "Error getting ValidatingWebhookConfiguration osm-webhook-osm; Will not update CA Bundle for webhook"
}
{
  "level": "error",
  "component": "configurator",
  "error": "validatingwebhookconfigurations.admissionregistration.k8s.io \"osm-webhook-osm\" not found",
  "time": "2021-05-18T22:57:07Z",
  "file": "validating_webhook.go:108",
  "message": "Error configuring ValidatingWebhookConfiguration osm-webhook-osm"
}
{
  "level": "fatal",
  "component": "kube-events",
  "error": "validatingwebhookconfigurations.admissionregistration.k8s.io \"osm-webhook-osm\" not found",
  "reason": "FatalInitializationError",
  "time": "2021-05-18T22:57:07Z",
  "file": "events.go:138",
  "message": "Error creating osm-config validating webhook"
}
```

I don't think an error in fetching the ValidatingWebhook should be a fatal error:  https://github.com/openservicemesh/osm/blob/3d923b3f2d72006f6cdaad056938c492c364196d/cmd/osm-controller/osm-controller.go#L209

---

# Fix
### Recreate
Recreate the ValidatingWehook with the script below
```bash
kubectl apply -f - <<EOF
 apiVersion: admissionregistration.k8s.io/v1
 kind: ValidatingWebhookConfiguration

 metadata:
   labels:
     app: osm-controller
   name: osm-webhook-osm

 webhooks:
 - admissionReviewVersions:
   - v1beta1
   clientConfig:
     service:
       name: osm-config-validator
       namespace: osm-system
       path: /validate-webhook
       port: 9093
   failurePolicy: Fail
   matchPolicy: Exact
   name: osm-config-webhook.k8s.io
   namespaceSelector:
     matchExpressions:
     - key: control-plane
       operator: DoesNotExist
     matchLabels:
       name: osm-system
   rules:
   - apiGroups:
     - ""
     apiVersions:
     - v1
     operations:
     - UPDATE
     resources:
     - configmaps
     scope: '*'
   sideEffects: None
   timeoutSeconds: 30
EOF
```

### Restart
Restart the OSM Controller, which will then find the new ValidatingWebhookConfigurationd, will update the CA bundle and will continue to run.
```bash
kubectl rollout restart deployment -n osm-system osm-controller
```

---
I know that we are removing the ConfigMap and changing how this work - filing this but will close it when the ValidatingWebhook is out of the repo completely.

**Comment by helayoty** [comment]
I'm looking into this issue and willing to pick it up

**Comment by helayoty** [comment]
@draychev I'm not able to find the mentioned fatal error within lines 207-209 or in the osm-controller. It seems that already removed from the main branch. Would you please confirm?

**Comment by shashankram** [comment]
> @draychev I'm not able to find the mentioned fatal error within lines 207-209 or in the osm-controller. It seems that already removed from the main branch. Would you please confirm?

The validating webhook used for osm-config ConfigMap validation is no longer used and initialized in osm-controller. The validating webhook code will be removed from the codebase soon. 

Closing this issue since it's a no-op.
