### ISSUE TITLE
(root) High availability for OSM control plane

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3390]
**Please describe the Improvement and/or Feature Request**
Provide high availability functionality for the OSM control plane. Make it configurable for use in vendor environments.

Investigate:
1. Replicas
2. Disruption budgets
3. Auto scaler
4. Affinity/anti-affinity rules for nodes deployed across availability zones
5. Availability provided by the multicluster feature 

**Scope (please mark with X where applicable)**
- New Functionality          [X]

**Possible use cases**
To make the control plane highly available.

**Comment by draychev** [comment]
First iteration of OSM HA is complete.
Will continue to test and evaluate additional HA features as we move forward.
