### ISSUE TITLE
Tests: add tests for pkg/catalog build outbound policies

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3406]
**Please describe the Improvement and/or Feature Request**

Add test cases for pkg/catalog `MeshCatalog.buildOutboundPolicies()`.

![image](https://user-images.githubusercontent.com/872876/119548677-4b646680-bd4b-11eb-8b63-2bb85997bd4a.png)

Test scenarios that error occurs.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Ref #1489

**Comment by SanyaKochhar** [comment]
Closing as the test coverage for this file is >80%
