### ISSUE TITLE
Tests: add tests for pkg/configurator

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3407]
**Please describe the Improvement and/or Feature Request**

Add test cases for pkg/configurator `Client.getMeshConfig()`.

![image](https://user-images.githubusercontent.com/872876/119549660-4ce25e80-bd4c-11eb-9af4-1ad0c97609fb.png)

We need to test the case that mesh config is not in the cache.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by allenlsy** [comment]
Ref #1489

**Comment by eduser25** [comment]
This should be closed (#3506)
