### ISSUE TITLE
Tests: add tests to pkg/envoy/ads respond to request

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3414]
**Please describe the Improvement and/or Feature Request**

Add test cases for pkg/envoy/ads `respondToRequest()`. It is completely not covered.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Ref #1489

**Comment by SanyaKochhar** [comment]
Consolidated in #3408
