### ISSUE TITLE
Tests: add test case to pkg/envoy/lds get outbound filter chain per upstream

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3420]
**Please describe the Improvement and/or Feature Request**

Add test cases for pkg/envoy/lds `listenerBuilder.getOutboundFilterChainPerUpstream()`.

Several scenarios not covered:

* No upstream service exists
* Retriving protocol to port map failed for a upstream
* Some error returning cases.

![image](https://user-images.githubusercontent.com/872876/119562367-19f39700-bd5b-11eb-998c-00cda0e6671a.png)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Ref #1489

**Comment by SanyaKochhar** [comment]
Consolidated in #3419
