### ISSUE TITLE
Tests: add test case to pkg/envoy/rds create response

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3422]
**Please describe the Improvement and/or Feature Request**

Add test cases for pkg/envoy/rds `NewResponse()`.

Scenarios not covered:

* When egress traffic policy exists, the cluster config generate is different.
* Duplicated cluster in config should be skipped.

---

This is a sub-issue of #1489

**Comment by mudit-01** [comment]
I would like to work on it
