### ISSUE TITLE
Tests: add test to pkg/ingress package

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3429]
**Please describe the Improvement and/or Feature Request**

Add tests to pkg/ingress package. Some functions are completed not covered.

* `Client.GetIngressNetworkingV1beta1()`
* `Client.GetIngressNetworkingV1()`
* `NewIngressClient()`
* `Client.run()`

![image](https://user-images.githubusercontent.com/872876/119565881-5cb76e00-bd5f-11eb-9163-0532fe7246d6.png)

![image](https://user-images.githubusercontent.com/872876/119565897-604af500-bd5f-11eb-9e38-aacd9b47eb62.png)

![image](https://user-images.githubusercontent.com/872876/119565915-64771280-bd5f-11eb-889b-e6ca3c85156e.png)

![image](https://user-images.githubusercontent.com/872876/119565924-68a33000-bd5f-11eb-8c87-7344b9f8370c.png)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Ref #1489

**Comment by shashankram** [comment]
This code will be deprecated in a future release, and we already have good coverage for those functions from the tests in `pkg/catalog/ingress_test.go`.
