### ISSUE TITLE
Tests: add tests to pkg/injectorget port of container method:

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3431]
**Please describe the Improvement and/or Feature Request**

Add tests to pkg/injector `getPort()`. 

Scenario not covered:

* Container does not declare any port
* No matching port to the given named port

![image](https://user-images.githubusercontent.com/872876/119567506-43172600-bd61-11eb-8e40-fc949c743b81.png)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Ref #1489

**Comment by SanyaKochhar** [comment]
Consolidated in #3432
