### ISSUE TITLE
Tests: add test to pkg/injector

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3432]
In `pkg/injector`, some areas need improved test coverage:

a) Add tests to pkg/injector `mutatingWebhook.createPatch`. Test should check if pod annotations are updated when `enableMetrics=true`.

![image](https://user-images.githubusercontent.com/872876/119568093-f6801a80-bd61-11eb-9202-eaab0ed0d822.png)

b) Add tests to pkg/injector `getPort()`. 

Scenario not covered:

* Container does not declare any port
* No matching port to the given named port

![image](https://user-images.githubusercontent.com/872876/119567506-43172600-bd61-11eb-8e40-fc949c743b81.png)

Ref #1489

**Comment by SanyaKochhar** [comment]
@shuheiktgw I see you have two PRs open for this issue, do you mind if I assign it to you?
