### ISSUE TITLE
test: pkg/certificate/providers/tresor/certificate.go - NewCertManager() failures

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm#3437]
In `pkg/certificate/providers/tresor/certificate.go`, the unit test coverage can be improved for the NewCertManager() func. See highlighted lines below.

![image](https://user-images.githubusercontent.com/42152676/119570097-a7e07980-bd7d-11eb-99ea-ec93e670c3dd.png)

Scenarios not covered:
* error creating cert manager for a nil ca

ref #1489

**Comment by uds5501** [comment]
Would love to pick this one up.

**Comment by SanyaKochhar** [comment]
@uds5501 definitely feel free to pick this up and assign it to yourself, and let us know if you have any questions

**Comment by mudit-01** [comment]
@uds5501 are you still working on this issue?

**Comment by allenlsy** [comment]
@mudit-01 Since uds5501 didn't assign the task to himself, do you want to take over?

**Comment by mudit-01** [comment]
@allenlsy I would like to work on it.

**Comment by allenlsy** [comment]
@mudit-01 Feel free to assign the issue to yourself, and try to finish it in a reasonable amount of time. If you cannot finish it for some reasons, you can leave a comment about your findings, and unassign it.
