### ISSUE TITLE
certificate management for multicluster 

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3446]
**Please describe the Improvement and/or Feature Request**

Each osm instance creates its own root certificate which will be referenced on the multicluster gateway in that cluster. As the multicluster gateway is the entry point for communication between clusters, for connections to be successfully established the clusters either need to share their certificate information with one an other or there needs to be a common certificate that is used across all osm instances participating in the multicluster scenario.

This issue is to figure out what the best approach would be to solve this problem and to prototype the same. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by allenlsy** [comment]
Here is my opinion:

If we want to form a multicluster mesh, each single mesh needs a way to find all other meshes. There should be a place to stores the metadata of meshes.

### Approach 1: centralized metadata storage

We can create a centralized metadata storage, act like a mesh discovery service. I believe in the community this concept is called federation. Every single cluster service mesh needs to register itself at the federation. Thus the federation can own a top level cert, signs the cert for each individual OSM. This way we enables inter-cluster communication.


### Approach 2: without centralized metadata storage

If we don't want to  have a centralized metadata storage, then every single-cluster mesh has to have a complete global view of the multicluster mesh. There should be a consensus protocol among meshes, to synchronous the global view. And at the same time, a single-cluster mesh needs to distribute its cert to all other clusters, and also handle related works, such as cert rotation if needed.


Both approaches are feasible. However, the first approach seems to be more preferred by the community.
