### ISSUE TITLE
test: pkg/identity/types.go - test for GetCertificateCommonName

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm#3448]
In `pkg/identity/types.go`, the unit test coverage can be added for the GetCertificateCommonName() func by adding a small test. See highlighted lines below.

![image](https://user-images.githubusercontent.com/42152676/119573529-656d6b80-bd82-11eb-9362-5fb1b4173e91.png)

ref #1489

**Comment by shalier** [comment]
Function removed, test no longer needed
