### ISSUE TITLE
test: pkg/kubernetes/event_handlers.go func logNotObservedNamespace

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm#3450]
In `pkg/kubernetes/event_handlers.go`, the unit test coverage can be added for the logNotObservedNamespace() func by adding a small test. See highlighted lines below.

![image](https://user-images.githubusercontent.com/42152676/119574014-11af5200-bd83-11eb-9383-3aeebfb063bc.png)

Scenarios not covered:
* If emitLogs is true, debug message should be logged

ref #1489

**Comment by shashankram** [comment]
Testing this implies testing if a boolean works as expected and if the zerolog logger works as expected. Both seem unnecessary to me. 

I am inclined to close this and remove the need for the utility log in a PR  soon.
