### ISSUE TITLE
CI environment for multicluster 

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3452]
**Please describe the Improvement and/or Feature Request**

We will need a CI environment to test our multicluster scenarios, for starts this environment would require the following : 

- [ ] create 2 clusters and deploy osm on them with  multicluster feature enabled 
- [ ] Have a service that is distributed across the two clusters 

To start off we can even have this as an e2e test 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by marcindulak** [comment]
:eyes:
