### ISSUE TITLE
Create an optional (on/off) debug endpoint on OSM pod which outputs SMI graph

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#346]
We need to create an endpoint on the OSM pod, which will output the list of SMI policies observed and the config (graph) constructed based on these policies.

 - [ ] The endpoint must be disabled by default. We need to be able to turn this on for debugging when necessary.
 - [ ] document the new endpoint

**Comment by SanyaKochhar** [comment]
@draychev has this been resolved?

**Comment by draychev** [comment]
@SanyaKochhar this indeed it has been resolved.
This was implemented by https://github.com/openservicemesh/osm/pull/861
