### ISSUE TITLE
Support for Statefulsets

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#3477]
**Please describe the Improvement and/or Feature Request**
OSM should support routing to specific statefulset pods within a mesh.

**Scope (please mark with X where applicable)**
- New Functionality          [x ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
This is required for many statefulset applications like Kafka, MongoDB, cassandra, or other sharded/replicated databases.

Statefulsets use headless services to route to each pod, meaning an Endpoint is not created, but a DNS entry for each Pod is used. Pods in a statefulset have a predictable naming format, so it would be as simple as adding a domain entry for each statefulset, that maps to the Pod endpoint, or allowing DNS lookups to be used

**Comment by steeling** [comment]
Creating a headless service actually brings us to a counter-intuitive solution where the service is created as if it was not a headless service (via instantiating the endpoints for each pod).

ie: in kubernetes a headless service is not addressable on it's own, yet it is in OSM.

Consider the heeadless service: `my-svc` targeting the `my-sts` statefulset in `my-ns` namespace.

In K8s:

`my-svc.my-ns[.svc[.cluster[.local]]]` does not exist, and will not be able to lookup an endpoint. In OSM however, this is generated and points to the set of endpoints backing the sts.

Yet in K8s:

`my-sts-0.my-svc.my-ns[.svc[.cluster[.local]]]` *does* work, but *does not* work in OSM.

**Comment by keithmattix** [comment]
Is the issue that OSM can't route to specific statefulsets via a headless service or is it something else? Endpoints actually [do get created](https://kubernetes.io/docs/concepts/services-networking/service/#with-selectors) as long as the headless service has a selector, so is this issue specifically describing the non-selector use-case?

**Comment by steeling** [comment]
The endpoints may get created, but we don't properly route to them.

A couple things:

Headless services are not addressable themselves. That is, a headless service, "my-headless-svc", does not contain any DNS records directly. Instead, the pod's backing the headless service are each individually addressable. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

So right now, we do create an addressable service, "my-headless-svc", which is incorrect. It shouldn't exist. What we should do, is instead lookup the pod's backing that service, and create one for each envoy "cluster" for each pod.

Taking it a step further, we can additionally add the named port spec, but I've never personally seen that used, and am not aware of other service mesh's that support that. We can defer on that for the indefinite future.
