### ISSUE TITLE
SMI Traffic Access Should be applied Server side

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#3493]
OSM currently applies SMI Traffic Access only on the client. SMI Trafffic access should be applied on the server side according to the spec, and optionally on the client. https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-access/v1alpha3/traffic-access.md#traffic-access-control

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [x ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

This is especially useful for correctness in the multicluster case, where we need to have the Traffic Targets created in both clusters. Otherwise it leaves the counter-intuitive scenario of creating a traffic policy in the dest cluster that denies traffic from a service in the src cluster, without actually enforcing that policy

**Comment by shashankram** [comment]
@steeling Please provide a description for this issue.

**Comment by steeling** [comment]
Not sure how that didn't get filled i definitely filled out hte template :/ WIll circle back now

**Comment by snehachhabria** [comment]
@steeling please could you help clarify with some examples on how you see that OSM applies SMI Access only on client side ? 

According to SMI : access control is always enforced on the server side of a connection (or the target). It is up to implementations to decide whether they would also like to enforce access control on the client (or source) side of the connection as well.

We are actually enforcing the rules the access policy specifies on the server side in OSM by ensuring that the envoy on the server side is configured with the access policy rules : https://github.com/openservicemesh/osm/blob/4dc533719e31ef8047fd78c1e6345a922a72d12f/pkg/catalog/inbound_traffic_policies.go#L36 . 

With regard to multicluster, having the Traffic Targets created in both clusters is an intermediate solution until we have multicluster support from SMI. The policy will always be applied on the server /dest side and it will be enforsed
