### ISSUE TITLE
check the port-forward-all script for correctness

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm#3521]
**Bug description**:

When used with either v0.8.4 or the unreleased v0.9.x, the manual demo documented at https://docs.openservicemesh.io/docs/install/manual_demo/#view-the-application-uis suggests the use of https://github.com/openservicemesh/osm/blob/main/scripts/port-forward-all.sh.

In that script, we seem to invoke [bookstore](https://github.com/openservicemesh/osm/blame/main/scripts/port-forward-all.sh#L4) as well as bookstore v1 and bookstore v2.

Some errors like "No resources found in bookstore namespace" and "error: resource name may not be empty" make it seem that this script has gotten a bit out of sync with current practice.

**Affected area (please mark with X where applicable)**:
- Demo                       [X]

**Expected behavior**:

We would expect all scripts in the manual demo (including the port-forward-all script) to launch only the expected resources and, if there are expected to be errors, we would want to display an informative message assuring the user about what is happening.

**Steps to reproduce the bug (as precisely as possible)**:
Run the [manual demo](https://docs.openservicemesh.io/docs/install/manual_demo/) as published, and look at the output from the port forwarding script.

Here I have added echo statements to show more clearly where it errors out:

```
./scripts/port-forward-all.sh
start bookbuyer-ui
start jaeger
start grafana
start bookthief-ui
No resources found in bookstore namespace.
start bookstore-ui-v1
No resources found in bookstore namespace.
start bookstore-ui-v2
start osm-debug
start bookstore-ui
error: resource name may not be empty
error: resource name may not be empty
stop bookstore-ui-v2
stop bookstore-ui-v1
Forwarding from 127.0.0.1:8080 -> 14001
Forwarding from [::1]:8080 -> 14001
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Forwarding from 127.0.0.1:8083 -> 14001
Forwarding from [::1]:8083 -> 14001
Forwarding from 127.0.0.1:16686 -> 16686
Forwarding from [::1]:16686 -> 16686
Forwarding from 127.0.0.1:9092 -> 9092
Forwarding from [::1]:9092 -> 9092
Forwarding from 127.0.0.1:8084 -> 14001
Forwarding from [::1]:8084 -> 14001
^Cstop grafana
stop jaeger
stop osm-debug
stop bookbuyer-ui                                                                                  
stop bookstore-ui
stop bookthief-ui
```
**How was OSM installed?**:

Built from source, but installation may not be relevant here.

**Comment by zr-msft** [comment]
Best experience would be to update the script to fix the errors or note that the behavior is expected. 

If its the latter case, we can update the docs in the short term to show this is intended, but need confirmation that this behavior is correct and expected.

**Comment by bridgetkromhout** [comment]
We should check the script, see if it is emitting unhelpful errors, and fix it.

**Comment by trstringer** [comment]
Thanks, @bridgetkromhout! I added it to the vFuture milestone so we can triage this work (also it won't be considered for the stale bot anymore).
