### ISSUE TITLE
Egress story

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#354]
How would a pod that is in the mesh and has Envoy sidecar do `curl http://contoso.com/` ?

**Tasks**
- [x] ref #1000
- [x] ref #999
- [x] ref #1011
- [x] ref #1120
- [x] ref #1185 
- [x] ref #1186
- [ ] ref #982

**Comment by draychev** [comment]
This is finished!

**Comment by michelleN** [comment]
We can do #982 separately. Egress is marked done from an MVP point of view for now.
