### ISSUE TITLE
osm-controller: avoid usage of global variables for cmd line flags that can result in test pollution

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#3547]
**Please describe the Improvement and/or Feature Request**

Many CLI commands are using the Golang native flags library, and temporary variables are declared globally in packages. This is difficult for doing unit test, as we need to store and restore global variable values in the process.

Cobra is a better choice for creating commands. Check [trafficpolicy_check](https://github.com/openservicemesh/osm/blob/7a36ec9a25cbe9afb59cc666a869617a96186a61/cmd/cli/trafficpolicy_check.go#L56) command. 

I suggest we refactor all CLI commands to use Cobra-like CLI wrapper. This means, we can write our own light-weighted Go struct to organize CLI command parameters and maybe other functionalities.

Related discussion: https://github.com/openservicemesh/osm/pull/3485#discussion_r647666472

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [x]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [x]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

N/A

**Comment by shashankram** [comment]
@allenlsy We decided to scrap this effort previously (ref: https://github.com/openservicemesh/osm/issues/576). 
Cobra-style flags are more suitable for programs that have a hierarchy of commands, which osm-controller and injector don't require.

Is using Cobra the only possibility to avoid global flags in tests?

**Comment by allenlsy** [comment]
No, we can also create our own command struct, and store CLI parameters inside. It is also easy to create command object during test.

**Comment by shashankram** [comment]
> No, we can also create our own command struct, and store CLI parameters inside. It is also easy to create command object during test.

Maybe that's a better option rather than using Cobra here which seems a bit odd to use with a single command structure (no sub-commands).

**Comment by adhaamehab** [comment]
Hey all,
Just FYI, I'm gonna start working on this issue. Thanks!

**Comment by shashankram** [comment]
> Hey all,
> Just FYI, I'm gonna start working on this issue. Thanks!

Hey @adhaamehab, are you still interested in working on this?
