### ISSUE TITLE
e2e_deployment_client_server_test 504 gateway timeout error

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3558]
**Bug description**:  The e2e_deployment_client_server test fails on an AKS cluster with OSM v0.9.0-rc.2 pre-installed. 

`client0/client0-59b4ff4dfc-lmn5f - server.server: 504  -
client0/client0-59b4ff4dfc-t7phc - server.server: 504  -
client0/client0-59b4ff4dfc-tmc6d - server.server: 504  -
client0/client0-59b4ff4dfc-ttvz9 - server.server: 504  -
client0/client0-59b4ff4dfc-x2xwh - server.server: 504  -
client1/client1-8698c7f49-59pgs - server.server: 504  -
client1/client1-8698c7f49-j74pp - server.server: 504  -
client1/client1-8698c7f49-nhjc2 - server.server: 504  -
client1/client1-8698c7f49-nrj4k - server.server: 504  -
client1/client1-8698c7f49-zdvqb - server.server: 504  -
client2/client2-69446f8b9-bt45n - server.server: 504  -
client2/client2-69446f8b9-lghgm - server.server: 504  -
client2/client2-69446f8b9-p9tz9 - server.server: 504  -
client2/client2-69446f8b9-x6745 - server.server: 504  -
client2/client2-69446f8b9-xjwq7 - server.server: 504  -
client3/client3-7fdb7fd5c-6p9b8 - server.server: 504  -
client3/client3-7fdb7fd5c-b59mz - server.server: 504  -
client3/client3-7fdb7fd5c-kzlk9 - server.server: 504  -
client3/client3-7fdb7fd5c-pcbz9 - server.server: 504  -
client3/client3-7fdb7fd5c-rdw5w - server.server: 504  -
client4/client4-77dcb4f757-9k5rn - server.server: 504  -
client4/client4-77dcb4f757-mzdz9 - server.server: 504  -
client4/client4-77dcb4f757-qjfsm - server.server: 504  -
client4/client4-77dcb4f757-vrdxd - server.server: 504  -`

This error persists after exec inside the client container and sending a request manually: 

`/ # /usr/bin/curl -s -o /dev/null -D - -I -w StatusCode:%%{http_code} -L server.server`

`HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Wed, 09 Jun 2021 18:21:44 GMT
server: envoy`

Client envoy logs specifies an "upstream response timeout" error: 

`{"bytes_sent":0,"response_flags":"UT","duration":14998,"protocol":"HTTP/1.1","time_to_first_byte":null,"requested_server_name":null,"upstream_cluster":"server/server","response_code_details":"upstream_response_timeout","upstream_service_time":null,"upstream_host":"10.244.2.10:80","bytes_received":0,"user_agent":"curl/7.52.1","path":"/","x_forwarded_for":null,"authority":"server.server","request_id":"ab13e873-2757-4808-ad8a-e53cd6eafbb3","start_time":"2021-06-09T18:17:39.147Z","method":"HEAD","response_code":504}
{"request_id":"91a8d865-89b2-4d18-843f-0a2cb091ac6f","upstream_service_time":"15001","x_forwarded_for":null,"requested_server_name":null,"bytes_sent":0,"path":"/","bytes_received":0,"upstream_cluster":"server/server","protocol":"HTTP/1.1","start_time":"2021-06-09T18:17:56.342Z","authority":"server.server","user_agent":"curl/7.52.1","response_code":504,"response_flags":"-","upstream_host":"10.244.1.5:80","response_code_details":"via_upstream","duration":15002,"method":"HEAD","time_to_first_byte":15002}
{"start_time":"2021-06-09T18:18:14.436Z","bytes_sent":0,"response_flags":"-","time_to_first_byte":15006,"user_agent":"curl/7.52.1","upstream_service_time":"15006","response_code_details":"via_upstream","duration":15006,"protocol":"HTTP/1.1","request_id":"692e888c-9aff-4d09-8dda-5cb361ea19c5","upstream_host":"10.244.2.10:80","bytes_received":0,"upstream_cluster":"server/server","method":"HEAD","response_code":504,"path":"/","requested_server_name":null,"authority":"server.server","x_forwarded_for":null}
{"response_code":504,"path":"/","upstream_cluster":"server/server","request_id":"600712dd-4b4f-4901-b8ca-823cbe93b2ea","time_to_first_byte":null,"authority":"server.server","bytes_sent":0,"response_flags":"UT","method":"HEAD","upstream_host":"10.244.2.5:80","x_forwarded_for":null,"requested_server_name":null,"bytes_received":0,"upstream_service_time":null,"user_agent":"curl/7.52.1","response_code_details":"upstream_response_timeout","start_time":"2021-06-09T18:18:31.268Z","protocol":"HTTP/1.1","duration":15000}
{"time_to_first_byte":null,"user_agent":"curl/7.52.1","requested_server_name":null,"x_forwarded_for":null,"start_time":"2021-06-09T18:18:48.140Z","upstream_cluster":"server/server","request_id":"ee813b9a-e275-44d6-acd3-f1025a1f9d7f","response_code_details":"upstream_response_timeout","response_code":504,"bytes_received":0,"bytes_sent":0,"protocol":"HTTP/1.1","response_flags":"UT","duration":15000,"upstream_host":"10.244.0.12:80","path":"/","upstream_service_time":null,"method":"HEAD","authority":"server.server"}
{"time_to_first_byte":null,"user_agent":"curl/7.52.1","response_code":504,"x_forwarded_for":null,"request_id":"8688a776-f7f4-4621-9063-4b7321386888","duration":15000,"bytes_sent":0,"response_code_details":"upstream_response_timeout","response_flags":"UT","path":"/","upstream_host":"10.244.0.4:80","authority":"server.server","upstream_cluster":"server/server","protocol":"HTTP/1.1","bytes_received":0,"requested_server_name":null,"upstream_service_time":null,"start_time":"2021-06-09T18:19:56.823Z","method":"HEAD"}
{"duration":14999,"response_flags":"UT","response_code_details":"upstream_response_timeout","upstream_service_time":null,"request_id":"4ecbed43-ba30-4a4d-8165-c54723b01732","x_forwarded_for":null,"response_code":504,"bytes_received":0,"start_time":"2021-06-09T18:21:30.034Z","time_to_first_byte":null,"authority":"server.server","path":"/","upstream_host":"10.244.1.5:80","user_agent":"curl/7.52.1","requested_server_name":null,"protocol":"HTTP/1.1","bytes_sent":0,"method":"HEAD","upstream_cluster":"server/server"}`

And server envoy logs mention "downstream remote disconnect" 

`{"bytes_received":0,"path":"/","time_to_first_byte":null,"upstream_service_time":null,"start_time":"2021-06-09T18:18:48.073Z","duration":14976,"bytes_sent":0,"response_code_details":"downstream_remote_disconnect","authority":"server.server","user_agent":"curl/7.52.1","request_id":"403cc7de-b8f3-4e4e-b608-3925fca88410","x_forwarded_for":null,"requested_server_name":"server.server.svc.cluster.local","response_code":0,"response_flags":"DC","upstream_cluster":"server/server-local","upstream_host":"0.0.0.0:80","protocol":"HTTP/1.1","method":"HEAD"}
{"response_code_details":"downstream_remote_disconnect","response_flags":"DC","bytes_received":0,"path":"/","method":"HEAD","requested_server_name":"server.server.svc.cluster.local","duration":14980,"x_forwarded_for":null,"protocol":"HTTP/1.1","start_time":"2021-06-09T18:18:48.068Z","response_code":0,"bytes_sent":0,"upstream_service_time":null,"upstream_cluster":"server/server-local","time_to_first_byte":null,"request_id":"b9f12f63-df64-4b70-a3cc-4d16af26d68b","upstream_host":"0.0.0.0:80","authority":"server.server","user_agent":"curl/7.52.1"}
{"start_time":"2021-06-09T18:18:48.071Z","path":"/","user_agent":"curl/7.52.1","protocol":"HTTP/1.1","authority":"server.server","requested_server_name":"server.server.svc.cluster.local","upstream_host":"0.0.0.0:80","upstream_cluster":"server/server-local","x_forwarded_for":null,"bytes_received":0,"time_to_first_byte":null,"request_id":"8e93868d-53da-43b0-84eb-0e170906701b","response_flags":"DC","bytes_sent":0,"response_code_details":"downstream_remote_disconnect","method":"HEAD","response_code":0,"upstream_service_time":null,"duration":14987}
{"upstream_cluster":"server/server-local","authority":"server.server","path":"/","request_id":"0edab281-e7eb-4a58-b566-2219a2ea7775","method":"HEAD","bytes_sent":0,"upstream_host":"0.0.0.0:80","protocol":"HTTP/1.1","user_agent":"curl/7.52.1","start_time":"2021-06-09T18:18:48.074Z","requested_server_name":"server.server.svc.cluster.local","bytes_received":0,"x_forwarded_for":null,"upstream_service_time":null,"time_to_first_byte":null,"duration":14986,"response_flags":"DC","response_code":0,"response_code_details":"downstream_remote_disconnect"}
{"method":"HEAD","response_flags":"DC","path":"/","bytes_received":0,"response_code":0,"x_forwarded_for":null,"start_time":"2021-06-09T18:19:56.825Z","upstream_host":"0.0.0.0:80","user_agent":"curl/7.52.1","upstream_service_time":null,"protocol":"HTTP/1.1","response_code_details":"downstream_remote_disconnect","authority":"server.server","bytes_sent":0,"request_id":"8688a776-f7f4-4621-9063-4b7321386888","upstream_cluster":"server/server-local","time_to_first_byte":null,"duration":14997,"requested_server_name":"server.server.svc.cluster.local"}`

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Requests should succeed with response 200 between client and server. 

**Steps to reproduce the bug (as precisely as possible)**: Create an AKS cluster and install osm v0.9.0-rc.2 via osm cli. Then, run the e2e_deployment_client_server_test with no-install flag: 

`go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -test.timeout 60m -installType=NoInstall -ginkgo.focus="\bTest HTTP traffic from N deployment client -> 1 deployment server\b" -OsmNamespace=osm-system`

**How was OSM installed?**: OSM cli. 

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): v0.9.0-rc.2 
- Kubernetes version (use `kubectl version`): 1.19.11
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by nshankar13** [comment]
[client0_config_dump.txt](https://github.com/openservicemesh/osm/files/6626135/client0_config_dump.txt)
[server_config_dump.txt](https://github.com/openservicemesh/osm/files/6626136/server_config_dump.txt)

**Comment by eduser25** [comment]
Seems could have been a temporary failure, we haven't seen this nor been able to reproduce over several days.
We'll keep an eye just in case.
