### ISSUE TITLE
OSM namespace add command show incomplete information

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3569]
**Please describe the Improvement and/or Feature Request**
osm namespace add command dosent give information regarding the sidecar injection 
i.e it dont give information if sidecar injection is disabled or not
![image](https://user-images.githubusercontent.com/53465654/121491434-90e38d80-c9f3-11eb-8923-7ec028359c0a.png)

![image](https://user-images.githubusercontent.com/53465654/121492106-35fe6600-c9f4-11eb-8c7e-9b76c83eeb6a.png)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
It will be helpfull if it show message  sidecar injection is disabled
Eg: Namespace [bookbuyer] successfully added to mesh [osm] with  sidecar injection enabled

**Comment by mudit-01** [comment]
I can work on this, If this is needed.

**Comment by shashankram** [comment]
@mudit-01 you need to use the `osm namespace list` command to get this info, because `osm namespace add` is meant to add a namespace to the mesh, and users can choose to enable/disable sidecar as they please.

```
$ osm namespace list
NAMESPACE   MESH   SIDECAR-INJECTION
test        osm    enabled
```

Moreover, the help text of `osm namespace add` already specifies that sidecar injection is enabled by default:
```
$ osm namespace add -h

This command adds a namespace or set of namespaces to the mesh so that the osm
control plane with the given mesh name can observe resources within that namespace
or set of namespaces. It also enables automatic sidecar injection for all pods
created within the given namespace. Automatic sidecar injection can be disabled
via the --disable-sidecar-injection flag.

Usage:
  osm namespace add NAMESPACE ... [flags]
```
