### ISSUE TITLE
Create PSP test

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#3587]
**Please describe the Improvement and/or Feature Request**

Create test to ensure all control plane components include PSP
**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by ksubrmnn** [comment]
Closing since PSP not supported on kind. 

Will re-evaluate when we replace PSP with its successor when it's replaced by "PSP Replacement Policy" : https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

**Comment by ksubrmnn** [comment]
Linked to #3588

**Comment by ksubrmnn** [comment]
Create nightly job with kind cluster with psp admission controller then run demo

**Comment by snehachhabria** [comment]
OSM has deprecated support for PSP, closing this issue for now
