### ISSUE TITLE
Unified Provider Interface for Endpoint and Service Providers

### ISSUE THREAD

**Issue by whitneygriffith** [openservicemesh/osm#3632]
**Please describe the Improvement and/or Feature Request**

A separate service provider was created in #3614 to enable multicluster functionality. 

The mesh catalog is now aware of `endpoint.Provider` and `service.Provider` interfaces and we will like to collapse these two interfaces into one `service.Provider`. 

**Scope (please mark with X where applicable)**
- New Functionality          [X ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

[Multi Cluster Proposal Addendum
](https://docs.google.com/document/d/1sA03IwqC6tuJpCleGMakQpHzwFJ5ulfxzCq7iSXSqZc/edit#heading=h.ae8gbsiygb1m)

**Comment by steeling** [comment]
One other recommendation.. there's some duplication between the provider methods and the meshcatalog. You could do the following:

1. Create a single Provider interface and have a new field on the meshcatalog:

```
type MeshCatalog struct {
   ...
   provider Provider
   ...
}
```

as opposed to an array of providers. If you ever really needed multiple providers you could have 

type AggregatedProvider struct {
   providers []Provider
}

This would remove a good amount of code.

2. Following this train of thought, why not make the provider an embedded interface?
type MeshCatalog struct {
   ...
   Provider
   ...
}

This will allow some of the xDS files to directly call these methods, removing some more boiler plate.
