### ISSUE TITLE
OSM 0.9.0 does not work on OpenShift

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#3641]
**Bug description**:

OpenShift requires the osm-controller RBAC to have permission to delete secrets for the garbage collection of Envoy secrets. Without this (as is the case in 0.9.0), pods in the mesh are not schedulable in OpenShift.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        []
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Pods can be scheduled in the mesh.
**Steps to reproduce the bug (as precisely as possible)**:
Deploy meshed pods on OpenShift with OSM 0.9.0
**How was OSM installed?**:
Demo script
**Anything else we need to know?**:
```
{"level":"error","component":"kube-controller","error":"secrets \"envoy-bootstrap-config-888a79b4-4ec2-489a-a0f8-886b30d1959e\" is forbidden: cannot set an ownerRef on a resource you can't delete: , <nil>","time":"2021-06-21T22:14:31Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookbuyer/envoy-bootstrap-config-888a79b4-4ec2-489a-a0f8-886b30d1959e to reference Pod bookbuyer/bookbuyer-6bb8ddbb99-ltdbm"}
```
**Environment**:
- OSM version (use `osm version`): 0.9.0
- Kubernetes version (use `kubectl version`): v1.19.0
- Size of cluster (number of worker nodes in the cluster): 3
- Others: OpenShift

**Comment by draychev** [comment]
@ksubrmnn I'm closing this since we fixed it in v0.9.1
