### ISSUE TITLE
Improve output of `osm mesh list` cli command

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3648]
**Please describe the Improvement and/or Feature Request**
The output of the `osm mesh list` command is too verbose and not well aligned on standard terminal sized windows.

Ex.
![image](https://user-images.githubusercontent.com/21697719/123142791-a9e63880-d40e-11eb-9cd5-94a8c0081432.png)

Since multiple replicas of the pod exist, the output is more verbose than necessary. Instead of dumping all the pod names, which can increase with multiple replicas and auto scaling, provide a query string to view all the pods instead. The query could be a `kubectl` command such as `kubectl get po -n osm-system -l app=osm-controller`, that can be dropped as a note in the output of the CLI, without necessarily being formatted in the table output.

Similarly, the SMI version supported doesn't have to be a part of the output table, but can be a separate section in the output.

**Scope (please mark with X where applicable)**
- CLI Tool                   [X]

**Possible use cases**
Enhance the output of this CLI so it doesn't look cluttered when multiple replicas of osm-controller pods exsit.

**Comment by johnsonshi** [comment]
This issue needs to be revisited.
