### ISSUE TITLE
e2e: ensure control plane pods are ready before running the test

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3665]
This GitHub Issue is to:
 - [ ] verify that the end-to-end tests have a mechanism by which they wait for the OSM Controller and OSM Injector are in status `READY` before the tests run
 - [ ] understand why sometimes tests run **before** Injector is `READY` (@allenlsy and @nojnhuh ran into this)
 - [ ] fix if this is indeed an issue

**Comment by nojnhuh** [comment]
Possible related to Docker Desktop for Mac, where I've seen similar issues: #3143

**Comment by eduser25** [comment]
unrelated to Jon's, but number of people has complained about issues with the helm wait in the past
https://github.com/helm/helm/issues/3173
https://github.com/helm/chart-testing/blob/4960e30445ead42157850a75245a6c543460ddee/lib/chartlib.sh#L326
https://www.prodops.io/blog/helm-install-wait-does-not-wait-workaround#:~:text=Helm%20provides%20the%20option%20to,to%20install%20and%20upgrade%20commands.&text=Wait%3A%20if%20set%2C%20will%20wait,for%20as%20long%20as%20%E2%80%94%20timeout.

Not sure how safe is to assume it is all fixed. For the time being, we can put a small check to ensure common e2e infra is always waiting for both injector and osm to be up.
