### ISSUE TITLE
Search box results are not in format

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3711]
**Please describe what should be documented**
The search results are not consistent with the docs website https://docs.openservicemesh.io/docs/
![image](https://user-images.githubusercontent.com/53465654/124109570-eb1cbf00-da84-11eb-8f60-40101a13f69d.png)

**Please suggest where in the repo the document should be located**

**Comment by shashankram** [comment]
The search seems to be working fine.

![image](https://user-images.githubusercontent.com/21697719/132764101-d7fc9bca-c585-45a6-be89-f9e4b279b573.png)

If this is not working as intended, please open an issue at https://github.com/openservicemesh/osm-docs/issues
