### ISSUE TITLE
Run OSM e2e tests on ARO cluster with GitHub actions

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3720]
This GitHub Issue is for the creation of another workflow, which will execute all end-to-end tests on an ARO (OpenShift) cluster for each PR.

The goal of this is to be able to run tests not only on a (current setup) [kind ](https://kind.sigs.k8s.io/) cluster, but also on ARO.

### Links
- How to create an ARO cluster: https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster

**Comment by ksubrmnn** [comment]
Three successful nightly runs: https://github.com/openservicemesh/osm/actions/workflows/openshift-nightly.yml

Closing issue.
