### ISSUE TITLE
Permissive mode not working in automated demo with root bookstore service

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#3740]
**Bug description**: Running the automated demo with permissive mode enabled, neither the bookbuyer nor the bookthief reach the bookstore successfully. All requests result in a HTTP 503 because of a TLS error:

```json
{"response_flags":"UF","response_code":503,"request_id":"6dab1e9b-5475-48d1-9fc0-b8a824a812e6","requested_server_name":null,"start_time":"2021-07-07T18:50:46.790Z","bytes_sent":182,"authority":"bookstore.bookstore:14001","path":"/buy-a-book/new","upstream_host":"10.96.235.202:14001","protocol":"HTTP/1.1","method":"GET","time_to_first_byte":null,"user_agent":"Go-http-client/1.1","upstream_cluster":"bookstore/bookstore/local","response_code_details":"upstream_reset_before_response_started{connection_failure,TLS_error:_268435612:SSL_routines:OPENSSL_internal:HTTP_REQUEST}","bytes_received":0,"upstream_service_time":null,"duration":1000,"x_forwarded_for":null}
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [X]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [X]
- CI System                  [ ]

**Expected behavior**: Requests from both the bookbuyer and bookthief get HTTP 200 responses from the bookstore.

**Steps to reproduce the bug (as precisely as possible)**: `make kind-up && demo/run-osm-demo.sh --set OpenServiceMesh.enablePermissiveTrafficPolicy=true`

**How was OSM installed?**: Running the automated demo.

**Anything else we need to know?**:

I noticed there are 3 bookstore clusters programmed on the bookbuyer: v1, v2, and the root. Using `curl` from inside the bookbuyer to either v1 or v2 works, but not to the root. The EDS config for the v1 and v2 clusters is minimal, from `/config_dump?include_eds`:

```json
{
  "endpoint_config": {
    "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
    "cluster_name": "bookstore/bookstore-v2/local",
    "policy": {
      "overprovisioning_factor": 140
    }
  }
}
```

The root service's looks quite a bit different:

```json
{
  "endpoint_config": {
    "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
    "cluster_name": "bookstore/bookstore/local",
    "endpoints": [
      {
        "locality": {},
        "lb_endpoints": [
          {
            "endpoint": {
              "address": {
                "socket_address": {
                  "address": "10.96.235.202",
                  "port_value": 14001
                }
              },
              "health_check_config": {},
              "hostname": "bookstore/bookstore/local10.96.235.202:14001"
            },
            "health_status": "HEALTHY",
            "load_balancing_weight": 1
          }
        ]
      }
    ],
    "policy": {
      "overprovisioning_factor": 140
    }
  }
}
```

`kubectl get endpoints -n bookstore` shows 1 endpoint for each of the v1 and v2 services and none for the root service (as expected since its selector matches no pods).

Seems like the overall error is that Envoy is configured to forward requests for `bookstore.bookstore` to the root service's IP, but that service has no k8s endpoints. Patching the root service to select either backend gets around the issue: `kubectl patch svc -n bookstore bookstore --type merge -p '{"spec": {"selector": {"app": "bookstore-v1"}}}'`.

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: 0b1131a05a0efafb9ed9a2b32bdb3a91cf4088d7; Date:`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by shashankram** [comment]
@nojnhuh, you need to set the `BOOKSTORE_SVC` env var to `bookstore-v1` or `bookstore-v2` for it to work with permissive mode. 

There is no code to parse `--set OpenServiceMesh.enablePermissiveTrafficPolicy=true` in `run-osm-demo.sh` that sets the `BOOKSTORE_SVC` env var used by the deployment scripts.

**Comment by nojnhuh** [comment]
Ah, ok. And CI must have been doing that when this was running there.

Adding some weird parsing to the demo script to set the variable explicitly doesn't seem worth it. Is there anything we could do in the control plane or could we set up the labels on the demo apps in such a way that this would work more seamlessly? i.e. so I could toggle permissive mode at runtime and the bookbuyer can always reach the bookstore while the bookbuyer always refers to the bookstore root service?

If not, feel free to close this.

**Comment by shashankram** [comment]
> Ah, ok. And CI must have been doing that when this was running there.

Yes.

> Adding some weird parsing to the demo script to set the variable explicitly doesn't seem worth it. Is there anything we could do in the control plane or could we set up the labels on the demo apps in such a way that this would work more seamlessly? i.e. so I could toggle permissive mode at runtime and the bookbuyer can always reach the bookstore while the bookbuyer always refers to the bookstore root service?
> 
> If not, feel free to close this.

We'd need to deploy the bookstore pod with the label `app: bookstore`. 

The manual demo works with both permissive and SMI mode, so we could replicate the same in the automated demo. In fact, I think that's the best way going forward by keeping the automated demo as close to the manual demo as possible

**Comment by shashankram** [comment]
> @nojnhuh, you need to set the `BOOKSTORE_SVC` env var to `bookstore-v1` or `bookstore-v2` for it to work with permissive mode.
> 

Permissive mode should work with the automated demo as long as the BOOKSTORE_SVC env var is set.
