### ISSUE TITLE
MeshConfig values that default to "true" can't be set to "false" via Helm values

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#3742]
**Bug description**: Boolean fields with a default of "true" in the MeshConfig CRD aren't overridden when the corresponding Helm value is set to "false" when OSM is installed. This applies to `OpenServiceMesh.featureFlags.enableWASMStats` and `OpenServiceMesh.featureFlags.enableEgressPolicy`.

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: When the value is set to "false" on install, that value ultimately shows up in the osm-mesh-config.

**Steps to reproduce the bug (as precisely as possible)**:
```
make kind-up && demo/run-osm-demo.sh --set OpenServiceMesh.featureFlags.enableWASMStats=false
kubectl get meshconfig -n osm-system osm-mesh-config -o jsonpath='{.spec.featureFlags.en
ableWASMStats}'
```

**How was OSM installed?**: Demo

**Anything else we need to know?**:

In the preset-mesh-config the value is set correctly to `false` (`kubectl get configmap -n osm-system preset-mesh-config -o yaml`), so there must be some issue with how the osm-mesh-config is created.

Changing the default to `false` in the CRD before installing OSM gets around the issue. In that case the default in values.yaml is true then it will still be enabled by default.

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: ead5c9e8095d55dacbe79cb67259c9ccc78bb0ff; Date: `
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by allenlsy** [comment]
Tracked by a more general issue #3908
