### ISSUE TITLE
Improve readability of e2e framework if statement

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3754]
The complex multi-line `if-statement` needs to to be simplified so this is understood by people reading the code.

A few techniques that we could use:

- `!(A == B)` could become `A != B`
- `td.InstType == KindCluster` could be `isKindCluster`
- complex multiline statements could be evaluated and assigned to a variable, with a self-explanatory name, ahead of time

https://github.com/openservicemesh/osm/blob/93c9be585f8bbd7e295f3ff1c07233bbf41c9a34/tests/framework/common.go#L1088-L1092

**Comment by eduser25** [comment]
will take a look
