### ISSUE TITLE
E2E Port Exclusion test failure

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3755]
**Bug description**: E2E Port Exclusion test fails when running the port exclusion test on a Kind cluster with the "NoInstall" flag enabled, then the pod level test is run along with the global exclusion level test. If both the global and pod level are run individually, then both will pass. However, the pod level test will fail when both tests are invoked via the same "describe" statement. From testing locally, this appears to be due to the way the namespaces are cleaned up in the global level test, as changing the namespace names in the pod level test mitigates this error. Moreover, this only seems to be reproducible on WSL2/Linux, and not Mac. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [X]
- CI System                  [ ]

**Expected behavior**: 

**Steps to reproduce the bug (as precisely as possible)**: `go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -ginkgo.focus="\bTests traffic via port exclusion\b" -test.timeout 60m -installType=NoInstall`

**How was OSM installed?**: CLI, v0.9.1

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): v0.9.1
- Kubernetes version (use `kubectl version`): Kind v0.11.1 go1.16.4 linux/amd64, kubernetes v1.19.x or v1.21.x
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by draychev** [comment]
While troubleshooting this e2e test failure - we ran into a block of complex `if-statement` - I opened an issue to take a stab at simplifying it: #3754

**Comment by nshankar13** [comment]
Was able to resolve by changing the namespace names between the pod level and global level exclusion test.
