### ISSUE TITLE
CLI: Avoid deleting CRDs by default unless explicitly stated by the user

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3760]
**Please describe the Improvement and/or Feature Request**
With the recent changes made to OSM for the purpose of upgrade, the CRDs installed get removed during uninstall. We need to avoid deleting CRDs unless explicitly specified because deleting the CRD will also delete all the custom resources (SMI policies, Egress policies etc.) from the cluster. This is a very destructive operation that needs to be explicitly stated by the user when required.

- Proposal 1:
Only delete CRDs if `--delete-crds`  is passed to `osm uninstall`.
When `--delete-crds` is passed, OSM CLI could patch `charts/osm/templates/cleanup-hook.yaml` to delete the CRDs, otherwise they should not be deleted.

- Proposal 2
Add an option in `MeshConfig` to allow the user to specify whether the CRD should be deleted or not, and appropriately have the cleanup hook query this value prior to deleting the CRDs.

- Proposal 3
When uninstalling (using Helm or CLI), use a hook to backup all custom resources before removing the CRDs.

**Scope (please mark with X where applicable)**
- Uninstall                    [X]

**Possible use cases**
To avoid deleting all policies that the user may or may not have backed up.

**Comment by snehachhabria** [comment]
As discussed offline, we will go with proposal 3 and add a pre-delete hook to backup custom resources

**Comment by snehachhabria** [comment]
Instead of providing the option of deleting the CRDs on uninstall, the clean up hook `charts/osm/templates/cleanup-hook.yaml` will patch the CRDs to remove the conversion webhook. Therefor no longer coupling the CRD to OSM and preventing custom resources from being deleted.
