### ISSUE TITLE
Add test to verify Envoy config and/or traffic after switching between permissive mode and SMI

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3778]
**Please describe the Improvement and/or Feature Request**
#3775 reported a bug where the XDS state machine did not function as expected after switching from permissive mode to SMI.

This issue proposed to add the following tests to catch such issues.
1. unit test under `tests/scenarios` that verifies the entire Envoy config is as expected when switching from permissive mode to SMI and vice versa
2. e2e test that verifies traffic works as expected when switching from permissive mode to SMI

**Scope (please mark with X where applicable)**
- Tests                      [X]

**Comment by eduser25** [comment]
test was added and is running on CI (#3887)
