### ISSUE TITLE
multicluster: Parameterize the port of the Multicluster Gateway - propagate same value everywhere

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#3804]
This needs to be a parameter and this param should change everywhere we use the `14080` value

https://github.com/openservicemesh/osm/blob/94fc23d4d6e063eef871af8f44fcece576af4e15/charts/osm/templates/osm-gateway-deployment.yaml#L46

**Comment by shashankram** [comment]
@draychev could you describe in the issue why this is required? Unless there is a use case to parameterize it, I wouldn't introduce more permutations.

**Comment by draychev** [comment]
@shashankram The trouble arises with reusing the same value in multiple places. Ideally this value (port number) would be a constant somewhere in a central place.
Then this value would be used to:
1. configure the Envoy for the Multicluster Gateway
2. create the Multicluster Gateway deployment (pods)
2. create the Kubernetes service backing that Gateway
3. populate that in the various MulticlusterService objects

We could infer this value or have some number by "convention" - but ideally there would be one central source of truth.

And for some cluster where this port is for some reason not available - it'd be easy and quick to change.
