### ISSUE TITLE
Init container image pull policy can't be changed

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#3809]
**Bug description**:

The `imagePullPolicy` of the init container image used for meshed Pods is unspecified, which Kubernetes interprets as "Always" when the image tag is "latest" and "IfNotPresent" otherwise. This is usually the behavior we want, since "latest" is the only tag we update, other tags are created once and never changed afterward.

This causes issues in certain scenarios though. For example, when running the e2e tests with `-installType KindCluster` and `-osmImageTag latest`, injected Pods may fail to start due to an image pull error on the `init` image. When we run e2e tests in kind, we pre-load the images onto the node so we don't need to hook into a registry for the OSM images. However, the init container image is still pulled when its tag is "latest" which will fail unless the image has been pushed to a public registry.

The inverse issue would be when running an e2e test on a pre-provisioned cluster with a non-"latest" `-osmImageTag`. There, if the init image with that tag already exists on the node, the new one will not be pulled. The test will break if the new init container image contains needed fixes. Deleting the image on the node would be required to workaround this issue.

Overall I wonder if a reasonable solution is to tie the init container's `imagePullPolicy` to the existing `OpenServiceMesh.image.pullPolicy` value in the Helm chart since that image is built and tagged like all the other OSM images that use that for their pull policy.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: The init container image isn't pulled when its tag is "latest"

**Steps to reproduce the bug (as precisely as possible)**: Run any e2e test in kind with a kind cluster provisioned by the test and the "latest" image tag, e.g.:

```
make test-e2e CTR_REGISTRY=localhost:5000 CTR_TAG=latest E2E_FLAGS="-installType=KindCluster -cleanupKindClusterBetweenTests -ginkgo.focus='SimpleClientServer egress TCP'"
```

**How was OSM installed?**: By the test as above

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: ab484877fe436fd17824172bcc8465c9c85f3f20; Date: `
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-22T22:54:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by michelleN** [comment]
This feels more like a feature for testing purposes rather than a bug in the project. Not opposed to making the init pull policy configurable but what if instead, we scripted it so that even while testing, we never use the tag "latest"?

**Comment by michelleN** [comment]
I think this may present as an issue when we're working on [a soak test environment ](https://github.com/openservicemesh/osm/issues/2392)if we use the image tag "latest"

**Comment by shashankram** [comment]
> Overall I wonder if a reasonable solution is to tie the init container's imagePullPolicy to the existing OpenServiceMesh.image.pullPolicy value in the Helm chart since that image is built and tagged like all the other OSM images that use that for their pull policy.

This seems the correct thing to do.
