### ISSUE TITLE
Make the Tresor root CA cert key bit size configurable

### ISSUE THREAD

**Issue by trstringer** [openservicemesh/osm#3814]
**Please describe the Improvement and/or Feature Request**

This is loosely related to #1933, which aims at creating data plane certificates with a configurable key bit size. When using the Tresor certificate provider, it is currently hard-coded to create the root CA key with 2048 bits. This should also be configurable.

**Scope (please mark with X where applicable)**
- New Functionality          [x]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [x]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

In the event a user wants to use the Tresor certificate provider but also set their root CA to a different bit size than 2048, they should be able to.

**Comment by shashankram** [comment]
Done as a part of https://github.com/openservicemesh/osm/pull/3837
