### ISSUE TITLE
Add debug statement to log response contents (resources), nonce created and version being sent

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#3890]
We are missing a log line to properly log the contents of a response. The only log message we have is:

```
	// NOTE: Never log entire 'response' - will contain secrets!
	log.Trace().Msgf("Constructed %s response: VersionInfo=%s", response.TypeUrl, response.VersionInfo)
```

Which is missing proxy information, nonce and resource names being sent. It should be augmented with previous information (and made Debug?) to match other parts of the XDS state machine logging.

**Comment by shashankram** [comment]
Will revisit XDS state machine and logging enhancements separately.
