### ISSUE TITLE
osm-injector and osm-crd-converter not able to discover MeshConfig resource

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3904]
**Bug description**:
Both the osm-crd-converter and osm-injector pods show these messages & errors in the logs:
```
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:55Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"info","component":"osm-injector/main","time":"2021-07-30T21:33:55Z","file":"osm-injector.go:145","message":"Initial MeshConfig osm-mesh-config: {\n    \"sidecar\": {\n        \"resources\": {}\n    },\n    \"traffic\": {\n        \"inboundExternalAuthorization\": {}\n    },\n    \"observability\": {\n        \"tracing\": {}\n    },\n    \"certificate\": {},\n    \"experimental\": {\n        \"multicluster\": {}\n    },\n    \"featureFlags\": {}\n}"}
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:56Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"error","component":"configurator","error":"time: invalid duration \"\"","time":"2021-07-30T21:33:56Z","file":"methods.go:156","message":"Error parsing service certificate validity duration "}
{"level":"warn","component":"configurator","time":"2021-07-30T21:33:56Z","file":"client.go:200","message":"MeshConfig osm-system/osm-mesh-config does not exist. Default config values will be used."}
{"level":"error","component":"configurator","time":"2021-07-30T21:33:56Z","file":"methods.go:167","message":"Invalid key bit size: 0"}
```

Upon further inspection, this is probably occurring because the init-container for the osm-controller is what is creating the MeshConfig object called osm-mesh-config by reading the config map called preset-osm-config. However the osm-controller, injector, and crd-converter all get deployed at the same time which is probably resulting in a timing issue where the injector and crd-converter are trying to read the MeshConfig resource which doesn't exist.

One way to solve this would be have the injector and crd-converter wait until the MeshConfig resource is available.

**Affected area (please mark with X where applicable)**:
- Install                    [ X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Expect no errors in the osm-injector and crd-converter logs

**Steps to reproduce the bug (as precisely as possible)**:
Run the demo

**How was OSM installed?**:
Using the demo script

**Anything else we need to know?**:
No

**Environment**:
- OSM version (use `osm version`): main @ 65e567a6201910d681165656b1bb21329e4fa93f
- Kubernetes version (use `kubectl version`): v1.21.1
- Size of cluster (number of worker nodes in the cluster): Kind
- Others:

**Comment by snehachhabria** [comment]
> One way to solve this would be have the injector and crd-converter wait until the MeshConfig resource is available.
