### ISSUE TITLE
Integrate with SMI conformance GitHub action

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3948]
**Please describe the Improvement and/or Feature Request**
Use SMI conformance GitHub action, to run SMI conformance tests. Would love some feedback from the community on how often this should be done. On every merge to main, every PR or every release?

https://github.com/layer5io/meshery-smi-conformance-action

cc/ @navendu-pottekkat who is available for a walk through and any questions

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [X ]
- Demo                       [ ]
- Project Release            [X ]

**Possible use cases**
Tells us and the community if OSM is conformant with SMI and which parts.

**Comment by navendu-pottekkat** [comment]
Every release sounds like a good starting point.

I can open up a PR to add the workflow if I can coordinate with someone from the OSM team to add repository secret, setup an official account to automatically publish test results to the [SMI Conformance Dashboard](https://meshery.io/service-mesh-interface) it would be helpful.

You can use these docs to familiarise with the action and SMI Conformance with Meshery:

* [Running SMI Conformance Tests](https://docs.meshery.io/guides/smi-conformance#running-smi-conformance-tests-in-cicd-pipelines)
* [Meshery and SMI](https://docs.meshery.io/functionality/service-mesh-interface)
* [Service Mesh Interface Conformance with Meshery GitHub Action](https://github.com/marketplace/actions/service-mesh-interface-conformance-with-meshery)

_Meshery is SMI's official tool for validating conformance. Learn more at [smi-spec.io](https://smi-spec.io/blog/validating-smi-conformance-with-meshery/)._

**Comment by navendu-pottekkat** [comment]
@michelleN FYI, I have opened up a PR.
