### ISSUE TITLE
Error while running coverage test

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3957]
**Bug description**:
test coverage script shows below error
![image](https://user-images.githubusercontent.com/53465654/129148751-82057196-ee81-41f8-a080-3f219a9d561d.png)

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v0.9.1
- Kubernetes version (use `kubectl version`): 1.20
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by mudit-01** [comment]
can be fixed by uncommenting line 20 in https://github.com/openservicemesh/osm/blob/main/pkg/envoy/lds/wasm.go should I proceed?

**Comment by shashankram** [comment]
> can be fixed by uncommenting line 20 in https://github.com/openservicemesh/osm/blob/main/pkg/envoy/lds/wasm.go should I proceed?

No, that's required. 

What version of `Go` do you have installed? (`go version`)

**Comment by mudit-01** [comment]
I am using go version go1.16.6 linux/amd64

**Comment by shashankram** [comment]
@mudit-01 you need to embed the WASM binary for the tests to pass, so use the Makefile target that does this:
`make go-test-coverage`.

**Comment by shashankram** [comment]
> @mudit-01 you need to embed the WASM binary for the tests to pass, so use the Makefile target that does this:
> `make go-test-coverage`.

Closing this based on comment above, which should resolve the error.
