### ISSUE TITLE
OSM CLI: give more information for failed installations. 

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3960]
**Please describe the Improvement and/or Feature Request**

OSM CLI install command should give more information as to why an installation failed. Currently, the only message for failed installs is: 

`Error: failed pre-install: timed out waiting for the condition` 

More information is needed to address why the failure occurred. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [X]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
`osm install --verbose` should provide more info. Closing this.
