### ISSUE TITLE
Pipelines built off of main could fail if $${ github.sha }} images unavailable in dockerhub. 

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3961]
**Please describe the Improvement and/or Feature Request**

Currently, the OSM NoInstall nightly job and OpenShift nightly job set the $CTR_TAG to the GH actions variable ${{ github.sha }}, which corresponds with the most recent commit to main. For most runs this will be fine. However, if the most recent commit to main is a docs change or a scripts/cleanup change, then the OSM images for these commits will not be pushed to main, since the paths-ignore in main.yml is set to the following: 

`paths-ignore:
      - "docs/**"
      - "**.md"
      - "scripts/cleanup/**"`

Thus, the OSM NoInstall nightly job and OpenShift nightly jobs (as well as other future pipelines that run off of main) will error upon OSM installation, since the OSM components will try to search for and install OSM image tags that do not exist. 

This can be addressed by either changing the CTR_TAG so that it always points to the most recent commit hash that has been pushed to dockerhub. Another option is to have a separate github action from main.yaml that only runs the "Docker image" step for docks or scripts/cleanups changes. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by ksubrmnn** [comment]
I would check to see if the latest commit has a corresponding image and if not, I'd build new ones.

This way the tests will be resilient and cover any cases where perhaps our logic for pushing images from the PR runs is faulty.

**Comment by shashankram** [comment]
> I would check to see if the latest commit has a corresponding image and if not, I'd build new ones.
> 
> This way the tests will be resilient and cover any cases where perhaps our logic for pushing images from the PR runs is faulty.

I don't think we should be building new images when there is no change to the source code corresponding to the binaries the images are associated with. 
If the logic for pushing images is not correct, we should identify and address those gaps instead of masking them.

A straightforward solution would be to push images nightly with the `latest` tag, which the nightly jobs can use.
