### ISSUE TITLE
Allow for osm binary installs to be available post osm installation

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#3979]
**Please describe the Improvement and/or Feature Request**
OSM supports several project installation at install time using "osm install", but there is no way to install those applications post the osm installation. Support of all installation applications should be available with a "osm deploy" command.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
User deploys OSM with Jaeger and forgets to deploy Prometheus. User can use a command "osm deploy set=OpenServiceMesh.deployPrometheus=true" to update the osm mesh with the same Prometheus installation available with osm install --set=OpenServiceMesh.deployPrometheus=true

**Comment by shashankram** [comment]
There has been no ask for this use case. Will reopen when necessary.
