### ISSUE TITLE
Avg and Max Envoy Update Time metrics are incorrect

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#3987]
**Bug description**:
@eduser25 found that avg and max are showing 300/600s for update time, but the histogram doesn't show any update more than 0.1s
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/69616256/129599926-eced9e37-9205-4416-95fa-842b9330ae56.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/69616256/129599937-efe08d3b-78f4-4ad9-9754-8f2d70634c92.png)

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ x]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Comment by shalier** [comment]
Max update time can't be calculated using Prometheus 
https://groups.google.com/g/prometheus-users/c/4V3A0t6u9ME

**Comment by michelleN** [comment]
@shalier Thanks for pointing this out. How is update time being calculated today?
