### ISSUE TITLE
Active health checks only reflect draining status of Envoy, independent of actual application health status

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#4017]
**Bug description**:

Active health check doesn’t seem working. On the server side, Envoy receives the HC request, and always returns healthy, regardless of the status of the main containers. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

If the main container is not healthy on the server side, the client side should observe it as unhealthy.

**Steps to reproduce the bug (as precisely as possible)**:

In the OSM demo, run the following command.

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: errors
  namespace: bookstore
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bookstore
      purpose: fault
  template:
    metadata:
      labels:
        app: bookstore
        purpose: fault
    spec:
      serviceAccountName: bookstore-v1
      containers:
        - image: curlimages/curl
          imagePullPolicy: IfNotPresent
          name: curl
          command: ["sleep", "365d"]
EOF
```

The command adds 4 curl pods to bookstore service. Because they don't listen to any request, these pods should be seen as unhealthy.

When listing clusters on the client side (from bookbuyer):

```
> osm proxy get clusters bookbuyer-68b7d6b6c5-79njg -n bookbuyer | grep 'health'

envoy-metrics-cluster::127.0.0.1:15000::health_flags::healthy
osm-controller::10.96.141.68:15128::health_flags::healthy
bookstore/bookstore::10.244.1.15:14001::health_flags::healthy
bookstore/bookstore::10.244.2.13:14001::health_flags::healthy
bookstore/bookstore::10.244.2.12:14001::health_flags::healthy
bookstore/bookstore::10.244.1.16:14001::health_flags::healthy
bookstore/bookstore-v2::10.244.1.11:14001::health_flags::healthy
bookstore/bookstore-v1::10.244.2.10:14001::health_flags::healthy

```

Error pods are marked as healthy.

When looking at failed the response from bookstore:

```
> kubectl logs -n bookbuyer --selector app=bookbuyer -c bookbuyer -f

Fetching http://bookstore.bookstore.svc.cluster.local:14001/books-bought
Request Headers: map[Client-App:[bookbuyer] User-Agent:[Go-http-client/1.1]]
Error fetching http://bookstore.bookstore.svc.cluster.local:14001/books-bought: Get "http://bookstore.bookstore.svc.cluster.local:14001/books-bought": EOF
ERROR: response code for "http://bookstore.bookstore.svc.cluster.local:14001/books-bought" is 0;  expected 200
```

When looking at incoming requests in bookstore errors pod:

```
[2021-08-20 16:37:50.412][17][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:70] checking request: requestedServerName: bookstore.bookstore.svc.cluster.local, sourceIP: 10.244.2.14:56452, directRemoteIP: 10.244.2.14:56452, remoteIP: 10.244.2.14:56452,localAddress: 10.244.1.17:14001, ssl: uriSanPeerCertificate: , dnsSanPeerCertificate: bookbuyer.bookbuyer.cluster.local, subjectPeerCertificate: CN=bookbuyer.bookbuyer.cluster.local,O=Open Service Mesh, headers: ':authority', 'bookstore.bookstore.svc.cluster.local'
':path', '/healthz/osm'
':method', 'GET'
':scheme', 'https'
'user-agent', 'Envoy/HC'
'x-osm-envoy-healthcheck', '1'
'x-forwarded-proto', 'https'
'x-request-id', '40378307-1ac8-4789-ad54-be70c453739e'
, dynamicMetadata:
[2021-08-20 16:37:50.412][17][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:124] no engine, allowed by default
[2021-08-20 16:37:50.412][17][debug][lua] [source/extensions/filters/common/lua/lua.cc:39] coroutine finished
[2021-08-20 16:37:50.412][17][debug][http] [source/common/http/filter_manager.cc:883] [C3][S8350218856912366873] Sending local reply with details health_check_ok
[2021-08-20 16:37:50.412][17][debug][http] [source/common/http/conn_manager_impl.cc:1469] [C3][S8350218856912366873] encoding headers via codec (end_stream=true):
':status', '200'
'x-envoy-upstream-healthchecked-cluster', 'bookstore-v1.'
'date', 'Fri, 20 Aug 2021 16:37:50 GMT'
'server', 'envoy'

[2021-08-20 16:37:51.314][1][debug][main] [source/server/server.cc:209] flushing stats
```

Server side sidecar returns 200.

**How was OSM installed?**:

Change demo/run-osm-demo.sh script, by adding `--set=OpenServiceMesh.featureFlags.enableEnvoyActiveHealthChecks="true"` to the `osm install` command.

Then run `make kind-demo`.

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 
- Kubernetes version (use `kubectl version`): v1.21.3
- Size of cluster (number of worker nodes in the cluster): 1
- Others:

**Comment by allenlsy** [comment]
cc @nojnhuh

**Comment by nojnhuh** [comment]
This is intended for now, though I see I didn't make that clear in #3042 or #3840. I'll edit the title to better reflect the gap here.

From the [design doc](https://docs.google.com/document/d/1EZt2VTQ5SfHYG-52k78Al2tMnzLmVpzHe6NDADacJW0/edit?usp=sharing):
> Each service also uses Envoy’s health check HTTP filter to configure how it handles health requests from others. I opted to configure the HTTP filter with `pass_through_mode: false` which tells Envoy to respond with success to each health check request unless the server is [draining](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining) connections. Enabling pass through mode would involve passing health check requests to an existing endpoint on the service, which is better equipped to give a more accurate picture of the service’s actual health. Since each service may implement health endpoints differently, this is much harder to configure than with pass through mode disabled where Envoy itself will respond to the health check request so we can configure that the same way for any service in the mesh.

**Comment by allenlsy** [comment]
Thanks for the clarification. Closing this issue.
