### ISSUE TITLE
retries: Determine what to retry on

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#4031]
**Please describe the Improvement and/or Feature Request**

For retry policy there are a list of possible fields for when to retry a request, which ones should be included as possible options for users to use? Parent Issue: #3338
- 5xx
- gateway-error
- reset
- connect-failure
- envoy-ratelimited
- retriable-4xx
- refused-stream
- retriable-status-codes
- retriable-headers

[For details on each option](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on)

**Scope (please mark with X where applicable)**
- New Functionality          [ x]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
Pretty old issue. @shalier Kindly create a single issue for the retry policy feature work if an issue doesn't exist already.
