### ISSUE TITLE
Upgrade test fails when minKubeVersion is bumped

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#4068]
**Bug description**:
The upgrade test fails for the release-v0.9 branch. This issue still needs to be root caused

https://github.com/openservicemesh/osm/runs/3426497621
```
• Failure [62.565 seconds]
[Tier 2][Bucket 10] Upgrade from latest
/home/runner/work/osm/osm/tests/framework/common.go:139
  Tests upgrading the control plane [It]
  /home/runner/work/osm/osm/tests/e2e/e2e_upgrade_test.go:28

  Unexpected error:
      <*errors.fundamental | 0xc0009c7c20>: {
          msg: "chart requires kubeVersion: >= 1.19.0-0 which is incompatible with Kubernetes v1.18.0",
          stack: [0x1897690, 0x189acde, 0x1aadfa8, 0x77e5c3, 0x77e17c, 0x77d4a7, 0x78488f, 0x783f32, 0x7ace31, 0x7ac947, 0x7ac157, 0x7ae926, 0x7be018, 0x7bdca7, 0x1a59e78, 0x52b48f, 0x472521],
      }
      chart requires kubeVersion: >= 1.19.0-0 which is incompatible with Kubernetes v1.18.0
  occurred

  /home/runner/work/osm/osm/tests/e2e/e2e_upgrade_test.go:100
```
**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
The test should pass regardless of min k8s version

**Steps to reproduce the bug (as precisely as possible)**:
Run the upgrade e2e across two charts with diff minimum k8s version

**How was OSM installed?**:
CI
**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 
- Kubernetes version (use `kubectl version`): 1.21 (kind)
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
OSM v0.9 supports k8s v1.18.0+, while OSM v0.10 supports v1.19.0+,  so upgrading from v0.9 -> v0.10 requires the underlying k8s cluster to be upgraded.

This needs to be documented and the e2 test needs to be updated to work around this if necessary.

**Comment by ksubrmnn** [comment]
Upgrade job now passing in release-v0.9

**Comment by ksubrmnn** [comment]
> OSM v0.9 supports k8s v1.18.0+, while OSM v0.10 supports v1.19.0+, so upgrading from v0.9 -> v0.10 requires the underlying k8s cluster to be upgraded.
> 
> This needs to be documented and the e2 test needs to be updated to work around this if necessary.

Captured this in new issue #4107
