### ISSUE TITLE
Cluster endpoint load balancing weight assignment is possibly 0

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#4092]
**Bug description**:

https://github.com/openservicemesh/osm/blob/5c491ac24f7893b088eb52ffe60b84214d328da2/pkg/envoy/eds/cluster_load_assignment.go#L42

Endpoint weight is calculated as 100 divide by number of endpoints. When a cluster has more than 100 endpoints, this value will be 0. This is not allowed by Envoy. 

Tested using my docker-compose load balancing demo. When weights are manually set to 0, Envoy will raise an error and stop running:

```
[1][warning][config] [source/common/config/filesystem_subscription_impl.cc:43] Filesystem config update rejected: Proto constraint validation failed (ClusterValidationError.LoadAssignment: embedded message failed validation | caused by ClusterLoadAssignmentValidationError.Endpoints[0]: embedded message failed validation | caused by LocalityLbEndpointsValidationError.LoadBalancingWeight: value must be greater than or equal to 1): name: "backend"
```

If the intention is to set each endpoint an equal weight, according to Envoy doc here, we don't need to set any weight to it: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-lbendpoint

> If unspecified, each host is presumed to have equal weight in a locality. The sum of the weights of all endpoints in the endpoint’s locality must not exceed uint32_t maximal value (4294967295).

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

When more than 100 endpoints are in a cluster, Envoy should keep running.

**Steps to reproduce the bug (as precisely as possible)**:

Using the demo script, and manually set endpoint weight to 0 here: https://github.com/allenlsy/envoyproxy-locality-weighted-lb-demo/blob/master/configs/cds.yaml#L20

**How was OSM installed?**:

Not reproduced using OSM.

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by allenlsy** [comment]
cc @shashankram

**Comment by shashankram** [comment]
> If the intention is to set each endpoint an equal weight, according to Envoy doc here, we don't need to set any weight to it: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#config-endpoint-v3-lbendpoint

@allenlsy this makes sense and is the intention. Would you mind fixing this bug?

**Comment by allenlsy** [comment]
Yes, I can assign it to myself. I would create a separate PR for the fix, since it needs some more testing.
