### ISSUE TITLE
Move demo into a separate repo

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4095]
Conceptually, the bookstore demo should be completely decoupled from OSM implementation details. Separating the OSM and demo source code will help enforce this distinction.

The most sensitive areas of OSM to this change are demo documentation and CI tests. The core of OSM shouldn't need any modification that would adversely affect stability.

**Comment by shashankram** [comment]
The demo manifests have been moved to the osm-docs repo.

**Comment by nojnhuh** [comment]
This issue is to track all of the demo, including source code for the book* services and scripts. The manifests referenced in the docs are just one piece.

**Comment by shashankram** [comment]
> This issue is to track all of the demo, including source code for the book* services and scripts. The manifests referenced in the docs are just one piece.

I don't think we should be increasing the maintenance overhead by moving the automated demo manifests outside the osm repo. It is being used by the CI and developers and seems well suited to be within the osm repo. Sometimes it's also helpful to evolve the demo with new features (e.g. mySQL integration) so having the automated demo within the osm repo makes a lot more sense to me.

**Comment by snehachhabria** [comment]
I think i agree with @shashankram here, we are not yet ready to move all the demo related code to a separate repo. As of today, having it as a part of osm will help with faster turnaround, be it testing one's changes locally or extending out the demo to cover newly developed scenarios/ integrations

**Comment by nojnhuh** [comment]
Closing since we're not planning to do this anytime soon.
