### ISSUE TITLE
inconsistent spaces in sidebar

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4161]
**Please describe what should be documented**
In the docs website https://docs.openservicemesh.io/  the sidebar as some space issue in alignment.
![sidebar](https://user-images.githubusercontent.com/53465654/134461931-58fa3b5e-789e-450d-9579-e02176fce5d9.jpg)
Are these intentional?
**Please suggest where in the repo the document should be located**

**Comment by shashankram** [comment]
Moved this issue to the osm-docs repo: https://github.com/openservicemesh/osm-docs/issues/189
Closing this one. Thanks @mudit-01 for reporting.
