### ISSUE TITLE
Create a Prometheus counter for invalid SMI policies

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#4187]
In places like https://github.com/openservicemesh/osm/pull/4177/files#diff-af1c6a20af9b063e6884179e1dd6c64b53a5a33ada281679393f66162344dd88R294 we created tools and watch for invalid TrafficTargets.

This task is to create a Prometheus counter for invalid SMI policies.

It would be of great value to have a dashboard that shows how many invalid SMI policies are currently on a given OSM-enabled cluster.

**Comment by jaellio** [comment]
**Specifically regarding TrafficTarget metrics**
Some errors related to invalid TrafficTarget configurations are captured by the error code metric. For example, `ErrInvalidDestinationKind` and `ErrInvalidSourceKind`. I see several options for how to collect metrics for invalid TrafficTargets
1. Use the existing ErrCodeCounter Prometheus metric, and
    1. Combine all invalid TrafficTarget related errors into a single error, ErrInvalidTrafficTarget
    2. Create an error for each unique TrafficTarget configuration error
2. Create a `InvalidTrafficTargetCount` Prometheus metric
    1. Increment the counter for all possible TrafficTarget configuration errors

**Invalid SMI policy metric**
Here are several options for creating a general metric for all invalid SMI policies
1. Use the exiting ErrCodeCounter Prometheus and 
    2. Combine all invalid SMI policy errors into a single error, ErrInvalidSMIPolicy
2. Create a `InvalidSMIPolicyCount` metric 
    3. Use a counter metric
    4. Use a vector counter metric and use a label to specify why the policy was invalid (similar to the ErrCodeCounter)
