### ISSUE TITLE
NoInstall Nightly Job Failing

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#4208]
**Bug description**: The OSM NoInstall Nightly Job is consistently failing the e2e_validate_smi_traffic_target_test. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- Demo                       [ ]
- CI System                  [X]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
> The OSM NoInstall Nightly Job is consistently failing the e2e_validate_smi_traffic_target_test

Seems to be related to the newly added test by @michelleN
