### ISSUE TITLE
Document performance

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4223]
**Please describe what should be documented**
Although the documentation should be created in the `osm-docs` repo, filing this issue here for tracking purposes.

The issue proposes to document the performance of OSM components under heavy load:
- OSM control plane CPU and memory usage
- Envoy proxy CPU and memory usage
- Latency introduced by Envoy proxy

The load test should consist of the following at minimum (values are based on reasonable estimations):
- 1000 services
- 1000 pods
- 20000 requests per second throughout the mesh

**Comment by allenlsy** [comment]
We will split this issue into two:

* Document on OSM performance
* Document on OSM scalability

Thus a new issue will be created for scalability documentation and this issue will be updated to only document on performance.

These results are still valid for performance documentation.

**Comment by allenlsy** [comment]
PR for the document: https://github.com/openservicemesh/osm-docs/pull/309

**Comment by allenlsy** [comment]
PR is merged. https://github.com/openservicemesh/osm-docs/pull/342
