### ISSUE TITLE
update osm_components_interactions.md

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#4226]
osm/docs/development_guide/osm_components_interactions.md needs to be updated as it is no longer the correct representation of how the components in osm interact

**Comment by allenlsy** [comment]
@snehachhabria I think [osm_components_interactions.md](https://github.com/openservicemesh/osm/blob/main/docs/development_guide/osm_components_interactions.md) is not needed any more. The content overlaps with [design.md](https://github.com/openservicemesh/osm/blob/main/DESIGN.md#osm-components--interactions). I will update design.md instead.
