### ISSUE TITLE
Batch proxy update events received in close proximity

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4238]
**Bug description**:
Proxy update events received in close proximity must be throttled to avoid repeated proxy updates for all proxies in a hot loop. Proxy updates received in a given window must be batched to generate as few proxy update events as possible.

The batching mechanism can be implemented in `pkg/messaging/broker.go`.

**Affected area (please mark with X where applicable)**:
- Performance                    [X]

**Comment by eduser25** [comment]
Did not realize the previous coalescence mechanism was also gone with your refactor.
yap, this is pretty much a must.
