### ISSUE TITLE
Using --set for array/string values result in incorrect preset-mesh-config JSON data

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4239]
**Bug description**:
`charts/osm/templates/preset-mesh-config.yaml` encodes the `preset-mesh-config` MeshConfig resource as a JSON data in a ConfigMap, which is then unmarshalled to the `MeshConfig` type by `osm-bootstrap`. When using `--set` to override default
array/string values in the preset-mesh-config, it could render the JSON value incorrectly.

E.g. When using `--set="OpenServiceMesh.outboundIPRangeExclusionList={1.1.1.1/32,2.2.2.2/24}"`, the value `[1.1.1.1/32 2.2.2.2/24]` is not a valid JSON value, but is a valid YAML value due to quotes missing for the items in the array.

The same applies to string values that need to be quoted in JSON.

```
# Source: osm/templates/preset-mesh-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: preset-mesh-config
  namespace: default
data:
  preset-mesh-config.json: |
    {
      "traffic": {
        "outboundIPRangeExclusionList": [1.1.1.1/32 2.2.2.2/24]
```

Please investigate whether the data in the ConfigMap can be encoded in YAML format, and if not possible, ensure the set overrides result in valid JSON data.

**Affected area (please mark with X where applicable)**:
- Install                    [X]

**Expected behavior**:
Array and string values set via `--set` Helm option should result in a valid MeshConfig resource.

**Comment by michelleN** [comment]
I'll update the values in this template to use the `mustToJson` helm template function which transforms an input from the yaml file to valid Json and returns an error if it can't be converted.
