### ISSUE TITLE
Main README.md points to broken link for OSM Development Guide

### ISSUE THREAD

**Issue by clarenceb** [openservicemesh/osm#4280]
**Please describe what should be documented**

In the main README.md:

If you would like to contribute to OSM, check out the development guide.

The link points to: https://github.com/openservicemesh/osm/blob/main/docs/dev_guide/README.md
but it should point to: https://github.com/openservicemesh/osm/blob/main/docs/development_guide/README.md

**Please suggest where in the repo the document should be located**

https://github.com/openservicemesh/osm/blob/main/README.md

**Comment by bridgetkromhout** [comment]
Thanks! Looks like this was resolved in https://github.com/openservicemesh/osm/issues/4321.
