### ISSUE TITLE
cli: osm version should return client and server versions

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#4289]
Current `osm version` returns the  following:
```
$ ./osm version
Version: v1.0.0-rc.1; Commit: 9b3fba88ab5b42f670986d9f516219731e9a4b3f; Date: 2021-10-13-18:13
```

Ideally this would return the version of the OSM Controller(s) as well.

Additionally `Commit` could be shortened to the first 7 characters of the commit hash -- `9b3fba8` for readability.

Could we also put the Version, Commit hash and Date on separate lines?

**Comment by mudit-01** [comment]
Hi @draychev would like to pick this up.
we would like to look at the output like this?
![image](https://user-images.githubusercontent.com/53465654/138213539-f0a7a0fe-06bc-4d09-b5dc-0f96aee1bbb1.png)

**Comment by jaellio** [comment]
@draychev Currently, the `osm mesh list` command displays a list of all meshes in a cluster and their versions. This does not contain the build date or commit id. The `osm mesh list` command could be augmented to include those fields. `osm version` could also be augmented to include the build version of the installed mesh.

```
CLI
   Version: v1.0.0-rc.2
   Commit:  bee1cac
   Date: 2021-11-15-17:21

MESH NAME   MESH NAMESPACE   VERSION       COMMIT ID   BUILD DATE
osm         osm-system       v1.0.0-rc.2   bee1cac     2021-11-15-17:21
```

A `version` option could also be added to `osm mesh`. The output could be something like the following:
```
osm mesh version

MESH NAME   MESH NAMESPACE   VERSION       COMMIT ID   BUILD DATE
osm         osm-system       v1.0.0-rc.2   bee1cac     2021-11-15-17:21

```

**Comment by johnsonshi** [comment]
Already resolved through https://github.com/openservicemesh/osm/pull/4395
