### ISSUE TITLE
initContainer should be idempotent

### ISSUE THREAD

**Issue by nasuku** [openservicemesh/osm#4307]
**Bug description**:
The sidecar containers should be idempotent. Currently they are not. More details below..

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
In k8s environments, initContainers can get restarted after the actual pod is up and running.
Discussion about it is in https://github.com/kubernetes/kubernetes/issues/67261
This is triggered by 'docker system prune -af' on the worker nodes which are running the pods.

kubelet starts the initContainers and they fail because 
iptables -t nat -N PROXY_INBOUND
command fails saying
iptables: Chain already exists.

While we can argue that proper fix needs to come from kubelet side, there is also a requirement from k8s that initContainers should be idempotent. please see
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

Can we take some sample approach like istio's fix for this issue:
 https://github.com/istio/istio/pull/33839
i.e if initContainer ran successfully, store the state and at the start of initContainer check if it was initialized before and skip further initiallization

**Steps to reproduce the bug (as precisely as possible)**:
please do 'docker system prune -af' on a worker node and you should see that initContainer on the pod is restarted and keeps failing

**Comment by shashankram** [comment]
Hey @nasuku, I am unable to reproduce this using `docker system prune -af` on my local Kind cluster. That being said, I did figure out a way to make the iptables rules execution idempotent. If there's a way this can be consistently reproduced, kindly share the steps in detail.

Thanks

**Comment by nasuku** [comment]
@shashankram  - my setup was a ubuntu VM running k8s (not KIND) based on k8s version 1.21 .
Your changes look great.
