### ISSUE TITLE
Planning Milestone v1.1.0

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#4349]
This GitHub Issue is to be used for planning Open Service Mesh release v1.1.0

Please comment with recommendations on GitHub Issues or general areas that we should bundle with the v1.1.0 release.

**Comment by draychev** [comment]
Proposed tasks for v1.1.0:

- #4351
-

**Comment by snehachhabria** [comment]
Closing this as we will be planning v1.1.0 differently
