### ISSUE TITLE
Forbidden errors when accessing service randomly when using opa-envoy-plugin with external authorization 

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [openservicemesh/osm#4374]
We deployed opa-envoy-plugin for external authorization with v 0.11 of OSM on AKS cluster for authorization based on JWT bearer token audience. We followed instructions mentioned in [Link](https://release-v0-11.docs.openservicemesh.io/docs/guides/integrations/external_auth_opa/). Most of the test http calls made with curl command work as expected. However, we noticed the service calls from our test client randomly fail with forbidden errors. In order to test we made all calls set to allow=true in opa configmap. Even then the calls are getting dropped leading to the assumption that calls are getting dropped even before reaching the filter. Can you please assist in debugging this issue?
Mesh Config:
![image](https://user-images.githubusercontent.com/19557867/143149567-a9f1d7ef-2afc-4028-b3af-833e91acc80b.png)

Test opa config map:
![image](https://user-images.githubusercontent.com/19557867/143149621-1e137a36-8565-4f87-8e41-59475395d541.png)

**Comment by allenlsy** [comment]
We have discussed offline with @SoujanyaMangipudi . As we were not able to reproduce the issue since the it only failed randomly, and Soujanya is not actively using OPA plugin right now, we are putting this issue to the backlog for now.

**Comment by shashankram** [comment]
>  As we were not able to reproduce the issue since the it only failed randomly

Closing this as it's not reproducible.
