### ISSUE TITLE
In cluster service connectivity not working with permissive mode

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [openservicemesh/osm#4378]
Deployed Open Service Mesh v0.11 to Azure Kubernetes Services cluster. Enabled permissive traffic policy mode. But calls to service within clusters are failing with following error 
![image](https://user-images.githubusercontent.com/19557867/143940505-e85dc8db-799e-4fa3-992e-e5788a1c2885.png)

Mesh config 
![image](https://user-images.githubusercontent.com/19557867/143940558-ff3e2e1c-9d4d-43f1-afbc-45313e49011f.png)

Both services and namespaces are added to osm. Also I could not find any logs in envoy side cards for either source or destination pods. 
Please suggest how this can be debugged further

**Comment by SoujanyaMangipudi** [comment]
Following are the snapshots of errors I am seeing when running osm-health for pod-to-pod and pod-to-url 
[osm-health-logs.txt](https://github.com/openservicemesh/osm/files/7622254/osm-health-logs.txt)

**Comment by allenlsy** [comment]
Destination service IP 10.0.211.171 is within the excluded outbound IP range 10.0.0.0/16, thus the traffic stopped going through the IPTables filtering process, the request cannot be routed within the mesh.  Removing 10.0.0.0/16 should resolve the issue.

This is also related to https://github.com/openservicemesh/osm/issues/4375

**Comment by shashankram** [comment]
> Destination service IP 10.0.211.171 is within the excluded outbound IP range 10.0.0.0/16, thus the traffic stopped going through the IPTables filtering process, the request cannot be routed within the mesh. Removing 10.0.0.0/16 should resolve the issue.
> 
> This is also related to #4375

Closing based on the above update.
