### ISSUE TITLE
Sidecar injection annotation added with no value

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4385]
**Bug description**:

When adding a namespace to the mesh with sidecar injection disabled the namespace is patched with a sidecar injection annotation with a value of null. The expected behavior is that an annotation with a value of null will be ignored if the annotation key does not already exist or will remove the annotation when applied if it already exists on the namespace. Currently, when the patch is made on a namespace that does not have the sidecar injection annotation key (or any other annotation), the annotation is added with a value of "" rather than being ignored.

For example, the following patch command produces different results when applied to namespaces with and without the sidecar injection annotation.

`kubectl patch namespace --type=strategic test -p '{"metadata":{"annotations":{"openservicemesh.
io/sidecar-injection":null}}}'`

If the annotation doesn't exist it will be added to the namespace as `openservicemesh.io/sidecar-injection:""`. If the annotation exists with any value (including "") the above command will remove the annotation.

This unexpected behavior results in admission errors in the osm-injector when pods are created in the namespace with sidecar injection disabled. 

```txt
{"level":"error","component":"sidecar-injector","error":"Invalid annotation value for key \"openservicemesh.io/sidecar-injection\": ","error_code":"E6109","time":"2021-12-01T02:32:43Z","file":"webhook.go:309","message":"Error determining if namespace test is enabled for sidecar injection"}
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [x]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

1. Install OSM
2. Create a namespace
3. Add the namespace to the mesh with sidecar injection disabled
    `osm namespace add test --disable-sidecar-injection`
4. Run `kubectl get ns test -o jsonpath='{.metadata.annotations}'`. Nothing should be returned, but I get the following output `{"openservicemesh.io/sidecar-injection":""}`
5. Add a pod to the namespace. For example, deploy the httpbin application: `kubectl apply -f https://raw.githubusercontent.com/openservicemesh/osm/main/docs/example/manifests/samples/httpbin/httpbin.yaml -n test`
6. Grep the osm injector logs for errors. `kubctl logs -n osm-system <injector pod> | grep "error"`. Something similar to this error should be found:
``` bash
{"level":"error","component":"sidecar-injector","error":"Invalid annotation value for key \"openservicemesh.io/sidecar-injection\": ","error_code":"E6109","time":"2021-12-01T02:32:43Z","file":"webhook.go:309","message":"Error determining if namespace test is enabled for sidecar injection"}
```

**How was OSM installed?**:
```bash
osm install --set=osm.enablePermissiveTrafficPolicy=true \
    --set=osm.deployPrometheus=true \
    --set=osm.deployGrafana=true \
    --set=osm.deployJaeger=true
```

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): replicated on the current main and v0.11.1
- Kubernetes version (use `kubectl version`): v1.22.1
- Size of cluster (number of worker nodes in the cluster): kind and aks cluster, 2 nodes
- Others:

**Comment by shashankram** [comment]
@jaellio this seems like an issue in Kubernetes, because previously patching the key with null was equivalent to deleting the key.  E.g. `kubectl patch namespace --type=strategic test -p '{"metadata":{"annotations":{"openservicemesh.io/sidecar-injection":null}}}'` would remove the annotation key regardless of whether it was present or not.

Can we try using JSON patch instead of strategic merge patching to see if it resolves the issue?

**Comment by trstringer** [comment]
Same thing happens with a JSON patch:

```
 $ kubectl patch namespaces test --type=json --patch='[{"op":"add","path":"/metadata/annotations","value":{"openservicemesh.io/sidecar-injection":null}}]'
namespace/test patched
~
 $ kubectl get ns test -o jsonpath='{.metadata.annotations}'
{"openservicemesh.io/sidecar-injection":""}
```

**Comment by trstringer** [comment]
Interestingly enough, this behavior seems to happen because there are no annotations originally (and therefore the `annotations` key doesn't exist in the dynamic object). If there are existing annotations, the behavior is as expected:

```
 $ kubectl annotate ns test hello=world
namespace/test annotated
~
 $ kubectl get ns test -o jsonpath='{.metadata.annotations}'
{"hello":"world"}
~
 $ kubectl patch ns test --type=strategic --patch='{"metadata":{"annotations":{"openservicemesh.io/sidecar-injection":null}}}'
namespace/test patched (no change)
~
 $ kubectl get ns test -o jsonpath='{.metadata.annotations}'
{"hello":"world"}
```
