### ISSUE TITLE
ingressBackend doesn't validate or document available kinds

### ISSUE THREAD

**Issue by tdihp** [openservicemesh/osm#4391]
**Bug description**:

A.T. Reviewing the source code and documentation, I cannot find [validator](https://github.com/openservicemesh/osm/blob/f262ef5d5bb6fbde1a06eadd31f7575cd6ad46ef/pkg/validator/validators.go#L79) or the [policy logic](https://github.com/openservicemesh/osm/blob/e9ec05f5152b5e090af46b4d9c0d24fa578ca1c4/pkg/catalog/ingress.go#L57) includes validation of available kinds. Not even a warning. I'm able to conclude the same by modifying `"kind": "Service"` to `"kind": "Foobar"` without getting a warning or validation failure. And I'm not able to find documentation on `KindIPRange`.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ x]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

* To have all kind documented with available parameters
* To have verification and warn user if a unsupported kind is used

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

AKS addon

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 0.11.1
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (number of worker nodes in the cluster): 2
- Others:

**Comment by shashankram** [comment]
@tdihp the validator has been updated to validate IngressBackend sources and the docs have been updated to demonstrate usage of various source kinds. The changes will be available in the next release, v1.0.0 version. You can find a preview of the documentation at https://main--osm-docs.netlify.app/docs/guides/traffic_management/ingress/#ingressbackend-api with examples at https://main--osm-docs.netlify.app/docs/guides/traffic_management/ingress/#examples.
