### ISSUE TITLE
When proxy connections to HTTPS backend, nginx-ingress cannot pick up new certificate

### ISSUE THREAD

**Issue by ksooner** [openservicemesh/osm#4393]
**Bug description**:
Configured the ingress following this demo, and it worked for a period of time https://release-v0-11.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/.

After 24-25 Hrs, Error similar below in nginx logs can be seen
37#37: *2025387 SSL_do_handshake() failed (SSL: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:SSL alert number 45) while SSL handshaking to upstream, client: 127.0.0.1, server: name1.example.com, request: "GET /httpbin/get HTTP/2.0", upstream: "https://10.10.250.166:14001/get", host: "name1.example.com"

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [X ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
nginx proxy the traffic as usual

**Steps to reproduce the bug (as precisely as possible)**:
Just follow the demo page

**How was OSM installed?**:
AKS add on

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 0.11.1
- Kubernetes version (use `kubectl version`): 1.20.7
- Size of cluster (number of worker nodes in the cluster): 
- Others: 
   tested with nginx-ingress 0.42.0, 0.50.0, and 1.1.0

**Comment by draychev** [comment]
Hi @ksooner, I have been chasing this same problem and just filed this GitHub Issue: #4394

@ksooner, if you have a cluster on which you can repro this - would you be so kind to perform the following:
1. save the mTLS secret locally
2. delete the mTLS secret from the cluster
3. reapply the same secret (which we saved locally in 1) back - without any modifications.

Here is a script to do this:
```bash
#!/bin/bash

FN=osm-nginx-client-cert.temp.crt
kubectl get secrets -n ingress-nginx osm-nginx-client-cert -o yaml > $FN
kubectl delete secrets -n ingress-nginx osm-nginx-client-cert
kubectl apply -f $FN
```

The script assumes the k8s secret is in namespace `ingress-nginx` and is called `osm-nginx-client-cert` - please change these to match your setup.

Here is an issue we filed against NGINX Ingress Controller on this issue:  https://github.com/kubernetes/ingress-nginx/issues/5608

**Comment by shashankram** [comment]
This is an issue in Nginx ingress controller that is now addressed, see https://github.com/kubernetes/ingress-nginx/issues/5608.
There is an open issue (https://github.com/openservicemesh/osm/issues/4394) to work around this in OSM. 

Closing this one as it's a combination of the 2 issues listed above, both of which are tracked.
