### ISSUE TITLE
Provide an option to configure exclude InboundPorts for interception at pod level

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [openservicemesh/osm#4397]
The ask is to provide an option to configure exclude InboundPorts for interception at pod level. 

New Functionality [X]
Install [ ]
SMI Traffic Access Policy [ ]
SMI Traffic Specs Policy [ ]
SMI Traffic Split Policy [ ]
Permissive Traffic Policy [ ]
Ingress [ ]
Egress [X]
Envoy Control Plane [ ]
CLI Tool [ ]
Metrics [ ]
Certificate Management [ ]
Sidecar Injection [ ]
Logging [ ]
Debugging [ ]
Tests [ ]
CI System [ ]
Demo [ ]
Project Release [ ]

We currently use similar feature with istio service mesh. We use this option to bypass traffic interception for dotnet monitor that we use for service monitoring. Having this option in OSM will make our migration simpler.

**Comment by shashankram** [comment]
@SoujanyaMangipudi this is already supported, see https://release-v0-11.docs.openservicemesh.io/docs/guides/traffic_management/iptables_redirection/#2-pod-scoped-inbound-port-exclusions
