### ISSUE TITLE
Consolidate output for mesh list

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4399]
**Please describe the Improvement and/or Feature Request**

osm mesh list command output can be merged into a single table
SMI Supported column can be added instead of a new table.
![image](https://user-images.githubusercontent.com/53465654/146345219-5669980a-db01-4d53-b1f7-9169e1499398.png)

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by mudit-01** [comment]
If needed I can work on this

**Comment by trstringer** [comment]
What would be interesting here is if `osm mesh list` just showed a select few short columns like name, namespace, and version. And following the example of `kubectl` we could have a `-o wide` option to add additional (lengthy) data, such as namespaces and SMI versions.

**Comment by mudit-01** [comment]
@trstringer Thanks for the suggestion, I will look into it and how to implement the same to `osm mesh list` command 👍🏽
