### ISSUE TITLE
Use of mesh and namespace in docs vs code

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4405]
**Bug description**:
In code https://github.com/openservicemesh/osm/blob/main/cmd/cli/version.go there is mention of `No mesh found in namespace`
As a newbie to OSM I thought we add namespaces to mesh as per the documentation. What should be the correct way?

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
> As a newbie to OSM I thought we add namespaces to mesh as per the documentation. What should be the correct way?

https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/namespaces/ describes how to add a namespace to the mesh.
