### ISSUE TITLE
"osm install" should show warning msg about single-mesh-enforcement preventing multiple installs

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4438]
**Bug description**:

When an existing osm mesh is already installed with single mesh enforcement (default true), and “osm install” is run again, the cli should warn that installation cannot proceed because of single-mesh-enforcement.

As of now, the cli does not make this fact clear, and instead prevents installation by prompting the user to run the install command again with a new mesh name and mesh namespace. It should instead warn users that installation cannot proceed because of single mesh.

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Appropriate prompt

**Steps to reproduce the bug (as precisely as possible)**:

- Install osm with single mesh enforcement (default true). Installing again with various options show incorrect prompt.

![image](https://user-images.githubusercontent.com/13926417/149272785-fc2a597c-026c-4d76-9aa2-ce3406b12a01.png)

![image](https://user-images.githubusercontent.com/13926417/149272866-717ebb6c-eac2-4311-8a60-059450b059e3.png)

**How was OSM installed?**: See above.

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0-rc.3
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shalier** [comment]
picking up this issue

**Comment by snehachhabria** [comment]
@shalier are you currently working on this? If not, please unassing yourself
