### ISSUE TITLE
"osm uninstall mesh" prompts user to uninstall non-existent mesh if there are no meshes installed

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4439]
**Bug description**:

When osm is not installed in the cluster but “osm uninstall” cli command is run, the cli prompts the user to uninstall a non-existent mesh.

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: If no mesh is installed, do not prompt user to uninstall non-existent mesh.

**Steps to reproduce the bug (as precisely as possible)**:

![image](https://user-images.githubusercontent.com/13926417/149273281-6a4b3bd7-a47e-4a0d-8af1-a5e93f4aac3c.png)

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0-rc.3
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
This is pretty cosmetic given that the CLI correctly detects that a mesh does not exist:
```
$ osm uninstall mesh -f
$ osm uninstall mesh 

List of meshes present in the cluster:
No osm mesh control planes found

Uninstall OSM [mesh name: osm] in namespace [osm-system] ? [y/n]: y
Error: No OSM control plane with mesh name [osm] found in namespace [osm-system]
```

The enhancement would be to avoid the prompt if no mesh exists.
