### ISSUE TITLE
"osm install --enforce-single-mesh false" never allows multiple mesh installations

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4441]
**Bug description**: Currently, the enforce-single-mesh flag has no effect (single mesh seems to be hardcoded by default). 

(1) Additionally during install, `osm install` command should go through all pre-existing meshes enforce-single-mesh value before proceeding/aborting.
(2) additionally, during install, if the second time `osm install` runs with `enforce-single-mesh true`, the installation should abort even if the existing mesh says `enforce-single-mesh false`.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: The code block below is supposed to succeed when the second `osm install` is run - this is because of `--enforce-single-mesh false` option.

**Steps to reproduce the bug (as precisely as possible)**:

```
bin/osm mesh list
kubectl get ns -A
bin/osm install --enforce-single-mesh false
bin/osm install --enforce-single-mesh false --mesh-name osm-2 --osm-namespace osm-system-2
```

![image](https://user-images.githubusercontent.com/13926417/149273979-2c6aad8a-5510-4471-8c4a-fa9fbd832033.png)

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0-rc.3
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shalier** [comment]
@johnsonshi To set enforce-single-mesh to false there should be an = sign
![image](https://user-images.githubusercontent.com/69616256/152435063-cab1df7d-b10c-41d5-ae60-7d676f9cb030.png)
