### ISSUE TITLE
"osm uninstall mesh" and "osm namespace ignore [ns]" should remove osm-related labels and annotations from monitored namespace + pods

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4444]
**Bug description**: During `osm uninstall mesh`, all monitored namespaces (and monitored pods in these ns) should have their osm-related annotations and labels REMOVED. Another scenario is `osm namespace ignore [ns]` - [language from osm docs](https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/namespaces/#ignore-a-namespace) indicate that once a mesh is set to be `ignored`, it should no longer participate in the mesh so osm-related labels/annotations have to be removed.

Labels that should be removed include osm's sidecar-injection, osm's monitored-by, openserviceh.io/metrics.

Additional candidates for removal include osm's prometheus scraping labels and osm's pod ip exclusion labels.

Labels that should NOT be removed include osm-ignore label, as the ignore label is designed to mark a namespace as being permanently excluded from osm-related operations (as long as the ignore label is in place and not explicitly removed by the user).

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: osm-related labels and annotations should be removed from monitored namespaces. After running `osm uninstall mesh`, `osm namespace list` should not list namespaces like in the scenario below.

Additionally, `osm namespace list` should show a list of "orphaned" ignored namespaces. These are namespaces where the `monitored-by` label has been removed but the namespace still has the `ignored` label left in place.

**Steps to reproduce the bug (as precisely as possible)**:

![image](https://user-images.githubusercontent.com/13926417/149275380-438bc217-bf15-444c-8493-1587825fabb8.png)

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0-rc.3
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by mudit-01** [comment]
I would like to work on this
