### ISSUE TITLE
"osm namespace add ns" and "osm metrics enable ns" should abort if namespace has ignore label

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4445]
**Bug description**: Language in [osm docs for `osm ignore`](https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/namespaces/#ignore-a-namespace) suggests that as long as a namespace has the `ignore` label, it should NEVER be a part of a mesh. As a consequence, if a pod has been marked with ignore, adding the namespace or enabling metrics should abort.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**: Below shows 

```
bin/osm install
kubectl create ns abc
bin/osm namespace ignore abc
bin/osm namespace add abc # should NOT succeed
bin/osm metrics enable --namespace abc # should NOT succeed

kubectl get namespace abc -o yaml
```

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0-rc.3
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by mudit-01** [comment]
I would like to work on it pls assign it to me.

**Comment by johnsonshi** [comment]
Sure @mudit-01 that would be greatly appreciated! <3

**Comment by allenlsy** [comment]
What does `"if a pod has been marked with ignore, "` in the description? Is it possible that a namespace is not ignored, but only the pod it the namespace has the ignore label?
