### ISSUE TITLE
Why SMI TrafficSplit spec support older version only?

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4446]
**Bug description**:
Is there any specific reason we are using TrafficSplit version v1alpha2 although there is latest one available?

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [X ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
> Is there any specific reason we are using TrafficSplit version v1alpha2 although there is latest one available?

OSM does not support the later versions yet because the project is focusing on adding stability to the existing features. At this moment we do not have a timeline on supporting the latest version of the SMI policies.

Feel free to use the [discussions feature](https://github.com/openservicemesh/osm/discussions) to discuss such questions.
