### ISSUE TITLE
metrics annotation should be removed like other annotations/labels when "osm namespace remove" is run

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4447]
**Bug description**:

When bin/osm metrics enable is run on a namespace and its pods, the metrics: enabled annotation is added.

When this namespace is REMOVED from osm using osm namespace remove, all other osm annotations are removed EXCEPT for metrics annotations, which are left behind.

When a namespace is being marked for remove using “osm namespace remove abc”, metrics should also be disabled on the namespace as part of namespace monitoring removal.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

```
bin/osm metrics enable --namespace abc
kubectl get ns abc -o yaml
bin/osm namespace remove abc
kubectl get ns abc -o yaml
```

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by mudit-01** [comment]
I would like to work on this pls assign it to me.
