### ISSUE TITLE
"osm metrics enable/disable" are effectively no-ops without args

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4448]
**Bug description**:

If both metrics commands are run without any other options, then both commands *do not do ANYTHING*, are effectively no-ops and just return without doing anything.
Both commands require the `--namespace` flag to be required - use something like `cobra.MarkFlagsRequired` to require this flag.

Also the flag should be more appropriately named “--namespaces” to emphasize that multiple namespaces can have metrics enabled or disabled.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

bin/osm metrics enable # without any other options
bin/osm metrics disable # without any other options

![image](https://user-images.githubusercontent.com/13926417/149387638-802a5706-1752-4bd7-bbd2-caa6dd4420de.png)

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by mudit-01** [comment]
Hi @johnsonshi now `osm namespace remove` will remove the metrics annotation https://github.com/openservicemesh/osm/pull/4539 

also, the command `osm metrics enable` helps mention that multiple namespaces can have metrics enabled or disabled.  
![image](https://user-images.githubusercontent.com/53465654/157011092-b29706cc-89cd-4a16-9aff-3f238531709e.png)

**Comment by mudit-01** [comment]
Hi @johnsonshi I can work on this, which task should I start with first?
