### ISSUE TITLE
pkg/k8s/client.go/IsMetricsEnabled - function which checks if a pod should be scraped for prometheus

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4449]
**Bug description**:

`pkg/k8s/client.go/IsMetricsEnabled` - function which checks if a pod should be scraped for prometheus.

This function is currently only checking for metrics enablement based on the annotation “prometheus.io/scrape” whether it exists or is true/false.

This is incorrect as metrics should only be enabled on a pod if ALL 3 of the following conditions succeed:
prometheus.io/scrape is true
openservicemesh.io/monitored-by corresponds to this mesh
openservicemesh.io/ignore is not true or does not exist

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [X]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**: Enable metrics on a pod but see that the criteria depends entirely on prometheus annotations only, not reliant on the `ignore` label

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
IsMetricsEnabled() is only invoked on pods that are a part of the mesh, so the existing behavior is okay.
