### ISSUE TITLE
Replace idelta() functions with irate() on Prometheus histogram metrics

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4452]
**Bug description**:

The `idelta` Prometheus function is used with some of OSM’s histogram metrics which is not recommended. The `rate`, `irate` or `histogram_quantile` functions are typically the only functions used with a histogram. The`idelta` function is used with gauge metrics that can increase or decrease in value; the bucket values will only increase.

The following queries using idelta on histograms:
- sidecar injection timings 
    - `idelta(osm_injector_injector_rq_time_bucket{source_pod_name=~"$osm_injector_instance"}[1m])`
- certificate issue timings 
    - `sum(idelta(osm_cert_issued_time_bucket{source_pod_name=~"$osm_injector_instance"}[1m])) by (le)`
- xds path histogram 
    - `sum(idelta(osm_proxy_config_update_time_bucket{resource_type="$xds_path", source_pod_name=~"$osm_controller_instance"}[1m])) by (le)` 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [x]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

The `rate` or `irate` function should be used instead of `idelta`.

**Comment by johnsonshi** [comment]
Alright @jaellio taking on this work
