### ISSUE TITLE
Pods crashing after manually creating osm-ca-bundle secret

### ISSUE THREAD

**Issue by shahriak** [openservicemesh/osm#4458]
**Bug description**:
Hello OSM team,

I have been trying to install OSM using Helm using the secret osm-ca-bundle that I have created using OpenSSL commands. However, I seem to run into the below error after I use helm to install the components.

Logs from osm-injector or any other crashing pods:

kubectl get all -n osm-system
NAME                                  READY   STATUS             RESTARTS   AGE
pod/osm-controller-54b5fccf8d-v8s7g   0/1     CrashLoopBackOff   3          73s
pod/osm-injector-657c7d9d69-vdfkk     0/1     CrashLoopBackOff   3          73s

{"level":"info","component":"osm-injector/main","time":"2022-01-18T18:31:58Z","file":"osm-injector.go:94","message":"Starting osm-injector dev; 7df9badece2f251515a2bc5e5ac79438b0c58812; "}
W0118 18:31:58.551460       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"info","component":"osm-injector/main","time":"2022-01-18T18:31:58Z","file":"osm-injector.go:142","message":"Initial MeshConfig osm-mesh-config: {\n    \"sidecar\": {\n        \"logLevel\": \"error\",\n        \"envoyImage\": \"envoyproxy/envoy-alpine:v1.18.3\",\n        \"initContainerImage\": \"openservicemesh/init:v0.9.2\",\n        \"configResyncInterval\": \"0s\",\n        \"resources\": {}\n    },\n    \"traffic\": {\n        \"inboundExternalAuthorization\": {\n            \"statPrefix\": \"inboundExtAuthz\",\n            \"timeout\": \"1s\"\n        }\n    },\n    \"observability\": {\n        \"osmLogLevel\": \"info\",\n        \"tracing\": {\n            \"port\": 9411,\n
   \"address\": \"jaeger.osm-system.svc.cluster.local\",\n            \"endpoint\": \"/api/v2/spans\"\n        }\n    },\n    \"certificate\": {\n        \"serviceCertValidityDuration\": \"24h\"\n    },\n    \"featureFlags\": {\n        \"enableWASMStats\": true,\n        \"enableEgressPolicy\": true\n    }\n}"}
{"level":"info","component":"kube-controller","time":"2022-01-18T18:31:58Z","file":"client.go:139","message":"Namespace controller client started"}
{"level":"info","component":"kube-controller","time":"2022-01-18T18:31:58Z","file":"client.go:154","message":"Waiting for Namespaces informer cache sync..."}
{"level":"info","component":"kube-controller","time":"2022-01-18T18:31:58Z","file":"client.go:164","message":"Caches for [Namespaces] synced successfully"}
{"level":"info","component":"cert-provider-util","time":"2022-01-18T18:31:58Z","file":"config.go:184","message":"CA already exists in kubernetes, loading."}
{"level":"error","component":"tresor","error":"no certificate in PEM","time":"2022-01-18T18:31:59Z","file":"certificate_manager.go:60","message":"Error decoding Root Certificate's Private Key PEM "}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ff905]
goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x1b8cce0, 0x0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/crypto/rsa/rsa.go:112 +0x5
crypto/x509.CreateCertificate(0x1f2e600, 0xc0001231d0, 0xc0007ad3e0, 0xc00037a680, 0x1a79aa0, 0xc0007e34a0, 0x1b8cce0, 0x0, 0xc000a46cc0, 0x4, ...)
        /opt/hostedtoolcache/go/1.15.15/x64/src/crypto/x509/x509.go:2103 +0xb7
github.com/openservicemesh/osm/pkg/certificate/providers/tresor.(*CertManager).issue(0xc0007e33e0, 0xc000a46f20, 0x1b, 0x460623fc85e0000, 0x0, 0xc000723970, 0x4f1bf1, 0x2c00ca0)
        /home/runner/work/osm/osm/pkg/certificate/providers/tresor/certificate_manager.go:63 +0x3eb
github.com/openservicemesh/osm/pkg/certificate/providers/tresor.(*CertManager).IssueCertificate(0xc0007e33e0, 0xc000a46f20, 0x1b, 0x460623fc85e0000, 0x2, 0xc000a46f20, 0x1b, 0x1f89a60)
        /home/runner/work/osm/osm/pkg/certificate/providers/tresor/certificate_manager.go:120 +0xca
github.com/openservicemesh/osm/pkg/injector.NewMutatingWebhook(0x2382, 0x1fa6fe0, 0xc000152f20, 0x1f89a00, 0xc0007e33e0, 0x1f968a0, 0xc000545530, 0x7ffc5aab19ae, 0x3, 0x7ffc5aab1997, ...)
        /home/runner/work/osm/osm/pkg/injector/webhook.go:70 +0x116
main.main()
        /home/runner/work/osm/osm/cmd/osm-injector/osm-injector.go:161 +0x9e5

**Affected area (please mark with X where applicable)**:
- Install                    [x]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [x]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Pods should start without any errors

**Steps to reproduce the bug (as precisely as possible)**:
I am using the below openssl command to generate the root cert:
#### Generate cert
openssl genrsa -out cakey.pem 2048 # generate root key
openssl req -x509 -new -nodes -key cakey.pem -sha256 -days 2000 -out cacert.pem # generate root cert

#### create secret in osm namespace
kubectl create secret generic osm-ca-bundle --from-file=ca.crt=cacert.pem --from-file=private.key=cakey.pem -n osm-system (add expiration as well)

#### deploy osm using helm
helm install osm osm --repo https://openservicemesh.github.io/osm --version 0.11 --namespace osm-system --values values.yaml

**How was OSM installed?**:
Helm
**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v0.11
- Kubernetes version (use `kubectl version`): 1.21
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by jaellio** [comment]
**Issue resolved offline**: Notes summarizing findings

In the OSM injector logs shared above, the osm-injector finds the osm-ca-bundle secret and does attempt to recreate it since it already exists. The following error indicates that the secret was not configured correctly and the injector was unable to decode it. 

```
{"level":"info","component":"cert-provider-util","time":"2022-01-18T18:31:58Z","file":"config.go:184","message":"CA already exists in kubernetes, loading."}
{"level":"error","component":"tresor","error":"no certificate in PEM","time":"2022-01-18T18:31:59Z","file":"certificate_manager.go:60","message":"Error decoding Root Certificate's Private Key PEM "}
panic: runtime error: invalid memory address or nil pointer dereference
```

Prior to installing OSM, users can bring their own root certificates to be used by the specified certificate manager. When using OSM's default certificate manager, Tresor, the Kubernetes secret must be of the following form:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
      name: <caBundleSecretName; default value: osm-ca-bundle>
      namespace: <osmNamespace; default value: osm-system>
data:
  ca.crt: <base64 encoded root cert>
  expiration: <base64 encoded ISO 8601 certificate expiration date; for example: 2031-01-11T23:15:09.299Z> 
  private.key: <base64 encoded private key>
```
 
The private key must be of the form PKCS #8, ASN.1 DER for it to be properly decoded by OSM.

Example instructions for generating a certificate for testing:
```shell
openssl genrsa -out keypair.pem 2048
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in keypair.pem -out private.key
openssl req -x509 -new -nodes -key private.key -sha256 -days 1825 -out ca.crt
```

**Comment by shashankram** [comment]
> Example instructions for generating a certificate for testing:
> 
> ```shell
> openssl genrsa -out keypair.pem 2048
> openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in keypair.pem -out private.key
> openssl req -x509 -new -nodes -key private.key -sha256 -days 1825 -out ca.crt
> ```

@jaellio would you mind documenting the steps involved to use custom CA in the docs repo.
