### ISSUE TITLE
Use osm cli's bug-report command to collect logs in e2e framework

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4477]
**Please describe the Improvement and/or Feature Request**
Use the `osm support bug-report` command to collect mesh related logs for CI failures (primarily e2e failures).
Currently, some log collection logic is baked into the e2e framework. If there are any gaps in the bug-report tool to triage e2e failures, address these gaps in the tool.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Tests                      [X]

**Possible use cases**
Leverage osm bug-report tool for log collection in CI.

**Comment by nshankar13** [comment]
https://github.com/openservicemesh/osm/pull/4504
