### ISSUE TITLE
docs around container registry use

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#448]
Right now, there are references to using acr for pointing to private osm images that we build and maintain. We'll want to update the docs to point to the public osm images.

**Comment by SanyaKochhar** [comment]
PR #1358 changed the default container registry to point to public osm images. 

Related feature work for issue #1416. Docs should be updated [here](https://github.com/openservicemesh/osm/blob/main/docs/development_guide.md#create-environment-variables)

**Comment by michelleN** [comment]
Looks like this has been resolved. thanks!
