### ISSUE TITLE
Document required capabilities (e.g. "NET_RAW")

### ISSUE THREAD

**Issue by RichDCs** [openservicemesh/osm#4492]
Hi team,

I cannot figure out in the documentation if the capability "NET_RAW" is required.
Could you please add the capabilities required to the documentation?

Thanks a lot,
Richard

**Comment by trstringer** [comment]
Are you referring to the required capabilities/security context of the OSM processes? Also, is there something that makes you question if CAP_NET_RAW is required?

**Comment by shashankram** [comment]
This needs to be documented at https://release-v0-11.docs.openservicemesh.io/docs/guides/app_onboarding/prereqs/

**Comment by RichDCs** [comment]
Error messages like the one [displayed in this issue](https://github.com/openservicemesh/osm/issues/975) makes me think it is required. It was originally a customer interrogation.

**Comment by SanyaKochhar** [comment]
Documented this in app onboarding prereqs: https://github.com/openservicemesh/osm-docs/pull/328
