### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4524]
There's a few things we can do to improve error messages and error handling:

1. lowercase error messages to comply with lint: https://staticcheck.io/docs/checks#ST1005
2. remove usage of github.com/pkg/errors (in maintenance mode), in favor of stdlib fmt.Errorf & errors.Unwrap, errors.As, errors.Is
3. Errors should be handled exactly once. There are many places where we log then immediately return an error. We should do one or the other. Most often we want to return a wrapped error.

#3 will result in slightly different error messages, that may affect any JSON parsers, but will colocate errors in a single log line so that they inherently associated vs spread throughout the log files.

Any lack of ability to parse error messages with JSON could be solved externally with full text search or regex search (recommended). Alternatively we could create our own errors that fit in neatly with zerolog, to log wrapped errors in a JSON friendly format. I believe the latter is not worth the effort at this time.

https://github.com/openservicemesh/osm/pull/4521 as an example draft PR

**Comment by allenlsy** [comment]
This issue is not completely resolved. PR #4904 only fixed item 2 in the description. Most important item is ensuring error handled exactly once. We haven't worked on it. I suggest re-open this issue.
