### ISSUE TITLE
ARM platform builds of the CLI

### ISSUE THREAD

**Issue by tbertenshaw** [openservicemesh/osm#4528]
ARM64 (and other) compatible versions of the cli would be very helpful. It would be great to be able to use the cli from a Raspberry pi or a M1 mac.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [x]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Comment by nojnhuh** [comment]
Fixed in #4553
