### ISSUE TITLE
Pods running raft algorithm not able to communicate with Permissive Mode enabled

### ISSUE THREAD

**Issue by Shrizo** [openservicemesh/osm#4531]
**Bug description**: I am deploying consul with 3 replicas into a namespace added to osm v1.0.0 with permissive traffic mode enabled.  The pods are not able to communicate with each other and elect a leader (via raft), and I see errors like the following in the logs of all 3 pods:

```
[ERR] raft: Failed to make RequestVote RPC to {Voter 988d543c-c51c-563d-9b52-949716f4d49c 10.244.2.71:8300}: read tcp 10.244.3.79:49466->10.244.2.71:8300: read: connection reset by peer
```

Note that the IP addresses change based on which pod I'm looking at and what other pod they are trying to communicate with.  I have restarted all pods in my namespace and the osm namespace as well as ensured my meshconfig has permissive mode enabled:

```
apiVersion: config.openservicemesh.io/v1alpha1
kind: MeshConfig
metadata:
  creationTimestamp: "2022-02-14T17:15:27Z"
  generation: 2
  name: osm-mesh-config
  namespace: osm-system
  resourceVersion: "7518980"
  uid: c4e5044e-8e54-42ac-a257-bebe5a9d05e8
spec:
  certificate:
    certKeyBitSize: 2048
    serviceCertValidityDuration: 24h
  featureFlags:
    enableAsyncProxyServiceMapping: false
    enableEgressPolicy: true
    enableEnvoyActiveHealthChecks: false
    enableIngressBackendPolicy: true
    enableMulticlusterMode: false
    enableRetryPolicy: false
    enableSnapshotCacheMode: false
    enableWASMStats: true
  observability:
    enableDebugServer: false
    osmLogLevel: info
    tracing:
      enable: false
  sidecar:
    configResyncInterval: 0s
    enablePrivilegedInitContainer: false
    logLevel: error
    resources: {}
  traffic:
    enableEgress: false
    enablePermissiveTrafficPolicyMode: true
    inboundExternalAuthorization:
      enable: false
      failureModeAllow: false
      statPrefix: inboundExtAuthz
      timeout: 1s
    inboundPortExclusionList: []
    outboundIPRangeExclusionList: []
    outboundPortExclusionList: []
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ X]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Pods are able to communicate freely with permissive mode enabled.

**Steps to reproduce the bug (as precisely as possible)**:  install osm v1.0.0, add namespace, start pods running consul (and raft algorithm) in namespace.

**How was OSM installed?**: Download binary from github release, and use 'osm install' to install into the cluster.

**Anything else we need to know?**: Azure cluster, did not use az cli to install since I did not see a way to install the latest release with it.

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (number of worker nodes in the cluster): 6
- Others:

**Comment by steeling** [comment]
Drive-by comment for whoever picks this up, this is likely due to https://github.com/openservicemesh/osm/issues/3477

**Comment by steeling** [comment]
closing as a dup against #3477. We will add all debugging and planning to that issue
