### ISSUE TITLE
Add UDP encryption support

### ISSUE THREAD

**Issue by richardwhiuk** [openservicemesh/osm#4545]
**Please describe the Improvement and/or Feature Request**

UDP is commonly used for intra-cluster communication and securing this traffic is critical to a zero trust security model. Using service mesh to fulfil this need simplifies securing Kubernetes clusters.

Encryption could either be achieved with DTLS, or by tunnelling the traffic over TCP.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
- DNS traffic between pods and kube-dns
- UDP traffic - e.g. HTTP/3, or telephony protocols such as SIP or PFCP.

**Comment by allenlsy** [comment]
According to the information [here](https://github.com/envoyproxy/envoy/issues/10584), Envoy does not support DTLS as of today.
