### ISSUE TITLE
Update control plane metrics

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4568]
**Please describe the Improvement and/or Feature Request**

Based on [this doc](https://docs.google.com/document/d/1NB42lJ0Uvrevuqsv3ab8h-q_4bvX0FTWWrN_EPNf4NQ/edit?usp=sharing), I propose the following changes to the metrics generated by OSM's control plane components:

#### Keep

Metric|Type|Description
-|-|-
k8s_api_event_count|Counter|Represents the number of events received from the Kubernetes API Server
resource_namespace_count|Gauge|Represents the number of monitored namespaces in the service mesh
proxy_connect_count|Gauge|Represents the number of proxies connected to OSM controller
proxy_config_update_time|Histogram|Histogram to track time spent for proxy configuration
cert_issued_count|Counter|Represents the total number of XDS certificates issued to proxies
err_code_count|Counter|Respesents the number of errcodes generated by OSM
proxy_broadcast_event_count|Counter|Represents the number of ProxyBroadcast events published by the OSM controller

#### Add

Metric|Type|Description
-|-|-
proxy_xds_request|Counter|Total number of XDS requests made by each proxy
proxy_max_connections_rejected|Counter|Number of proxies rejected due to the configured connection limit
events_queued|Gauge|Number of events seen but yet to be processed
feature_flag_enabled|Gauge|Indicates whether each feature flag is enabled (1) or disabled (0)
http_response_count|Counter|Counter of HTTP responses sent handled
http_response_duration_ms|Histogram|Time in milliseconds taken to respond to HTTP requests
reconciliation_count|Counter|Total number of resource reconciliations invoked

#### Change

Metric|Type|Description|Change
-|-|-|-
proxy_response_send_success_count|Counter|Represents the number of responses successfully sent to proxies|Add labels for proxy and XDS type URI
proxy_response_send_error_count|Counter|Represents the number of responses that errored when being set to proxies|Add labels for proxy and XDS type URI
injector_sidecar_count|Counter|Counts the number of injector webhooks dealt with over time|Make this generic for all webhooks, add success indicator and resource kind
injector_rq_time|Histogram|Histogram for time taken to perform sidecar injection|Make this generic for all webhooks, add success indicator and resource kind

#### Remove

Metric|Type|Description
-|-|-
proxy_reconnect_count|Counter|Represents the number of reconnects from known proxies to OSM controller
cert_issued_time|Histogram|Histogram to track time spent to issue xds certificate

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

More details in the doc linked above.

**Comment by shashankram** [comment]
@nojnhuh for the metrics that are being changed or removed, could you kindly add a column stating why they are being updated/removed? If you capture this table in the doc, I can leave follow-up questions on the doc itself.

**Comment by nojnhuh** [comment]
@shashankram Done

**Comment by nojnhuh** [comment]
Looking for feedback on exactly how Kubernetes webhook metrics should look:

Currently, osm-injector runs a mutating webhook to inject sidecars to Pods, osm-controller runs a validating webhook for OSM and SMI custom resource types, and osm-bootstrap runs a conversion webhook for OSM and SMI custom types.

I'm thinking since both validating and mutating webhooks overlap quite a bit since they're both classified as "admission" webhooks, those could share a metric name and label set. Something like:

```
osm_admission_webhook_response_total{kind="",success="true/false"}
```
- Do we need to distinguish between mutating and validating webhooks here? Currently each kind is only handled by one or the other.

Then since conversion webhooks are quite a bit different, those could track their own metric with its own labels. Something like:

```
osm_conversion_webhook_response_total{kind="",from_version="",to_version="",success="true/false"}
```

Since all the webhooks are HTTP handlers, all of these webhooks will be easy to hook into the HTTP metrics we track on other HTTP endpoints for request counts and durations. Would we also want to track webhook response durations separate from general HTTP response durations? Otherwise I'm not sure it would be possible to see how long successful webooks take compared to failed ones if they both respond with the same HTTP status code. Is it worthwhile to be able to make that distinction though?

/cc @shashankram

**Comment by nojnhuh** [comment]
As it stands, the only remaining item is adding `reconciliation_count`. I would call that soft-blocked on #4575 since we could probably hack around that to make the metrics accurate but I would say that's not worth it over just fixing that issue first.
