### ISSUE TITLE
Expose MeshConfig parameters to be overriden via Add-on profile

### ISSUE THREAD

**Issue by shahriak** [openservicemesh/osm#4572]
**Please describe the Improvement and/or Feature Request**

Currently OSM Add-on does not provide a mechanism to override any meshConfigs at the time off install. I am aware that it is possible to patch the meshConfig once OSM is deployed onto the cluster, however, this does not seem like a very straightforward solution and requires custom logic on our end. The ask is to expose config via add-on profile in order to override certain MeshConfig parameters.

**Scope (please mark with X where applicable)**
- New Functionality          [ x]
- Install                    [x ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@shahriak The OSM AKS addon is not managed as a part of this open source project. Kindly follow up with the AKS team managing the OSM addon for enhancements required in the addon.
