### ISSUE TITLE
Expose config in Add-on profile to Inject sidecar on the given list of namespaces

### ISSUE THREAD

**Issue by shahriak** [openservicemesh/osm#4573]
**Please describe the Improvement and/or Feature Request**

The ask is to provide a mechanism (possibly in add-on profiles) to be able to send in a list of namespaces such that all these namespaces if they don't exist will be created and automatically be injected with OSM sidecars. The reason for this is for those that follow Helm deployments for Applications, helm v3 does not allow creating metadata in namespaces. Therefore, it is not possible to add in annotations/labels in the namespace resources.

**Scope (please mark with X where applicable)**
- New Functionality          [x ]
- Install                    [x ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@shahriak The OSM AKS addon is not managed as a part of this open source project. Kindly follow up with the AKS team managing the OSM addon for enhancements required in the addon.
