### ISSUE TITLE
Allow plugging in custom CA at the time of install via Add-on profile

### ISSUE THREAD

**Issue by shahriak** [openservicemesh/osm#4574]
**Please describe the Improvement and/or Feature Request**

Currently OSM creates a default secret via Tresor package initially if there is no secret with name osm-ca-bundle present in the cluster. The ask is to be able to allow plugging in custom CA at the time of install which will create the secret based on the given certificate. The reason for this is OSM currently does not auto-rotate the secret in a compliant manner. The use-case of our org is that we must auto-rotate the secret every 90 days and allowing plugging in custom CA allows us to maintain auto rotation of the secret.

**Scope (please mark with X where applicable)**
- New Functionality          [x ]
- Install                    [ x]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ x]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment]
@shahriak The OSM AKS addon is not managed as a part of this open source project. Kindly follow up with the AKS team managing the OSM addon for enhancements required in the addon.
