### ISSUE TITLE
osm-init Back-off restarting failed container

### ISSUE THREAD

**Issue by shanghai636848** [openservicemesh/osm#4609]
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'nat'
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

**Comment by mudit-01** [comment]
Hi @shanghai636848 which env you are using and which version of OSM?
Also, can you give the steps you followed before encountering the error?
