### ISSUE TITLE
Uninstall command should suggest existing mesh to uninstall

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#4613]
**Please describe the Improvement and/or Feature Request**

Right now `osm uninstall mesh` will show the meshes present in the cluster and defaults to suggesting to uninstall mesh name 'osm' in namespace 'osm-system' - this gives the impression that there is such a mesh in the 'osm-system' namespace even when there is not
![image](https://user-images.githubusercontent.com/69616256/159991229-b22aba79-8b69-4a6e-9fdf-c829dd0eb375.png)
Instead it should suggest to uninstall the existing mesh(es) if the user runs `osm uninstall mesh` instead of having to add the tags `--osm-namespace` and `--mesh-name` and the tags would only be used if the user knows the exact mesh they'd like to uninstall
![image](https://user-images.githubusercontent.com/69616256/159992106-f316ee10-eaba-453e-bbf1-49f95eddbfac.png)

**Scope (please mark with X where applicable)**
- CLI Tool                   [x ]

**Possible use cases**

**Comment by mudit-01** [comment]
One suggestion it will be more helpful if it asks the user to enter the name of the mesh rather than suggesting otherwise in the case of multiple meshes user will keep on selecting meshes by Y or N
