### ISSUE TITLE
How to add a namespace when using Helm

### ISSUE THREAD

**Issue by benediktwetzel** [openservicemesh/osm#4616]
**Please describe what should be documented**
How to add a namespace to the mesh when using Helm? I could not find an option in the values.yaml file which corresponds to the `osm namespace add <namespace>` command of the osm cli (analogous for the `osm metrics enable --namespace <namespace> command`).

**Please suggest where in the repo the document should be located**
For example in the  [Helm installation guide](https://release-v0-11.docs.openservicemesh.io/docs/getting_started/install/#using-the-helm-cli) or directly in the [values.yaml file](https://github.com/openservicemesh/osm/blob/release-v1.0/charts/osm/values.yaml).

**Comment by gdippolito** [comment]
I had the same issue. It wasn't easy to find. The following annotation is required on the namespace `openservicemesh.io/metrics=enabled`
