### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by majoli** [openservicemesh/osm#4617]
I enjoyed the information given by the page but i would love it if the images would work properly :)

**Comment by trstringer** [comment]
Hello and thank you for opening this issue! Can you provide more specifics? What is not working properly?

**Comment by majoli** [comment]
sorry i just recognized that i am in the wrong version.
https://release-v0-11.docs.openservicemesh.io/docs/guides/ha_scale/scale/

The images wont work here but for v1 they work. Google sent me to the old guides for any reason.
