### ISSUE TITLE
Add load testing support in e2e framework

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4621]
**Please describe the Improvement and/or Feature Request**

Add load testing support with [fortio](https://github.com/fortio/fortio) in the e2e framework. 
Currently, the e2e framework allows sending synchronous HTTP requests using `curl`. However, this is inconvenient to use to test more complex scenarios such as circuit breaking, where parallel connections may need to be initiated with a given number of total requests. Since the `fortio` tool provides this capability along with statistics per request and a dashboard, integrate this into the framework.

**Scope (please mark with X where applicable)**
- Tests                      [X]

**Possible use cases**
Load testing within e2e.

**Comment by allenlsy** [comment]
If the goal of this issue overlaps of the OSM perf and scalability test suite, I think it's not necessary to migrate to fortio. We can add perf and scalability test as part of the CI. However if the goal is to improve features, e.g. further customize request in e2e test, or even to have a simple regression check on the latency, then it worth to use Fortio.

**Comment by shashankram** [comment]
> If the goal of this issue overlaps of the OSM perf and scalability test suite, I think it's not necessary to migrate to fortio. We can add perf and scalability test as part of the CI. However if the goal is to improve features, e.g. further customize request in e2e test, or even to have a simple regression check on the latency, then it worth to use Fortio.

The goal is to improve traffic test scenarios in the e2e framework to test features such as circuit breaking. This is absolutely required in the e2e framework where we need to test more complex scenarios outside the "performance and scalability" scenarios.
