### ISSUE TITLE
(*feat) Migrate to EndpointSlices instead of Endpoints API

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4637]
**Please describe the Improvement and/or Feature Request**

Stable as of Kubernetes 1.21, [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) are "a more scalable and extensible alternative to Endpoints." Specifically, they associate the pod name with its backing ip address in the manifest, AND they [contain zone/node information](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#topology) with [improvements on the way](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/). 

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Envoy Control Plane        [X]

**Possible use cases**

EndpointSlices would make several new features/initiatives easier, namely more robust locality load balancing as well as [StatefulSet support](https://github.com/openservicemesh/osm/issues/3477). OSM only supports Kubernetes 1.20 and up, so EndpointSlice support is a pretty reasonable expectation for target clusters.

**Comment by steeling** [comment]
Going to resize this to a medium, and bring it into the Multicluster project board, as the MCS API will exclusively create endpoint slices, not endpoints
