### ISSUE TITLE
OSM Regression Testing/Profiling

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4644]
With the new [load test suite](https://github.com/openservicemesh/osm-docs/pull/342), we have an opportunity to bring regression testing into our releases.

This is also a good opportunity to grab profiles (pprof) for each scenario and have folks perform some manual inspection to determine bottle necks. This in turn will better feed into our prioritization around performance improving efforts.

**Comment by phillipgibson** [comment]
[The OSM project has been officially archived by the CNCF.](https://github.com/cncf/toc/pull/1044) There will be no more new development on any repo under the OpenServiceMesh organization.
