### ISSUE TITLE
Docs: Configure OSM to use cert-manager after install

### ISSUE THREAD

**Issue by TylerHaigh** [openservicemesh/osm#4656]
**Please describe what should be documented**

Hi Team,
Is it possible to configure OSM to use cert-manager after it has been installed? The docs on the below links only provide info for setup before OSM installed in the cluster.

* https://release-v0-11.docs.openservicemesh.io/docs/guides/certificates/#configure-cert-manger-for-osm-signing
* https://release-v1-0.docs.openservicemesh.io/docs/demos/cert-manager_integration/

**Please suggest where in the repo the document should be located**

* https://release-v0-11.docs.openservicemesh.io/docs/guides/certificates/#configure-cert-manger-for-osm-signing
* https://release-v1-0.docs.openservicemesh.io/docs/demos/cert-manager_integration/

**Comment by trstringer** [comment]
Thanks for raising this issue, @TylerHaigh! We will look further into this.

**Comment by steeling** [comment]
Our current docs on certificate rotation do incur downtime of the services https://release-v0-11.docs.openservicemesh.io/docs/guides/certificates/#rotate-the-root-certificate-tresor.

We are currently working on a [feature to allow certificate rotation with zero downtime](https://github.com/openservicemesh/osm/issues/4502). One of the side effects of this is that we will allow zero-downtime rotation to other certificate providers (including Tresor to cert-manager).

Until then unfortunately the best way to do this would be to uninstall and reinstall osm with the appropriate cert-manager settings. I'll keep this issue open for ~1 week in case there's any further questions/comments. Cheers!
