### ISSUE TITLE
Mention of GA for v1.0 release

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4663]
**Please describe what should be documented**
Currently, there is no mention in the OSM repo or in the doc website about v1.0 being GA release of OSM. 
**Please suggest where in the repo the document should be located**
Can we mention it in release notes or in the readme?

**Comment by trstringer** [comment]
Thanks for opening up this issue! Currently the [README already reflects the production readiness of the project](https://github.com/openservicemesh/osm#project-status). We follow semantic versioning in the project, and therefore rely on the [semver](https://semver.org/) guidelines and definitions.

Let me know if that helps clarify!

**Comment by mudit-01** [comment]
Thanks @trstringer got it 👍🏽
