### ISSUE TITLE
fix this url please

### ISSUE THREAD

**Issue by srinman** [openservicemesh/osm#4674]
https://github.com/openservicemesh/osm)

**Comment by trstringer** [comment]
Hello! Can you clarify? That is the URL for this GitHub repo (which works).

**Comment by srinman** [comment]
I noticed a ) at the end of the url which breaks the link. It works without
the )

**Comment by trstringer** [comment]
Where do you see this URL though? I'm having a hard time understanding the location of the issue.

**Comment by srinman** [comment]
here it is
https://release-v1-0.docs.openservicemesh.io/docs/getting_started/install_apps/

**Comment by trstringer** [comment]
Ah ok, I totally understand. I've opened up a PR to fix this. Thank you!

**Comment by srinman** [comment]
Awesome, thanks!
