### ISSUE TITLE
ServiceMonitor feature

### ISSUE THREAD

**Issue by nlamirault** [openservicemesh/osm#4699]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

A lot of Helm charts could create Kubernetes resources (ServiceMonitor, PodMonitor, ...) managed by the [Prometheus Operator](https://prometheus-operator.dev/).
Ex:
- [keda](https://github.com/kedacore/charts/blob/main/keda/templates/26-metrics-podmonitor.yaml)
- [grafana](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/servicemonitor.yaml)

It would be interesting to have such a feature into the Helm chart.

**Comment by shashankram** [comment]
> It would be interesting to have such a feature into the Helm chart.

@nlamirault Thanks for opening this issue. Could you describe in the issue why this is required and how is it useful. Adding additional context will help us review this requirement better and see how we can integrate it into our existing observability story.

**Comment by defenestration** [comment]
Not the OP but maybe i can provide more context.  The Prometheus Operator deployed by [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) (and probably other projects) does not support the prometheus.io annotations , and instead uses PodMonitor/ServiceMonitor CRDS to figure out what to scrape.  It would be convenient for OSM to support these methods. 

Other issues i noticed in the same vein:

* https://github.com/openservicemesh/osm/issues/4780
* https://github.com/openservicemesh/osm/issues/1537
