### ISSUE TITLE
Create a MeshRootCertificate on osm install 

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4712]
**Please describe the Improvement and/or Feature Request**

Part of #4502 

Create a MeshRootCertificate resource when installing OSM. 

Notes: 
- the MRC custom resource would use the existing certificate provider values defined in `values.schema.json`. The same default values would apply
- the MRC resource must also be cleaned up on uninstall  

**Scope (please mark with X where applicable)**
- New Functionality          [x]
- Install                    [x]
- Certificate Management     [x]

**Comment by jaellio** [comment]
Some thoughts and questions regarding creating MeshRootCertificate creation on install:

Creating the MeshRootCertificate on OSM install 
- Should the MeshRootCertificate be created in the same way the MeshConfig is created? Currently, on install a ConfigMap containing the preset mesh configurations is created. The osm-bootstrap is responsible for loading the preset mesh configuration and then creating the mesh config using those settings if it doesn't already exist. The osm-controller and osm-injector on the osm-bootrstap to start (and create the MeshConfig before starting up).
  - A Kubernetes secret or ConfigMap could be created on install containing the preset Mesh Root Certificate settings. The osm-bootstrap would be responsible for creating the MRC in the same way it is responsible for creating the MeshConfig.
  - Should the user be able to specify whether they want a Secret or Config map to contain the settings of the MRC
- Could all control plane components wait on the creation of the MRC? Even though the custom resource is the last resource kind to be created by Helm, could all control plane components just wait in a pending state until the default MRC CR is created?

Upgrading OSM:
- What happens if the upgrade occurs during a root certificate rotation? Is it possible to disallow this?
  - This shouldn't be a problem if the osm-bootstrap is able to determine if an MRC or multiple MRCs already exist and not a new one.  When information is obtained from the MRCs, OSM should be able to pick back up on rotation.
- When checking for existing MRCs, the osm-bootstrap (or some other process) will look for MRCs in the control plane namespace with an active status. If there are no MRCs in an active status, a default MRC will be created.
- How should certificate provider settings be preserved during an upgrade? No MRC to MRC?
  - Are the certificate provider settings currently preserved during an upgrade?

**Comment by steeling** [comment]
> Some thoughts and questions regarding creating MeshRootCertificate creation on install:
> 
> Creating the MeshRootCertificate on OSM install
> 
> * Should the MeshRootCertificate be created in the same way the MeshConfig is created? Currently, on install a ConfigMap containing the preset mesh configurations is created. The osm-bootstrap is responsible for loading the preset mesh configuration and then creating the mesh config using those settings if it doesn't already exist. The osm-controller and osm-injector on the osm-bootrstap to start (and create the MeshConfig before starting up).
>   
>   * A Kubernetes secret or ConfigMap could be created on install containing the preset Mesh Root Certificate settings. The osm-bootstrap would be responsible for creating the MRC in the same way it is responsible for creating the MeshConfig.

If you mean by creating a configmap first I see no reason to do so. I believe the reasons to do this initially for the mesh config are now obsolete.

>   * Should the user be able to specify whether they want a Secret or Config map to contain the settings of the MRC

If there are any secret values required in an MRC, a standard approach would be to add a field `secretRef` which is an object that contains secret name, secret key, and maybe namespace (or just use same namespace).

> * Could all control plane components wait on the creation of the MRC? Even though the custom resource is the last resource kind to be created by Helm, could all control plane components just wait in a pending state until the default MRC CR is created?

Wait/error (kill the pod) seems like a reasonable approach.

> 
> Upgrading OSM:
> 
> * What happens if the upgrade occurs during a root certificate rotation? Is it possible to disallow this?
>   
>   * This shouldn't be a problem if the osm-bootstrap is able to determine if an MRC or multiple MRCs already exist and not a new one.  When information is obtained from the MRCs, OSM should be able to pick back up on rotation.
> * When checking for existing MRCs, the osm-bootstrap (or some other process) will look for MRCs in the control plane namespace with an active status. If there are no MRCs in an active status, a default MRC will be created.
> * How should certificate provider settings be preserved during an upgrade? No MRC to MRC?

We can also provide directions for users (require multiple steps in the upgrade directions), or put more logic in the CLI to query existing settings.

>   
>   * Are the certificate provider settings currently preserved during an upgrade?
