### ISSUE TITLE
Validate MeshRootCertificate

### ISSUE THREAD

**Issue by schristoff** [openservicemesh/osm#4723]
Please describe the Improvement and/or Feature Request
Part of https://github.com/openservicemesh/osm/issues/4502

Add validating webhook for MeshRootCertificate that: 

- Allow at most 2 MeshRootCertificate resources in either the pending-up, pending-down, complete, inactive, error or unknown state to be created. MeshRootCertificates that are inactive are not included in the count 
    - If there are already 2 MeshRootCertificate resources in either the pending-up, pending-down, OSM will set the status to error 
- Check for the correct status settings 
- Prevent out of order status changes 
- Don’t allow operators to change certain values in existing _MeshRootCertificates_ 

Areas of Interest:
Add MeshRootCertificate CRD to validatingWebhookServer
https://github.com/openservicemesh/osm/blob/d4853664a5ee34dfaf7367b54822b307bd19d99e/pkg/validator/server.go#L55-L61

Create a validateFunc that satisfies the above requirements
https://github.com/openservicemesh/osm/blob/966405b29161ee650d01a8c0ebaa5fe4ed324b79/pkg/validator/validators.go#L26

Validations [X]

**Comment by steeling** [comment]
When this gets implemented, with the new trust domain we should also validate that no parts in `strings.Split(TrustDomain, ".")` are the empty string

**Comment by jaellio** [comment]
Blocked on #4962

**Comment by keithmattix** [comment]
Note: Make sure the logic from the [rotation design doc](https://docs.google.com/document/d/1QF7wL1su4CUzwo3Yo2_vFL90XG2d-wUhBU6uifNrkws/edit#heading=h.r5r6bqgddlfx) is include (especially the finalizer).
