### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by dasMulli** [openservicemesh/osm#4725]
**Please describe the Improvement and/or Feature Request**
Currently establishing WebSocket connections to in-cluster services can fail in envoy producing upgrade failure logs.

Envoy however does support WebSocket upgrades given the appropriate upgrade config. This upgrade config should be supported in OSM.

**Scope (please mark with X where applicable)**
- New Functionality          [x ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [x]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Hosting Services that accept WebSocket connections

**Comment by dasMulli** [comment]
Prototype implementation using a feature flag seems to make what I need work: https://github.com/openservicemesh/osm/compare/release-v1.1...dasMulli:feature/websockets-on-release-v1.1

**Comment by dasMulli** [comment]
Thanks, I'll work on a PR for that.

A few questions I'd still have:

1. Do we want to allow only one `HTTPUpgradeType` configuration - even though `CONNECT` is probably not going to be used a lot, it would still force someone to choose either `websocket` or `CONNECT`.
2. Defaults. Do we want it on by default at some point?

**Comment by shashankram** [comment]
> Thanks, I'll work on a PR for that.
> 
> A few questions I'd still have:
> 
> 1. Do we want to allow only one `HTTPUpgradeType` configuration - even though `CONNECT` is probably not going to be used a lot, it would still force someone to choose either `websocket` or `CONNECT`.
> 2. Defaults. Do we want it on by default at some point?

Those are good questions. Based on my understanding from the [upgrade_config doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig), it seems like Envoy does not support multiple upgrade types at the moment?
`The current implementation of upgrade headers does not handle multi-valued upgrade headers. Support for multi-valued headers may be added in the future if needed.`

For now let's default to the existing behavior of not upgrading if this configuration is not set. Another thing to consider is whether this property should be global or per upstream. If this configuration goes into MeshConfig, it's going to be a global property for all upstreams. If we need to make this configurable per upstream, then we have more work to be done in this regard, and would need to add this to the existing UpstreamTrafficSetting CRD.

**Comment by steeling** [comment]
> > Prototype implementation using a feature flag seems to make what I need work: [release-v1.1...dasMulli:feature/websockets-on-release-v1.1](https://github.com/openservicemesh/osm/compare/release-v1.1...dasMulli:feature/websockets-on-release-v1.1)
> 
> @dasMulli thanks for the prototype. Could you make the following tweaks and create a PR:
> 
> 1. Add a field called `HTTPUpgradeType` under `MeshConfig.Spec.TrafficSpec`
> 2. If the above field is set, update the HttpConnectionManager configuration
> 
> *Note: You do not need to add helpers to pkg/configurator. Instead, use `GetMeshConfig().Spec.TrafficSpec.HTTPUpgradeType` directly.

Why not add this as a default, and just always allow it? As in, not even provide a toggle to turn it off?

If there is a reason to turn it off, I think that would indicate there's a reason to turn this on/off on individual services. In that case it likely shouldn't be a field on the mesh_config. Do others have thoughts?
Adding this on the `mesh_config` feels like the wrong place, since that would have it apply to the entire mesh.

**Comment by shashankram** [comment]
As noted in https://github.com/openservicemesh/osm/issues/4725#issuecomment-1124004397, it's okay to have a global default, and such defaults should be added in the MeshConfig. For per upstream configuration, this would need to be incorporated into the UpstreamTrafficSetting CRD.

However, the other upgrade option `connect` is unlikely to be commonly used, so I think to simplify this we can set the default upgrade_type to `websocket` and not worry about exposing a toggle.

@dasMulli let's go with this approach of setting the default to `websocket` as it will simplify this task. We can look into supporting support for other upgrade types in the future if the need arises.

**Comment by dasMulli** [comment]
>@dasMulli let's go with this approach of setting the default to websocket as it will simplify this task. We can look into supporting support for other upgrade types in the future if the need arises.

@shashankram so that means similar to my draft PR just with the default being `"websocket"` instead of `""`?

> However, the other upgrade option connect is unlikely to be commonly used, so I think to simplify this we can set the default upgrade_type to websocket and not worry about exposing a toggle.

I do agree that "connect" is unlikely to be used unless someone wants to implement an HTTP proxy within a service mesh.

> Based on my understanding from the [upgrade_config doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig), it seems like Envoy does not support multiple upgrade types at the moment?

I think they do support multiple differnt upgrade types, so for example websocket upgrades (`GET /mysocket HTTP/1.1\nUpgrade: websocket\nConnection: Upgrade`) and a connect request (`CONNECT my.service.com:123 HTTP/1.1`) but not an upgrade header with multiple values where the client offers multiple supported protocols in oder of preference and waits for the server to decide on the protocol in the 101 response (e.g. `GET /myresource HTTP/1.1\n:Upgrade: foo, bar`).

**Comment by shashankram** [comment]
> > @dasMulli let's go with this approach of setting the default to websocket as it will simplify this task. We can look into supporting support for other upgrade types in the future if the need arises.
> 
> @shashankram so that means similar to my draft PR just with the default being `"websocket"` instead of `""`?

Yes, let's set `{UpgradeType: "websocket"}` for the [http connection manager](https://github.com/openservicemesh/osm/blob/main/pkg/envoy/lds/http_connection.go#L49). Since we don't care about `connect` for now, we don't need to worry about exposing additional values.
