### ISSUE TITLE
Question / Doc: Expose TCP services

### ISSUE THREAD

**Issue by dasMulli** [openservicemesh/osm#4726]
I'm unable to figure out using the documentation if/how tcp-based services can be exposed to mesh-external or cluster-external sources or if that szenario is even supported.

This includes:
* Gradually onboarding services to the cluster but still allowing inbound TCP connections (SMTP and AMQP in my case)
* Exposing TCP-based services (IngressBackend with `protocol: tcp` doesn't seem to work)

**Comment by mudit-01** [comment]
Hi @dasMulli this can help https://release-v1-1.docs.openservicemesh.io/docs/demos/egress_policy/#tcp-egress ?

**Comment by dasMulli** [comment]
@mudit-01 this is about egress, i'm looking for TCP ingress

**Comment by dasMulli** [comment]
What would be needed for TCP ingress? As in: does it interfere with mTLS config in other lesteners / filter chains etc, parts of work that would need to be done etc.
