### ISSUE TITLE
Deprecate osm.vault.token in favor of a secret reference

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4745]
**Please describe the Improvement and/or Feature Request**

If Vault is the chosen certificate provider, the user must set the `osm.vault.token` value. I propose removing this option. Instead, we would require the user to create a Kubernetes secret storing the Vault token and set a new `osm.vault.tokenSecretName` value. The secret name would be used to populate the Vault provider token secret reference section of the MeshRootCertificate created by OSM or the user.  OSM would obtain the Vault token for the Vault client from the Kubernetes secret referenced in the MeshRootCertificate.

Related to #4737 

**Scope (please mark with X where applicable)**
- Certificate Management     [x]

**Comment by jaellio** [comment]
Blocked by version supportability constraint. Cannot add a breaking change between minor osm versions.

**Comment by jsturtevant** [comment]
Another approach that can enable this without removing immediately would be to use the `osm.vault.tokenSecretName` on the MRC and if not found look it up. This is the approach taken in #5027. Once we have this transition can then remove in a later release.
