### ISSUE TITLE
Enable Permissive Mode by Default

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4748]
**Please describe the Improvement and/or Feature Request**
For upstream OSM, permissive mode is currently disabled by default. In order to ensure a smooth first user experience, permissive mode should be enabled by default

**Scope (please mark with X where applicable)**
- Permissive Traffic Policy  [X]

**Possible use cases**
As a first-time OSM user, I want to be able to experience the benefits of OSM as quickly as possible.

**Comment by steeling** [comment]
We should also consider enabling this by default for ingress/egress traffic

**Comment by steeling** [comment]
done
