### ISSUE TITLE
Feature: Custom Trust Domains

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4754]
We have received feature requests from customers that require custom trust domains for their services. This means that certificates issued should have a common name of the format:

`<identity-name>.<namespace>.<custom-trust-domain>`

Additionally, we should add the DNS entry with the custom trust domain in `k8s.GetHostnamesForService`.

With the new MRC, we can build this in such a way that we can migrate from one trust domain to another with 0 downtime. To do so, we will add a new immutable field to the MRC, "trustDomain".

This issue will track the sub-issues for implementation:

- [x] Decouple service identity from common name, by stripping the trust domain from service identity
- [x] Add the trust domain field to the MRC, and plumb through to the Getter described in the step above.
- [x] Add a validation that the trust domain field cannot change to the validating webhook
- [x] Add the required business logic to actually use the new trust domain

**Comment by steeling** [comment]
Brief proposal https://docs.google.com/document/d/1nLI4PcfB7-hdPvJipQwQ9dw28f8G7p77iqv3VzsCRFI/edit#

**Comment by steeling** [comment]
Kind of. That is actually already possible although the service certs won’t have the custom trust domain. 

This is for users that use a PKI with a requirement that all certs have a specific trust domain

**Comment by jsturtevant** [comment]
Synced with @steeling, this work is complete but dependent on cert-rotation work to be released

**Comment by keithmattix** [comment]
@steeling If the work for this is complete, can we close this? I think we've captured cert-rotation work elsewhere
