### ISSUE TITLE
Provide mTLS certificate issuance outside of OSM self-signed mechanisms

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#4766]
**Please describe the Improvement and/or Feature Request**
There are secured environments that cannot utilize self-signed certificates. Certificates need to be signed by existing PKI infrastructure and maintain cert chain.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [X]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
User can configure OSM to utilize certificates signed from existing PKI infrastructure for mTLS service to service authz.

**Comment by steeling** [comment]
Can we close this as completed with support through cert manager?

**Comment by phillipgibson** [comment]
@steeling can you ref the issue # on that one pls? I'll take a look at it.
