### ISSUE TITLE
Enable Envoy Access Logging

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm#4797]
**Please describe the Improvement and/or Feature Request**
Allow configuration in OSM to allow the ability to enable Envoy access logging. This Envoy configuration is documented as part of the project [Access logging](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging). 

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
This would enable users to send Envoy access logs to a SEIM for analysis.

**Comment by shashankram** [comment]
Hey @phillipgibson, I believe access logging is enabled for Envoy. Is there a problem you are seeing with these not being seen in the Envoy logs?

**Comment by phillipgibson** [comment]
Not a problem if this is enabled. I guess we need to provide some docs on how to view and/or access the logs. Use case is to send  stdout to a SEIM system.

**Comment by shashankram** [comment]
@phillipgibson I am going to close this issue as access logging is enabled. Would you mind opening an issue in the `osm-docs` repo pertaining to the documentation request.
Thanks

**Comment by shashankram** [comment]
@phillipgibson The access log should look like this in the Envoy logs:
```
{"bytes_received":0,"x_forwarded_for":null,"request_id":"10c5afce-746f-451b-a02f-58840d501d56","response_code":200,"upstream_cluster":"bookstore/bookstore|14001|local","time_to_first_byte":725,"path":"/buy-a-book/new","start_time":"2022-06-08T17:17:06.820Z","response_code_details":"via_upstream","authority":"bookstore.bookstore.svc.cluster.local:14001","bytes_sent":1407,"requested_server_name":"bookstore-v1.bookstore.svc.cluster.local","method":"GET","protocol":"HTTP/1.1","upstream_service_time":"725","user_agent":"Go-http-client/1.1","response_flags":"-","duration":726,"upstream_host":"127.0.0.1:14001"}
```

**Comment by phillipgibson** [comment]
> @phillipgibson The access log should look like this in the Envoy logs:
> 
> ```
> {"bytes_received":0,"x_forwarded_for":null,"request_id":"10c5afce-746f-451b-a02f-58840d501d56","response_code":200,"upstream_cluster":"bookstore/bookstore|14001|local","time_to_first_byte":725,"path":"/buy-a-book/new","start_time":"2022-06-08T17:17:06.820Z","response_code_details":"via_upstream","authority":"bookstore.bookstore.svc.cluster.local:14001","bytes_sent":1407,"requested_server_name":"bookstore-v1.bookstore.svc.cluster.local","method":"GET","protocol":"HTTP/1.1","upstream_service_time":"725","user_agent":"Go-http-client/1.1","response_flags":"-","duration":726,"upstream_host":"127.0.0.1:14001"}
> ```

@shashankram can you provide the command that shows the log output?

**Comment by shashankram** [comment]
> > @phillipgibson The access log should look like this in the Envoy logs:
> > ```
> > {"bytes_received":0,"x_forwarded_for":null,"request_id":"10c5afce-746f-451b-a02f-58840d501d56","response_code":200,"upstream_cluster":"bookstore/bookstore|14001|local","time_to_first_byte":725,"path":"/buy-a-book/new","start_time":"2022-06-08T17:17:06.820Z","response_code_details":"via_upstream","authority":"bookstore.bookstore.svc.cluster.local:14001","bytes_sent":1407,"requested_server_name":"bookstore-v1.bookstore.svc.cluster.local","method":"GET","protocol":"HTTP/1.1","upstream_service_time":"725","user_agent":"Go-http-client/1.1","response_flags":"-","duration":726,"upstream_host":"127.0.0.1:14001"}
> > ```
> 
> @shashankram can you provide the command that shows the log output?

The access logs are a part of Envoy logs as noted in my previous comment.
You can retrieve the Envoy logs using `kubectl logs <pod> -n <namespace> -c envoy [options]`
