### ISSUE TITLE
Question: Filter HTTP Request by Path or Method

### ISSUE THREAD

**Issue by benediktwetzel** [openservicemesh/osm#4806]
Is there any way to filter the metric/http request by a specific requested path (e.g. /login/login.html)? Or is it possible to filter by HTTP methods, like GET or POST? 
 Unfortunately I am not able to find anything in the docs.

Thanks a lot!

**Comment by shashankram** [comment]
> Is there any way to filter the metric/http request

Hey @benediktwetzel, are you looking to filter stats specifically?
If yes , the default stats emitted by Envoy do not encode path/method specific info. See https://github.com/envoyproxy/envoy/issues/1585 and https://github.com/envoyproxy/envoy/issues/13673 for more info.
It may be possible to aggregate stats by these HTTP attributes, but that likely requires a WASM extension which we don't support at the moment.

Or are you referring to filtering traffic access via policies?

**Comment by steeling** [comment]
Specifically for path, this would actually be really tough for any service mesh to do properly for a couple reasons:

1) [Metric label cardinality limits](https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels), and an unbounded set of of potential paths could grind any timeseries DB to a halt.
2) Paths often contain identifiers, ie: `/users/abc`, might be an exact path, or it might be a variable path of the form `/users/:id` which our users may not want to record.

Hypothesizing a solution, we could allow for an API that allows users to specify subsets of paths, path prefixes, or path regexes. However, given our current roadmap, I would probably recommend to users that they implement their own path counters for this purpose.

**Comment by benediktwetzel** [comment]
Yes, I do understand your point. Maybe filtering/labeling by paths is not suitable in practice. 

But labeling by HTTP method should be possible. I think this could be a good feature in many situations.
