### ISSUE TITLE
Traffic to service through AzureLoad balancer blocked after injecting osm envoy proxy

### ISSUE THREAD

**Issue by saranstarz** [openservicemesh/osm#4829]
We have a service running on kubernetes (setup using aks engine) that is exposed to VMs outside the cluster using Azure Internal Load balancer as shown below. The clients inside the VM connect to the service using GRPC w/http2.

VM (outside k8s) ---- LB -- Service(inside K8s)

When I was evaluating OSM, I created an alternate path to the service using Contour and OSM.
With OSM the topology looks like this.

VM ----- LB --------- Service 
     \\------- Contour-----/

Now, after injecting the envoy proxy to the service pods, the existing connections through the Load balancer fail. New connection through the Load balancer receive a RST from the service. However, new connections through Contour works. I don't see the issue when i disable the proxy injection. Also, I don't see any logs on the proxy container for the failed connections.

I already set the enablePermissiveTrafficPolicy flag to true on the config. It doesn't help.
Need help to check if I am missing any other configurations.

**Comment by shashankram** [comment]
Currently, the only way to access a service that is a part of the mesh is by using an Ingress controller, and using the IngressBackend configuration to permit external clients to access the backend service.

Have you looked at https://release-v1-1.docs.openservicemesh.io/docs/guides/traffic_management/ingress/?

**Comment by saranstarz** [comment]
Thank you for the response. We are a brownfield deployment and I was exploring options to check the possibility of a smooth transition to using OSM without disrupting the existing connections.
