### ISSUE TITLE
Leverage a builder pattern for all generated Envoy configs

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4862]
[See motivation here](https://docs.google.com/document/d/1L_u-XlVU8Fog-uFS3Uf0O2nz8IArQy82cd6Npxm038Y/edit#)

This issue will serve as the master issue for translating all Envoy config generation code to builders.

There are 2 additional caveats to using builders:

- [ ] All inputs to the builder should be OSM objects. That is to say, if the input is a k8s service, the input should instead be a `service.MeshService` We can make exceptions for cases where there are no OSM objects to represent the underlying K8s object.
- [ ] Inputs should be fully decoupled from outputs. Currently, some of the trafficpolicy objects are loosely coupled with the resulting envoy config. For instance, some of the trafficpolicy objects mention `WeightedClusters`, or have the `MeshService` exposed in multiple places. These should be normalized, with calls to the builder, ie:

```go
builder.SetServices(services)
builder.Routes(routes)
```

An example of what this will look like:

In each of the `NewResponse` functions, we build the envoy configs in an inconsistent manner. For example, in sds, we create an `sdsImpl`

```go
	s := &sdsImpl{
		meshCatalog:     meshCatalog,
		certManager:     certManager,
		serviceIdentity: proxy.Identity,
		TrustDomain:     certManager.GetTrustDomain(),
	}
```

This mixes the builder pattern with a client/composer. Instead, we should set (data) inputs on a builder, and call a `Build()` method to generate the output, only once all the input is provided. That means pulling out the client calls outside of the `sdsImpl`. This would look like:

```go

builder := sds.NewBuilder()
builder.SetCertificate(cert)
builder.SetServiceIdentities(svcIdentities)

return builder.Build()
```

This makes it clear what the inputs and outputs to the builder is, without hiding the inputs behind deeply nested client calls.

**Comment by keithmattix** [comment]
@steeling has this been completed?

**Comment by steeling** [comment]
Ya, closing out
