### ISSUE TITLE
Need guidance for Maintainer role

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#4864]
**Please describe what should be documented**
Hi, OSM maintainers I have been actively working in OSM for a few months and would like to level up to the maintainer position and need some guidance for the same.
It would be very helpful if I can work closely with someone so that I can level up on the contribution ladder.
Thank you
**Please suggest where in the repo the document should be located**

**Comment by shalier** [comment]
@openservicemesh/osm-maintainers PTAL

**Comment by phillipgibson** [comment]
@mudit-01 please review the contribution ladder here https://github.com/openservicemesh/osm/blob/main/CONTRIBUTOR_LADDER.md

**Comment by mudit-01** [comment]
Thanks, @phillipgibson I came across https://github.com/openservicemesh/osm/blob/main/CONTRIBUTOR_LADDER.md#review-process and what to know more about how I can work with any maintainer for moving up in the role ladder?

**Comment by mudit-01** [comment]
@phillipgibson any update on the mentor thing?

**Comment by keithmattix** [comment]
Hi @mudit-01; sorry for the delay! I'm pleased to inform you that @allenlsy has agreed to help mentor you through the contributor ladder! Allen is an extremely talented engineer, and he'll be able to help you move through the contributor ladder. We can talk about the details on Slack, but I'll consider this issue closed 👍🏾

**Comment by mudit-01** [comment]
Thanks!!! @keithmattix for the update and @allenlsy for taking me as a mentee :).
