### ISSUE TITLE
Add CI job that runs the full load test suite

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm#4872]
**Please describe what should be documented**

This is a sub-issue for #4822 

Create a CI job runs the internal OSM load test suite (currently a private project) periodically.

This CI job works as:

1. Pull [osm-perftest](https://github.com/openservicemesh/osm-perftest) repo.
2. Execute the script that performs the full load test suite. The final result will be saved in a local csv file on the job VM.
3. Output the results to a certain page. Possible solutions are: a Github wiki page, as comment to the latest merged PR, or cloud file storage.

In order to implement step 1, an access token should be created in osm-perftest and secret should be added to osm repo.

**Please suggest where in the repo the document should be located**

**Comment by steeling** [comment]
do you know what scopes you need the token to have?
https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes

**Comment by allenlsy** [comment]
@steeling since the job only need to read osm-perftest repo, according to the doc, I think `(no scope)` grants read-only permission which is sufficient for our case.

**Comment by steeling** [comment]
A PAT will give access to a user's private repo's, so we should figure out another way to do this, including considering open sourcing that repo if we want.
