### ISSUE TITLE
OSM CLI command for root cert rotation and checking status

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4890]
Add a command to the OSM CLI to allow users to initiate OSM root certificate rotation and move between rotation stages. The command should also output the current status of a rotation if one is ongoing.

**Todo:**
- [ ] Design doc https://docs.google.com/document/d/1MQZ4QPeKV2pxZ30uaYIxMjVYQUGdgQmK0eLYy1JzpHs/edit#
- [ ] Customer meetings/ feedback on design
- [ ] Implementation
- [ ] Testing
- [ ] Docs
- [ ] Demo

**Comment by shalier** [comment]
Waiting on Root certificate rotation MVP [#4998](https://github.com/openservicemesh/osm/issues/4998), to help figure out our unknowns and get additional feedback

**Comment by jsturtevant** [comment]
rotation as initial mvp is covered in https://github.com/openservicemesh/osm/pull/5207

Status is something to do in next phase.
