### ISSUE TITLE
Support OSM root certificate rotation rollback

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4893]
If OSM root certificate rotation fails, OSM should be able to recover and revert to a previous stable state. This issue proposes adding the functionality to support root certificate rotation rollback on error or on user request

Questions to consider:
- Should the user be able to stop root certificate rotation at any stage and revert to a previous stable state?
- How should OSM handle reverting to a previous MRC?
- Should OSM be responsible for performing this recovery?

**Comment by jsturtevant** [comment]
With the new design in #5201, we implicitly support this since I user could move from one stage to another. If we have a fully automated solution, we can revisit this as part of the design there.
