### ISSUE TITLE
Osm-gitops

### ISSUE THREAD

**Issue by Parul-mahajan** [openservicemesh/osm#4895]
Please help me!

Is it possible to use gitops or github actions with flagger and osm with multiple pods. I am working on the basic demo osm bookstore app on aks cluster.

And how will this CI/CD pipeline work.  

https://github.com/clarenceb/bookstore

I am new to whole gitops and service mesh part can someone help me with relevant resources

**Comment by phillipgibson** [comment]
Hey @Parul-mahajan. Have you checked out our [Flagger integration doc](https://release-v1-2.docs.openservicemesh.io/docs/guides/integrations/flagger/). That might be the best starting point.
