### ISSUE TITLE
Cleanup inactive MeshRootCertificates

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4896]
After a successful OSM root certificate rotation, there will be a MeshRootCertificate resource in an inactive state. The user or OSM should be able to clean up the unused MeshRootCertificate resource.

Questions to consider:
- Should the user be able to specify if they want OSM to clean up the inactive MeshRootCertificate or if they want to perform the cleanup manually?
- Should OSM immediately delete an inactive MeshRootCertificate in response to a state change to inactive? Or should there be a waiting period before the resource is deleted?

**Comment by steeling** [comment]
I don't think we should be automating deletions here. If you think  of a standard CI/CD setup, it would be very easy to delete, and another run comes in but still has the old MRC, now it will re-create it, but without the data on its state OSM will think its a new one, and begin a rollout to that.

**Comment by jaellio** [comment]
Got it, thank you for adding that context. Closing.
