### ISSUE TITLE
Add e2e tests for bundled chart (e.g. Contour)

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4903]
**Please describe the Improvement and/or Feature Request**

Add e2e tests to validate the behavior of integrations (e.g. Contour)
**Scope (please mark with X where applicable)**

- Tests                      [X]

**Possible use cases**

**Comment by mudit-01** [comment]
Hi pls assign this to me.

**Comment by keithmattix** [comment]
You got it @mudit-01. Thanks for helping to tackle this issue!

**Comment by mudit-01** [comment]
working on this pls don't close

**Comment by mudit-01** [comment]
@keithmattix For this issue is there specific bundled chart that is required like contour or there is some other expectation?

**Comment by keithmattix** [comment]
@mudit-01 just contour! We need an E2E test (similar to the existing ones) that tests that requests can be made to contour after installing the helm chart

**Comment by mudit-01** [comment]
working on it

**Comment by mudit-01** [comment]
wip
