### ISSUE TITLE
Bug in Getting Started (https://release-v1-1.docs.openservicemesh.io/docs/getting_started/install_apps/#view-the-application-uis)

### ISSUE THREAD

**Issue by mifurm** [openservicemesh/osm#4906]
**Please describe what should be documented**
In the section (View the Application UI) of OSM you refer to ./scripts/port-forward-all.sh script. The script is using set of other forward scripts, one for bookstore (./scripts/port-forward-bookstore-ui-v1.sh). The bookstore script is looking for pod with label bookstore-v1 while there is no such app in the cluster.
**Please suggest where in the repo the document should be located**
The script ./scripts/port-forward-bookstore-ui-v1.sh should refer to the pod with label bookstore, not bookstore-v1.

**Comment by shashankram** [comment]
@mifurm Yes this due to a recent change in `main` regarding labels on the bookstore app + service. Will fix this on `main`.

**Comment by shashankram** [comment]
> @mifurm Yes this due to a recent change in `main` regarding labels on the bookstore app + service. Will fix this on `main`.

Never mind, figured this is an existing issue unrelated to the recent change I made. Will fix this along with the other labeling changes to the app manifests and scripts.
