### ISSUE TITLE
Make manual bookstore demo terminal friendly without needing UI navigation

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4908]
**Please describe the Improvement and/or Feature Request**
Currently, the manual bookstore demo documented in the [getting started guide](https://main--osm-docs.netlify.app/docs/getting_started/install_apps/) requires a bunch of additional scripts (port-forward, tail, etc.) and UI navigation with multiple windows to understand the demo.

This issue proposes to make the manual bookstore demo purely an experience that can be visualized on the terminal without needing to run several scripts and UI navigation. It's also inconvenient for users to checkout the `osm` repo and run these scripts, so replacing these scripts with individual commands would render a better user experience.

This will reduce the maintenance burden that comes from having scripts specifically targeting the manual demo experience and UI rendering on the browser.

**Scope (please mark with X where applicable)**
- Demo                       [X]

**Possible use cases**

Make the manual demo a purely terminal experience.

**Comment by phillipgibson** [comment]
I thought about re-architecting the demo app down to a single view to show all the activity. I'm thinking we should decouple it from the build as well as a separate project. Thoughts?

**Comment by shashankram** [comment]
> I thought about re-architecting the demo app down to a single view to show all the activity. I'm thinking we should decouple it from the build as well as a separate project. Thoughts?

Currently, it's a hassle to maintain the demo specific scripts such as the port-forwarding ones. I'd rather we drop the UI from the demo and make it a purely terminal experience so that the documented demo is testable on the CI as well.

I didn't get the part about decoupling it from the main repo. Could you share the motivation for that?

**Comment by keithmattix** [comment]
>  I'd rather we drop the UI from the demo and make it a purely terminal experience so that the documented demo is testable on the CI as well.

+1 from me
