### ISSUE TITLE
Leverage Builder pattern for LDS

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4920]
Subtask of #4862, this is specifically for the LDS configs.

We should create a builder object that takes as inputs all data, and calls build. It should not make any network calls, or call out to other methods to get *more data*.

It *can* use nested builders if it makes sense to do so. See the parent issue and associated design doc for more info.

**Comment by shashankram** [comment]
I am refactoring the existing HTTP connection manager code. I'll ensure to follow this pattern, but a heads up to not refactor the LDS part of the code till that's done. Thanks
