### ISSUE TITLE
Leverage Builder pattern for EDS

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4923]
Subtask of #4862, this is specifically for the EDS configs.

We should create a builder object that takes as inputs all data, and calls build. It should not make any network calls, or call out to other methods to get *more data*.

It *can* use nested builders if it makes sense to do so. See the parent issue and associated design doc for more info.

**Comment by allenlsy** [comment]
https://github.com/openservicemesh/osm/pull/4957
