### ISSUE TITLE
Leverage builder pattern for RDS

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4924]
Subtask of #4862, this is specifically for the RDS configs.

We should create a builder object that takes as inputs all data, and calls build. It should not make any network calls, or call out to other methods to get *more data*.

It *can* use nested builders if it makes sense to do so. See the parent issue and associated design doc for more info.

**Comment by shashankram** [comment]
@nshankar13, this will be impacted by the work I am doing for HTTP rate limiting as a part of https://github.com/openservicemesh/osm/issues/2018. I might wrap that in a week or so. Can this wider refactor of the RDS code wait till then?

**Comment by shashankram** [comment]
@nshankar13 the rate limiting work is complete.
