### ISSUE TITLE
Leverage Builder pattern for trafficpolicy.* objects

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4925]
Subtask of #4862
This isn't quite needed for *every* object type, but for some of the more complex objects it makes sense.

The mesh catalog currently has 2 responsibilities:

1. Querying the underlying clients to retrieve control plane data
2. constructing the trafficpolicy.* objects.

We should separate these and move the logic of data construction into a builder object. There should be one builder for each object type.

**Comment by steeling** [comment]
FYI This may be splittable into further sub tasks as well

**Comment by nshankar13** [comment]
Currently, the logic for constructing traffic policies is entirely handled by the mesh cataloger. For instance, the inbound mesh traffic policy is built in the GetInboundMeshTraffic policy in inbound_traffic_policies.go, outbound in outbound_traffic_policies, etc. Instead, this logic can reside in an "inboundTrafficPolicyBuilder" object, which would be defined in pkg/traffic policies. Instead of constructing the trafficpolicies from the meshcataloger, the response.go for lds, rds, cds can instead create this builder object and pass in all the necessary information, which will then create and return the corresponding trafficpolicy in the Build() method. 

Because this logic would affect lds, cds, and rds, it would make sense for this task to wait for the refactoring tasks corresponding to those 3 xDS protocols to be completed.

**Comment by nshankar13** [comment]
Another option is to additionally build sub builders for the trafficPolicies themselves - for instance, distinguishing between the inboundMeshTrafficPolicyBuilder and the inboundTrafficPolicy builder (the meshtrafficpolicy objects stores the trafficpolicies for each port). However, this may only be necessary if the meshtrafficpolicybuilder code gets too long / unwieldy.

**Comment by steeling** [comment]
> Currently, the logic for constructing traffic policies is entirely handled by the mesh cataloger. For instance, the inbound mesh traffic policy is built in the GetInboundMeshTrafficPolicy method in inbound_traffic_policies.go, outbound in outbound_traffic_policies, etc. Instead, this logic should be removed from the meshcataloger and instead be handled by an "inboundMeshTrafficPolicyBuilder" object, which would be defined in pkg/traffic policies (and outboundMeshTrafficPolicyBuilder, etc). Instead of constructing the trafficpolicies from the meshcataloger, the response.go for lds, rds, cds can instead create this builder object and pass in all the necessary information, which will then create and return the corresponding trafficpolicy in the Build() method.
> 
> Because this logic would affect lds, cds, and rds, it would make sense for this task to wait for the refactoring tasks corresponding to those 3 xDS protocols to be completed.

A couple things here:

1) We should be deconstructing these objects as much as possible. For instance, inboundMeshTrafficPolicyBuilder, is used in 3 builders (LDS, CDS, RDS). It also has exactly 3 fields, each field uniquely is distinctly used by one of the builders above. That is to say, that object does not need to exist. Instead, there should be 3 methods on the MeshCatalog in its place:

1. GetInboundTrafficMatches
2. GetInboundHTTPRouteConfigsPerPort
3. GetInboundClustersConfigs

2) Second point, we are in the process of separating our domains of the client objects in #4863. So the MeshCatalog's responsibility is to query the compute.Interface for low-level OSM objects (think MeshService, SMI objects, ServiceIdentities, Endpoints, etc), and build higher level OSM objects (think trafficpolicy.* objects).

The MeshCatalog however looks a lot like the prior state of the xDS configs, were it mixes building and querying through deeply nested calls. We want to separate this out for the builder pattern.

One major caveat is that if in point "1" above, if we can "desconstruct" these objects enough, such that the xDS builders take as input more "low-level" OSM objects, instead of the higher level trafficpolicy.* objects, we may completely remove the MeshCatalog altogether (or collapse it into the compute.Interface -- time will tell if we will be able to do this).

**Comment by nshankar13** [comment]
> Instead, there should be 3 methods on the MeshCatalog in its place:
GetInboundTrafficMatches
GetInboundHTTPRouteConfigsPerPort
GetInboundClustersConfigs

Little confused by this, isn't the point of using the builder pattern here so that the meshcataloger doesn't have to construct the trafficpolicies or build the traffictargets, routingRules, etc?

**Comment by steeling** [comment]
The MeshCatalog will be analogous to the response.go's NewResponse method.

It will make  queries to the compute.Interface, and set fields on a builder object, finally calling `Build`.

Except instead of one NewResponse, there can be N methods (one for each object type), each method following that pattern

**Comment by nshankar13** [comment]
Got it. 

> That is to say, that object does not need to exist

Just to clarify, by this, did you mean that we should have a generic builder object that handles Inbound, Outbound, Ingress, and Egress, instead of having a distinct builder for each of these traffic policies?

**Comment by steeling** [comment]
> Member

Great question! 

Maybe, it's quite possible it would be cleaner to do it that way. I'd say that's up to whoever implements it :)

**Comment by nshankar13** [comment]
Subtasks:
- https://github.com/openservicemesh/osm/issues/5059

**Comment by nshankar13** [comment]
https://github.com/openservicemesh/osm/issues/5098

**Comment by nshankar13** [comment]
Update: The traffic policy objects have been broken up in favor of individual methods in `pkg/catalog` traffic_policies files (ex: GetInboundMeshConsterConfigs, GetOutboundMeshClusterConfigs, etc). However, we still want these methods to be part of a separate builder object (InboundMeshTrafficPolicyBuilder, for instance) rather than being coupled with the meshcatalog itself.
