### ISSUE TITLE
Collapse all k8s funcs/methods onto k8s.Client

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4933]
From #4863 collapse all of the k8s input/output methods/funcs onto the k8s.Client object.

This includes any function that accepts a controller/client object as a parameter, as well as all of

pkg/smi
pkg/configurator
pkg/policy
pkg/k8s
pkg/config

**Comment by allenlsy** [comment]
`pkg/smi` cannot be directly collapsed into `k8s.Client` as there will be [circular import](https://github.com/openservicemesh/osm/blob/52bd5a7d8d190fc2e02a13f252250cd585a66619/pkg/smi/types.go#L24).  Therefore we will create a new `Client` interface in `pkg/mesh`. This MeshClient will do that job that communicate with k8s resources.

**Comment by steeling** [comment]
Hey @allenlsy, there may be some misunderstanding here on how to accomplish this.

The methods on the SMI client should be moved to the k8s client, and the SMI client should go away. Any necessary fields can be added to the k8s client. Take a look at this PR which did the same for the configurator https://github.com/openservicemesh/osm/pull/5006

**Comment by allenlsy** [comment]
PR for pkg/policy: https://github.com/openservicemesh/osm/pull/5014
