### ISSUE TITLE
[Research] Investigate MultiClusterService (MCS) APIs

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4935]
Kubernetes sig-multicluster hosts a set of APIs for describing services that exists between clusters. We need to investigate the APIs, their semantics, existing implementations, and what a potential implementation would look like for OSM. 

**Deliverables**
A markdown file briefly describing what the MCS APIs do, whether or not OSM will implement support for it (based on discussion here and in GitHub discussions), and the rationale for that decision. 

**Related Reading**
[MCS Kubernetes Enhancement Proposal (KEP)](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api) describing the APIs
YouTube [playlist](https://www.youtube.com/playlist?list=PLD7fHK-tlhJa2mh8hnpyU15lX5Ru0nF23) with videos on the APIs

**Comment by allenlsy** [comment]
A quick summary of MCS API and thoughts related to OSM project (deliverable) is posted https://github.com/openservicemesh/osm/discussions/4945

**Comment by keithmattix** [comment]
@allenlsy Can we close this?

**Comment by allenlsy** [comment]
yes we can mark it as completed I think
