### ISSUE TITLE
Migrate MRC Status State to use Conditions

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#4962]
[Conditions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) are a pattern for status reporting in Kubernetes that has several advantages over a single field with a set of enumerated values.  A good example of a resource that uses conditions effectively is [pods](https://maelvls.dev/kubernetes-conditions/#pod-example).

For the resources such as `MeshRootCertificate` that represent long-running actions, having stable conditions that represent a higher-level state of the object is useful. Additionally, an aggregate status field (such as `Phase` for Pod) is also beneficial for even more generic reporting. 

Considerations:
- [Conditions are part of API compatibility](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)
>  Once defined, the meaning of a Condition can not be changed arbitrarily - it becomes part of the API, and has the same backwards- and forwards-compatibility concerns of any other part of the API.
- Conditions should be computable based on the spec of the object; this applies to `status` fields in general. This means we likely need to add more information to the MRC spec fields. 
  - What's the minimum number of fields we have to add?
- What states should be represented via status vs condition?

**Comment by keithmattix** [comment]
Should we consider using [conditions](https://github.com/kubernetes/community/pull/4521/files) here?

**Comment by keithmattix** [comment]
We should likely close this in favor of #5044
