### ISSUE TITLE
Upgrade to Go 1.18 or higher

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4966]
After the release of Go 1.19, Go 1.17 has fallen out of support. We need to upgrade to Go 1.18 or higher to receive the latest security fixes.

**Comment by steeling** [comment]
Not that we shouldn’t upgrade, but do you have a link to that support policy?

**Comment by keithmattix** [comment]
Sure: https://go.dev/doc/devel/release#policy
