### ISSUE TITLE
Migrate pkg/cli/verifier/* to use the kube.Provider for all queries

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4970]
This will require translating from k8s inputs to to OSM inputs. ie: `NewPodConnectivityVerifier` should become `NewProxyConnectivityVerifier`

We should keep everything in cmd/cli aware of k8s, but it should translate into the OSM types to request info from the kube client.

This will help us reduce and reuse existing code for querying the control plane.

**Comment by shashankram** [comment]
Let's discuss this before working on the task. I don't think we need to spin up a controller within the CLI just to make fetch objects from the API server.

**Comment by steeling** [comment]
When you say "spin up" what do you mean? Are you referring to informer cache related things?

If that's the case I agree, and have some plans to address that (thought I had created a bug but now seeing that's not the case)

**Comment by shashankram** [comment]
> When you say "spin up" what do you mean? Are you referring to informer cache related things?
> 
> If that's the case I agree, and have some plans to address that (thought I had created a bug but now seeing that's not the case)

I am referring to not needing to run a controller (informer client, event handling + cache) within the CLI binary.
Let's not refactor any of the code till we are clear on what the current gaps are.
