### ISSUE TITLE
Document user stories around Multicluster tooling

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#4976]
What CLI commands are needed? Some ideas to get the ball rolling:

- [ ] For inspecting the health of a multicluster mesh
- [ ] Joining a set of clusters
- [ ] removing a cluster from a multicluster mesh
- [ ] Insepcting certificates across the mesh
- [ ] inspecting network topology
- [ ] Viewing single services that may exist in multiple clusters
- [ ] ?

Add as a component to the design doc https://docs.google.com/document/d/1Do9iw55mRuQii6W_l8ULbDiVZb1iG7dLhL75Nz_D8OE/edit

**Comment by keithmattix** [comment]
Is the deliverable for this issue CLI commands or user stories?

**Comment by steeling** [comment]
> Is the deliverable for this issue CLI commands or user stories?

user stories, that may have CLI commands proposed as a solution to those user stories.

Basically to plug into a tooling section in a larger design doc

**Comment by steeling** [comment]
Here's the doc where we will plug this info into https://docs.google.com/document/d/1Do9iw55mRuQii6W_l8ULbDiVZb1iG7dLhL75Nz_D8OE/edit
