### ISSUE TITLE
Determine feasibility of requiring containerD for Windows

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#4986]
Research if Windows customers need Docker or are willing to use containerD for service mesh

**Comment by ksubrmnn** [comment]
[containerD](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd)
[Docker](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker)

**Comment by phillipgibson** [comment]
Confirmed that Windows Containers does utilize containerD for runtime.
