### ISSUE TITLE
Investigate OSM root certificate rotation failure states and potential recoveries

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4997]
How to handle reverting an in-progress or failed root certificate rotation
How to depict an error state
How status should be represented
How to determine when to progress through each rotation stage
The root certificate rotation failure states and how to handle each failure scenario
What commands the users need to navigate the rotation stages and errors

Doc: [OSM Root Certificate Rotation Unknowns](https://docs.google.com/document/d/1jts40WtlTUcTRUohCIzU-qETL1IqnCY3ij2_DfPVDc8/edit?usp=sharing)

**Comment by keithmattix** [comment]
@jaellio I think this is done?
