### ISSUE TITLE
Root certificate rotation MVP

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4998]
#Get OSM root certificate rotation in a working state to be tested and receive feedback from customers.

MVP Goals
- Support manual root certificate rotation through status updates using the kubectl --subresource command 
  - Nice to have: CLI commands to navigate rotation stages
- Support happy path rotation and reverting rotation
  - Progression between rotation stages, no MRC deletion
- Metrics for certs in cache rotated (including issuer and validator IDs)
  - Nice to have % distribution metrics
- Certificate rotation documentation
- Happy path certificate rotation demo

Required items:
- [x] #4839
- [x] #4818 
- [ ] #4890 
- [x] #4962 
- [x] #4815 
- [x] #4723 
- [x] #5044
- [x] #5045
- [x] #5046

**Comment by jsturtevant** [comment]
For more details, please review the [Simplified Proposal for Manual Root Cert Rotation MVP](https://docs.google.com/document/d/1bh3Yfn5DXWjmzdKa4XHlk-9KepUNb_EgDDrzd1G_deY/edit#heading=h.86n6n6h1rqmo)
