### ISSUE TITLE
Improve behavior of certificate issuance and rotation fuctions

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#5002]
**Please describe the Improvement and/or Feature Request**
Some of the code pertaining to cert issuance and rotation seems to do more than it should, specifically `IssueCertificate` and `checkAndRotate` have logic in them that seems out of place.

- `IssueCertificate()` checks if a cert should be rotated. This should not be the case. `IssueCertificate()` should either issue a new cert, or get the cert from the cache if present. `startRotationTicker()` routine already implements logic to periodically rotate expired certs. It's more intuitive to not execute rotation business logic in the issuance API.

- `checkAndRotate()` should only issue a certificate if the cert has expired, and not call IssueCertificate unless the cert has expired. Currently, `checkAndRotate()` calls into `IssueCertificate()` *before* verifying if a cert needs to be rotated. This is also ambiguous to reason.

- Disambiguate `prefix` is in function parameters. From an API perspective, this seems like an internal implementation rather than something the caller should be aware of.

**Scope (please mark with X where applicable)**
- Certificate Management     [X]

**Possible use cases**
Improve API semantics.

**Comment by steeling** [comment]
FYI we'll need to move off the sync.map so we can do an atomic compare and swap

**Comment by shashankram** [comment]
> FYI we'll need to move off the sync.map so we can do an atomic compare and swap

Why is that necessary?

**Comment by jsturtevant** [comment]
> Disambiguate prefix is in function parameters. From an API perspective, this seems like an internal implementation rather than something the caller should be aware of.

I found a need to have more structure to the incoming IssueCertificate request.  Right now we take this prefix and optionally attach the trust domain (if not present).  To be able integrate spiffe, I have to know the internal structure of this a bit more than I would like to get the parts needed to for the Spiffe id in the certificate provider.  For example I need the trust domain, and currently the CN can come in the format of `ads.trustcomain.com`, `sa.ns.trustdomain.com`, and `proxyuid.type.sa.ns.trustdomain`.  Parsing these feels fragile.  

I am thinking we could make the concept of encoding the Identity into the IssueCertificate a bit more first class by providing more than just the pre-encoded CN to the Providers.  This would allow the providers to construct the names as needed.  

Going to explore this a bit more but wanted to get thoughts in case someone has already thought about this in some capacity.
