### ISSUE TITLE
'osm version' command returns invalid output with locally compiled versions

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#5007]
**Bug description**:
When using locally compiled binaries, the `osm version` command returns an invalid output:
```
$ osm version
CLI Version: version.Info{Version:"dev", GitCommit:"dddb8fa5a7a60dbb3c03843252807ee7bde2ffc8", BuildDate:""}

MESH NAME   MESH NAMESPACE   VERSION   GIT COMMIT                                 BUILD DATE
osm         osm-system       dev       dddb8fa5a7a60dbb3c03843252807ee7bde2ffc8   
Error: 1 error occurred:
	* Failed to output latest release information: could not parse "dev" as version
```

Since the version defaults to `dev` in the Makefile for local builds, outputting `dev` as a version should suffice to indicate a developer build of the software.

**Affected area (please mark with X where applicable)**:
- CLI Tool                   [X]

**Expected behavior**:
Developer builds should output the version as `dev`

**Steps to reproduce the bug (as precisely as possible)**:
Compile control plane binaries locally and deploy it using the CLI.
Run the `osm version` command.

**Comment by jaellio** [comment]
Assigning to @lam-man

**Comment by jaellio** [comment]
For reference, this is the PR that added the remote osm version to the `osm version` CLI output https://github.com/openservicemesh/osm/pull/4395

**Comment by lam-man** [comment]
Thanks @jaellio . I will work on this.

**Comment by lam-man** [comment]
I was able to reproduce the problem. Working on the fix.

**Comment by lam-man** [comment]
PR for the issue has been created. Thanks!
