### ISSUE TITLE
Make container injection idempotent to support Velero+Restic Restore

### ISSUE THREAD

**Issue by patst** [openservicemesh/osm#5008]
**Please describe the Improvement and/or Feature Request**
We are using Velero together with [restic](https://velero.io/docs/v1.9/restic/) on AKS to backup our cluster and the persistent volumes.

Right know there is an issue during restore of Pods in OSM enabled namespaces and we raised an issue in the velero project at https://github.com/vmware-tanzu/velero/issues/5193 . 

During a velero restore there is an error because the osm-init  init container and envoy sidecar are restored from velero and then the MutatingAdmissionWebhook of OSM tries to create them as well. This results in an "duplicate container" error and the pod restore of Velero fails. 
This has the unfortunate side-effect that the volume(claims) bound to that pod are not restored by restic and we end up with new persistent volumes which are empty.

It would be great if OSM sees the existing sidecar and init container on a new pod and recreate or ignore them.

The same issue existed for Istio (https://github.com/vmware-tanzu/velero/issues/2997) and was fixed on their side by making injection idempotent https://github.com/istio/istio/issues/25931 

At the moment we have a workaround with a custom velero plugin which removes the init container, sidecar and envoy-configuration-volume during restore: https://github.com/patst/velero-plugin-osm-prune

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [x ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Successful restores using Velero and Restic.

**Comment by shashankram** [comment]
Seems like a reasonable ask. My only concern is around false positives that may arise from checking attributes such as container and image names, and other attributes that are entirely under the user's control when deploying an app. A malicious user could make their app and/or init-container look similar to the proxy and proxy-init container thereby bypassing sidecar injection if the checks introduced are superficial. 

Instead of "trusting" the user's pod spec, we could try to swap the existing envoy and osm-init container spec if present with the spec the sidecar injection would generate anyway. This would alleviate the issue highlighted above where a malicious user attempts to bypass the sidecar injection process.

@patst, let me know your thoughts.

**Comment by patst** [comment]
@shashankram thanks for your thoughts.

I agree, swapping an existing envoy and osm-init container spec (and only them!) sounds like the best option and would help us. I think that is the option Istio is going for as well (see https://github.com/istio/istio/blob/324b3e098fd75e051a2cc8a82fe86b594aa48909/pkg/kube/inject/webhook.go#L508-L513 )
This should not be a breaking change and pretty straightforward to build.

**Comment by steeling** [comment]
@patst what version of OSM are you running? https://github.com/openservicemesh/osm/pull/4688 should have fixed the issue, which didn't get released till v1.2.

RE: security issue, if a malicious user has the ability to create/mutate pods already then we're I'd say the cluster is already compromised. I'm of the opinion this is not a problem for OSM to solve.

**Comment by shashankram** [comment]
> RE: security issue, if a malicious user has the ability to create/mutate pods already then we're I'd say the cluster is already compromised. I'm of the opinion this is not a problem for OSM to solve.

I disagree. Such a scenario is especially common with `Insider Threats`. Just because a user has permission to create an application, doesn't mean they should be allowed to somehow bypass the sidecar injection process because of a loophole in the product. Bypassing sidecar injection is an explicit action, either via labeling the namespace or by annotating the pod to disable sidecar injection. Attempting to bypass sidecar injection by naming their containers similar to the injected containers is a good indicator of potential malicious intent.

**Comment by shashankram** [comment]
> what's stopping them from turning up another container though? or another init container that further modifies IP tables after ours?
> 
> IMO there's too many attack vectors and if a user has access to do that it's already game over

If they do, they have enough permissions via `NET_ADMIN` to do so. This isn't the same as simply naming an application container to trick the software to do something undesirable.

**Comment by steeling** [comment]
Fair point on permission, however I still disagree. If they can mutate containers it is still game over.

This would be better solved with Gatekeeper or notary to ensure images are signed/attested

**Comment by shashankram** [comment]
> Fair point on permission, however I still disagree. If they can mutate containers it is still game over.
> 
> This would be better solved with Gatekeeper or notary to ensure images are signed/attested

It's always desirable to reduce the attack surface, especially when it's trivial to do so as in this scenario. I don't think it comes at any extra cost to detect that a user is attempting to have an init and proxy container that may conflict with and/or potentially bypass our software. In fact, I'd argue it's desirable to have this check in place regardless of security implications.

**Comment by patst** [comment]
> @patst what version of OSM are you running? #4688 should have fixed the issue, which didn't get released till v1.2.
> 
> RE: security issue, if a malicious user has the ability to create/mutate pods already then we're I'd say the cluster is already compromised. I'm of the opinion this is not a problem for OSM to solve.

thanks for your reply. We are using OSM as AKS addon. Today we started upgrading to AKS 1.24.3 which contains OSM v1.2. The above behaviour was observed using OSM v1.1.1. 

I will test tomorrow if v1.2 works with velero and restic
