### ISSUE TITLE
Missing name in tracing

### ISSUE THREAD

**Issue by piotrgwiazda** [openservicemesh/osm#5048]
**Bug description**:

In https://github.com/openservicemesh/osm/blob/main/pkg/injector/envoy_container.go#L43 the `--service-cluster` parameter is set based on ServiceAccount and pod.Namespace.

As a result for a simple deployment all services in a mesh are identified as "default.".
- The name component could be based on some other parameter, e.g. deployment name
- The namespace component of name is always missing, even in example tracing documentation https://release-v0-11.docs.openservicemesh.io/docs/guides/observability/tracing/

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

- Services are easily distinguishable in Jeager tracing by providing proper argument to `--service-cluster` parameter into Envoy.
- There is a documentation describing how to modify the naming pattern

**Steps to reproduce the bug (as precisely as possible)**:

Install OSM

**How was OSM installed?**:

As AKS add-on

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by keithmattix** [comment]
Thanks for raising these issues @piotrgwiazda! @whitneygriffith I'm assigning this to you to make sure our tracing works as expected. Feel free to use this issue to gather any more context you need

**Comment by whitneygriffith** [comment]
@piotrgwiazda we were able to fix the missing name in tracing and have updated the docs which will be available in our next release which will be out in <2 weeks! If you need this fix before then feel free to build the latest [OSM](https://github.com/openservicemesh/osm)
