### ISSUE TITLE
Update envoy to v1.23.1 and test sidecar injection on ARM64

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#5053]
**Please describe the Improvement and/or Feature Request**

When envoy-distroless v1.23.1 is available both for AMD and ARM, and contour starts supporting envoy v1.23.1, we will need to update to v1.23.1. In addition to the usual testing of running the contour demo, we will also need to test sidecar injection on ARM64, with envoy-distroless v1.23.1, as this will be the first envoy-distroless images compatible for multi-arch (the v1.23.0 envoy-distroless image had a bug). 

This is a subtask of: https://github.com/openservicemesh/osm/issues/4716. The PR for v1.23.0 is out but will need to be updated to v1.23.1 when it becomes available: https://github.com/openservicemesh/osm/pull/4954. 

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by keithmattix** [comment]
Fixed by #4954
