### ISSUE TITLE
Leverage Builder Pattern for IngressTrafficPolicy

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#5061]
**Please describe the Improvement and/or Feature Request**

Subtask of https://github.com/openservicemesh/osm/issues/4925

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [X]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by steeling** [comment]
Subsumed by https://github.com/openservicemesh/osm/issues/5098
