### ISSUE TITLE
Not able to upgrade OSM control plane

### ISSUE THREAD

**Issue by vishalpant** [openservicemesh/osm#5067]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: The osm mesh upgrade command should run successfully

**Steps to reproduce the bug (as precisely as possible)**: Launch AKS with Kubernetes version 1.22.11

**How was OSM installed?**: Using the command, az aks enable-addons --resource-group myResourceGroup --name myAKSCluster --addons open-service-mesh

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.0.0
- Kubernetes version (use `kubectl version`): 1.22.11
- Size of cluster (number of worker nodes in the cluster): 5
- Others:

**Comment by shashankram** [comment]
Hey @vishalpant, it seems like you are experiencing an issue with the OSM AKS addon. The OSM AKS addon is managed by Microsoft. Could you kindly open a support ticket against Microsoft if the issue you are experiencing pertains to the usage the OSM AKS addon in Azure.

Further, it seems like you are attempting to manually upgrade the service mesh that was installed as an AKS addon using the `osm mesh upgrade` CLI. From my experience using the AKS addon, this will not work. While using the AKS addon, upgrades will be managed by AKS itself, and using the CLI to upgrade is not permitted. The CLI can only be used to upgrade when the install was done using CLI or Helm.
