### ISSUE TITLE
Use an intermediate certificate to sign all service-to-service mTLS certs

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#507]
Currently OSM uses the root cert to sign all leaf certs (for service to service mTLS). We need to create an intermediate cert and sign with it instead of using the root cert.

**Comment by allenlsy** [comment]
@snehachhabria  Can I understand this as, we have root cert for a single cluster now. To support multicluster, we need a new root cert for existing root cert, which means existing root cert becomes the intermediate cert?
