### ISSUE TITLE
Add vulnerability checking to the CI pipelines

### ISSUE THREAD

**Issue by trstringer** [openservicemesh/osm#5079]
**Please describe the Improvement and/or Feature Request**

Our CI pipeline should be actively checking for Go vulnerabilities with the newly announced [govulncheck](https://go.dev/blog/vuln) tooling to catch issues as soon as possible.

**Scope (please mark with X where applicable)**
- CI System                  [X]

**Possible use cases**

CI vulnerability checking.

**Comment by lam-man** [comment]
@trstringer I think this is still not taken. Would you mind assigning it to me?

**Comment by keithmattix** [comment]
Thanks for your willingness to tackle this! You're now assigned to the issue 👍🏾

**Comment by lam-man** [comment]
Thanks @keithmattix !

**Comment by lam-man** [comment]
Progress update: Figured out how to run the Go vulnerability check in GitHub Action. However, the CI job I created always got killed by GitHub Actions when running the command `govulncheck ./...`. I am trying to resolve this. Thanks!

**Comment by lam-man** [comment]
- Result update: **I think this issue is blocked due the memory limitation of our CI environment (VM for Github Actions).**
    - Result of `free -m` for VM:
    ```
                  total        used        free      shared  buff/cache   available
    Mem:           6943         623         936          12        5384        6009
    Swap:          4095           0        4095
    ```
- Suggestion: Increase the memory limit for Github Action VMs.
- Details:
    - The first thought I had is that `govulncheck` will check modules parallelly and consume more memory than expected. I then ran the command `govulncheck` module by module. However, I found the memory limitation still cause the issue. For some module, the command allocated more than **12 GB** memory. The total available in the CI environment is about 11 GB (~7GB RAM + ~4GB SWAP). That is why the CI job always got killed with out of memory error.

@keithmattix  @trstringer
