### ISSUE TITLE
Sidecar injection fails, trying to access osm-injector in wrong namespace 

### ISSUE THREAD

**Issue by jaohurtas** [openservicemesh/osm#5084]
**Bug description**:

OSM error trying to access osm-injector in kube-system namespace when it is in th osm-system namespace 

Error in application replicaset:
failed to call webhook: Post "https://osm-injector.kube-system.svc:9090/mutate-pod-creation?timeout=20s:
service "osm-injector" not found"

The sidecar is not injected

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [x ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
No error in the application replicaset.  Sidecar is injected to the application pods.

**Steps to reproduce the bug (as precisely as possible)**:

Add monitored namespace with OSM CLI  osm namespace add <namespace>
Deploy application to <namespace>
View replicaset logs showing it trying to access the  osm-injector in the kube-system namespace.  Pods are not created.

**How was OSM installed?**:
OSM CLI V 1.2
**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
1.2.0
- Kubernetes version (use `kubectl version`):
 Minor:"24", GitVersion:"v1.24.3",
- Size of cluster (number of worker nodes in the cluster):
2

**Comment by keithmattix** [comment]
Thanks for filing this issue! Can you please post the OSM CLI command you used to install the mesh? Note that if you don't specify a `osmNamespace` when installing OSM, it will default to the namespace the helm release is installed in (which in turn defaults to your kube context namespace if unset)

**Comment by jaohurtas** [comment]
I believe I just used  "osm install" and it created the osm-system namespace
