### ISSUE TITLE
Implement a k8s.Controller that does not use informers

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#5099]
This client should adhere to the k8s KubeController interface, but should implement methods on the k8s apiserver instead of on the informer client.

This can be used in places where we don't want to enable the informer cache, but do still want the abstractions provided by the meshcatalog and compute Interface

This can be done be either: 

a) creating a new object with identical method signatures
b) adding an option `NoInformer()` to the k8s.Client such that it queries the informer cache or the k8s master conditionally

**Comment by steeling** [comment]
@keithmattix  FYI
@shashankram FYI this would be a pre-req to [#4970](https://github.com/openservicemesh/osm/issues/4970)

**Comment by shashankram** [comment]
We will still be using a SharedIndexInformer within the controller though right, or are you proposing to not use informers anymore?

**Comment by steeling** [comment]
correct, i think just the CLI, and I believe @keithmattix has a use case for certificates where there is a concern of a potential race condition due to cache being out of sync?

This is more to allow more pieces of the code to access the underlying k8s infra through the mesh catalog or compute.Interface

**Comment by shashankram** [comment]
> correct, i think just the CLI, and I believe @keithmattix has a use case for certificates where there is a concern of a potential race condition due to cache being out of sync?
> 
> This is more to allow more pieces of the code to access the underlying k8s infra through the mesh catalog or compute.Interface

Ok if that helps avoiding duplication and simplifies CLI, sounds reasonable
