### ISSUE TITLE
 osm controller forwarding of the envoy config is no longer working on debug endpoint

### ISSUE THREAD

**Issue by jsturtevant** [openservicemesh/osm#5102]
**Bug description**:
The osm controller forwarding of the envoy config is no longer working:

http://localhost:9092/debug/proxy?stream-id=5&cfg=true

```
Proxy for Stream ID 5 not found, may have been disconnected
```

Certs works:
http://localhost:9092/debug/proxy?stream-id=5

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [x]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): main branch
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by steeling** [comment]
Do you have steps to repro?

**Comment by jaellio** [comment]
I ran the demo script with the debug server enabled, port forwarded the debug server, and then navigated to debug/proxy. 

I think I found the small bug though!
