### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by srinman** [openservicemesh/osm#5107]
Please check this documentation 
https://release-v0-11.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/

This following command in the documentation fails because httpbin.yaml is not found in this location.  Please repoint this to working location. Thanks. 
kubectl apply -f https://raw.githubusercontent.com/openservicemesh/osm/main/docs/example/manifests/samples/httpbin/httpbin.yaml -n httpbin

**Comment by keithmattix** [comment]
Hi @srinman - please take a look at the latest version of our documentation:
https://release-v1-2.docs.openservicemesh.io/docs/demos/ingress_k8s_nginx/

The download link should be correct in the latest version the docs

**Comment by shalier** [comment]
@srinman Closing this issue. Feel free to re-open this issue if the link doesn't work!
