### ISSUE TITLE
K8s headless services targeting the same endpoints (pod + port) break the Mesh

### ISSUE THREAD

**Issue by lorenzo-biava** [openservicemesh/osm#5108]
**Bug description**:

When multiple K8s services target the same endpoints (pod + port), or a single service targets the same port twice (with different names), the Envoy configuration is invalid and part of it are discarded, breaking the Mesh connectivity (e.g. outbound listener).

Sometimes such configuration can be a mistake, sometimes it's perfectly reasonable (e.g. if you need a Service just for discovery, which is what Prometheus Operator and kube-prometheus-stack do, having 2 separate Services for different purposes).
If any of the enabled namespaces contain such configuration, the entire Mesh can break (e.g. outbound connectivity is lost), also resulting in breaking the multitenant model that K8s allows with namespaces.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [x]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [x]
- Egress                     [x]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

If the configuration is invalid, only the invalid parts of it should be discarded (e.g. keep the first endpoint, and not all of them).
Although not ideal, it prevents the Mesh from entering an invalid state.
Potentially, the duplicate endpoints could even be reconciled and used together.
Additionally, an annotation could be provided to allow OSM to ignore certain Services.

**Steps to reproduce the bug (as precisely as possible)**:

A) Create 2 services with different names but targeting the same pods and ports
or B) Create 1 service with two ports, with different names, but same number.

**How was OSM installed?**:

aks add-on v1.1.1

**Anything else we need to know?**:

```
      "last_update_attempt": "2022-09-09T12:46:10.236Z",
      "details": "error adding listener '0.0.0.0:15001': filter chain 'outbound-mesh-http-filter-chain:monitoring/prometheus-operator-thanos-discovery_10901_http' has the same matching rules defined as 'outbound-mesh-http-filter-chain:monitoring/prometheus-operated_10901_http'"
     }
```

<details><summary>Problematic section of resulting conf: </summary>

```
{
         "filter_chain_match": {
          "prefix_ranges": [
           {
            "address_prefix": "10.37.64.153",
            "prefix_len": 32
           },
           {
            "address_prefix": "10.37.64.180",
            "prefix_len": 32
           }
          ],
          "destination_port": 10901
         },
         "filters": [
          {
           "name": "envoy.filters.network.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
            "stat_prefix": "mesh-http-conn-manager.rds-outbound.10901",
            "rds": {
             "config_source": {
              "ads": {},
              "resource_api_version": "V3"
             },
             "route_config_name": "rds-outbound.10901"
            },
            "http_filters": [
             {
              "name": "envoy.filters.http.rbac"
             },
             {
              "name": "envoy.filters.http.lua",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua",
               "inline_code": "--\nfunction envoy_on_request(request_handle)\n  request_handle:headers():add(\"osm-stats-pod\", \"kafka-rest-prod-66f65b75dc-dcdcn\")\n  request_handle:headers():add(\"osm-stats-namespace\", \"fabric-prod\")\n  request_handle:headers():add(\"osm-stats-kind\", \"Deployment\")\n  request_handle:headers():add(\"osm-stats-name\", \"kafka-rest-prod\")\nend"
              }
             },
             {
              "name": "envoy.filters.http.wasm",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
               "config": {
                "name": "stats",
                "vm_config": {
                 "runtime": "envoy.wasm.runtime.v8",
                 "code": {
                  "local": {
                    [...]
                  }
                 },
                 "allow_precompiled": true
                }
               }
              }
             },
             {
              "name": "envoy.filters.http.router"
             }
            ],
            "access_log": [
             {
              "name": "envoy.access_loggers.stream",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog",
               "log_format": {
                "json_format": {
                 "requested_server_name": "%REQUESTED_SERVER_NAME%",
                 "start_time": "%START_TIME%",
                 "method": "%REQ(:METHOD)%",
                 "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                 "request_id": "%REQ(X-REQUEST-ID)%",
                 "duration": "%DURATION%",
                 "user_agent": "%REQ(USER-AGENT)%",
                 "authority": "%REQ(:AUTHORITY)%",
                 "time_to_first_byte": "%RESPONSE_DURATION%",
                 "upstream_cluster": "%UPSTREAM_CLUSTER%",
                 "response_flags": "%RESPONSE_FLAGS%",
                 "bytes_sent": "%BYTES_SENT%",
                 "protocol": "%PROTOCOL%",
                 "response_code": "%RESPONSE_CODE%",
                 "bytes_received": "%BYTES_RECEIVED%",
                 "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                 "response_code_details": "%RESPONSE_CODE_DETAILS%",
                 "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                 "upstream_host": "%UPSTREAM_HOST%"
                }
               }
              }
             }
            ],
            "local_reply_config": {
             "mappers": [
              {
               "filter": {
                "not_health_check_filter": {}
               },
               "headers_to_add": [
                {
                 "header": {
                  "key": "osm-stats-pod",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-namespace",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-kind",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-name",
                  "value": "unknown"
                 }
                }
               ]
              }
             ]
            }
           }
          }
         ],
         "name": "outbound-mesh-http-filter-chain:monitoring/prometheus-operated_10901_http"
        },


{
         "filter_chain_match": {
          "prefix_ranges": [
           {
            "address_prefix": "10.37.64.153",
            "prefix_len": 32
           },
           {
            "address_prefix": "10.37.64.180",
            "prefix_len": 32
           }
          ],
          "destination_port": 10901
         },
         "filters": [
          {
           "name": "envoy.filters.network.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
            "stat_prefix": "mesh-http-conn-manager.rds-outbound.10901",
            "rds": {
             "config_source": {
              "ads": {},
              "resource_api_version": "V3"
             },
             "route_config_name": "rds-outbound.10901"
            },
            "http_filters": [
             {
              "name": "envoy.filters.http.rbac"
             },
             {
              "name": "envoy.filters.http.lua",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua",
               "inline_code": "--\nfunction envoy_on_request(request_handle)\n  request_handle:headers():add(\"osm-stats-pod\", \"kafka-rest-prod-66f65b75dc-dcdcn\")\n  request_handle:headers():add(\"osm-stats-namespace\", \"fabric-prod\")\n  request_handle:headers():add(\"osm-stats-kind\", \"Deployment\")\n  request_handle:headers():add(\"osm-stats-name\", \"kafka-rest-prod\")\nend"
              }
             },
             {
              "name": "envoy.filters.http.wasm",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
               "config": {
                "name": "stats",
                "vm_config": {
                 "runtime": "envoy.wasm.runtime.v8",
                 "code": {
                  "local": {
                  [...]
                  }
                 },
                 "allow_precompiled": true
                }
               }
              }
             },
             {
              "name": "envoy.filters.http.router"
             }
            ],
            "access_log": [
             {
              "name": "envoy.access_loggers.stream",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog",
               "log_format": {
                "json_format": {
                 "time_to_first_byte": "%RESPONSE_DURATION%",
                 "upstream_cluster": "%UPSTREAM_CLUSTER%",
                 "response_flags": "%RESPONSE_FLAGS%",
                 "bytes_sent": "%BYTES_SENT%",
                 "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                 "user_agent": "%REQ(USER-AGENT)%",
                 "start_time": "%START_TIME%",
                 "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                 "request_id": "%REQ(X-REQUEST-ID)%",
                 "requested_server_name": "%REQUESTED_SERVER_NAME%",
                 "upstream_host": "%UPSTREAM_HOST%",
                 "method": "%REQ(:METHOD)%",
                 "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                 "protocol": "%PROTOCOL%",
                 "response_code": "%RESPONSE_CODE%",
                 "duration": "%DURATION%",
                 "authority": "%REQ(:AUTHORITY)%",
                 "response_code_details": "%RESPONSE_CODE_DETAILS%",
                 "bytes_received": "%BYTES_RECEIVED%"
                }
               }
              }
             }
            ],
            "local_reply_config": {
             "mappers": [
              {
               "filter": {
                "not_health_check_filter": {}
               },
               "headers_to_add": [
                {
                 "header": {
                  "key": "osm-stats-pod",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-namespace",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-kind",
                  "value": "unknown"
                 }
                },
                {
                 "header": {
                  "key": "osm-stats-name",
                  "value": "unknown"
                 }
                }
               ]
              }
             ]
            }
           }
          }
         ],
         "name": "outbound-mesh-http-filter-chain:monitoring/prometheus-operator-thanos-discovery_10901_http"
        },
```
</details>

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@lorenzo-biava I am unable to reproduce this issue by creating 2 different services targeting the same pod.

I deployed the simple [curl to httpbin demo](https://release-v1-2.docs.openservicemesh.io/docs/demos/permissive_traffic_mode/), and then created a second service called `httpbin2` whose selector matches the httpbin pod. I was able to access the backend pod via both `httpbin` and `httpbin2` service FQDNs.

```
$ kc get svc -n httpbin
NAME       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
httpbin    ClusterIP   10.96.207.17   <none>        14001/TCP   5d20h
httpbin2   ClusterIP   10.96.231.90   <none>        14001/TCP   47s

$ kc get ep -n httpbin
NAME       ENDPOINTS          AGE
httpbin    10.244.1.3:14001   5d20h
httpbin2   10.244.1.3:14001   52s

$ kubectl exec -n curl -ti "$(kubectl get pod -n curl -l app=curl -o jsonpath='{.items[0].metadata.name}')" -c curl -- curl -I http://httpbin.httpbin:14001
HTTP/1.1 200 OK
server: envoy
date: Mon, 12 Sep 2022 16:34:00 GMT
content-type: text/html; charset=utf-8
content-length: 9593
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 15

$ kubectl exec -n curl -ti "$(kubectl get pod -n curl -l app=curl -o jsonpath='{.items[0].metadata.name}')" -c curl -- curl -I http://httpbin2.httpbin:14001
HTTP/1.1 200 OK
server: envoy
date: Mon, 12 Sep 2022 16:34:05 GMT
content-type: text/html; charset=utf-8
content-length: 9593
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 4
```

Could you provide a reliable reproduction of the reported issue with the [curl + httpbin demo](https://release-v1-2.docs.openservicemesh.io/docs/demos/permissive_traffic_mode/)?

Thanks

**Comment by lorenzo-biava** [comment]
The key appears to be Headless services for this bug (clusterIP: None)

```
{"level":"error","component":"envoy/ads","proxy":"[Serial=75559413265722028154617586200091602541], [Pod metadata=UID=d0af2793-230d-4b20-9369-8ef40b4e5f45, Namespace=fabric-prod, Name=ccss-synthetic-test-prod-job-27717380-4s4xm, ServiceAccount=default]","time":"2022-09-13T09:08:53Z","file":"stream.go:216","message":"[NACK] err: \"code:13 message:\"Error adding/updating listener(s) outbound-listener: error adding listener '0.0.0.0:15001': filter chain 'outbound-mesh-http-filter-chain:httpbin/httpbin_14001_http' has the same matching rules defined as 'outbound-mesh-http-filter-chain:httpbin/httpbin2_14001_http'\\n\"\" for nonce 1663060133725973104, last version applied on request 25"}
```

```
apiVersion: v1
kind: Namespace
metadata:  
  name: httpbin
  labels:
    openservicemesh.io/monitored-by: osm
#  annotations:
#    openservicemesh.io/sidecar-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - image: mcr.microsoft.com/oss/tutum/curl
        imagePullPolicy: IfNotPresent
        name: curl
        command: ["sleep", "365d"]
        ports:
        - name: http
          containerPort: 14001

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
spec:
  clusterIP: None
  ports:
  - name: http
    port: 14001
    targetPort: http
  selector:
    app: curl

---
apiVersion: v1
kind: Service
metadata:
  name: httpbin2
  namespace: httpbin
spec:
  clusterIP: None
  ports:
  - name: http
    port: 14001
    targetPort: http
  selector:
    app: curl
```

**Comment by shashankram** [comment]
> The key appears to be Headless services for this bug (clusterIP: None)

@keithmattix could you look into this

**Comment by keithmattix** [comment]
Hi @lorenzo-biava. I did some digging and it turns out that having multiple headless services targeting the same pod isn't supported by OSM due to some Envoy limitations. The reason for this is because at the L4 level where Envoy is doing filter chain matches, there's no `Host` header or other L7 context we can use in order to determine which service to send traffic to. Does that make sense? I'd be happy to clarify further

**Comment by lorenzo-biava** [comment]
@keithmattix Thanks for the explanation. It does, yet OSM should do something to make that configuration working, even if it's just dropping one of the duplicated services.
The 2 services don't even have to be onboarded to the mesh (i.e. with Envoy); it's enough to have the discovery enabled in that namespace (the monitored-by=osm label) to disrupt the entire mesh.
This is a reliability and security risk that we cannot really take; and the same time we would like to support the use case of having the Prometheus-Operator running alongside the mesh (maybe even inside in the future). This issue just won't allow it.

**Comment by keithmattix** [comment]
Ah, understood, and I agree. I'll put together a PR and some docs to pick a service at random

**Comment by lorenzo-biava** [comment]
What about adding an annotation or label to the Services to have them
ignored?

You can still pick at random (well maybe the first alphabetically?) to
avoid breaking the config, but you leave a bit of control over which
service will be used (they might have overlapping endpoints, not
necessarily identical ones, so they won't be just interchangeable).

Alternatively, you could just merge all the endpoints of all such services
(I guess that would make it more complex to implement, and probably an
issue in terms of policies that select a specific service as the target).

Il gio 15 set 2022, 00:56 Keith Mattix II ***@***.***> ha
scritto:

**Comment by djsly** [comment]
@keithmattix , more on this, we also discovered that for the same use case, this error was breaking other services in different namespaces. Their outbound listeners weren't getting created, I presume by the error mentioned in this ticket. It seems that once OSM stops processing other output listeners on error.

**Comment by keithmattix** [comment]
Hmm, that shouldn't happen; the outbound listener loop [doesn't return on error](https://github.com/openservicemesh/osm/blob/76db0c6d81c67b1434bd248f0463ca43870862cb/pkg/envoy/lds/inmesh.go#L466). Furthermore, each sidecar's config request is processed separately. If you remove the duplicate headless services, do the services in the other namespace start working again?

**Comment by lorenzo-biava** [comment]
The issue has always been across namespaces, based on the policies used.
The outbound listener config is created by OSM controller. Is just Envoy
that doesn not like it.

Il gio 29 set 2022, 05:58 Keith Mattix II ***@***.***> ha
scritto:

**Comment by shashankram** [comment]
@keithmattix assigning this one to you as you already have a [PR](https://github.com/openservicemesh/osm/pull/5164) out.

**Comment by keithmattix** [comment]
So, I'm doing some local testing for this, and I can't reproduce the bug in the `main` branch of OSM. It appears that switching our adoption of the Envoy snapshot cache introduced some dedup logic for this use-case. I'm doing some digging to find a line of code to confirm, but I'm ~80% sure this shouldn't happen in v1.3+ of OSM

**Comment by djsly** [comment]
We will be upgrading to AKS 1.24 which brings 1.2   I’m guessing it will take so w time for us to be able to test. On Oct 11, 2022, at 7:31 PM, Keith Mattix II ***@***.***> wrote:﻿
So, I'm doing some local testing for this, and I can't reproduce the bug in the main branch of OSM. It appears that switching our adoption of the Envoy snapshot cache introduced some dedup logic for this use-case. I'm doing some digging to find a line of code to confirm, but I'm ~80% sure this shouldn't happen in v1.3+ of OSM

**Comment by keithmattix** [comment]
OSM supports N-2 versions, so now that I've confirmed that this is fixed in HEAD, I'll look into a backport/patch for OSM v1.2

**Comment by keithmattix** [comment]
Ok so I've got a full understanding of this bug, and the good news is that it's confined to OSM versions before v1.2. The first thing that completely left my mind until recently is that OSM didn't fully support headless services in the mesh _until_ v1.2, so that explains the problems that you're seeing in v1.1.1. Once you upgrade to v1.2, you shouldn't really run into this issue.

Now, the reason this problem won't occur in v1.2+ of OSM is because our support for headless services relies on the `hostname` field in the `Endpoints` resource created by the headless service. As it turns out, that `hostname` field is only populated when [the headless service name matches the `subdomain`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields) on the pod (as is often the case when the pod is managed by a StatefulSet), so it's impossible for there to be duplication of the filter chain match. This means that there's likely some functionality missing from our current headless service features, so please let us know your experience when using OSM v1.2. For now, I'll close this issue since headless services weren't supported before OSM v1.2. Hope this clears things up!
