### ISSUE TITLE
Policy: Document supported release tooling

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#5119]
NOTE: There needs to be further discussion and agreement on this before we decide.

Narrowing down our supported release tooling will greatly simplify our release processes. ie: by removing helm from our official support of release tooling, we can focus on tooling that is specific to OSM. This can allow us to place more guardrails and safety checks in the OSM cli.

We can still allow power users to leverage helm, but our official support (and the happy path), is through the OSM CLI.

**Comment by keithmattix** [comment]
This feels like we need to create a Discussion on GitHub or a thread in Slack
