### ISSUE TITLE
Remove the mock mesh catalog, and the meshcatalogger interface

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#5156]
With the new split of MeshCatalog, compute.Interface, and k8s.Client, there is no need to have an interface for the MeshCatalog. The MeshCatalog strictly contains business logic, with no actual API calls being made within the catalog itself.

As such there's no need to have an interface for it. The biggest hurdle will be to migrate all of the `NewMockMeshCataloger` calls to instead mock the `compute.Interface` via `compute.NewMockInterface`.

Finally, interfaces should be defined where they are consumed, not where their implementations are defined. So let's move the compute.Interface (and it's mock) to the catalog package.

This should probably be in 3-4 PR's, e.g:

1. Migrate NewMockMeshCataloger to NewMockInterface
2. Remove the MeshCatalogger interface
3. Move the compute.Interface and NewMockInterface to the catalog package

**Comment by jaellio** [comment]
Updating to size/M to reflect the amount of work required to create all 3/4 PRs.

**Comment by SanyaKochhar** [comment]
1. Migrate NewMockMeshCataloger to NewMockInterface - addressed in #5233 
2. Remove the MeshCatalogger interface - addressed in #5244
3. Move the compute.Interface and NewMockInterface to the catalog package - addressed in #5244
