### ISSUE TITLE
Remove pkg/certificate dependencies on k8s

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm#5159]
Replace usage of pkg/certificate/castorage/k8s with the new compute client's secret methods. Probably best to get rid of the packages under pkg/certificate/castorage altogether, and move any required methods into pkg/certificate/providers.

**Comment by shalier** [comment]
Blocked on https://github.com/openservicemesh/osm/issues/5099, when switching to using the compute client `getHashiVaultOSMToken` fails because computeClient.GetSecret uses the informer and returns not found since the secret doesn't have the label that the informer filters on.
