### ISSUE TITLE
Move each componentStatus to ValidatingRollout

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#5181]
[updateMRCComponentStatus](https://github.com/openservicemesh/osm/blob/main/pkg/certificate/mrc_reconciler.go#L131), should see that the MRC in question has the following attributes:

```spec.intent == Passive && status.Conditions[type=Accepted].Status == True && status.Conditions[type=ValidatingRollout] => { x.Status == False && x.Reason == Pending }```

And then move the componentStatuses to Validating based on ownedUseCases.

**Comment by jsturtevant** [comment]
not currently needed, will revisit componentStatuses at later point
