### ISSUE TITLE
Create MVP for manual root certificate rotation

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#5198]
**Please describe the Improvement and/or Feature Request**

Create a process by which OSM users can manually rotate the root certificate without any downtime. This issue only focuses on creating an MVP and not covering all possible edge cases.

For more details, please review the [Simplified Proposal for Manual Root Cert Rotation MVP](https://docs.google.com/document/d/1bh3Yfn5DXWjmzdKa4XHlk-9KepUNb_EgDDrzd1G_deY/edit#heading=h.86n6n6h1rqmo)
**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Allow users to rotate root certificates without down time. This can be done using the MRC Intent field and a level triggered approach.

**Comment by jsturtevant** [comment]
closing in favor of #4998
