### ISSUE TITLE
upstream_reset_before_response_started{connection_failure,TLS_error:_268435612:SSL_routines:OPENSSL_internal:HTTP_REQUEST}

### ISSUE THREAD

**Issue by Shiva2199** [openservicemesh/osm#5203]
**Bug description**:
We have installed OSM on Azure, we are facing issue with one of our service where serviceB is not able to call serviceA where both services are inside mesh. I have created httproutegroup and traffictarget but still we see below errors in envoy and osm-controller. 

ENVOY:
{"start_time":"2022-10-14T04:54:00.738Z","upstream_service_time":null,"protocol":"HTTP/1.1","request_id":"bd8697cc-3beb-4f84-bc6b-24bc70f84792","upstream_host":"192.168.5.3:8080","response_code_details":"upstream_reset_before_response_started{connection_failure,TLS_error:_268435612:SSL_routines:OPENSSL_internal:HTTP_REQUEST}","bytes_sent":182,"response_flags":"UF","bytes_received":369,"requested_server_name":null,"user_agent":"Java/11.0.14","response_code":503,"x_forwarded_for":null,"method":"POST","path":"/services/v1.0/users","upstream_cluster":"dop/a3s-service|8080","time_to_first_byte":null,"duration":1,"authority":"a3s-service.dop.svc.cluster.local:8080"}

OSM-CONTROLLER:
{"level":"error","component":"envoy/ads","proxy":"[Serial=67145863734779147314448535556576093277], [Pod metadata=UID=0b68b6f6-6631-4ae5-a18f-7beec4f49c77, Namespace=dop, Name=a3s-c7f9866f4-xgkq6, ServiceAccount=fndsec-a3s]","time":"2022-10-14T04:55:27Z","file":"stream.go:216","message":"[NACK] err: \"code:13 message:\"Error adding/updating listener(s) inbound-listener: error adding listener '0.0.0.0:15003': filter chain 'inbound-mesh-http-filter-chain:dop/a3s-service:8080' has the same matching rules defined as 'inbound-mesh-http-filter-chain:dop/a3s-service:8080'\\n\"\" for nonce 1665723327749720492, last version applied on request "}

{"level":"error","component":"envoy/cds","error_code":"E5021","time":"2022-10-14T04:55:27Z","file":"response.go:102","message":"Found duplicate clusters with name dop/a3s-service|8080|local; duplicate will not be sent to proxy."}

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [X ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
Successful communication between ServiceA and ServiceB

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version
OSM: v1.1.2
- Kubernetes version
-  kubernetes: 1.23
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by keithmattix** [comment]
Are the services in question headless services? OSM didn't support headless services at all until v1.2

**Comment by Shiva2199** [comment]
no they are not headless services

**Comment by keithmattix** [comment]
If you're running OSM on Azure via the addon, please open a support ticket so that we can best debug this issue. Thanks
