### ISSUE TITLE
Unit test TestGetInboundMeshTrafficPolicy flakes in CI

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#5229]
**Bug description**:
Unit test     
TestGetInboundMeshTrafficPolicy/multiple_services,_SMI_mode,_1_TrafficTarget,_1_HTTPRouteGroup,_1_TrafficSplit_and_multiple_trust_domains flakes in the CI.

```
    inbound_traffic_policies_test.go:2417: 
        	Error Trace:	inbound_traffic_policies_test.go:2417
        	Error:      	Condition never satisfied
        	Test:       	TestGetInboundMeshTrafficPolicy/multiple_services,_SMI_mode,_1_TrafficTarget,_1_HTTPRouteGroup,_1_TrafficSplit_and_multiple_trust_domains
```

Failed run: https://github.com/openservicemesh/osm/actions/runs/3299314699/jobs/5442591548

**Affected area (please mark with X where applicable)**:
- Tests                      [X]

**Comment by shashankram** [comment]
@nshankar13 assigning this one to you as this test started to flake after the recent refactoring.

**Comment by jsturtevant** [comment]
is there a link to where it failed?  This might be after I added this test.  @shalier reported it to me as well, but wasn't able to reproduce with `go test -run=TestGetInboundMeshTrafficPolicy -count 30` or `go test -run=TestGetInboundMeshTrafficPolicy -race`

**Comment by shashankram** [comment]
> is there a link to where it failed? This might be after I added this test. @shalier reported it to me as well, but wasn't able to reproduce with `go test -run=TestGetInboundMeshTrafficPolicy -count 30` or `go test -run=TestGetInboundMeshTrafficPolicy -race`

I reran the test in the CI so it overwrote the previous run. 
I thought I pasted the error but it seems like it didn't correctly get copied to my clipboard!

Could you share the change that you think might have caused this?

**Comment by jsturtevant** [comment]
this test was introduced in https://github.com/openservicemesh/osm/pull/5193

**Comment by shashankram** [comment]
@jsturtevant I was able to retrieve the logs. Seems like Github preserves the logs from older runs now. I updated the description with more info.

**Comment by shashankram** [comment]
> this test was introduced in #5193

Thanks, assigned it to you. Hopefully, the logs suffice.

**Comment by jsturtevant** [comment]
The way the certificates are rotated for this test is changing in #5201 which is close. Will revisit if we continue to see it after that merges.
