### ISSUE TITLE
Egress traffic fails due to duplicate filter chains resulting from headless service configuration with OSM version 1.2.1

### ISSUE THREAD

**Issue by adprakash4** [openservicemesh/osm#5231]
**Bug description**:
With OSM version 1.2.1, we are seeing that even though egress is enabled in the mesh config. Envoy is blocking all the outgoing traffic from the Pod.

Due to that we are not able to achieve the initial Readiness in some our pods.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [X]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: 

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**: OSM cli

**Anything else we need to know?**: Same issue was raised with IcM 342797926 

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 1.2.1
- Kubernetes version (use `kubectl version`): 1.23.5
- Size of cluster (number of worker nodes in the cluster): 1 Master + 1 worker
- Others: 
Below Commands are used to install and configure OSM
install osm using below command.
osm install --set="osm.enableEgress=true" --set="osm.certificateProvider.kind=tresor" --set="osm.enablePermissiveTrafficPolicy=true"

Add <product-namespace> Namespace to OSM

osm namespace add <product-namespace> --mesh-name osm --disable-sidecar-injection=true

kubectl patch meshconfig osm-mesh-config -n osm-system -p '{"spec":{"traffic":{"outboundPortExclusionList":[2379, 2380]}}}'  --type=merge

kubectl patch meshconfig osm-mesh-config -n osm-system -p '{"spec":{"traffic":{"outboundPortExclusionList":[2379, 2380]}}}'  --type=merge

kubectl patch deployment <pod-name> -n <product-namespace> -p '{"spec":{"template":{"metadata":{"annotations":{"openservicemesh.io/monitored-by": "osm", "openservicemesh.io/sidecar-injection": "enabled"}}}}}'

After investigating more with the OSM team, it turned out that the current OSM version has limited support of headless service with stateful sets. And because of duplicate route entry, envoy blocks the outgoing traffic.

```
"error adding listener '0.0.0.0:15001': filter chain '###############' has the same matching rules defined as '################'"

```
Because of this issue, we are not able to proceed further, and pods stay in n-1/n states.

**Comment by sagarbhatt2290** [comment]
The issue is still present with the latest version of osm 1.2.3. 

"details": "error adding listener '0.0.0.0:15001': filter chain 'outbound_core/core-pod-service-reg-server-0.core-pod-service-reg-server_8301_http' has the same matching rules defined as 'o      utbound_core/core-pod-service-reg-server-0.core-pod-service-reg-server_8301_http'"

Note : core-pod-service-reg-server-0 is a headless service withing the monitored namespace. 

This has been a blocker issue for integrating osm in our deployment.  
Any new workaround here ? or any update or ETA for supporting headless services fully?

**Comment by keithmattix** [comment]
Can you please attach a bug report? Including the envoy config and the osm-controller logs?
