### ISSUE TITLE
Support Headless Services for Deployments as well

### ISSUE THREAD

**Issue by lorenzo-biava** [openservicemesh/osm#5252]
**Please describe the Improvement and/or Feature Request**

Support for K8s Headless services has been introduced with https://github.com/openservicemesh/osm/issues/3477

However the same kind of support would be helpful for K8s Deployments as well.

To avoid overloading the generated Envoy config and increase resource consumption (most likely it needs to be a Listener per backend Pod?), the feature should be made opt-in per K8s Service, probably leveraging an annotation.

**Scope (please mark with X where applicable)**
- New Functionality          [x]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

There are some scenarios where an application requires custom routing of requests to downstream Pods, without relying on the load balancing offered by the Mesh (e.g. when using extra contextual information, and only leveraging the Mesh for mTLS and observability features).

**Comment by lorenzo-biava** [comment]
@keithmattix FYI

**Comment by lorenzo-biava** [comment]
Looks like it's been implemented by https://github.com/openservicemesh/osm/pull/5250

**Comment by steeling** [comment]
marking this closed by the above comment
