### ISSUE TITLE
Failed to update the 'useHttpsIngress' in osm-mesh-config

### ISSUE THREAD

**Issue by rcpandula** [openservicemesh/osm#5253]
**Bug description**:
I am trying to set the 'useHTTPSIngress:true' in osm-mesh-config by using the below kubectl command, but it is failling with below error: 
strict decoding error: unknown field "spec.traffic.useHTTPSIngress"
The complete error log: 
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# meshconfigs.config.openservicemesh.io "osm-mesh-config" was not valid:
# * patch: Invalid value: "{\"apiVersion\":\"config.openservicemesh.io/v1alpha2\",\"kind\":\"MeshConfig\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"kind\\\":\\\"MeshConfig\\\",\\\"apiVersion\\\":\\\"config.openservicemesh.io/configv1alpha2\\\",\\\"metadata\\\":{\\\"name\\\":\\\"osm-mesh-config\\\",\\\"creationTimestamp\\\":null},\\\"spec\\\":{\\\"sidecar\\\":{\\\"enablePrivilegedInitContainer\\\":false,\\\"logLevel\\\":\\\"error\\\",\\\"configResyncInterval\\\":\\\"0s\\\",\\\"resources\\\":{},\\\"localProxyMode\\\":\\\"Localhost\\\"},\\\"traffic\\\":{\\\"enableEgress\\\":true,\\\"outboundIPRangeExclusionList\\\":[],\\\"outboundIPRangeInclusionList\\\":[],\\\"outboundPortExclusionList\\\":[],\\\"inboundPortExclusionList\\\":[],\\\"enablePermissiveTrafficPolicyMode\\\":true,\\\"inboundExternalAuthorization\\\":{\\\"enable\\\":false,\\\"failureModeAllow\\\":false},\\\"networkInterfaceExclusionList\\\":[]},\\\"observability\\\":{\\\"osmLogLevel\\\":\\\"info\\\",\\\"enableDebugServer\\\":false,\\\"tracing\\\":{\\\"enable\\\":false}},\\\"certificate\\\":{\\\"serviceCertValidityDuration\\\":\\\"24h\\\",\\\"certKeyBitSize\\\":2048},\\\"featureFlags\\\":{\\\"enableWASMStats\\\":true,\\\"enableEgressPolicy\\\":true,\\\"enableSnapshotCacheMode\\\":false,\\\"enableAsyncProxyServiceMapping\\\":false,\\\"enableIngressBackendPolicy\\\":true,\\\"enableEnvoyActiveHealthChecks\\\":false,\\\"enableRetryPolicy\\\":false}}}\\n\"},\"creationTimestamp\":\"2022-11-18T11:49:58Z\",\"generation\":2,\"managedFields\":[{\"apiVersion\":\"config.openservicemesh.io/v1alpha2\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kubectl.kubernetes.io/last-applied-configuration\":{}}},\"f:spec\":{\".\":{},\"f:certificate\":{\".\":{},\"f:certKeyBitSize\":{},\"f:serviceCertValidityDuration\":{}},\"f:featureFlags\":{\".\":{},\"f:enableAsyncProxyServiceMapping\":{},\"f:enableEgressPolicy\":{},\"f:enableEnvoyActiveHealthChecks\":{},\"f:enableIngressBackendPolicy\":{},\"f:enableRetryPolicy\":{},\"f:enableSnapshotCacheMode\":{},\"f:enableWASMStats\":{}},\"f:observability\":{\".\":{},\"f:tracing\":{}},\"f:sidecar\":{\".\":{},\"f:configResyncInterval\":{},\"f:enablePrivilegedInitContainer\":{},\"f:localProxyMode\":{},\"f:resources\":{},\"f:tlsMaxProtocolVersion\":{},\"f:tlsMinProtocolVersion\":{}},\"f:traffic\":{\".\":{},\"f:enableEgress\":{},\"f:enablePermissiveTrafficPolicyMode\":{},\"f:inboundExternalAuthorization\":{\".\":{},\"f:enable\":{},\"f:failureModeAllow\":{},\"f:statPrefix\":{},\"f:timeout\":{}},\"f:inboundPortExclusionList\":{},\"f:networkInterfaceExclusionList\":{},\"f:outboundIPRangeExclusionList\":{},\"f:outboundIPRangeInclusionList\":{},\"f:outboundPortExclusionList\":{}}}},\"manager\":\"Go-http-client\",\"operation\":\"Update\",\"time\":\"2022-11-18T11:49:58Z\"},{\"apiVersion\":\"config.openservicemesh.io/v1alpha2\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:spec\":{\"f:observability\":{\"f:enableDebugServer\":{},\"f:osmLogLevel\":{},\"f:tracing\":{\"f:enable\":{}}},\"f:sidecar\":{\"f:logLevel\":{}}}},\"manager\":\"kubectl-edit\",\"operation\":\"Update\",\"time\":\"2022-11-18T11:53:17Z\"}],\"name\":\"osm-mesh-config\",\"namespace\":\"osm-system\",\"resourceVersion\":\"3566\",\"uid\":\"241fd07b-0abd-4c35-b4aa-88ee8318db3a\"},\"spec\":{\"certificate\":{\"certKeyBitSize\":2048,\"serviceCertValidityDuration\":\"24h\"},\"featureFlags\":{\"enableAsyncProxyServiceMapping\":false,\"enableEgressPolicy\":true,\"enableEnvoyActiveHealthChecks\":false,\"enableIngressBackendPolicy\":true,\"enableRetryPolicy\":false,\"enableSnapshotCacheMode\":false,\"enableWASMStats\":true},\"observability\":{\"enableDebugServer\":true,\"osmLogLevel\":\"trace\",\"tracing\":{\"enable\":true}},\"sidecar\":{\"configResyncInterval\":\"0s\",\"enablePrivilegedInitContainer\":false,\"localProxyMode\":\"Localhost\",\"logLevel\":\"trace\",\"resources\":{},\"tlsMaxProtocolVersion\":\"TLSv1_3\",\"tlsMinProtocolVersion\":\"TLSv1_2\"},\"traffic\":{\"enableEgress\":true,\"enablePermissiveTrafficPolicyMode\":true,\"inboundExternalAuthorization\":{\"enable\":false,\"failureModeAllow\":false,\"statPrefix\":\"inboundExtAuthz\",\"timeout\":\"1s\"},\"inboundPortExclusionList\":[],\"networkInterfaceExclusionList\":[],\"outboundIPRangeExclusionList\":[],\"outboundIPRangeInclusionList\":[],\"outboundPortExclusionList\":[],\"useHTTPSIngress\":false}}}": strict decoding error: unknown field "spec.traffic.useHTTPSIngress"
#
apiVersion: config.openservicemesh.io/v1alpha2
kind: MeshConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"MeshConfig","apiVersion":"config.openservicemesh.io/configv1alpha2","metadata":{"name":"osm-mesh-config","creationTimestamp":null},"spec":{"sidecar":{"enablePrivilegedInitContainer":false,"logLevel":"error","configResyncInterval":"0s","resources":{},"localProxyMode":"Localhost"},"traffic":{"enableEgress":true,"outboundIPRangeExclusionList":[],"outboundIPRangeInclusionList":[],"outboundPortExclusionList":[],"inboundPortExclusionList":[],"enablePermissiveTrafficPolicyMode":true,"inboundExternalAuthorization":{"enable":false,"failureModeAllow":false},"networkInterfaceExclusionList":[]},"observability":{"osmLogLevel":"info","enableDebugServer":false,"tracing":{"enable":false}},"certificate":{"serviceCertValidityDuration":"24h","certKeyBitSize":2048},"featureFlags":{"enableWASMStats":true,"enableEgressPolicy":true,"enableSnapshotCacheMode":false,"enableAsyncProxyServiceMapping":false,"enableIngressBackendPolicy":true,"enableEnvoyActiveHealthChecks":false,"enableRetryPolicy":false}}}
  creationTimestamp: "2022-11-18T11:49:58Z"
  generation: 2
  name: osm-mesh-config
  namespace: osm-system
  resourceVersion: "3566"
  uid: 241fd07b-0abd-4c35-b4aa-88ee8318db3a
spec:
  certificate:
    certKeyBitSize: 2048
    serviceCertValidityDuration: 24h
  featureFlags:
    enableAsyncProxyServiceMapping: false
    enableEgressPolicy: true
    enableEnvoyActiveHealthChecks: false
    enableIngressBackendPolicy: true
    enableRetryPolicy: false
    enableSnapshotCacheMode: false
    enableWASMStats: true
  observability:
    enableDebugServer: true
    osmLogLevel: trace
    tracing:
      enable: true
  sidecar:
    configResyncInterval: 0s
    enablePrivilegedInitContainer: false
    localProxyMode: Localhost
    logLevel: trace
    resources: {}
    tlsMaxProtocolVersion: TLSv1_3
    tlsMinProtocolVersion: TLSv1_2
  traffic:
    enableEgress: true
    enablePermissiveTrafficPolicyMode: true
    inboundExternalAuthorization:
      enable: false
      failureModeAllow: false
      statPrefix: inboundExtAuthz
      timeout: 1s
    inboundPortExclusionList: []
    networkInterfaceExclusionList: []
    outboundIPRangeExclusionList: []
    outboundIPRangeInclusionList: []
    outboundPortExclusionList: []
    useHTTPSIngress: false

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [x ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
There should not be any error while setting the useHTTPSIngress

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:
using osm cli v1.2.2.
**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v1.2.2.
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
`useHTTPSIngress` was deprecated many releases ago. Please refer to the [HTTPS ingress demo] on how to configure HTTPS with IngressBackend API.

Thanks
