### ISSUE TITLE
TrafficMetrics and custom metrics support in OSM. 

### ISSUE THREAD

**Issue by krishnadce** [openservicemesh/osm#5272]
In the OSM documentation, it's mentioned that OSM supports the smi-spec Traffic Metrics etc. However, the none of these metrics can be found in the prometheus side. Even TrafficMetrics CRD is also not installed with OSM.

I'm using the following OSM release.
```
MESH NAME   MESH NAMESPACE   VERSION   GIT COMMIT                                 BUILD DATE
osm         osm-system       v1.2.0    4c832d1e49c20006abc818f859365d0488c77890   2022-07-20-20:43
```

Any additional configuration changes to be applied?

**Comment by steeling** [comment]
Do you have a link to where we state we support traffic metrics? 

https://release-v1-2.docs.openservicemesh.io/docs/overview/smi/ is the canonical location. We don't currently support metrics, so if we've included that somewhere we should remove it
