### ISSUE TITLE
Provision to configure Envoy access logs

### ISSUE THREAD

**Issue by savaradh** [openservicemesh/osm#5278]
OSM doesn’t have a provision to turn off or configure the format for envoy access logs. The default JSON format is not compatible to be parsed with monitoring agents (like Geneva MDM). Request to provide configuration settings to disable and change the access logs format.

For reference,
1.	Istio has a provision to format the access logs - https://istio.io/latest/docs/tasks/observability/logs/access-log/
2.	Contour changed their default formatting to be a log string instead of JSON fields - https://projectcontour.io/docs/v1.23.0/config/access-logging/

**Comment by ToniA** [comment]
Envoy access logs also cause high Azure Log Analytics data ingestion billing
