### ISSUE TITLE
Services Without Selectors in an OSM Namespace Should be Ignored

### ISSUE THREAD

**Issue by andrewpleasants-bjss-nhs** [openservicemesh/osm#5284]
**Please describe the Improvement and/or Feature Request**
When a [service is created without a selector](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) in a namespace that is enrolled in a mesh, a cluster should not be created for this service.  

Services of this type are designed (partly) to represent external endpoints and therefore they should be handled by egress related functionality, not in-mesh functionality.  

For example, this service:

```
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: mynamespace
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
Is intended to represent an external HTTP service, and can be resolved by pods within the `mynamespace` namespace with just the hostname `myservice`.  However, if mynamespace has been enrolled in OSM, a cluster will be created for it, resulting in SSL/TLS errors.  

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Services without selectors are designed to represent external services, while providing DNS convenience.

**Comment by phillipgibson** [comment]
When you add a namespace to OSM, all pods created in the namespace will receive the sidecar injection based on a mutating webhook admission controller provided by OSM. This is instructed by the annotation on the namespace and not a label.

**Comment by andrewpleasants-bjss-nhs** [comment]
Thanks for your reply.  

This improvement doesn't necessarily have to do with pods.  

If you were to create a service resource similar to the above pointing to an endpoint outside of the cluster; there would be an OSM config created for it as if it were inside the cluster (because the service resource exists within the OSM managed namespace).  

Really I believe this should be ignored

**Comment by phillipgibson** [comment]
If it is egress functionally you're looking for, have you checked out the Egress configuration document? https://release-v1-2.docs.openservicemesh.io/docs/guides/traffic_management/egress/
