### ISSUE TITLE
Add CI test for traffic split

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#579]
To avoid https://github.com/open-service-mesh/osm/issues/578

**Comment by k3rn3l-p4n1c** [comment]
Hi, I'd like to start contributing to OSM, but I don't know where to begin. I believe this issue would help to get familiar with the code base and since it's been inactive for a while, I think it's a good choice to start with.

**Comment by SanyaKochhar** [comment]
This issue requires that we write a CI test that verifies the weights for the backend services of a traffic split are programmed correctly. We do have a script that can get the envoy config: https://github.com/openservicemesh/osm/blob/main/scripts/port-forward-osm-debug.sh . @shashankram do you have any other recommendations?

**Comment by SanyaKochhar** [comment]
@snehachhabria are you working on this?

**Comment by snehachhabria** [comment]
> @snehachhabria are you working on this?

@SanyaKochhar nope I am not

**Comment by snehachhabria** [comment]
@shashankram do you think we will still need this ? We now have e2e tests for traffic split : https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_trafficsplit_test.go and https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_trafficsplit_same_sa_test.go

**Comment by shashankram** [comment]
> @shashankram do you think we will still need this ? We now have e2e tests for traffic split : https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_trafficsplit_test.go and https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_trafficsplit_same_sa_test.go

We still need a test to test whether traffic splitting correctly distributes traffic based on the weights. Maybe we can incorporate this in the e2e test.

**Comment by snehachhabria** [comment]
Closing issue in lieu of the e2e test coverage
