### ISSUE TITLE
Use Kubernetes Events for OSM state changes

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#654]
Emit Kubernetes Events for state changes. 

Examples: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/8e25c1e2367e32d2d62d1c2a73af7b37781b431c/cmd/appgw-ingress/utils.go#L88-L103

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/0bf5fa3c1bdd5f4af38d19c260200a5d35733a2e/pkg/appgw/validators.go#L49

Reasons: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/c944ea8ec3cba71b2d2b6e332d092d5bd6408e53/pkg/events/types.go

**Comment by SanyaKochhar** [comment]
@draychev is this still relevant? If so, could you provide more context? If not, can we close this out?

**Comment by draychev** [comment]
@SanyaKochhar this is very much relevant.

The idea was emit Kubernetes events when we emit `log.Fatal()` and `log.Error()` (so essentially emit a K8s event and log a message).

I like how Application Gateway Ingress Controller (AGIC) is doing it: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/b1d68f1e693a07f3231915e713f5583d0877f439/cmd/appgw-ingress/main.go#L164-L166

For AGIC - it has been very helpful to have these Kubernetes events when troubleshooting issues.

**Comment by shashankram** [comment]
This is done.
