### ISSUE TITLE
Use custom image for Envoy container with necessary debugging tools or a debug sidecar for debugging

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#682]
For debugging traffic issues, tcpdump/tshark is useful. Add this to the sidecar image to help debug traffic issues without mutating the pods.

**Comment by phillipgibson** [comment]
[The OSM project has been officially archived by the CNCF.](https://github.com/cncf/toc/pull/1044) There will be no more new development on any repo under the OpenServiceMesh organization.
