### ISSUE TITLE
SMI crd management

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#685]
~Currently, we copy/paste the SMI crds that we require for the control plane into our helm chart. It'd be great to have upstream SMI charts that we can reference as a dependency in our chart. This issue is place holder to track this work. I'll add an issue in the SMI community and contribute back the charts if there is interest there and then we can circle back to this issue.~

We need a way to manage the SMI CRDs that OSM uses. OSM currently installs SMI CRDs but there is no way to safely upgrade those CRDs. This document linked [here](https://docs.google.com/document/d/16M69Pd7jWouP9e2nPda-2XyhfuXToRe2GNbRlUfrqfE/) reflects the conversation on the problem and proposed solutions. 

The current way we'd like to handle SMI CRD upgrades is by making use of pre-install and pre-upgrade helm hooks for the OSM chart. This hook is a container that runs before install/upgrade, checks the cluster to see if the necessary crds are installed at the right version, and installs/upgrades them if necessary. This hook should only run if the user wants OSM to manage SMI CRDs and that should be denoted as a value in the the values file.

Once the hooks are in place, create a readiness probe in the osm-controller that checks if the correct version of the SMI resources are installed. This ensures that the osm-controller won't crash on configuration issues and dependencies are met. 

Start making use of the new conversion webhooks in the SMI SDK when we update the osm-controller to use SMI TrafficSplit  v1alpha4. With conversion webhooks, we can ensure that even an SMI resource is created a different version than the one osm-controller supports, it will be converted to the version osm-controller needs.

- [ ] Create pre-install/pre-upgrade helm hooks to ensure correct version of SMI CRD is configured in Kubernetes cluster
- [ ] Build a readiness probe for osm-controller that ensures the version of SMI CRDs it needs are installed before serving traffic

Great resources for implementing this work:
- [https://github.com/jinghzhu/KubernetesCRD](https://github.com/jinghzhu/KubernetesCRD)
- [https://vincenthou.medium.com/how-to-create-conversion-webhook-for-my-operator-with-operator-sdk-36f5ee0170de]( https://vincenthou.medium.com/how-to-create-conversion-webhook-for-my-operator-with-operator-sdk-36f5ee0170de)

**Comment by snehachhabria** [comment]
For now the SMI CRD's will be managed by OSM which will be solved by issue #3396
