### ISSUE TITLE
Update TrafficSplit version from v1alphav2 to v1alpha4

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#705]
SMI has a new version of TrafficSplit, OSM needs to be updated to use this version.

Note: The main feature available with this latest version is that it enables the use of TrafficSpec with TrafficSplit. This upgrade isn't mandatory as we are updating TrafficSpec with #449 so all its features could be used with a TrafficTarget

We can work on this item once we get more clarity from the PMs if it is an immediate requirement for add-on or open source

**Comment by michelleN** [comment]
To implement this in a way where routes associated with a traffic target are decoupled from a traffic split, we need to do the following steps in order:
1. Relax logic on how outbound clusters get programmed. Outbound clusters should be programmed with wildcard routes. Ensure that routes are programmed via RDS on the server side (already happening). 
2. Any time an SMI traffic split is applied, create an outbound cluster/virtual host with weighted cluster information from the SMI traffic split on every envoy proxy.  
3. Apply route information (SMI Traffic Split rules / HTTPRouteGroup) to the virutal host for that traffic split.

**Comment by michelleN** [comment]
Currently blocked on #2034

**Comment by snehachhabria** [comment]
closing this issue cause of duplicate issue #2368
