### ISSUE TITLE
Integrate ingress scenario into CI demo

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#734]

**Comment by snehachhabria** [comment]
@michelleN , @delqn we already have an e2e test for ingress : https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_http_ingress_test.go. My guess is we can close this issue, WDYT ?

**Comment by shashankram** [comment]
> @michelleN , @draychev we already have an e2e test for ingress : https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_http_ingress_test.go. My guess is we can close this issue, WDYT ?

This issue was filed a long time back. We have an ingress e2e test as pointed above.
