### ISSUE TITLE
Create a demo for an A/B testing example

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#737]
This issue encompasses upgrading:
- build a demo application scenario
- update Traffic Split version (v1alpha3) #705 

Note: 
How to handle traffic policy conflicts? Should validations be handled in sdk? Should these validation scenarios be discussed more explicitly with the SMI community?

**Comment by michelleN** [comment]
blocked on #2368

**Comment by shashankram** [comment]
We have an example for canary rollouts, which should be pretty similar to A/B test barring the differences between the two strategies.
