### ISSUE TITLE
smi policy dashboard

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#824]
This is a UI that allows end users to see the SMI policies that they have configured. If a user has multiple open service mesh control planes installed, they should be able to choose which control plane they want to see policies for.

A user should be able to:
- List all traffic show all SMI TrafficTargets installed in the cluster in all namespaces that the selected osm control plane monitors 
- A user should be able to click on a particular SMI TrafficTarget's details to see the yaml that has been configured

SMI TrafficTarget yaml will have a reference an SMI Traffic Spec resource which contains details about what routes or headers to allow traffic on. The SMI Traffic Spec is another resource that is installed and can be found in your Kubernetes cluster. In the future, it would be great to also have a way to have a way to get the yaml for the SMI Traffic Spec resource(s) that are referenced in the listed SMI TrafficTargets.

**Comment by SanyaKochhar** [comment]
@michelleN is this work complete? Can we close this issue?

**Comment by michelleN** [comment]
Yea we can close this issue
