### ISSUE TITLE
(can we) Enable mTLS between prometheus endpoints and prometheus 

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#836]
OSM controller should provision Envoy's prometheus endpoints w/ certs for mTLS.
Graphana pod querying from prometheus should also establish mTLS connection.

Questions to answer:
  - can we provision special cert to encrypt and authenticate Envoy's prometheus endpoints?
  - can we equip the grafana pod with a side car so that grafana -> prometheus is mTLS
  - can we provision prometheus with a sidecar so that in talks mTLS to Envoys and grafana

These sidecars will be a service mesh, but that would not be part of SMI.

**Comment by SanyaKochhar** [comment]
@snehachhabria @eduser25 is anybody working on this?

**Comment by draychev** [comment]
We researched this and it proves to be very difficult to achieve and unnecessary. Shelving this issue.
