### ISSUE TITLE
Support for 1:N mapping between Service Account and Services

### ISSUE THREAD

**Issue by aanandr** [openservicemesh/osm#846]
OSM today assumes that there is only one service associated with service account. However, there is a strong possibility of the customer using a single service acct for many services. Following are common scenarios where using the OSM becomes challenging
1. Some small customers might be using just one for all their services
2. Customers might have already defined the mapping between their services and services accounts. These customer would have to go back and recreate all their services before they can start using OSM.

If the customer has multiple services using the same service account, then the policies should apply to all of them. For e.g. is service account SA1 is allowed to talk to service account SA2 then all services associated with SA1 should be able to talk to all services associated with SA2. For finer grained control we can recommend 1-1 mapping between service accounts and services, but cannot make it mandatory.

**Comment by snehachhabria** [comment]
OSM now supports multiple services for one service account cause of the following changes : #1567 #1553
