### ISSUE TITLE
add homebrew installation for osm

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#868]

**Comment by tharun208** [comment]
https://github.com/Homebrew/homebrew-core/pull/59210

**Comment by michelleN** [comment]
Thank you!

**Comment by tharun208** [comment]
got merged !

**Comment by michelleN** [comment]
Thank you so much @tharun208 ! Few quick questions:

1. Where does the sha256 checksum listed for the formula [here](https://github.com/tharun208/homebrew-core/blob/7a616224e42c07c4d411717ff94bba3517aae101/Formula/osm.rb#L5) come from? In the assets, we list sha256 for all the packages but that one is not listed.

2. Do we need to make a PR for a every release we want to put on homebrew?

**Comment by tharun208** [comment]
> Thank you so much @tharun208 ! Just updated brew and found it. 😻 Few quick questions:
> 
> 1. Where does the sha256 checksum listed for the formula [here](https://github.com/tharun208/homebrew-core/blob/7a616224e42c07c4d411717ff94bba3517aae101/Formula/osm.rb#L5) come from? Is this the sha256 checksum for the entire repo? Is it something you had to calculate or was it available at url anyone could access?
> 2. Do we need to make a PR for a every release we want to put on homebrew?
> 3. We do releases off of release [branches](https://github.com/openservicemesh/osm/branches). Should we send the archive of the release branch instead of of main?

1. the sha256 will be generated for the git tar file from which you create this formula. it is separate for each brew formula.
2. yes, we need to raise a pr for every version upgrade.
3. home-brew maintainers right now accept only release branches for formula.

**Comment by michelleN** [comment]
Thank you again @tharun208 ! If it's not too much trouble, would you minding adding some documentation to upgrade the homebrew formula to the release guide (issue #1475)?

**Comment by tharun208** [comment]
sure @michelleN
