### ISSUE TITLE
Migrate from ptypes.MarshalAny to a deterministic MarshalAny function to stabilize tests

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#878]
The current `MarshalAny()` function we use results in non-deterministic output, which causes test failures.
Even though it may cost in CPU cycles, it would be great to implement a deterministic Marshal function.
Github has great examples on this: https://github.com/search?q=MarshalAnyDeterministic&type=Code

**Comment by SanyaKochhar** [comment]
@eduser25 are you working on this issue?

**Comment by draychev** [comment]
no longer needed
