### ISSUE TITLE
OSM to watch for Azure CNI Network policy that conflicts with OSM

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#890]
Kubernetes could have Calico policies applied.  These could disrupt traffic between pods in the service mesh.
OSM should observe Calico policies applied and WARN the operator when these could disrupt service mesh operation.

**Comment by SanyaKochhar** [comment]
@shashankram @aanandr @draychev what's the status of this issue?

**Comment by draychev** [comment]
@SanyaKochhar I'd say this is in design phase.
We need to come up with a good software design as well as UX and implement.
In my opinion it would be a great addition to the greater SMI community to create a go package that can find SMI conflict snad surface them (somehow) to the operator.

**Comment by shashankram** [comment]
I don't see OSM needing to start watching Calico policies for conflicts. This is outside the scope of OSM and should likely be implemented as a separate tool to be used by the cluster admin.
