### ISSUE TITLE
Cross namespace ingress support

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#892]
It is possible to specify a service backend which is in a different namespace than the namespace the ingress resource belongs to if the service is of type `ExternalName`.

Currently OSM requires the ingress resource to be in the same namespace as its backends, to be able to match a service (namespace/service) to an ingress resource.

**Comment by SanyaKochhar** [comment]
@shashankram what is the priority of this feature?

**Comment by draychev** [comment]
Typically Ingress k8s resource is namespaced and each namespace would get its own Ingress.  Further reading https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-multiple-namespace-support#motivation :)
