### ISSUE TITLE
How does OSM upgrade handle SMI version upgrades on a cluster with existing policies?

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#893]
If a customer is running OSM vN with SMI vN and decides to upgrade to OSM vN+1, which requires SMI vN+1 -- how would the process of upgrading OSM handle SMI policies that may not be easily or at all be deterministically upgradable from vN to vN+1?

**Comment by shashankram** [comment]
Without an SMI spec API conversion facility, this unfortunately is a manual process where the older CRDs must be manually removed and newer ones installed. This is documented at https://github.com/openservicemesh/osm/blob/main/docs/content/docs/upgrade_guide.md#crd-upgrades

**Comment by snehachhabria** [comment]
This will be covered by issue #3396. A conversion webhook will be added in OSM that will help handle multiple versions of the SMI CRD's as well
