### ISSUE TITLE
add verbose output for osm install with -v flag

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#912]
The verbose output should show what components we've installed and configured in the user's cluster. It should also show what the name of the mesh is that was installed and in what namespace it was installed.

**Comment by aleigh6-gatech** [comment]
So if I don't have osm installed, and I run `osm install -v`, should I expect the osm to be installed, or just output that I haven't install any components? Another way to ask this question is, does `osm install -v` actually install osm, or just output installation status?

**Comment by allenlsy** [comment]
So if I don't have osm installed, and I run osm install -v, should I expect the osm to be installed, or just output that I haven't install any components? Another way to ask this question is, does osm install -v actually install osm, or just output installation status?

**Comment by allenlsy** [comment]
@michelleN I want some guidance on how to get the installed components? My idea is, after installation, `installClient.Run()` returns a `Release` object. I checked it, and found all the `deploments` CRD in the `manifest` of the `Release` object. Probably this is a feasible way. But any other suggestion on how to do it?

**Comment by michelleN** [comment]
Yes I think that's a great way to go about it @allenlsy

**Comment by shashankram** [comment]
@allenlsy do you plan on working on this issue? If yes, I'll assign this to you.

**Comment by allenlsy** [comment]
@shashankram Sure, please go ahead an assign to me. I will take some time this week to work on it.

**Comment by shashankram** [comment]
> @shashankram Sure, please go ahead an assign to me. I will take some time this week to work on it.

Great, thanks!

**Comment by allenlsy** [comment]
@shashankram Although Helm can provide a list of installed manifest files after installation, I want to ask, how are we going to define what are components? Because not all k8s deployments or k8s services are considered components, thus we cannot simply list them all. We probably want to say, grafana is a component, osm-controller is a component. User's service is not a component. 

So in this case, should we define a list of components (hard coded), and osm detects components according to this list? Or probably we can also determine the components using a specific annotation from Deployment manifest?

**Comment by allenlsy** [comment]
I think we need a clearer definition of what are components before moving now. I took a note of what's inside the `Release` object when reaching this [line](https://github.com/openservicemesh/osm/blob/67d6e854cd2501be9af559afe227cfabdaa1a663/cmd/cli/install.go#L209), extracted part of the data that might be useful:

```
{
  "name": "osm",
  "chart": {
    "metadata": {
      "name": "test-chart",
      "version": "0.1.0",
      "description": "A Helm chart for Kubernetes",
      "apiVersion": "v2",
      "appVersion": "1.0.0",
      "type": "application"
    },
    "files": [
      {
        "name": ".helmignore",
        "data": "IyBQYXR0ZXJucyB0byBpZ25vcmUgd2hlbiBidWlsZGluZyBwYWNrYWdlcy4KIyBUaGlzIHN1cHBvcnRzIHNoZWxsIGdsb2IgbWF0Y2hpbmcsIHJlbGF0aXZlIHBhdGggbWF0Y2hpbmcsIGFuZAojIG5lZ2F0aW9uIChwcmVmaXhlZCB3aXRoICEpLiBPbmx5IG9uZSBwYXR0ZXJuIHBlciBsaW5lLgouRFNfU3RvcmUKIyBDb21tb24gVkNTIGRpcnMKLmdpdC8KLmdpdGlnbm9yZQouYnpyLwouYnpyaWdub3JlCi5oZy8KLmhnaWdub3JlCi5zdm4vCiMgQ29tbW9uIGJhY2t1cCBmaWxlcwoqLnN3cAoqLmJhawoqLnRtcAoqLm9yaWcKKn4KIyBWYXJpb3VzIElERXMKLnByb2plY3QKLmlkZWEvCioudG1wcm9qCi52c2NvZGUvCg=="
      }
    ]
  },
  "config": {
    "OpenServiceMesh": {
    }
  },
  "manifest": "---\n# Source: test-chart/templates/deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: test-deployment\n  labels:\n    testing: test\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      testing: test\n  template:\n    metadata:\n      labels:\n        testing: test\n    spec:\n      containers:\n        - name: test\n          image: \"openservicemesh/test:1.0.0\"\n          imagePullPolicy: IfNotPresent\n          ports:\n            - name: http\n              containerPort: 80\n              protocol: TCP\n",
  "version": 1,
  "namespace": "osm-system"
}
```

This is extracted from one of the test cases. All the `Deployment`s should be stored in there `"manifest"` field. We can take advantage of it.

**Comment by shashankram** [comment]
> @shashankram Although Helm can provide a list of installed manifest files after installation, I want to ask, how are we going to define what are components? Because not all k8s deployments or k8s services are considered components, thus we cannot simply list them all. We probably want to say, grafana is a component, osm-controller is a component. User's service is not a component.
> 
> So in this case, should we define a list of components (hard coded), and osm detects components according to this list? Or probably we can also determine the components using a specific annotation from Deployment manifest?

Hey @allenlsy , I think the original issue meant to list all the components that the OSM Helm chart installs when using the verbose flag.

All the components deployed can be found in https://github.com/openservicemesh/osm/tree/main/charts/osm/templates

**Comment by allenlsy** [comment]
@shashankram Clarification:

1. does this command just print a static output(except the user's mesh name and namespace), which is a list of the components osm will install? In this case, it will be:

```
> osm install -v

Mesh name: my-mesh
OSM Namespace: osm-system
Components installed:

* grafana
* jaeger
* primetheus
```

2. or, does this command print the components that currently installed in the mesh? This means user can opt out some components during the installation, or remove components after installation.

**Comment by shashankram** [comment]
> @shashankram Clarification:
> 
> 1. does this command just print a static output(except the user's mesh name and namespace), which is a list of the components osm will install? In this case, it will be:
> 
> ```
> > osm install -v
> 
> Mesh name: my-mesh
> OSM Namespace: osm-system
> Components installed:
> 
> * grafana
> * jaeger
> * primetheus
> ```
> 
> 1. or, does this command print the components that currently installed in the mesh? This means user can opt out some components during the installation, or remove components after installation.

Hey @allenlsy that's an interesting question. I see why this could be a bit ambiguous.

If it were up to me, I would implement `osm install -v` such that it does the following:
1. Starts the install process and prints verbose messages during install
2. List the components that were installed from running `osm install`
3. If an installation already exists, list the components that were previously installed for that particular instance of `osm install` (for the given mesh-name)

@michelleN did you have a different expectation for this CLI command?

**Comment by uds5501** [comment]
Is this still up for grabs?

**Comment by johnsonshi** [comment]
I'm currently working on it @uds5501

**Comment by shashankram** [comment]
This has been implemented by @nshankar13: https://github.com/openservicemesh/osm/pull/3994
