### ISSUE TITLE
Prevent hostname conflicts for services in different namespaces when using k8s short form DNS names

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#951]
With allow-all, based on service discovery all possible combinations of FQDN for a k8s service is configured for a client to be able to access the service over its various FQDNs (service, service.namespace, service.namespace.svc etc.).

When the same service exists in multiple namespaces, the hostname corresponding to `service`, `service:port` should only be present for one service, else the same hostname would match against the same service name in multiple namespaces.

To prevent this, do one of the following:
1. Remove `service`, `service:port` DNS from allow-all
2. Detect multiple services with the same name in different namespaces and restrict `service`, `service:port` FQDN to a single namespace.

**Comment by michelleN** [comment]
@shashankram - is this issue still something we need to tackle? cc/ @draychev

**Comment by shashankram** [comment]
> @shashankram - is this issue still something we need to tackle? cc/ @draychev

This is still required. Its a corner case that we don't handle.

**Comment by michelleN** [comment]
You should only have `service` and `service:port` configured for a service that does indeed exist in the same namespace as the client. What do you think?

**Comment by shashankram** [comment]
> You should only have `service` and `service:port` configured for a service that does indeed exist in the same namespace as the client. What do you think?

This makes sense.
