### ISSUE TITLE
Update uninstall to clean-up OSM without downtime & document steps

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#959]
The current implementation of `osm mesh uninstall` only deletes Kubernetes resources that were installed/applied in the cluster as part of the control plane via `osm install`. The current implementation needs to be updated so that it cleans up labels/annotation on Namespaces, removes Envoys, and cleans up any resources created by the osm-controller. 

This issue requires a design document before implementing. See [docs/design](https://github.com/openservicemesh/osm/blob/main/docs/design/README.md)

**Comment by SanyaKochhar** [comment]
This design doc outlines how to document this: https://github.com/openservicemesh/osm/blob/1ddaf0de718edc0fbe47c5dc19860f0046c53342/docs/design/uninstall_osm.md

**Comment by michelleN** [comment]
Note: description was recently updated to reflect next iteration of the uninstall command.

**Comment by shashankram** [comment]
OSM uninstalls the mesh, and optionally the cluster wide resources.
The steps are documented in https://release-v0-11.docs.openservicemesh.io/docs/getting_started/uninstall/
