### ISSUE TITLE
Normalize HTTP ports for services

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#965]
In the current demo the Bookbuyer is HTTP GETting books from Bookstore on port `80`
The actual service is on port `8080`

This Issue is to:
1. Change the demo so when we cURL bookstore - we curl on the same port as the K8s services
-- this could be as easy as changing all `8080` ports in the ./demo/deploy-book*.sh scripts to 80

~2. When we configure the outbound listener for bookbuyer - we should use the same port as the K8s service~

**Comment by SanyaKochhar** [comment]
Resolved by #1009
