### ISSUE TITLE
add more info around how to fix pre-install check failures

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#975]
Users may get failures if they run `osm check --pre-install` and when they do, they may get frustrated about not knowing what to do to fix those failures to get up and running with OSM. 
In addition to checking an environment, we should add more information / instructions about what to change/enable in a cluster to get past failures.

Example failure:

```
Error: No PodSecurityPolicies found providing the capabilities ["NET_ADMIN" "NET_RAW"], sidecar injection will fail if  
the PSP admission controller is running
```

**Comment by SanyaKochhar** [comment]
Closing because checks have been removed
