### ISSUE TITLE
make demo rely less on environment variables

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#977]
It's easy to miss the instruction for moving the .env.example file to .env. Also, may confuse some people when just trying to run a simple demo. There's a lot to ingest in the env file. We should make the demo less dependent on environment variables and make instructions for creating the container registry and getting creds for it more obvious and explicit.

**Comment by draychev** [comment]
We introduced reasonable defaults for many of the environment variables to where it is possible to run the demo without having much in the .env file.
